### ISSUE TITLE
Metadata updates for Kazakhstan and Russian Federation (prefix 7)

### ISSUE THREAD

**Issue by Logrus86** [googlei18n/libphonenumber#1002]
**Country/region affected:** Kazakhstan and Russian Federation
**Example number(s) affected:** +7 (707) 1234567, +7 (7212) 123456, +7 (81856) 12345
**The phone number range(s) to which the issue applies:** +7 (XXX) XXXXXXX, +7 (XXXX) XXXXXX, +7 (XXXXX) XXXXX
**The type of the number(s):** fixed-line and mobile
**Supporting evidences:**
Kazakhstan:
http://telecom.kz/catalog/kazahstan.171777/5
Csv files with national numbering plans for Russia: 
http://www.rossvyaz.ru/opendata/7710549038-Rosnumbase/Kody_ABC-3kh.csv http://www.rossvyaz.ru/opendata/7710549038-Rosnumbase/Kody_ABC-4kh.csv http://www.rossvyaz.ru/opendata/7710549038-Rosnumbase/Kody_ABC-8kh.csv http://www.rossvyaz.ru/opendata/7710549038-Rosnumbase/Kody_ABC-9kh.csv
Timezones:
http://www.worldtimezone.com/dst_news/dst_news_russia-map-2014-07.html

**Updated data:**
[carrier_en_7.txt](https://github.com/googlei18n/libphonenumber/files/170571/carrier_en_7.txt)
[carrier_ru_7.txt](https://github.com/googlei18n/libphonenumber/files/170573/carrier_ru_7.txt)
[geocoding_ru_7.txt](https://github.com/googlei18n/libphonenumber/files/170572/geocoding_ru_7.txt)
[timezones_map_data_7.txt](https://github.com/googlei18n/libphonenumber/files/170574/timezones_map_data_7.txt)

**Comment by padmaksha** [comment]
Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by Logrus86** [comment]
That's great!

**Comment by Logrus86** [comment]
@padmaksha Could you take a look at this please? Six months passed and nothing related with that update was done. 

If the project is generating timezones data automatically (heard something about it during the reading other issues), might be we should leave the timezones_map_data_7.txt and use other updated files listed here only? 

There is a lot of new data for prefix 7. The library could be much more useful while describing such phone numbers.

**Comment by lararennie** [comment]
Ok, I have some bandwidth so will take a look at this. Sorry for the delay.

**Comment by lararennie** [comment]
Some comments looking at the Kazakh carrier data first:
a) Some data I can't find sources for: e.g. the KazakhTelecom mentioned for 750 and 761? We don't consider those prefixes valid, they aren't in the files you provided, not in the ITU doc: where did they come from?
b) We don't include VoIP prefixes in the carrier mappings so won't include 751
c) Why did you change Kcell to Kcell/Activ? Which name would a consumer be familiar with?
d) ITU doc says Arna for 763, you say Ducat: where did you get that from?
e) ITU doc says Kulan for 760, you say Kazakhtelecom, where did you get that from?

Kazakh ITU doc:
http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006F0001PDFE.pdf

**Comment by Logrus86** [comment]
@lararennie,
firstly thank you for paying attention!

a) I can't find the sources at telecom.kz which I used anymore. I suppose something has been changed there during last 1.5 years. If it is acceptable, there is the page in [Wiki](https://translate.google.ru/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=https%3A%2F%2Fru.wikipedia.org%2Fwiki%2F%25D0%25A2%25D0%25B5%25D0%25BB%25D0%25B5%25D1%2584%25D0%25BE%25D0%25BD%25D0%25BD%25D1%258B%25D0%25B9_%25D0%25BF%25D0%25BB%25D0%25B0%25D0%25BD_%25D0%25BD%25D1%2583%25D0%25BC%25D0%25B5%25D1%2580%25D0%25B0%25D1%2586%25D0%25B8%25D0%25B8_%25D0%259A%25D0%25B0%25D0%25B7%25D0%25B0%25D1%2585%25D1%2581%25D1%2582%25D0%25B0%25D0%25BD%25D0%25B0&edit-text=)(link content is translated to english via google).
b) ok
c) Because there is one carrier KCell with two brands - KCell and Activ. Since I live here I can assure you, people know both equally and it's confusing a little if all such numbers appear like KCell. But it's not critical from the other side.
d) the link from a) says it's Arna too. Looks like my info is out of date.
e) Kazakhtelecom is a provider of Kulan satellite network as I know now, but few years ago it was just Kazakhtelecom's prefix. Any option would be ok as for me.

**Comment by lararennie** [comment]
Thanks for the clarifications!

I'm on holiday for a week, just to set expectations, but when I come back
I'll submit the carrier data for Kazakh, I have a few more questions re
geocoding, and then I'll look at the Russian data.

14. okt. 2016 6.24 p.m. skrev "Pavel Bobylev" <notifications@github.com>:

**Comment by Logrus86** [comment]
@lararennie,
You are welcome! Looking forward to getting your questions!

**Comment by lararennie** [comment]
So re geocoding:
-- there are a number of prefixes present in the ITU doc for Kazakhstan not mentioned on this website, and vice versa. For example, 71041 is not in https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006F0001PDFE.pdf but it is in https://telecom.kz/catalog/kazahstan.171777/5 as
 8 71041 + XXXXX Актау Жезказган

I found this website showing some numbers with this prefix: http://malshibay.jezkazgan.gov.kz/ru/1015.html -- do you think the ITU doc just has holes, or were these prefixes migrated at some point and the telecom.kz is just showing what they were when numbers were first migrated to use them?

There are several other examples.

In the other direction, 718 45 for instance is in ITU doc (Pavlodar area) but missing from the telecom.kz - I think that the ITU doc is right here, and am just planning on adding them.

**Comment by kachkaev** [comment]
Thanks for your efforts to collect regional data for Russian phone numbers @Logrus86! Also looking for this to be merged.

**Comment by Logrus86** [comment]
@kachkaev,
thank you!

@lararennie,
telecom.kz represents national telecommunication provider, the only one which works countrywide. In the cooperation with government they define which prefix belongs to a city/settlement. So, the data from telecom.kz is more up-to-date than ITU docs I believe. Regarding those prefixes which exist in ITU docs and not at telecom.kz -> that means there is no such prefix used anymore, the old one was merged to another or something like that. One thing I could say for sure, their data is most actual for KZ.

**Comment by lararennie** [comment]
Other prefixes I found that weren't in the ITU doc:
-- 71438
-- 71449
-- 71463
-- 7145834
-- 71539
-- 71540
-- 72132 (e.g. http://abay.gov.kz/ru/tel_doverie/)

Prefixes in the ITU doc (from 2012) only and not elsewhere: 
-- 71845
-- 72146
-- 725 (e.g. http://kisa.kz/territory/uzhkaz/)

I could believe that a couple just missed one list or another, but the 725 one is very surprising: Wikipedia agrees with ITU on the area code (https://en.wikipedia.org/wiki/Shymkent), also in the Kazakh version (https://kk.wikipedia.org/wiki/%D0%A8%D1%8B%D0%BC%D0%BA%D0%B5%D0%BD%D1%82)

I am happy to add all to the geocoding files; I am just wondering whether I should at the same time change our validation to accept the 8 codes I list above as being only in the telecom.kz doc; if you think they are still in use, and they weren't e.g. migratory only, I will do this too.

**Comment by Logrus86** [comment]
I understand, you want to add trusted data only, no problem. Let's look through prefixes you listed above.

- 71438, 71449, 71539, 71540, 72132 - all exist at telecom.kz, should be trusted.
- 71463 - can't find them at telecom.kz neither in itu doc. Is it a typo?
- 7145834 - was presented at telecom.kz some time ago, when I was gathering this data (the initial merge request (https://github.com/googlei18n/libphonenumber/pull/682), April 2015). Something has changed at telecom.kz, and I am starting to think they lose some data during web-site redesign, e.g. prefix 7252, there is no such one now but it definitely was there, because I know the city of Shymkent, and my data contain it  and 725 too.

Overall, I suppose the data from telecom.kz is trustful, but in the same time, it seems they have some awful gaps at the data, which weren't exist earlier. (725 and 7252 prefixes).
All other data proved by ITU only looks outdated for me.
Concerning 8-digit prefix - I suppose it could be skipped for the moment, and corrected/added later if we find more trustful sources. I think there is no need to change validation workflow just because of one prefix.

**Comment by lararennie** [comment]
71463 - weird. I think it was supposed to be 714463 - but I now notice that ITU has that as a vsat prefix.

**Comment by lararennie** [comment]
Last question: for VSAT prefixes, are the locations what the prefix covers, or the location of the business offering the service or something? in the ITU doc the prefixes are listed with VSAT as the *location*, yet the telecom.kz page has actual locations for them.

**Comment by Logrus86** [comment]
I suppose such prefixes are not VSAT anymore, they are usual fixed line codes now, according to telecom.kz. Basically ITU doc is little bit outdated.

**Comment by Logrus86** [comment]
@lararennie 
any updates or questions?

**Comment by lararennie** [comment]
Change in review for half of this...

6. des. 2016 7.18 a.m. skrev "Pavel Bobylev" <notifications@github.com>:

**Comment by lararennie** [comment]
KZ changes will be released in the next release; because it's our holiday freeze that won't unfortunately be until early Jan, but they are done. I'm going on holiday for a month between now and then so won't finish the Russian changes, but will aim to get them in before end-of-Jan too.
Sorry this is taking so much time!

**Comment by Logrus86** [comment]
No problem and thank you! The later is better than never :) Looking forward for it.

**Comment by kachkaev** [comment]
Hi @lararennie. What are the plans on the Russian numbers at the moment? When about may they be merged in your opinion?

**Comment by lararennie** [comment]
Back from holiday and back to looking at this.
Doing Russian carrier files at the moment. They should be done this week, but I have a question on the data:

@Logrus86 
The CSV source sheet lists a bunch of operators, e.g. Telecom Evraziya, Smolenskaya Sotovaya Svyaz, Ekaterinurg-2000 - but the data says 7900|Tele2, and then there are a couple of more detailed ones like 790003 Motiv, 7900335 Beeline. Can you explain the mappings from the operators listed to the names used in the file? Some of them I can see, e.g. 7901473|Sotel-Chuvashia, others are trickier, e.g. РТ-Мобайл seems to go to Tele2, but it's not a 1:1 mapping?

**Comment by Logrus86** [comment]
@lararennie 
"Telecom Evraziya, Smolenskaya Sotovaya Svyaz, Ekaterinurg-2000 - but the data says 7900|Tele2" - that's correct, Tele2 have bought all of them (http://tele2life.ru/1/content/view/582 with list of prefixes);

The procedure was:
1) parse the CSVs to get library-compatible format instead of raw list of prefixes
2) override some parts according to main Russian Federation operator web-sites (Beeline, MTS, Tele2, Megafon, Rostelecom, etc) The purpose of that is update data, because CSVs were pretty out-of-date.

You know, there are 2 years passed since the initial merge request I've created
https://github.com/googlei18n/libphonenumber/pull/590
which later was converted to the current 'Issue'. Basically I don't remember the exact source of each operator or number. But generally it was like that.

**Comment by lararennie** [comment]
Thanks for the tele2 link: that explains the diff to wikipedia for 951.
However 901 is listed as Tele2 in the file, but not on the tele2 page you
linked, and wikipedia says Skylink. Any thoughts on that prefix?

2017-01-23 10:26 GMT+01:00 Pavel Bobylev <notifications@github.com>:

**Comment by Logrus86** [comment]
It depends on next symbols, in Russia the prefixes are grouped by region which means 901001 could be used by one carrier and 901010 - by another. I can't say for sure about any particular prefix though.

**Comment by andyst** [comment]
We've updated **carrier mappings for Russia** in the https://github.com/googlei18n/libphonenumber/releases/tag/v8.8.7 release back in December. It covered the following carriers:
- MTS
- MegaFon
- Tele2
- Motiv
- Beeline
- TMT

I'll mark the issue as closed. I think the one remaining part of this large issue here is **geo mappings for Russia**. If you can wait ~ 6 months, then I think we'll get to that as part of a larger initiative anyway. If you need this fixed sooner, feel free to file a new, targeted issue (e.g. Russia geo mapping data) on the new issue tracker at https://issuetracker.google.com/issues/new?component=192347 .
