### ISSUE TITLE
Validation issue with 0895 3297 088863 (ID)

### ISSUE THREAD

**Issue by fandygotama-tokobagus** [googlei18n/libphonenumber#1004]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): ID

Example number(s) affected ("+1 555 555-1234"): 0895 3297 088863

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0895+3297+088863&country=ID)

**Comment by padmaksha** [comment]
@fandygotama-tokobagus

We can't connect to +62 895 3297 088863. Did you have a typo?
We support the prefix 895 but only for numbers that are 9-12 digits in length. Your number seems to be 13 digits. We can't find official evidence that numbers this long are in use.
Please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by padmaksha** [comment]
Please reopen the issue with additional information if there was a misunderstanding.
