### ISSUE TITLE
Validation issue with 12504347262 (CA)

### ISSUE THREAD

**Issue by coreygeesey** [googlei18n/libphonenumber#1007]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): CA

Example number(s) affected ("+1 555 555-1234"): 12504347262

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 1250-XXX-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Don't Know

The cost, if applicable ("toll-free", "premium rate", "shared cost"): Don't know

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

http://www.allareacodes.com/250

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=12504347262&country=CA)

The timezone should be set as America/Vancouver based on my research.

**Comment by padmaksha** [comment]
This issue is similar to https://github.com/googlei18n/libphonenumber/issues/991 and will be tracked there. Hence closing the issue here.

Note: This isn't a validation issue, as per the bug title, but an issue with a missing time-zone definition

**Comment by padmaksha** [comment]
Closing this issue here.
