### ISSUE TITLE
Non-ASCII (beyond 0x7F) bytes in the source lead to C4819 warning when compiled with Visual Studio on WIndows + CJK locale

### ISSUE THREAD

**Issue by jungshik** [googlei18n/libphonenumber#1010]
Four source files in cpp version of the library have non-ASCII bytes (they're in UTF-8 representation of hyphens and other characters):

./phonenumbermatcher.cc : "(\[（［"    and others 
./phonenumberutil.cc  :   ＋   -x‐-―−ー－-
./asyoutypeformatter.cc  : Two quotation marks
./phonenumberutil.h   ( "Google Zürich")

MSVC does not offer a way to treat all the input source file as encoded in UTF-8. They're always interpreted as in the "code page" for non-Unicode apps. 

When compiled on Windows by Visual C++ with the default code page for non-Unicode applications set to one of CJK code pages (932, 936, 949, 950), non-ASCII characters in UTF-8  are not valid and MSVC emits C4819 warnings. 

This warning can be ignored in most cases (especially because they're all in comments), but on rare occasions this can lead to a real compile error.  Moreover, some projects strive to be as warning-free as possible (usually, 'treat warning as error' is turned ON). 

An upcoming version of Visual Studio (not yet released) will offer an option (long overdue) to treat all the input files as encoded in UTF-8 (without 'UTF-8 BOM' at the beginning). 

It might be considered to either document this or to replace those non-ASCII characters in comments with U+hhhh notation. Perhaps, just documenting should be good enough. 

This is spun off from  https://bugs.chromium.org/p/chromium/issues/detail?id=454858

**Comment by padmaksha** [comment]
@jungshik 

Thank you for taking the time to improve libphonenumber!

Could you please explain what exactly the documentation should contain and where it should be placed (e.g. in the CMakeLists file? README?)

**Comment by keghani** [comment]
Hi @jungshik, open-source community,

I'm documenting the caveat in #1597.

To actually require the VS 2015 update 2 or later seems infeasible given our
bandwidth and expertise, but if you the reader have these then please
feel free to re-open this issue and take it up.

We don't actively maintain windows builds but would be able to accept a PR.
We'd also need someone else in the open-source community to test it
out and help with the review. Please see the [known Windows
issues](FAQ.md#what-about-windows), maybe someone else there or in the
[discussion group](https://groups.google.com/group/libphonenumber-discuss) could
help.
