### ISSUE TITLE
Valid Number But Not Identified by LIBPHONENUMBER

### ISSUE THREAD

**Issue by azeem-mohammed** [googlei18n/libphonenumber#1011]
Dear Support,

I am trying to parse a valid mobile number for a country "SOMALIA"

It is throwing the message as invalid mobile number 

This is actually a valid mobile number 

Number Details
Country: SO (Somalia)
Number: 252906146066

**Comment by padmaksha** [comment]
@azeem-mohammed

Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by azeem-mohammed** [comment]
@Padmaksha,

Tentatively by when can I expect the updated release after fixing the
mentioned issue.

On Wed, Mar 16, 2016 at 2:21 PM, padmaksha <notifications@github.com> wrote:

> @azeem-mohammed <https://github.com/azeem-mohammed>
>
> Thanks for providing all the details we need!
> We've accepted this issue and will fix this in an upcoming release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/1011#issuecomment-197249338>
>



-- 
Regards,
Mohammed Azeem.
+971-50-4995269

**Comment by lararennie** [comment]
Hi! Can you just confirm what carrier you expect this mobile number to be for?

**Comment by penmetsaa** [comment]
@azeem-mohammed 
Fixed in release 7.2.8: https://libphonenumber.appspot.com/phonenumberparser?number=%2B252906146066

**Comment by azeem-mohammed** [comment]
Dear Support,

Thanks for the update

Please let me know if this version 7.2.8 is released ? since i am unable to
find the same in downloads section

Appreciate if you could provide the download link or the release date.

Regards,
Azeem.

On Mon, Mar 21, 2016 at 8:47 PM, penmetsaa <notifications@github.com> wrote:

> @azeem-mohammed <https://github.com/azeem-mohammed>
> Fixed in release 7.2.8:
> https://libphonenumber.appspot.com/phonenumberparser?number=%2B252906146066
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/1011#issuecomment-199373089>
>



-- 
Regards,
Mohammed Azeem.
+971-50-4995269

**Comment by penmetsaa** [comment]
@azeem-mohammed,

You can get the download file from releases page.
https://github.com/googlei18n/libphonenumber/releases

Please click on "..." button to see the latest versions.
