### ISSUE TITLE
in FALSEHOODS.md, point #9

### ISSUE THREAD

**Issue by markentingh** [googlei18n/libphonenumber#1013]
I am not certain (because I'm not an expert in phone number rules), but I believe you forgot to include +54 within the "transformed number" in point #9 in FALSEHOODS.md

> This transforms +54 9 2982 123456 into 02982 15 123456.

**Comment by dlyongemallo** [comment]
It says "to dial a mobile number domestically", so the country calling code is dropped.

See:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B5492982123456
National format	02982 15-12-3456
International format	+54 9 2982 12-3456

The point is that it's not a straightforward "change the digits in front somehow" to go from one to the other.
