### ISSUE TITLE
India new mobile numbers are returned as Fixed numbers

### ISSUE THREAD

**Issue by saivaranasi** [googlei18n/libphonenumber#1017]
We observed that there are new mobile numbers in India which start with +9173XXXXXXXX. These numbers are returned as fixed line numbers instead of mobile numbers. These are found to be new series mobile numbers. Please fix it.

**Comment by padmaksha** [comment]
Hi Sai,

Thank you for taking the time to improve libphonenumber!

Multiple valid subranges of 73 range are already returned as mobile type and not fixed-line type numbers by our library.
Can you please specify which specific number or subrange of 73 prefix you are trying to validate. Please find an example number for 73 range which is returned as mobile type [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B917304123456).

**Comment by saivaranasi** [comment]
Hi Padmaksha,
   Here are a few mobiles numbers that are returned as Fixed line.
+917337096728
+917396610154
+917337096432

**Comment by keghani** [comment]
These numbers are now categorized as FIXED_LINE_OR_MOBILE since the ranges can have either mobile or fixed-line numbers. Please update to the latest release to see the fix.
