### ISSUE TITLE
Add 7349 to valid mobile ranges in India

### ISSUE THREAD

**Issue by Shriniketannl** [googlei18n/libphonenumber#1018]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 7349074072, 7349074071

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 7349074XXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): toll-free

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
The above phone number mentioned are owned by me, It belongs to Airtel Karnataka India

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=7349074072&country=IN)

**Comment by padmaksha** [comment]
@Shriniketannl

Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
@Shriniketannl 
Fixed in release 7.3.1:
https://libphonenumber.appspot.com/phonenumberparser?number=7349074072&country=IN
