### ISSUE TITLE
Missing mobile prefix for Faroe Islands

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1019]
298-78 ( Føroya Tele) is missing. I will share documentation offline.

**Comment by penmetsaa** [comment]
@alecx 
Thanks for reporting this issue.
This is fixed in release 7.2.8, which is made live yesterday.
https://libphonenumber.appspot.com/phonenumberparser?number=781234&country=FO

We will update carrier name in an upcoming release.

**Comment by penmetsaa** [comment]
Closing this issue as carrier name is also updated.
