### ISSUE TITLE
Missing mobile prefix for Benin

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1020]
229-62 is used by MTN Benin. I do not have official documentation but the prefix is valid, some examples show up in the local white pages: 

https://www.google.ie/search?q=(%2B229)+62+site%3Ahttp%3A%2F%2Fwww.yellowpagesofafrica.com%2Fcompanies%2Fbenin

**Comment by alecx** [comment]
There's also 63 & 65 used by Moov.

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%28%2B229%29+62+41+0000
