### ISSUE TITLE
Missing mobile prefixes for Kenya

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1021]
254-776, 777 -> Telkom Kenya
254-795 -> Safaricom

I will share the documentation offline.

**Comment by penmetsaa** [comment]
@alecx 
Thanks for providing all the details we need!
We've accepted the issue for 776, 777 ranges and will fix this in an upcoming release.

We already support 795 range.
https://libphonenumber.appspot.com/phonenumberparser?number=795123456&country=KE

**Comment by padmaksha** [comment]
Fixed in release 7.3.0. 
http://libphonenumber.appspot.com/phonenumberparser?number=%2B254+777+010+000
