### ISSUE TITLE
Missing mobile prefixes for Cambodia

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1022]
Seatel Cambodia uses 855-18-xxxxxxx and several 855-xy48-abcde ranges. I'll share documentation offline.

**Comment by penmetsaa** [comment]
@alecx ,
We have added support for 855-18-xxxxxxx numbers in release 7.3.1:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B855+18+99+00+898

Thanks for providing all the details of 855-xy48-abcde numbers. 
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
@alecx ,
Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by keghani** [comment]
This was fixed, e.g. see http://libphonenumber.appspot.com/phonenumberparser?number=2348-00000&country=KH
