### ISSUE TITLE
Missing mobile prefix for Mauritius

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1023]
Cellplus:
230 580 xxxxx
230 581 xxxxx

I'll share documentation offline.

**Comment by padmaksha** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by andyst** [comment]
@alecx you can check things with the demo on AppEngine before reporting issues.
We also have nice permalinks now, e.g.
http://libphonenumber.appspot.com/phonenumberparser?number=%2B23058012345

Please reopen if you can reproduce the issue with the latest demo.
