### ISSUE TITLE
Missing mobile prefixes for Vietnam

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1024]
Vietnamese carriers started using 84-8xx-yyyyyy prefixes for mobile phones. I'll share documentation offline.
VNPT - 888
Mobifone - 898
Viettel - 868

**Comment by penmetsaa** [comment]
@alecx

Thanks for reporting this issue and providing required evidences.

The ranges 868, 888 and 898 are already supported as landline numbers.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B84+868+123456

We already have github issue [#992](https://github.com/googlei18n/libphonenumber/issues/992) for moving these ranges to mobile.

We will start working on it and post updates in github issue [#992](https://github.com/googlei18n/libphonenumber/issues/992).
