### ISSUE TITLE
Missing mobile prefix for Mali

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1025]
Orange: 223-82/83
Malitel: 223-89

I'll share documentation offline.

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%2B223+82+00+0000
Prefix 89 has not been added as there was no evidence found.
Please reopen this issue if you have evidence on the same,
