### ISSUE TITLE
Missing mobile prefix for Côte d'Ivoire

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#1026]
Moov Côte d'Ivoire uses 22551xxxxxx prefix. No official documentation but the prefix is listed on http://fr.wikipedia.org/wiki/Liste_des_indicatifs_téléphoniques_en_Côte_d’Ivoire

**Comment by penmetsaa** [comment]
@alecx 
Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%2B225+51+22+00+00
