### ISSUE TITLE
Google Fi Provider appears as other Providers

### ISSUE THREAD

**Issue by nerdpanda** [googlei18n/libphonenumber#1028]
I realize this isn't a pressing issue, but I've noticed that phone numbers that are provided through Google Fi are, at least in my instance, being assigned to various providers such as Vodafone and Verizon.

**Comment by penmetsaa** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
@nerdpanda 
Google Project Fi is only available in the US (per [Google support page](https://support.google.com/fi/answer/6172835?hl=en&ref_topic=4596407))

The phone numbers are assigned to Project Fi from general pool. Not that there are specific Fi prefix that are allocated. So we can make no assumptions here.

Like many other countries, US has mobile number portability. So the carrier mappings we have for different countries are only a guide anyway.

Closing this issue as infeasible for now. Please reopen if you have anything else to be added here.
