### ISSUE TITLE
New Belize phone numbers not validating

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1037]
This Belize phone number is a working phone number that you can call successfully, but the libphone is not validating it yet: +5016519885

This number is also reachable +5016529885, so I believe the +501 65x prefix is valid. Can this prefix please be added to the library?

**Comment by rzaryan** [comment]
Country/region affected: BZ (Belize)
Example number(s) affected: +5016519885, +5016529885
The phone number range(s) to which the issue applies: +501 65X XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a

**Comment by padmaksha** [comment]
@rzaryan

Thank you for taking the time to improve libphonenumber!
We've accepted this issue and will fix this in an upcoming release.
Can you just confirm what carrier you expect this mobile range 65X to be for and could you provide any evidence for it?

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%2B5016519885
