### ISSUE TITLE
Consider +5582988302329 valid and MOBILE in Brazil

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1041]
This number is reachable +5582988302329 and it should be a mobile number.

However, it is showing up as not a valid number in libphone: 

****Parsing Result:****
{"country_code":55,"national_number":82988302329,"raw_input":"+5582988302329","country_code_source":1,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: BR
Result from getNumberType(): UNKNOWN

**Comment by rzaryan** [comment]
Another example of a number that should also be validated with the inclusion of the '9' in between the area code and number is this: +55 (73) 94102-0799

Call it w/o the 9 and you get nothing. Call it with the 9 and you eventually reach either a person or an answering machine.

**Comment by rzaryan** [comment]
Context on the inclusion of the '9' in between the two-digit area code and the eight-digit phone number: https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil#Ninth_digit_for_mobile_numbers

**Comment by rzaryan** [comment]
Any update on this?

**Comment by keghani** [comment]
Re. the original issue, it is no longer an issue: http://libphonenumber.appspot.com/phonenumberparser?number=%2B5582988302329&country=BR

Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) for how to check in the future.

Re. the other issue I filed https://github.com/googlei18n/libphonenumber/issues/1086 and will take a look tomorrow. Please open new issues separately.
