### ISSUE TITLE
Since both CUBA and US phone numbers are 10 digits, So when we met a number in 10 digits, how do we know it is a CUBA number or US phone number if we use this util function?

### ISSUE THREAD

**Issue by jyx1369** [googlei18n/libphonenumber#1047]
For example, when we use the code this lib provided:
`Phonenumber.PhoneNumber phoneNumber = phoneNumberUtil.parse(phoneNumberToParse, "US");`

If we don't know when to add a '+' for  phoneNumberToParse, then when we parse the number "5347518460"(cuba phone number), it would regard it as a US number instead of cuba. Then how do we handle this situation?

PS: only when we have phone number with "+",  like "+5347518460", we can get the right country code for "CU", otherwise cannot get it correctly. So how do we know when to add "+" or no when using this util function?

**Comment by padmaksha** [comment]
@jyx1369

You can find how the parse method works [here](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2772). 
The best way to parse a number correctly is to know the country code where the number is being dialled from and provide it when parsing, or use a phone widget to enter the phone number in an international format such that it can be unambiguously understood. It is better not to explicitly provide the “+” symbol unless you are sure that it should be there.
For example, if the number is provided as “5347518460” and the country code “CU” is provided along with it the the number would be interpreted correctly even without the “+” symbol.
You can use our [demo](http://libphonenumber.appspot.com/) to test this. 

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
