### ISSUE TITLE
Why some regions share same countryCode?

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#1053]
Hello, I encountered a problem that a number +61425068632 that can not be printed geography description (it is empty). I checked code and found that AU, CC and CX share the same countryCode 61 and their mobile phone number rules are the same. PhoneNumberOfflineGeocoder can not decide to use which region description then empty string returns.
I asked our colleague in Australia and he told me CC and CX are in fact the territory of Australia. So I am doubt why libphonenumber separate these three regions in different metadatas? Will it bring any troubles if I merge them into one?
Furthermore, I checked all supported regions in libphonenumber and found 12 regions list that share a same countryCode, as below:
1 US AG AI AS BB BM BS CA DM DO GD GU JM KN KY LC MP MS PR SX TC TT VC VG VI 
262 RE YT 
61 AU CC CX 
358 FI AX 
7 RU KZ 
590 GP BL MF 
599 CW BQ 
290 SH TA 
47 NO SJ 
212 MA EH 
44 GB GG IM JE 
95 MM ZG
then I recognize this may be a mechanism in libphonenumber, so could you please describe it?
Thank you~

**Comment by yarcub** [comment]
Take a look at https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md.

The codes are defined in [ISO 3166](http://www.iso.org/iso/country_codes). Although Christmas Island is an Australian territory, it was assigned with it's own ISO Code (`CX`). Maybe it can be considered an autonomous entity (?), like Monaco that also has their own code (`MC`).

> The purpose of ISO 3166 is to define internationally recognised codes of letters and/or numbers that we can use when we refer to countries and subdivisions. However, it does not define the names of countries – this information comes from United Nations sources (Terminology Bulletin Country Names and the Country and Region Codes for Statistical Use maintained by the United Nations Statistics Divisions).

Regarding, country calling codes, [ITU](https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164D-11-2011-PDF-E.pdf) is responsible to assigned them. We can not expect that each country has their own. That are many factor that may lead to this. 

For example. Although most former Soviet republics switch country codes after the fall of the Soviet Union, Kazakhstan kept ([+7](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000AD0001MSWE.doc)) and in 2006 became part of Russia's National Numbering Plan.

> - Joint Communiqué of 11.VIII.2006:
The Ministry for Information Technologies and Communications of the Russian Federation, Moscow (Russian Federation) and the Agency of the Republic of Kazakhstan for Informatization and Communication, Astana (Kazakhstan), announce in this joint communiqué that they have signed an Agreement on the use of the international E.164 numbering resource of the numbering zone “7”.
Under the Agreement, the Administrations of the Russian Federation and the Republic of Kazakhstan retain the numbering zone “7”, pursuant to the Table of assigned codes of the numbering zone “7”. 

I'm not in any way an expert on this, but like you i was curious about it. After researching a little about it, made me appreciate even more the existence of `libphonenumber`. :smile:

**Comment by lethianqt94** [comment]
I have the same problems with which based on this lib: https://github.com/iziz/libPhoneNumber-iOS

**Comment by Mortimer2013** [comment]
Please take a look at 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Christmas_Island
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Cocos_(Keeling)_Islands.
Christmas Island and Cocos Islands used +672 country code until 1994, so this may be a choice based on history?

**Comment by lararennie** [comment]
It seems yarcub has answered this, thanks yarcub@!

I'll close this as it's not an issue with the library. Please consider joining the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
