### ISSUE TITLE
Validation issue with 2461380712 (MX)

### ISSUE THREAD

**Issue by AlfLuis** [googlei18n/libphonenumber#1058]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): MX

Example number(s) affected ("+1 555 555-1234"): 2461380712

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=2461380712&country=MX&geocodingLocale=und)

**Comment by penmetsaa** [comment]
@AlfLuis,

Thank you for using libphonenumber!
Looks like there is no issue with libphonenumber. 
It returns 2461380712 as valid fixedline number, see the [demo page](http://libphonenumber.appspot.com/phonenumberparser?number=2461380712&country=MX&geocodingLocale=und).

Please let us know what is the exact issue here.
Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)
