### ISSUE TITLE
Validation issue with +917349448642

### ISSUE THREAD

**Issue by parasnarang** [googlei18n/libphonenumber#1059]
Country/region affected (e.g., "US"): India

Example number(s) affected ("+1 555 555-1234"): +917349448642

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B917349448642)

**Comment by penmetsaa** [comment]
@parasnarang 
Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
Duplicate of #1018
