### ISSUE TITLE
Invalid area code passes as valid number +1 123 123 12321

### ISSUE THREAD

**Issue by klassicd** [googlei18n/libphonenumber#1061]
This number should be rejected for an invalid US area code.  If you subtract or add digits it will fail but it's being parsed as +1 231-231-2321 in the Phone Number Parser Demo.

**Comment by penmetsaa** [comment]
@klassicd

Thanks for reporting this issue.

I believe you are referring to the number +1 123 123 12321
The national prefix of US (i.e 1) is the same as its country code.

When parsing the number, libphonenumber trims off the country code and then national prefix (if they are present in input) and later, if you ask to validate the number, we have 231 231 2321 which we consider valid.  231 XXX XXXX is a valid range for US. 

This is done for all the countries. We ignore formatting when parsing, so the number grouping here doesn't tell us the number is invalid.
