### ISSUE TITLE
Swiss language translation

### ISSUE THREAD

**Issue by yasenpetrov88** [googlei18n/libphonenumber#1063]
Hello,

In the current version for a Swiss phone number the text shown is Switzerland (Schweiz). As there are 3 main languages in Switzerland would you be able to change it to Switzerland (Schweiz/Suisse/Svizzera)?

Thank you in advance!

Kind Regards,

Yasen Petrov

**Comment by keghani** [comment]
Hi Yasen,

Thanks for reporting! This is not an issue with our library though. Please ask the people who maintain the product that you're using.

See our demo for example, which displays the English name (no "Schweiz"): http://libphonenumber.appspot.com/phonenumberparser?number=%2B41+76+541+0000&country=CH

If the product is also displaying finer geocoding information (for fixed-line numbers), they can use our localized geocoding metadata:

https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/41.txt
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/fr/41.txt
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/it/41.txt
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/de/41.txt
