### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by xseven** [googlei18n/libphonenumber#1064]
Hello,

I'm trying to build libphonenumber under win using cmake 3.5.1 and MS VC++ 2015 

and seems like readdir_r function in generate_geocoding_data.cc is miisng on windows 
plus in your documentation http://www.boostpro.com/download/ link is broken

Cheers

**Comment by xseven** [comment]
Partially resolved by adding proper boost libs

**Comment by landrix** [comment]
i don't have enough expierence with C++, can you provide a tutorial or the dll itself to me and everyone else?

**Comment by xseven** [comment]
I think I can provide static libs (MSVC 2015) since I use them. I'll notify you in this issue.

Maybe updated tutorial of how to build. Maybe later this weekend but I don't promise

**Comment by xseven** [comment]
Here we go. Debug lib with includes and tests. You might need to install MSVC14 redist (Or you need MSVC 2015 to develop with this pack)

https://github.com/xseven/toy-projects/blob/master/libphonenumber/libphonenumber-redist-debug.7z

Later I can produce guide how to build if somebody will need it. Enjoy

Cheers

**Comment by keghani** [comment]
@xseven if you write a guide please consider contributing it under https://github.com/googlei18n/libphonenumber/blob/master/cpp/README :)

**Comment by xseven** [comment]
@keghani sure,  no worries

@xseven <https://github.com/xseven> if you write a guide please consider
contributing it under
https://github.com/googlei18n/libphonenumber/blob/master/cpp/README :)

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1064#issuecomment-209525397>

**Comment by landrix** [comment]
@xseven thank you
