### ISSUE TITLE
isValidNumber function returning "true" for invalid mobile number in Brazil

### ISSUE THREAD

**Issue by jean-andrade** [googlei18n/libphonenumber#1065]
For all area codes, except São Paulo state, where added the "9" digit, the function is returning "true" for number without the "9" digit before of eight digits.

e.g:(81) 9104-2155, (31) 8404-2155, (71) 8704-2155, (21) 9104-0175, (91) 9154-0123

These numbers are no longer valid

**Comment by keghani** [comment]
Thanks for reporting @jean-andrade!

We're following the Brazil renumbering updates closely and are aware of these ranges. We will keep them "valid" in the library to indicate that they're in transition. Both the old and new format are supported at this time, but previously renumbered ranges such as those beginning with 1 are already out of transition in the library. We'll remove these ranges out of transition when the old numbers are no longer in use.

For further discussion please consider joining [libphonenumber-discuss](https://groups.google.com/forum/#!forum/libphonenumber-discuss). I'll close as this is not an issue with the library.
