### ISSUE TITLE
javanano is not available in protobuf 2.6.1

### ISSUE THREAD

**Issue by puntogil** [googlei18n/libphonenumber#1070]
Hi
any ideas?

[INFO] Skipping libphonenumber-build-parent
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Libphonenumber build tools ......................... SUCCESS [  0.005 s]
[INFO] Libphonenumber common library for build tools ...... FAILURE [  4.440 s]
[INFO] Libphonenumber C++ build tools ..................... SKIPPED
[INFO] Libphonenumber Data tools .......................... SKIPPED
[INFO] Libphonenumber Java and JavaScript build tools ..... SKIPPED
[INFO] libphonenumber-parent .............................. SKIPPED
[INFO] libphonenumber ..................................... SKIPPED
[INFO] prefixmapper ....................................... SKIPPED
[INFO] carrier ............................................ SKIPPED
[INFO] geocoder ........................................... SKIPPED
[INFO] libphonenumber-build-parent ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.793 s
[INFO] Finished at: 2016-04-07T11:04:38+02:00
[INFO] Final Memory: 21M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project common-build: Compilation failure: Compilation failure:
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[188,31] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[226,49] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[260,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[290,40] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[295,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[9,31] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[302,31] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[59,49] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[121,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[176,40] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[181,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[452,49] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[698,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[920,40] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[925,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[932,31] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[962,49] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[992,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[1030,40] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[1035,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java:[21,32] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java:[78,10] cannot find symbol
[ERROR] symbol:   class CodedInputByteBufferNano
[ERROR] location: class com.google.i18n.phonenumbers.MetadataManager
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[16,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[15,22] illegal start of type
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[50,54] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[54,7] cannot find symbol
[ERROR] symbol:   variable cachedSize
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.NumberFormat
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[58,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[80,7] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.NumberFormat
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[83,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[85,18] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.NumberFormat
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[86,39] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[88,39] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[97,49] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[105,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[109,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[113,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[119,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[129,42] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[143,55] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[177,38] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[195,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[194,22] illegal start of type
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[221,7] cannot find symbol
[ERROR] symbol:   variable cachedSize
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneNumberDesc
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[225,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[237,7] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneNumberDesc
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[240,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[242,18] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneNumberDesc
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[244,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[248,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[252,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[258,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[268,42] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[291,38] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[309,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[308,22] illegal start of type
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[447,7] cannot find symbol
[ERROR] symbol:   variable cachedSize
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneMetadata
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[451,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[555,7] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneMetadata
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[558,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[560,18] cannot find symbol
[ERROR] symbol:   variable super
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneMetadata
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[562,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[566,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[570,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[574,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[578,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[582,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[586,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[590,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[593,39] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[596,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[600,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[604,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[608,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[612,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[616,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[620,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[624,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[631,45] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[640,45] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[646,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[650,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[654,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[658,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[662,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[666,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[670,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[674,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[678,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[682,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[686,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[690,41] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[696,5] method does not override or implement a method from a supertype
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[706,42] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[804,55] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[824,55] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[921,38] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[939,37] package com.google.protobuf.nano does not exist
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[938,22] illegal start of type
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[957,7] cannot find symbol
[ERROR] symbol:   variable cachedSize
[ERROR] location: class com.google.i18n.phonenumbers.nano.Phonemetadata.PhoneMetadataCollection
[ERROR] ~/rpmbuild/BUILD/libphonenumber-libphonenumber-7.3.0/java/libphonenumber/src/com/google/i18n/phonenumbers/nano/Phonemetadata.java:[961,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]

Since, this features are available in protobuf >= 3.0.0-alpha-1
Thanks in advance

**Comment by keghani** [comment]
Hi @puntogil,

I would guess this is happening because you don't have a javanano protocol buffer compiler in the local Maven repository (`~/.m2/repository`).

Correct, javanano is avaliable in >= 3.0.0 in GitHub (and Maven Central), but [external/protobuf](https://android.googlesource.com/platform/external/protobuf/+/master) has had it since 2.6. We put a snapshot of this in the local Maven repository from our source, not from Maven Central. See [java/lib/com/google/protobuf](https://github.com/googlei18n/libphonenumber/tree/master/java/lib/com/google/protobuf).

I'm confused why this isn't working for you. What commands are you running? What's your setup?

I can get this to work:

```
$ mkdir clone && cd clone && git clone https://github.com/googlei18n/libphonenumber.git && cd libphonenumber
$ mvn package
```

After all builds succeed I have a non-empty directory `~/.m2/repository/com/google/protobuf/protobuf-java/2.6.1/`.

Can you run this and share the output? Also try to look into `~/.m2/repository/` for protobuf. Maybe you have several versions (see https://github.com/googlei18n/libphonenumber/issues/913).

**Comment by puntogil** [comment]
hi
i packaged libphonenumber [1] for Fedora [2]
and i wondered how is easy done this confusion with original protobuf code and the chrome fork implementation.
For fedora packaging guideline is not possible use pre built libraries, our build system do not have a web connection, we use exclusively system libraries
thanks
regards
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1200115
[2] https://fedoraproject.org/wiki/Overview

**Comment by keghani** [comment]
Please share more details about the command lines you're using. I want to be able to reproduce the issue. I also don't understand the relevance of [[1]](https://bugzilla.redhat.com/show_bug.cgi?id=1200115); it looks like an issue, not a package. And it's from before 7.2, which introduced javanano.

Maybe this could help: see [cpp/README](https://github.com/googlei18n/libphonenumber/blob/master/cpp/README), "Manually installing the library on GNU/Linux". I would try `sudo apt-get install protobuf-compiler`.

**Comment by puntogil** [comment]
for import a package in Fedora distribution we must open a bug [1]
until is not reviewed by other persons we cant share the package
concerning our maven tool we use xmvn [3]
this is an example of our maven command line, using mvn_build macro
 xmvn --batch-mode --offline  -Dproject.build.sourceEncoding=UTF-8 package org.fedoraproject.xmvn:xmvn-mojo:install org.apache.maven.plugins:maven-javadoc-plugin:aggregate org.fedoraproject.xmvn:xmvn-mojo:builddep

[3] https://mizdebsk.fedorapeople.org/xmvn/site/

**Comment by puntogil** [comment]
protobuf-compiler is already installed is listed as BuildRequires

**Comment by keghani** [comment]
Hi @puntogil,

Our Maven build is hermetic as of 7.6.0 and does not require you to have any special setup for protocol buffers!

See release notes: https://github.com/googlei18n/libphonenumber/releases/tag/libphonenumber-7.6.0

Thanks for reporting, and thanks for your patience!
