### ISSUE TITLE
Validation issue with on 7331127454 Android library.

### ISSUE THREAD

**Issue by nareshreddym** [googlei18n/libphonenumber#1075]
We are using the library for iOS And android aswell in our projects , we are trying to validate the mobile number of a user(7331127454),but even if this 7331127454 is a valid format and valid number in India,the library is returning as it is an unknown(-1) number which is blocking us,So please we are hoping for the kind attention on the issue.would be really great if this kind of issues were solved. 

****
The issue was solved in iOS But we are unable to find the recent / updated jar for android,
we would be very great-full if we could get any solution or android library's download link.

Thanks in-advance.

**Comment by padmaksha** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=7331127454&country=IN).
Please find the latest jar files [here](http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/).
I'll close this as it's not an issue with the library.
_Help us help you! Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)
when reporting issues._
