### ISSUE TITLE
New Australia (AU) metadata

### ISSUE THREAD

**Issue by mitchellarchibald** [googlei18n/libphonenumber#1079]
Country: Australia (AU)
Source: Public information from governing body: https://www.thenumberingsystem.com.au/#/number-register/search
The block can be searched on this page, or the complete allocation register can be downloaded.
### Newly allocated +61 436 xxx xxx mobile block

Example number: +61 436 123 456
Range: +61 436 000 000 to +61 436 499 999
Type: Mobile
Block allocated to TELSTRA CORPORATION LIMITED on 2016/02/29.
### Newly allocated +61 8 7xxx xxxx fixed line blocks

There are a number of allocations in the +61 8 77xx xxxx and +61 8 78xx xxxx blocks, starting in 2012.  I think we should extend validation to all these numbers.
Type: Fixed line
Example number: +61 8 7701 2345
### Eight-digit premium-rate numbers

Eight-digit premium-rate numbers are allocated in three eight-digit blocks:
- 196 xxxxx
- 197 xxxxx
- 199 xxxxx

Examples:
19660044
19789104
19906666
### Eight-digit shared cost numbers

Eight-digit local-rate numbers have been allocated since 1993.  
Type: Shared cost
Example: 13452709
Range: 13450000 - 13454999

**Comment by penmetsaa** [comment]
@mitchellarchibald,

Thanks for providing all the details we need! We've accepted this issue.

This update consists of more than 600K lines that we need to verify. 
So we are planning to add the prefixes that you have mentioned on priority and support whole document later. We will keep you posting the updates.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
All prefixes mentioned are fixed in release 7.3.2: https://libphonenumber.appspot.com/phonenumberparser?number=%2B61+436+123+456

Supporting whole document will be done later releases.

**Comment by mitchellarchibald** [comment]
@penmetsaa, thanks for your help!
