### ISSUE TITLE
Update carrier details for United Kingdom (GB)

### ISSUE THREAD

**Issue by IainSutherland** [googlei18n/libphonenumber#1080]
Hi.

I found an issues with the carrier not being returned for this number - 447393201833

However the OFCOM numbering plan lists 447393 as Vodafone UK Ltd

Country/region affected : GB

Example number(s) affected : 447393201833 - Although I suspect it's the whole 447393 range 4473930 - 4473939

The type of the number(s) : mobile 

Supporting evidence: Attached the public carrier list from Ofcom
[S7.zip](https://github.com/googlei18n/libphonenumber/files/225544/S7.zip)

 [link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=447393201833&country=GB)

Thanks.

Iain

*Note, this range was allocated at the end of 2015, along with quite a few others.

**Comment by penmetsaa** [comment]
@IainSutherland 

Thanks for providing all the details we need!
We've accepted this issue and will fix this in an upcoming release.

**Comment by IainSutherland** [comment]
Thanks!

**Comment by giggsey** [comment]
@penmetsaa Will the full Ofcom carrier list be put into libphonenumber, not just this mobile range?

Also, the Ofcom list contains all prefixes, not just the Mobile, Fixed Line or Mobile, and Pager (the number types the Carrier Mapper supports) numbers?

Thanks

**Comment by penmetsaa** [comment]
@giggsey,

Thanks for your interest :)

We will support all the mobile and pager carrier updates that are mentioned in s7.xls as part of this issue.

In next coming updates we will start supporting documents that are listed in http://www.ofcom.org.uk/static/numbering/

Presently library can provide carrier details only for mobile and pager numbers. Not for numbers like fixed-line, personal numbers...etc

**Comment by DrHyde** [comment]
Is there any intention to expand it cover include carrier details for fixed lines etc in the future? If there is it would make sense to at least start gathering that data even if it's not yet used.

Also note that OFCOM don't publish anything about number portability.

**Comment by kkeshava** [comment]
@DrHyde,

We have no plans of including carrier details for fixed line numbers hence we won’t be collecting the data. However out of curiosity, we would like to know as to how can this data be useful for you.

**Comment by DrHyde** [comment]
I maintain [Number::Phone](https://metacpan.org/pod/Number::Phone), which is a mostly work-a-like for libphonenumber in perl. It supports a bit more functionality than libphonenumber, in particular exposing carrier details for any number where I have the information for it. It also allows third-parties to extend it by providing country-specific data themselves instead of trying to do everything itself, although for countries where I don't have better information I just suck in libphonenumber's metadata.

There is also a slight difference of emphasis - libphonenumber is aimed more at phone users, whereas Number::Phone is aimed more at small telcos, a number of which use it in their billing and provisioning systems.

**Comment by kkeshava** [comment]
Thanks for explaining your use case. It's not clear to us how this information can be useful for users and clients of the library so for now we'll keep maintaining carrier data only for mobile ranges. This could change in the future.

**Comment by giggsey** [comment]
Just as a FYI for those who are subscribed.

v8.0.1 now contains carrier information for GB mobiles.

**Comment by keghani** [comment]
Thanks @giggsey! We're still updating the metadata for +44 regions (GB, GG, IM, JE) but that's separate from this issue, so I'll close it.
