### ISSUE TITLE
phone number  match return "SHORT_NSN_MATCH" issue

### ISSUE THREAD

**Issue by qiuxinyidian** [googlei18n/libphonenumber#1081]
I have found a issue:
          when  I compared taibei phone number  0935833921 with  935833921 using libphonenumber-7.2.5.jar, it returned MatchType.SHORT_NSN_MATCH  ,should it returned  MatchType.NSN_MATCH?
 
Any help will be appreciate  !

**Comment by keghani** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Also see the Javadoc: https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3083

**Comment by qiuxinyidian** [comment]
Country/region affected ("TW"):
Example number(s) affected (" 093583XXXX"):
The phone number range(s) to which the issue applies ("93583XXXX"):
The type of the number(s) ("short code"):
The cost, if applicable ("toll-free""):

**Comment by lararennie** [comment]
Can you provide the code? We need the exact code to reproduce so we can fix
it (or decide it's work-as-intended).

Note that this enum can be returned if you don't provide the country for
both numbers, for instance.

2016-04-21 8:47 GMT+02:00 qiuxinyidian <notifications@github.com>:

**Comment by qiuxinyidian** [comment]
this is my code as bellow ：compare two phone numer ，if result is NSN_MATCH or EXACT_MATCH ，I think the number is equal ，if not  ，numbers not equal 。 
@Override
	public Contact getFriendInfoByPhone(String aPhone) {
		// TODO Auto-generated method stub

		if (null == aPhone || aPhone.length() == 0) {
			return null;
		}
		if (null == mContacts || mContacts.size() == 0) {
			//
			getContactsList();
			if(null == mContacts || mContacts.size() == 0)
			{
				return null;
			}
			
		}
		LogTool.d(TAG, "getFriendInfoByPhone ");

		 PhoneNumberUtil tmpPhoneNumberUtil = PhoneNumberUtil.getInstance();

	     for (Contact tmpContact : mContacts) {
	    	 LogTool.d(TAG, "comming call  = " + aPhone + "tmpContact.getPhone() = " + tmpContact.getPhone());
	    	 MatchType tmpMatchResult= tmpPhoneNumberUtil.isNumberMatch(tmpContact.getPhone(), aPhone);
	    	 LogTool.d(TAG, "MatchType = " + tmpMatchResult);
	    	 if(tmpMatchResult ==  MatchType.NSN_MATCH || tmpMatchResult == MatchType.EXACT_MATCH)
	    	 {
	    		 LogTool.d(TAG, "match comming call  = " + aPhone + "tmpContact.getPhone() = " + tmpContact.getPhone());
	    		 return tmpContact;
	    	 }
	    	 else
	    	 {
	    		 continue;
	    	 }
	     }
		return null;
	}
}

**Comment by qiuxinyidian** [comment]
when it comes 935833921 and 0935833921 ，it returns SHORT_NSN_MATCH

**Comment by keghani** [comment]
Our library is working as intended. Please read the Javadoc when using library functions: https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3083

In this case, you're getting this behavior because isNumberMatch(PhoneNumber, PhoneNumber) "Returns SHORT_NSN_MATCH if either or both has no region specified, or the region specified is the same, and one NSN could be a shorter version of the other number. This includes the case where one has an extension specified, and the other does not."

**Comment by qiuxinyidian** [comment]
Number matching is returning a wrong match #791 
Did this issue have  fixed？
