### ISSUE TITLE
Add 732\d{4} as valid Belize range

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1085]
There is a hotel called The Lodge At Big Falls located in Belize that has a phone number of +501 732-4444 and it is not validating, even though I can call it successfully.

Reference URL: http://www.thelodgeatbigfalls.com/contact-us/ 

Can this be added to the library please? Let me know if you need additional context.

**Comment by penmetsaa** [comment]
@rzaryan 

Thanks for reporting this issue.

We are not able to find what type of number is this. Looks like a landline number.

Please share any document / webpage by the government or the telecom company (carrier) which classifies this number/range as fixed-line (land line) or mobile.

**Comment by jjaazz** [comment]
http://www.belizespicefarm.com/index.php/contact shows  (501) 732-4014 as another one that doesn't validate

**Comment by penmetsaa** [comment]
@jjaazz 

Thanks for providing the reference.

We accept that 732 range numbers are valid phone numbers in Belize. 
But we are not sure whether these 732 range numbers are mobile / landline.

We can support 732 numbers only when there is evidence about its category. 
Please share any document / webpage by the government or the telecom company (carrier) which classifies this number/range as fixed-line (land line) or mobile.

**Comment by keghani** [comment]
Hi!

Just to be clear - we cannot support 732 until we know whether it is fixed-line or mobile. Any help would be appreciated.

**Comment by penmetsaa** [comment]
Friendly ping - please clarify. We can't proceed without the required evidence.

**Comment by jjaazz** [comment]
Still checking

**Comment by jjaazz** [comment]
According to Belize Telemedia Ltd these numbers are "Landline Postpaid PSTN" and routing as Fixed-Line.

**Comment by padmaksha** [comment]
Fixed in Release 7.4.2 
Demo: http://libphonenumber.appspot.com/phonenumberparser?number=7324444&country=BZ

**Comment by penmetsaa** [comment]
@jjaazz 
Thanks for the information provided. 
We have added it to fixed-line category for now with some comments in metadata file. 

Can you please point us to the Belize Telemedia Ltd page that says 732 XXXX range is "Landline Postpaid PSTN". So that we can remove / update the comments.

**Comment by jjaazz** [comment]
This was from directly contacting them, not their online docs.

**Comment by penmetsaa** [comment]
Thanks so much @jjaazz . :)
