### ISSUE TITLE
Add Tajikistan mobile number (+99288)

### ISSUE THREAD

**Issue by jaimefrites** [googlei18n/libphonenumber#1092]
New mobile numbers are used in Tajikistan (TJ), they start with +992 88.

For example, a travel agency on http://www.sareztour.com/ provides phone +992888887074 .

For evidence I provide a page of russian mobile provider, which said such phone numbers are belong to tajik mobile provider http://moscow.megafon.ru/tariffs/options/archive/megafon_tajikistan1.html .

And a page of that tajik mobile provider http://megafon.tj/shop/ .

**Comment by padmaksha** [comment]
@jaimefrites 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.3.2: https://libphonenumber.appspot.com/phonenumberparser?number=%2B992888887074
