### ISSUE TITLE
Area code +1 743 going into service 23 May 2016; +1 934 follows 16 July 2016

### ISSUE THREAD

**Issue by charness** [googlei18n/libphonenumber#1093]
The NANPA area code 743 will go into service 23 May 2016 as a geographic overlay of area code 336.

Country/region affected (e.g., "US"): US
Example number(s) affected ("+1 555 555-1234"): +1 743 555-1212
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1 743 XXX-XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line/mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

[NANPA _Planned NPAs Not Yet in Service_ Report](https://www.nationalnanpa.com/enas/plannedNpasNotInServiceReport.do)
[NANPA _Planning Letter PL-475_](https://www.nationalnanpa.com/pdf/PL_475.pdf), which updated one date in the following
[NANPA _Planning Letter PL-469_](https://www.nationalnanpa.com/pdf/PL_469.pdf)
[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+743+555-1212)

Note on the _Planned NPAs_ report two additional area codes going into service within 90 days which should already be active for testing. I suggest also implementing at least the first at this time.

548 going into service 4 June 2016
"The following test numbers for the new NPA 548 will be made available effective 4 March 2016."
— [PL-472](https://www.nationalnanpa.com/pdf/PL_472.pdf)
Verified 25 April 2016 via call to test number +1 548-610-8378.

934 going into service 16 July 2016
"A test number to verify the routing to the new NPA will be in service beginning March 16, 2016 through August 16, 2016."
— [PL- 476R1](https://www.nationalnanpa.com/pdf/PL_476R1.pdf).
Call to test number +1 934-990-8378 failed 25 April 2016.

**Comment by padmaksha** [comment]
@charness
 
Thank you for using libphonenumber!
We're working on this issue. We'll update this thread when it's released.

**Comment by charness** [comment]
PR #1102 added 743 to the metadata, and I can confirm that the demo shows it as valid. 

I see a 7.0.4 change from March 2015 (d480f21) that added 548, and the demo also shows it as valid (and should have at the time I filed this issue).

No support yet for 934, though, which is due to go into service 30 days from today.
[link to demo for 934](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+943+555-1212)

**Comment by charness** [comment]
I see @padmaksha added area code 934 in 6b348f4e for 7.4.4. Confirmed valid with the demo.

Closing the issue.
