### ISSUE TITLE
Inmarsat C phone number validation

### ISSUE THREAD

**Issue by de1phi48** [googlei18n/libphonenumber#1094]
Good day.

The Inmarsat C phone numbers not success validation. Please, add this phone types in lib.

**Comment by penmetsaa** [comment]
Thank you for taking the time to improve libphonenumber!

_Help us help you! Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) when reporting issues._

**Comment by keghani** [comment]
We don't have enough details to fix this (don't even know the region). Closing. Please see the contribution guidelines linked above.

**Comment by lararennie** [comment]
We have Inmarsat supported, country code 870, so it's probably an error with how you are using the library, or their ITU doc is out of date. As Keghani said, please see the contribution guidelines before filing a bug.
