### ISSUE TITLE
Ethiopia (ET) prefix 967

### ISSUE THREAD

**Issue by petert82** [googlei18n/libphonenumber#1096]
Country/region affected: ET
Example number affected: `+25196772673X`
The phone number range(s) to which the issue applies: `+251967XXXXXX`
The type of the number(s): mobile

Possibly related to #748, it appears that there are valid Ethiopian mobile numbers beginning with 967. I can't find any official documentation of this from Ethio Telecom, but I have users who have been calling a number in the range of the example number given above, and the number works and is a mobile phone.

**Comment by penmetsaa** [comment]
@petert82 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.3.2: https://libphonenumber.appspot.com/phonenumberparser?number=%2B251967726739
