### ISSUE TITLE
India prefix 7414

### ISSUE THREAD

**Issue by itsadok** [googlei18n/libphonenumber#1097]
We encountered an Indian Vodafone phone number of the form +91 7414 0xx xxx, which libphonenumber claims is invalid. Unfortunately, I haven't been able to find documentation for this prefix.
(All I could find is that `+917414[2-7]\d{5}` numbers are Jaora area land lines, but this seems unrelated).

**Comment by penmetsaa** [comment]
@itsadok 

Thanks for providing the details! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.3.2: https://libphonenumber.appspot.com/phonenumberparser?number=%2B91+7414+012+345
