### ISSUE TITLE
French Prefix 0700

### ISSUE THREAD

**Issue by lbeauvisage** [googlei18n/libphonenumber#1098]
- Country/region affected : FR
- Example number(s) affected : + 33 700 XX XX XX
- The phone number range(s) to which the issue applies : + 33 700 XX XX XX
- The type of the number(s): mobile M2M

Phone number starting by 0700 (national) , + 33 700 (international) are not valid mobile phone number.

According to http://www.arcep.fr/index.php?id=8146, number starting by "0700" are dedicaced to "Machine to Machine" and has an extended length (13 and 14 digits).
Complets specifications are available here : http://www.arcep.fr/uploads/tx_gsavis/12-0855.pdf (page 17)

So `700\d{6}` is not a valid mobile phone number pattern.

Valid mobile phone number : 7[3-9]\d{7}
Valid M2M number :

```
700(?:
            [0-4]\d{9}|
            [3-9]\d{8}
          )
```

**Comment by florianajir** [comment]
:+1:

**Comment by padmaksha** [comment]
@lbeauvisage

Thanks for providing all the details we need! We've accepted this issue (removing the 700\d{6} range) and will fix this in an upcoming release. 
With respect to the M2M numbers, we are currently working on their feasibility and will update you later on this.

**Comment by VincentMarmiesse** [comment]
Hello,
Any news on this issue?

**Comment by penmetsaa** [comment]
@lbeauvisage and @VincentMarmiesse 
We have removed the 9 digit 700 range from mobile numbers in release 7.7.2.
https://libphonenumber.appspot.com/phonenumberparser?number=700+123+456&country=FR

We need more information on 700 (13 and 14 digit) M2M range.
Please take a look at below page. Any help will be greatly appreciated. Thanks :)
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by bdewater** [comment]
Linking this to the master issue (#680) to ensure visibility there.

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). See: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
