### ISSUE TITLE
Semicolon as extension separator

### ISSUE THREAD

**Issue by afinne** [googlei18n/libphonenumber#1106]
Would it be possible to also allow semicolon `;` to be used as an extension separator?

Currently you can at least `ex`, `ext`, `ext.`, `#`, and `,` as separators, but it will fail if you try to use `;`

It would make sense to allow `;` too, since that indicates to the phone that it should wait, and allow the person that makes the call to select when to dial the extension. This works on at least android and iphones.

**Comment by penmetsaa** [comment]
@afinne
Thanks for your inputs. We agree with you on this
We want to check internally the side effects of this change and get back to you.

**Comment by SumathiSundara** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=%28800%29+901-3355+%3B+7246433&country=US is Fixed
