### ISSUE TITLE
How do I use libphonenumber in my Android project?

### ISSUE THREAD

**Issue by keghani** [googlei18n/libphonenumber#1113]
Reported by @ritunagpal in https://github.com/googlei18n/libphonenumber/issues/597.

@ritunagpal Thank you for using libphonenumber! Did you try the TextWatcher example at @vrunoa's fork? https://github.com/Urucas/libphonenumber/blob/master/README.md

The problem doesn't seem to be with our repository, and we're not familiar with your setup. But I'll leave this open for now in case other contributors may be able to help.

You can also try asking the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

**Comment by heatherSnepenger** [comment]
Add this line to your gradle file:
`compile group: 'com.googlecode.libphonenumber', name: 'libphonenumber', version: '5.5'`

in `dependencies`, and you should be good to go

**Comment by lexi-sr** [comment]
The TextWatcher example at @vrunoa's fork https://github.com/Urucas/libphonenumber/blob/master/README.md doesn't work. It has problems with lagging and missing some inputs, and if you enter a number in the middle, it doesn't shift the hyphens appropriately (for example, 111-2222 would become 1113-2222 if you entered 3 there). 

I found a way to get this to work without those problems by using code taken from Android's new `PhoneNumberFormattingTextWatcher` and getting it to work with `libphonenumber. (https://android.googlesource.com/platform/frameworks/base.git/+/jb-release/telephony/java/android/telephony/PhoneNumberFormattingTextWatcher.java)  It works on minSdkVersion 18, and maybe less, but I haven't tested it on less than 18. Hope this helps everyone!


In your build.gradle:

    compile 'io.michaelrocks:libphonenumber-android:8.1.0'


In your class's fields: 

    private PhoneNumberUtil phoneUtil = PhoneNumberUtil.createInstance(Application.getInstance());

This is an inner class in your class: 

    /**
     * NOTE: The following class was taken from https://android.googlesource.com/platform/frameworks/base.git/+/jb-release/telephony/java/android/telephony/PhoneNumberFormattingTextWatcher.java
     * and modified to use libphonenumber for dependencies, so that we can use as-you-type formatting with a custom country code parameter on android versions below API 21.
     */
    public class PhoneNumberTextWatcher implements TextWatcher {
        /**
         * Indicates the change was caused by ourselves.
         */
        private boolean mSelfChange = false;
        /**
         * Indicates the formatting has been stopped.
         */
        private boolean mStopFormatting;
        private AsYouTypeFormatter mFormatter;
        /**
         * The formatting is based on the current system locale and future locale changes
         * may not take effect on this instance.
         */
        public PhoneNumberTextWatcher() {
            this(Locale.getDefault().getCountry());
        }
        /**
         * The formatting is based on the given <code>countryCode</code>.
         *
         * @param countryCode the ISO 3166-1 two-letter country code that indicates the country/region
         * where the phone number is being entered.
         *
         */
        public PhoneNumberTextWatcher(String countryCode) {
            if (countryCode == null) throw new IllegalArgumentException();
            mFormatter = phoneUtil.getAsYouTypeFormatter(countryCode);
        }
        @Override
        public void beforeTextChanged(CharSequence s, int start, int count,
                                      int after) {
            if (mSelfChange || mStopFormatting) {
                return;
            }
            // If the user manually deleted any non-dialable characters, stop formatting
            if (count > 0 && hasSeparator(s, start, count)) {
                stopFormatting();
            }
        }
        @Override
        public void onTextChanged(CharSequence s, int start, int before, int count) {
            if (mSelfChange || mStopFormatting) {
                return;
            }
            // If the user inserted any non-dialable characters, stop formatting
            if (count > 0 && hasSeparator(s, start, count)) {
                stopFormatting();
            }
        }
        @Override
        public synchronized void afterTextChanged(Editable s) {
            if (mStopFormatting) {
                // Restart the formatting when all texts were clear.
                mStopFormatting = !(s.length() == 0);
                return;
            }
            if (mSelfChange) {
                // Ignore the change caused by s.replace().
                return;
            }
            String formatted = reformat(s, Selection.getSelectionEnd(s));
            if (formatted != null) {
                int rememberedPos = mFormatter.getRememberedPosition();
                mSelfChange = true;
                s.replace(0, s.length(), formatted, 0, formatted.length());
                // The text could be changed by other TextWatcher after we changed it. If we found the
                // text is not the one we were expecting, just give up calling setSelection().
                if (formatted.equals(s.toString())) {
                    Selection.setSelection(s, rememberedPos);
                }
                mSelfChange = false;
            }
        }
        /**
         * Generate the formatted number by ignoring all non-dialable chars and stick the cursor to the
         * nearest dialable char to the left. For instance, if the number is  (650) 123-45678 and '4' is
         * removed then the cursor should be behind '3' instead of '-'.
         */
        private String reformat(CharSequence s, int cursor) {
            // The index of char to the leftward of the cursor.
            int curIndex = cursor - 1;
            String formatted = null;
            mFormatter.clear();
            char lastNonSeparator = 0;
            boolean hasCursor = false;
            int len = s.length();
            for (int i = 0; i < len; i++) {
                char c = s.charAt(i);
                if (PhoneNumberUtils.isNonSeparator(c)) {
                    if (lastNonSeparator != 0) {
                        formatted = getFormattedNumber(lastNonSeparator, hasCursor);
                        hasCursor = false;
                    }
                    lastNonSeparator = c;
                }
                if (i == curIndex) {
                    hasCursor = true;
                }
            }
            if (lastNonSeparator != 0) {
                formatted = getFormattedNumber(lastNonSeparator, hasCursor);
            }
            return formatted;
        }
        private String getFormattedNumber(char lastNonSeparator, boolean hasCursor) {
            return hasCursor ? mFormatter.inputDigitAndRememberPosition(lastNonSeparator)
                    : mFormatter.inputDigit(lastNonSeparator);
        }
        private void stopFormatting() {
            mStopFormatting = true;
            mFormatter.clear();
        }
        private boolean hasSeparator(final CharSequence s, final int start, final int count) {
            for (int i = start; i < start + count; i++) {
                char c = s.charAt(i);
                if (!PhoneNumberUtils.isNonSeparator(c)) {
                    return true;
                }
            }
            return false;
        }
    }


An example of it being used:

    private EditText mPrimaryPhoneField;
    mPrimaryPhoneField = (EditText) v.findViewById(R.id.priPhone);
    String countryCodeTwoLetters = "MX"; //Mexico 

    mPrimaryPhoneField.addTextChangedListener(new PhoneNumberTextWatcher(countryCodeTwoLetters)) {

            @Override
            public void afterTextChanged(Editable s) {
                super.afterTextChanged(s);
                //Your code here.
            }
        });

**Comment by keghani** [comment]
Thanks for the info @heatherSnepenger and @lexi-sr !
Seems to be resolved now as we didn't hear back. Also I should have posted this to the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) as it's not an issue :) Closing.

**Comment by amitcse32** [comment]
Hello Team

I am sure why , this lib is not supporting the JIO phone number series in INDIA , please let me know how to fix this.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
