### ISSUE TITLE
Issue compiling the project on centos 7

### ISSUE THREAD

**Issue by mvnvm** [googlei18n/libphonenumber#1114]
I've been trying to build the cpp project on centos 7.
I installed all necessary dependencies however when I run make I get JAVA_BIN-NOTFOUND.
I have java jdk 8 installed and JAVA_HOME and PATH environment variables set.
I'd appreciate any help on this.

Here's the complete error log:

# make
[  2%] Built target generate_geocoding_data
[  7%] Built target geocoding
[ 12%] Built target geocoding-shared
[ 13%] Generating ../src/phonenumbers/alternate_format.cc, ../src/phonenumbers/alternate_format.h
make[2]: JAVA_BIN-NOTFOUND: Command not found
make[2]: *** [../src/phonenumbers/alternate_format.cc] Error 127
make[1]: *** [CMakeFiles/generate-alt-format-metadata.dir/all] Error 2
make: *** [all] Error 2

**Comment by dlyongemallo** [comment]
Obvious question: is your JAVA_BIN set? (What is the output of "echo $JAVA_BIN"?)

If not, does setting "JAVA_BIN=$JAVA_HOME/bin" help?

**Comment by mvnvm** [comment]
I believe JAVA_BIN does not point to an environment variable since I looked into the code and it seems like an internal one.
However I already gave it a try and still the same result.
JAVA_BIN points to the bin folder inside jre.

**Comment by dlyongemallo** [comment]
This isn't an issue with the library, but with your particular setup.

Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further. Someone on there might be able to help you.
