### ISSUE TITLE
New number range for UAE Etisalat +97154xxxxxxx 

### ISSUE THREAD

**Issue by jordan-goodall** [googlei18n/libphonenumber#1115]
We've seen reports of a new number range being provisioned to UAE Etisalat +97154xxxxxxx:

- http://www.emirates247.com/news/emirates/cost-of-054-4000000-uae-mobile-number-2016-04-21-1.627992
- http://gntech.ae/news/etisalat-launched-054-mobile-code-anyone-fancy-054-4000000/
- http://www.emaratalyoum.com/business/local/2016-04-22-1.890326
- http://www.albayan.ae/economy/local-market/2016-04-22-1.2623437

It looks like the the new range isn't supported yet in libphonenumber. Any help adding support for the new range would be appreciated. Thanks!

Jordan

**Comment by penmetsaa** [comment]
@jordan-goodall 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by padmaksha** [comment]
Fixed in Release 7.4.2
Demo: http://libphonenumber.appspot.com/phonenumberparser?number=541234567&country=AE
