### ISSUE TITLE
After Adding dependency in my android project,getting the error.

### ISSUE THREAD

**Issue by ritunagpal** [googlei18n/libphonenumber#1118]
Hi
I am trying to add dependency of this library in build.gradle file as

compile 'com.googlecode.libphonenumber:libphonenumber:7.3.2'

And i am getting error

Note: there were 1 references to unknown class members.
      You should check your configuration for typos.
Note: there were 4 classes trying to access annotations using reflection.
      You should consider keeping the annotation attributes
      (using '-keepattributes _Annotation_').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 3 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 22 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 28 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Note: you're ignoring all warnings!
Preparing output jar [C:\Users\Ritu Nagpal\Projects\Reached\app\build\intermediates\multi-dex\debug\componentClasses.jar]
  Copying resources from program jar [C:\Users\Ritu Nagpal\Projects\Reached\app\build\intermediates\transforms\jarMerging\debug\jars\1\1f\combined.jar]
:app:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_60\bin\java.exe'' finished with non-zero exit value 3
> Information:BUILD FAILED

Please help me to sort out this issue.

**Comment by lararennie** [comment]
Hi,

Did you get this working? This doesn't seem to be an issue with our library, so I'm going to close it; but if you want to discuss on the mailing list, please feel free to join the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) and post the qn there.

Thanks!
