### ISSUE TITLE
isValidNumber issue

### ISSUE THREAD

**Issue by lawloretienne** [googlei18n/libphonenumber#1119]
I am trying to validate a U.S. phone number but I am getting a false positive.

```java
validatePhoneNumber("3108920")

private boolean validatePhoneNumber(String phoneNumber){
        PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
        try {
            Phonenumber.PhoneNumber usNumberProto = phoneUtil.parse(phoneNumber, "US");            //with default country
            boolean isValid = phoneUtil.isValidNumber(usNumberProto);
            return isValid;
        } catch (NumberParseException e) {
            Timber.e("NumberParseException was thrown: " + e.toString());
        }
        return false;
    }
```

the call to 
`PhoneNumberUtil.isValidNumber()` 
gets a regionCode 
`String regionCode = getRegionCodeForNumber(number);`

However, this regionCode is different than the default region code i passed into
`Phonenumber.PhoneNumber usNumberProto = phoneUtil.parse(phoneNumber, "US");`      

Why is that?

**Comment by lararennie** [comment]
Are you getting true or false as the result of your overall function?

**Comment by lararennie** [comment]
(Just FYI, this does look like something more appropriate to discuss on the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) rather than to file directly as an issue, unless you really are getting true for isValidNumber above)

**Comment by lawloretienne** [comment]
I am getting true as the result of the overall function.  Internally, this

`String regionCode = getRegionCodeForNumber(number)` 
returns `CA` and not `US`.

**Comment by lararennie** [comment]
Aha! Yes indeed that is a valid Canadian number. We use the region code you provide to change it into E164 format, (+13108920) and then this is a valid Canadian number, so we tell you it's valid.

There is another function, isValidNumberForRegion, where you can ask if it's a valid US number, and we'd say no. However, using this function is usually not recommended (read the Java doc for more info).

**Comment by lararennie** [comment]
Also note if you passed in the number +41789223696, with region code US, we'd ignore the region code you provided, and say it's valid, because it is a valid Swiss number - and we know that it's supposed to be interpreted that way because it has a leading + sign. The region code you pass in when parsing is just a recommendation for us to use if it's not clear.

**Comment by lararennie** [comment]
(more info in the javadoc for parse)

**Comment by lararennie** [comment]
I'll close this as it's not an issue with the library. Don't forget you can always join
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.

**Comment by lawloretienne** [comment]
Thanks for clearing this all up and being so responsive.

**Comment by lawloretienne** [comment]
The second param of this function :
`phoneUtil.parse()`
is a default region.  This essentially looks like a country code.  Is there a recommended way of determining the country code of an Android device that works across various Android versions and devices?

**Comment by lararennie** [comment]
Can you post this on the discussion list? This is a great qn and maybe other library users have some experience about this.
