### ISSUE TITLE
I am not able to retrieve country code for UAE

### ISSUE THREAD

**Issue by Saket89** [googlei18n/libphonenumber#1123]
This is the code that I have written to get the country code 
numberProto = phoneUtil.parse("+917208802519","");
but I am getting 91 as the code

**Comment by keghani** [comment]
The UAE country calling code is 971. This is working as intended.

**Comment by keghani** [comment]
Please join the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you want to discuss this further. I'm closing as it's not an issue with the library.

**Comment by lararennie** [comment]
(Is there a typo in your input? maybe you meant +971208802519?)

**Comment by Saket89** [comment]
@lararennie  yes you are right it was a typo on my end.. Thank you so much
