### ISSUE TITLE
issue with 7888 Series in India

### ISSUE THREAD

**Issue by tanmay7amura** [googlei18n/libphonenumber#1124]
Number +91 7888048396 is shown as invalid number.

**Comment by mizuni** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo* (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

*http://libphonenumber.appspot.com/phonenumberparser?number=%2B91+7888048396&country=IN
