### ISSUE TITLE
Germany area codes formatting results not following regional differences

### ISSUE THREAD

**Issue by lfrailey** [googlei18n/libphonenumber#1127]
Country/region affected: Germany
Example number(s) affected: +49 02129 3743399
The phone number range(s) to which the issue applies: +49 02129 XXXXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed line
Supporting evidence/description: 
02129 3743399 is being returned as 0212 93743399, which actually indicates the phone is located in a different city (0212= Solingen, 02129=Haan). 

http://libphonenumber.appspot.com/phonenumberparser?number=02129+%E2%80%93+3743399&country=DE&geocodingLocale=de

https://en.wikipedia.org/wiki/List_of_dialling_codes_in_Germany

Can this be updated to respect regional differences?

**Comment by padmaksha** [comment]
@lfrailey

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
This is fixed now http://libphonenumber.appspot.com/phonenumberparser?number=%2B49+02129+3743399
