### ISSUE TITLE
Validation issue with KW Ooredoo +965 6222 XXXX range

### ISSUE THREAD

**Issue by jordan-goodall** [googlei18n/libphonenumber#1128]
Hi,

We're having issues validating phone numbers in the new (provisioned a few months ago) range for Ooredoo Kuwait: +965 6222 XXXX. Is this something you can enable support for? Thanks!

jg.

**Comment by padmaksha** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. We are not able to find any official evidence for this prefix 6222. We are even unable to find any numbers online with this prefix.
Can you please provide any official evidence for this prefix or at least or at least some dialable numbers, preferably business websites with numbers in this range.
Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by jordan-goodall** [comment]
Attached is documentation supporting the new +965 6222 XXXX range for KW Ooredoo:
- page 3 shows the new range in the change history for the doc.
- page 7 shows the range assigned to Ooredoo

The range is for mobile numbers, I don't have access to any MSISDNs that can be shared publicly. Thanks for your help!

jg.

[IR21KWTNM2016-02-14 IR.21.pdf](https://github.com/googlei18n/libphonenumber/files/292163/IR21KWTNM2016-02-14.IR.21.pdf)

**Comment by padmaksha** [comment]
Hi Jordan,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by keghani** [comment]
Thanks for providing the documentation @jordan-goodall! Please sign the CLA when sharing non-public documentation. We still need you to do this to support this range. Details are in [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence), please read this section before sharing non-public evidence.

Once you've signed the CLA let us know and we'll be happy to support the range.

**Comment by padmaksha** [comment]
Hi Jordon,

We have found supporting evidence that the range is valid and will support the it as requested.

**Comment by SumathiSundara** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=%2B965+6222+1234 it's Fixed
