### ISSUE TITLE
Validation issue with +1671747xxxx

### ISSUE THREAD

**Issue by flyerhzm** [googlei18n/libphonenumber#1129]
Country/region affected (e.g., "US"): GU

Example number(s) affected ("+1 555 555-1234"): +1671747xxxx

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1671747xxxx

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): ?

The cost, if applicable ("toll-free", "premium rate", "shared cost"): ?

Supporting evidence: It's our user's calling phone number and we can find it [here](http://www.area-codes.com/area-code/area-code-671.asp)

**Comment by padmaksha** [comment]
@flyerhzm

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by padmaksha** [comment]
Fixed in Release 7.4.2
Demo: http://libphonenumber.appspot.com/phonenumberparser?number=16717471234&country=GU
