### ISSUE TITLE
Validation issue with 001442084728187 (HK)

### ISSUE THREAD

**Issue by ChrisDavis8** [googlei18n/libphonenumber#1130]
001 is the IDD exit code for Hong Kong but only 00 works

Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): HK

Example number(s) affected ("+1 555 555-1234"): 001442084728187

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=001442084728187&country=HK)

**Comment by padmaksha** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=001442084728187&country=HK
