### ISSUE TITLE
Timezone issue (USA Areacode 551)

### ISSUE THREAD

**Issue by agilesolmw** [googlei18n/libphonenumber#1131]
Country/region affected : US
Example number(s) affected : 551-220-1111
The phone number range(s) to which the issue applies : 551-XXX-XXXX
The type of the number(s) : ALL
The cost, if applicable : N/A
Supporting evidence

http://libphonenumber.appspot.com/phonenumberparser?number=5512201111&country=US
It print wrong output (Time zone(s) [America/Los_Angeles])
It's not a time zone for New Jersey.

**Comment by padmaksha** [comment]
@agilesolmw

Thanks for taking the time to improve libphonenumber!
We've accepted this issue.

We auto-generate the timezones, so we'll see if we can make a generic fix to this case.
(will take some time- just to manage expectations).

**Comment by kkeshava** [comment]
Fixed in release 8.3.1.
