### ISSUE TITLE
PhoneNumberOfflineGeocoder issue (USA Areacode 747)

### ISSUE THREAD

**Issue by agilesolmw** [googlei18n/libphonenumber#1132]
Country/region affected : US
Example number(s) affected : 747-220-1111
The phone number range(s) to which the issue applies : 747-XXX-XXXX
The type of the number(s) : ALL
The cost, if applicable : N/A
Supporting evidence

http://libphonenumber.appspot.com/phonenumberparser?number=7472201111&country=US
Why it display "United States" for PhoneNumberOfflineGeocoder Results
I know 747 area code is for California.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.5 : http://libphonenumber.appspot.com/phonenumberparser?number=7472201111&country=US
