### ISSUE TITLE
Timezone Issue US area code 623

### ISSUE THREAD

**Issue by aaronjwhiteside** [googlei18n/libphonenumber#1133]
http://libphonenumber.appspot.com/phonenumberparser?number=6235529111&country=US

Location:   Arizona
Time zone(s):   [America/Denver]

Timezone should be America/Phoenix.

Denver observes daylight savings time but Phoenix does not.

**Comment by padmaksha** [comment]
@aaronjwhiteside

Thanks for taking the time to improve libphonenumber!
We've accepted this issue.

We auto-generate the timezones, so we'll see if we can make a generic fix to this case.
(will take some time- just to manage expectations).

**Comment by phuongmn** [comment]
Any update on this issue?

**Comment by padmaksha** [comment]
We're working on it. We'll update this thread when it's released.

**Comment by kkeshava** [comment]
Fixed in release 8.3.1.
