### ISSUE TITLE
Validation issue with 7286969561 (IN)

### ISSUE THREAD

**Issue by swatip-erosnow** [googlei18n/libphonenumber#1135]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 7286969561

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=7286969561&country=IN)

**Comment by swatip-erosnow** [comment]
Hi,

The validation for numbers - 7286969561, 7286063572 and similar are being returned as invalid for country IN. However, tech partner for the service partner has confirmed these are valid numbers. Can you let us know how to go ahead with such cell number range?
Appreciate your help.

Thanks,

**Comment by kkeshava** [comment]
Hi,

Thank you for taking the time to improve libphonenumber!

We found online that 72860 range belongs to mobile however could not find any references about the 72869 range. So we are not sure whether 72969 range is mobile range / or fixed-line. We also would like carrier details of these numbers.

Please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by swatip-erosnow** [comment]
Hi,

Thanks for your response. The carrier is IDEA. So far, we have received this link - http://www.coai.com/msc-codes for validation.

Let me know in case of additional questions.

Thanks,
Swati

On Jun 2, 2016, at 9:46 PM, kkeshava <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thank you for taking the time to improve libphonenumber!

We found online that 72860 range belongs to mobile however could not find any references about the 72869 range. So we are not sure whether 72969 range is mobile range / or fixed-line. We also would like carrier details of these numbers.

Please share any official evidence you may have. See our
guidelines<https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence>.

**Comment by kkeshava** [comment]
Hi,

We are unable to find the mentioned ranges (72860 and 72869) in the link provided by you. Could you please share any other official evidence for these ranges along with their carrier details.

**Comment by keghani** [comment]
Please see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence) for how to share evidence.

**Comment by kkeshava** [comment]
We accept this issue and will support the numbers as mobile. However as no conclusive evidence is found that these are Idea ranges, we will not be updating the carrier for now.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B917286969561
