### ISSUE TITLE
Invalid number in Honduras with correct format 2XXX XXXX

### ISSUE THREAD

**Issue by lfrailey** [googlei18n/libphonenumber#1142]
Country/region affected (e.g., "US"): Honduras
Example number(s) affected ("+1 555 555-1234"): 26170600
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): n/a
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line
The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): 

Format for dialing in country is 2XXX XXXX

1) http://blog.vonage.com/international-calling/how-to-call-honduras-from-the-us/
2) http://www.prokerala.com/how-to/call/honduras

I called this number successfully from the US by dialing 011-504-2617-0600, but the result is saying isValidNumber says false: https://libphonenumber.appspot.com/phonenumberparser?number=2617-0600&country=HN.

**Comment by penmetsaa** [comment]
@lfrailey
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. 

Do you know what area this prefix covers?

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by lfrailey** [comment]
As of 2010, all Honduras phone numbers begin with 2: https://en.m.wikipedia.org/wiki/Telephone_numbers_in_Honduras

2617 XXXX should be a valid for a location in Choloma, Cortés.

**Comment by penmetsaa** [comment]
Thanks for the info lfrailey.
We will update geocoding as well.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B504+26170600
