### ISSUE TITLE
Mobile prefixe '78' for Orange SENEGAL, not found in the metadata

### ISSUE THREAD

**Issue by abadiane** [googlei18n/libphonenumber#1146]
Country: SENEGAL (SN)
Example number(s) affected : "+221 78 108 7542"):
The phone number range(s) to which the issue applies ("+221 78 XXX XXXX"):
The type of the number(s) : mobile
Supporting evidence : no evidence found from the authority, howewer some links from the newspapers 
http://www.osiris.sn/Senegal-L-ouverture-d-un-nouveau.html
http://www.leral.net/Des-numeros-Orange-commencant-par-78-L-Artp-donne-son-accord_a60184.html
http://www.rewmi.com/l-artp-accorde-le-prefixe-78-a-la-sonatel_a69063.html

**Comment by padmaksha** [comment]
@abadiane 

Thank you for taking the time to improve libphonenumber!

The example number mentioned  “+221 78 108 7542” is already validated by our library. Please see [demo] (http://libphonenumber.appspot.com/phonenumberparser?number=%2B221+78+108+7542&country=SN). 
There are other subranges 783 and 784 which have been updated in the new [ITU document] (https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000B80002PDFE.pdf) for Senegal , which we are working on.

**Comment by abadiane** [comment]
Hi,

I use the Grails Framework. I have imported the lib in the BuildConfig file ( compile 'com.googlecode.libphonenumber:libphonenumber:7.4.2’), however I always get false with the following code:

            PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
            Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse(correctNumber, "SN");
            phoneUtil.isValidNumber(phoneNumber)

I notice that in the demo link, the number is correct.

What did I miss?

Regards,

Alioune.
___________________________________
Alioune Badara BADIANE

Email : alioune@badiane.org
Tel : +221 70 637 65 65
	+221 77 333 25 79
Skype: abadiane

**Comment by lararennie** [comment]
What exactly is the "correct number" string you are passing in?
7. jun. 2016 12.08 a.m. skrev "abadiane" <notifications@github.com>:

> Hi,
>
> I use the Grails Framework. I have imported the lib in the BuildConfig
> file ( compile 'com.googlecode.libphonenumber:libphonenumber:7.4.2’),
> however I always get false with the following code:
>
> PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
> Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse(correctNumber, "SN");
> phoneUtil.isValidNumber(phoneNumber)
>
> I notice that in the demo link, the number is correct.
>
> What did I miss?
>
> Regards,
>
> Alioune.
> ___________________________________
> Alioune Badara BADIANE
>
> Email : alioune@badiane.org
> Tel : +221 70 637 65 65
> +221 77 333 25 79
> Skype: abadiane
>
>
>
>
>
>

**Comment by lararennie** [comment]
Oh: are you doing this in a unit test, or elsewhere? The unit tests don't
use the real metadata.
7. jun. 2016 12.08 a.m. skrev "abadiane" <notifications@github.com>:

> Hi,
>
> I use the Grails Framework. I have imported the lib in the BuildConfig
> file ( compile 'com.googlecode.libphonenumber:libphonenumber:7.4.2’),
> however I always get false with the following code:
>
> PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
> Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse(correctNumber, "SN");
> phoneUtil.isValidNumber(phoneNumber)
>
> I notice that in the demo link, the number is correct.
>
> What did I miss?
>
> Regards,
>
> Alioune.
> ___________________________________
> Alioune Badara BADIANE
>
> Email : alioune@badiane.org
> Tel : +221 70 637 65 65
> +221 77 333 25 79
> Skype: abadiane
>
>
>
>
>
>

**Comment by abadiane** [comment]
Hi, 

I’am doing spock unit test. I was using the following number 783332579 which return false, and then I use 781399675 which return true.
I will try it in the running application.

 PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
 Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse("781399675", "SN");
 phoneUtil.isValidNumber(phoneNumber)  

___________________________________
Alioune Badara BADIANE

Email : alioune@badiane.org
Tel : +221 70 637 65 65
	+221 77 333 25 79
Skype: abadiane

**Comment by penmetsaa** [comment]
Fixed in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B221+78+108+7542
