### ISSUE TITLE
DK It wont accept my numbers above 93XXXXXX

### ISSUE THREAD

**Issue by ChristianMikkelsen** [googlei18n/libphonenumber#1148]
How do i cange the regex looking pattern to accept those numbers?
Made a hack to to the _DK file, but it could have been writen nicer, if it was saved from class.

**Comment by padmaksha** [comment]
@ChristianMikkelsen 
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by padmaksha** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
