### ISSUE TITLE
Numbers 69XXXXXXX not supported for Tanzania

### ISSUE THREAD

**Issue by arthurES** [googlei18n/libphonenumber#1149]
- Country/region affected (e.g., "US"): TZ
- Example number(s) affected ("+1 555 555-1234"): +255 692324326
- The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +255 69 XXX-XXXX, and maybe broader. See supporting evidence.
- The type of the number(s) ("fixed-line", "mobile", "short code", etc.): "mobile"
- The cost, if applicable ("toll-free", "premium rate", "shared cost"):
- Supporting evidence: According to the national plan updated in 2014 (http://www.tcra.go.tz/images/documents/reports/National_Numbering_Plan_June_%202014.pdf, page 7 and 8), prefixes 61 to 69 and 71 to 79 followed by 7 numbers are supposed to be potentially assigned to mobile operators. It has been reported to me that Airtel has started using the previously spare block 69 a few months ago. It might be the case that other of these prefixes that were not previously used are going to start being used.

**Comment by padmaksha** [comment]
@arthurES 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by arthurES** [comment]
Hi - I was wondering why this issue hasn't been included in any of the releases in the past few months. Did I misunderstand the process?

**Comment by padmaksha** [comment]
@arthurES 

Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the [demo] (http://libphonenumber.appspot.com/phonenumberparser?number=+692324326&country=TZ) Instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by arthurES** [comment]
Thanks for the answer - yes I've tried the demo after posting my comment and realized that it had been fixed. I was just confused by the fact that the issue hadn't been closed!

**Comment by lararennie** [comment]
Yes, you're right, it was an error on our side, apologies :)
