### ISSUE TITLE
Farsi(Persian) names of carriers

### ISSUE THREAD

**Issue by afarsi** [googlei18n/libphonenumber#1150]
Hi. Please create a new folder named "fa" in https://github.com/googlei18n/libphonenumber/tree/master/resources/carrier
also please copy the 98.txt file from en folder to there. Because I want translate Iranian carrier names to Persian(Farsi). For example Irancell Carrier in en folder should be translated to "ایرانسل" in fa folder.
Note: Now Arabic language have a folder named ar in there.
Note2: It would be helpful if we have a 93.txt also in fa folder. Because we can translate Afghanistan carrier names to Persian also.
Note: I can create a new file there by new file Button, but I can't create new folder there. Why?
Thanks.

**Comment by keghani** [comment]
Thanks for contributing to geocoding in Persian! We'd be happy to review a pull request.

Are you using the command-line? Try creating the files before pushing to your repository.

You should be able to upload the files like so in your fork:

```
mkdir resources/carrier/fa
cp resources/carrier/en/98.txt resources/carrier/fa/
cp resources/carrier/en/93.txt resources/carrier/fa/
```

Then edit the files under resources/carrier/fa/ to Persian and commit and push them to your fork, then send us a pull request! Let me know if you need further help.

**Comment by keghani** [comment]
Oh, and please sign the CLA. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
I also tried adding a file on the UI. Here's how:

Go to https://github.com/googlei18n/libphonenumber/tree/master/resources/carrier
Click on "Create new file"
In the "Name your file..." box type in "fa/" and hit Enter
It will then have a new "Name your file..." box, and you can enter 98.txt

Hope that helps!

**Comment by afarsi** [comment]
Thanks. I created a pull request for this. I described changes there. Look at here: https://github.com/googlei18n/libphonenumber/pull/1151
Please check and merge it.
I hope it will be helpful.

**Comment by keghani** [comment]
Thanks @afarsi! I'm reviewing the PR.
Closing this issue, let's track completion at the PR.
