### ISSUE TITLE
Invalid phone number formatting for iran in my mobile phones dialer

### ISSUE THREAD

**Issue by afarsi** [googlei18n/libphonenumber#1152]
Hi.
I have one mobile handset and one tablet(LG mobile and Samsung Tablet). Those operating systems are Android 4.4.x
When I go to virtual keypad on native dialer on my handset or tablet, then I try to call to a number.
It shows mobile numbers which I try to call true. But It shows fixed line numbers based on previews numbering format and national numbering plan in Iran. This problem also is in Contacts section.

Recently numbering plan of Iran was changed.
Before that numbering plan was 0xxx xxx xx xx which 0xxx was city prefix code. But Now it's not based on cities. Area codes of Cities in every province/state(Ostan in Iran) joined, and now area codes are based Provinces, not cities.
Length of prefix area code changed from 0xxx(Four Digits) to 0xx (3 Digits) and length of number changed from xxx xx xx (7 Digits) to xx xx xx xx(8 Digits).

Example:
Old numbering format(Isfahan City): 0311-xxx xx xx (0311 was area code of Isfahan City)
New numbering format(Isfahan city): 031-3x xx xx (031 is area code of Isfahan Province)

This issue reported to libphonenumber and now in resources/geocoding based on Iran provinces.(It's true)
But I think that codes which are for display formatting, not fixed.
As result my phone shows 0313-xxx xx xx(Invalid) not 031-3x xx xx(Valid) 

Please fix it. Or describe how can I fix it?

Question: How can I update libphonenumber which is on my handset/tablet to latest version? Via Google Play?
Question 2: Are LG and Samsung Dialers and other vendors using Google libphonenumber? Or the have owned libphonenumber?

Thanks.

**Comment by padmaksha** [comment]
Hi Amir,

Thank you for taking the time to improve libphonenumber!

With respect to the number format, we've accepted this issue and will fix this in an upcoming release.

Libphonenumber is a open source library and is used by multiple products and vendors like Android, Whats app etc . It is integrated with Android ( different vesions of Android use different versions of libphonenumber library) ,so to update to the latest version of libphonenumber on your phone or tablet please update to the latest version of Android on your phone/tablet. 
Libphonenumber cannot be downloaded from Google Play.
To include the code in your application, you can download the latest version of libphonenumber  [here](http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/).

The recent [ITU doc.](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000660003PDFE.pdf) dated 21.06.2016  for Iran says the minimum length of fixed-line numbers in Iran is 5 digits  and the maximum length is 10 digits as shown [here](https://screenshot.googleplex.com/KLz9H1c07ww) . So it means that fixed-line numbers in Iran are of variable length. Can you please confirm this. Also is the format for these numbers which are less than 10 digits in the form XX XX .. ..  or are they different. Any suggestions on this will be greatly appreciated.

Thanks

**Comment by afarsi** [comment]
Hi @padmaksha 
Thanks for your respect!
You are true about length of fixed line numbers in Iran are between 5 to 10 but with these details:
ITU Document says:

Detail of Numbering Scheme
NDC: National Destination Code 
**NSN: National Significant Number (NDC + SN)** 
The minimum number length (excluding the country code) is 5 digits The maximum number length (excluding the country code) is 10 digits 

This means NSN = NDC(Area code) +  SN(Subscriber Number).

If you look at ITU Doc, will understand NDC(Area codes) in Iran are 2 digits.
This means **minimum length of subscriber number is 3 Digits**, and if you add 2 digits of NDC(Area code)  it will be 5 digits which ITU Doc says.

Also maximum digits in ITU Doc is 10 digits. This contains NDC(Area code) which is 2 digits plus **subscriber number which is maximum 8 digits.**

Now subscriber number which is between 3 digits to 8 digits following these rules:
1- 3 Digit numbers (5 digits based ITU Doc), are only for emergency services like EMS, Fire, Telephone repair, Water emergency,...

2- 4 Digit numbers (6 digits based ITU Doc) to 6 Digit (8 Digit based) are for important(not emergency) and public services and important business needs like support services of any corporation.
You should pay more money for these numbers or you should be an gov organization.

3- 8 Digit numbers (10 digits based ITU Doc) are for common subscribers. These numbers are very common and widely usable in Iran now. I described about these numbers in previous post.
============================

Before continue, note: ac=area code(NDC) and is 2 Digits.
**Area code in current version of libphonenumber is 3 digits(based old numbering plan), now it should change to  2 Digits. This change in libphonenumber is important and should be first of changes.**

I think for 3 digit numbers (5 Digit in ITU) no need to change.
Sample: ac-xxx

Also for 4 Digit numbers(ITU Doc 6 Digit) to 6 Digit numbers(ITU Doc 8 Digits) we need we need like it 
Sample: ac-xx xx (my 4 Digit and ITU Doc 6 Digit)
Sample: ac-xxx xx (my 5 digit and ITU Doc 7 Digit)
Sample: ac-xx xx xx  (my 6 Digit and ITU Doc 8 Digit)

Also for common numbers in Iran (My 8 Digit and ITU Doc 10 Digits):
Sample: ac-xx xx xx xx


Thanks very much,

**Comment by keghani** [comment]
Hi @afarsi,

I just came upon this and I"m missing some context, could you please clarify?

I did a quick Google search and it's not clear to me that XX XX XX XX XX is indeed a more common format than XX XXXX XXXX. I found ~1,330,000 online results from Iranian websites using the former, and ~1,220,000 using the latter. This is not a significant difference.

Could you point us to specific information that recommends XX XX XX XX XX as the best format to use for Iran fixed-line numbers? Without this information we may not be able to make changes.

**Comment by afarsi** [comment]
Hi @keghani 
You are correct. In the internet, using xx xxxx xxxx format is more common than xx xx xx xx xx format.
But as you saw and as I said in my previous post, the two formats are common. As you said, between ~1330,0000 and ~1,220,000 is not a significant difference.
Iran haven't any official formatting. But these two formats are common. As result I haven't any official resource for recommendation of best formatting.

But my main problem is not using formatting like XX XX XX XX XX or XX XXXX XXXX format. You can chose one of them. I said my problem, but it seems like I couldn't say problem.
Main problem is here(Repeat from my pervious prost):

Example:
Old local numbering format(Isfahan City): 0311-xxx xx xx (0311 was area code of Isfahan City)

New local numbering format(Isfahan city): 031-3x xx xx (031 is new area code of Isfahan Province)
This local format **is true also** (Isfahan City): 031-3xxx xxxx (031 is new area code of Isfahan Province) 

Now Android show it invalid like: 0313-xxx xx or 0313-xxx xx xx because they using old format.


Old international format(Isfhan City): (+98)-311-xxx xx xx or (0098)-311-xxx xx xx

New international format(Isfahan City): (+98)-31-3x xx xx xx or (0098)-31-3x xx xx xx
This format **is true and common also** (Isfahan City): (+98)-31-3xxx xxxx or (0098)-31-3xxx xxxx

Now Android show it invalid like: (+98)-313-xxx xx xx or (0098)-313-xxx xx xx because they using old format.


The problem is simple:
1-Before now, area codes was 3 digits, now it should be 2 digits.
2-Maximum digits of numbers(without country code) should be 10 digits and first 2 digits are area code. 8 digits after that is subscriber number.

Best regards
Amir

**Comment by keghani** [comment]
Thanks for the clarification @afarsi!

Sorry for the confusion, there were many topics in one issue so the scope was lost on me as I was looking at the formatting issue. Someone from the team should look at this and determine next actions for the remaining issues.

Thanks for your patience!

**Comment by penmetsaa** [comment]
@afarsi,

Summary: We consider this issues as WAI but will leave it open for now to follow up with any evidence/disagree with anything below.

There are multiple things discussed in this bug:

- Regarding why Android is still showing Iran phone number in xxx xxx xxxx format: padmaksha@ have answered this in https://github.com/googlei18n/libphonenumber/issues/1152#issuecomment-241359666
Ex: Android phone (version 4): Displays Iran landline numbers in format xxx xxx xxxx.
Android phone (version 6): Displays Iran landline numbers in format xx xxxx xxxx.
You need to upgrade your Android version. Please check our [demo site](https://libphonenumber.appspot.com) for latest behaviour. If it can't be reproduced there, we can't fix it.

- As per ITU doc and below comment from you, NSN is of length 5 to 10 digits.

>>NSN: National Significant Number (NDC + SN) 
The minimum number length (excluding the country code) is 5 digits The maximum number length (excluding the country code) is 10 digits
This means NSN = NDC(Area code) + SN(Subscriber Number).
If you look at ITU Doc, NDC(Area codes) in Iran are 2 digits.

As per online search results this might be 5 or 10 digits. We are not able to connect to any of the numbers which are 6 to 9 digits. Please provide us any other official document which states these are valid or sample numbers which are working. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

- You mentioned that 

>> Now subscriber number which is between 3 digits to 8 digits following these rules:
1- 3 Digit numbers (5 digits based ITU Doc), are only for emergency services like EMS, Fire, Telephone repair, Water emergency,...


We already support some of them in our [ShortNumberMetadata.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/ShortNumberMetadata.xml#L5367)
We need more details like 
1. When dialling, can we prefix these 3 digit short codes with any National Destination Codes (area codes)? Do they work? Or just dialling the short code is enough?
2. Official evidence that mentions prefix and use cases of these numbers so that we can support them as well.


>>2- 4 Digit numbers (6 digits based ITU Doc) to 6 Digit (8 Digit based) are for important(not emergency) and public services and important business needs like support services of any corporation.
You should pay more money for these numbers or you should be an gov organization.


Our earlier official evidences have not mentioned 4 digit subscriber numbers. I believe these are short codes. Please share any official evidence you may have.


>>3- 8 Digit numbers (10 digits based ITU Doc) are for common subscribers. These numbers are very common and widely usable in Iran now. I described about these numbers in previous post.
Before change, NDC in Iran was 3 digits and these numbers was 7 Digits.


We already support 8 digit subscriber numbers which are prefixed by a valid National Destination Code. Please take a look at our [PhoneNumberMetadata.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L12070) and let us know if we are missing anything here.

**Comment by afarsi** [comment]
Hi @penmetsaa 
Thanks for your very good description and notes.
* You're true. It look like the latest version of libphonenumber(based on your web based [demo site](https://libphonenumber.appspot.com/phonenumberparser?number=03132345160&country=IR)) is working true and just right. But:

Note A: I haven't access to Android 6.0 and above. I have Android 4.4.2 and Android 5.1 on another phone. As result, I couldn't check how is phone number formatting on all versions of android. In addition **it seems my main problem is not for Android 6.0 and above.**

Note B: Fore preventing these problems, I think libphonenumber should become updatable on Android. I filled an issue few months ago. Please read it [here
](https://github.com/googlei18n/libphonenumber/issues/1288)

Note C: Please add the link of demo site to issue filling page, and request users to check on demo site first, then file a bug. In addition, the demo site can be upgraded and show android version which can show every numbering format. For example, users able to select the android version and the demo site show results based on libphonenumber which is available on that Android version.

=============

* You said: As per online search results this might be 5 or 10 digits. We are not able to connect to any of the numbers which are 6 to 9 digits.

I want to say I haven't any official document(except itu doc). But because I'm in Iran, I know these about phone numbers. In addition, I can give you a link of Tehran province telecommunication company.
It's in Persian language. But You can use Google Translate to translate it to English.
  Original(Persian) link: [4 digit and 5 digit codes(numbers)](http://tct.ir/?siteid=7&pageid=1114)
  [Translated(to English) by Google translate link](https://translate.google.com/translate?sl=fa&tl=en&js=y&prev=_t&hl=fa&ie=UTF-8&u=http%3A%2F%2Ftct.ir%2F%3Fsiteid%3D7%26pageid%3D1114&edit-text=)

Note A: The 4 digit numbers will be 6 digits based on itu doc(Because adding 2 digits of area code)
For sample of this type of number: +98 21 6422(international) and 021 6422(national) are calling center of saman bank. +98: Country code 21(international) or 021(national):Tehran Province area code 6422 is subscriber number For resource: [saman bank website](http://www.sb24.com/En/footer/contact-us/index.html#2)

Note B:  The 5 digit numbers will be 7 digits based on itu doc(Because adding 2 digits of area code)
For sample of this type of number: +98 21 82890 (international) and 021 82890(national) are call center numbers of Bank Pasargad. You can see the length of subscriber number is 5 digits and the length of number(NSN based itu doc) is 7 digits.

Note C: The 8 and 9 digits numbers(6 and 7 digit subscriber numbers) are not common.

================================================
You said: 1. When dialing, can we prefix these 3 digit short codes with any National Destination Codes (area codes)? Do they work? Or just dialing the short code is enough?
Answer: Just dialing the short code is enough. **Adding any prefix to 3 digit numbers will make the dialing fail**. It's based on my experience.

Pay attention: In Iran, 112 is main high emergency number(Like European union) but if you call to 911 then you will redirect to 112 system also.(911 is common in north America). All the phones should be able call to 112 and 911 even the keyboard is locked.

List of emergency numbers in Iran(Calling without any prefix):
110: Police(Common police and Traffic police)
115: EMS(Emergency medical service)
125: Fire
112 and 911: High Emergency for All(SOS)
123: Social Emergency Service(Childs, Women and Family Protection)
141: Roads information center
194: Gas Emergency
121: Electric Emergency
122: Water lines Emergency
Note: We have more 3 digit numbers. But these are very important.
====================================
You said: Our earlier official evidences have not mentioned 4 digit subscriber numbers. I believe these are short codes. Please share any official evidence you may have.
Yes. You are true. These are short codes. I mentioned a link to official website of Tehran Province Telecommunication company and two samples from phone numbers of two Iranian banks from their websites.

Important Note: Some times we will need to call area code before 4 digit short codes(like 021 6422 which is saman bank calling center). But some times you should call to 4 digit short codes without any prefix or area code. For example, internet providers using this type of 4 digit short codes. If you need to call the prefix(area code), the owner of number will write the area code in website, business card,...

I think we can say type 1(with prefix) is 4 digit subscriber number and type 2(without need the prefix) is 4 digit short code.
Sample of type 1(With prefix) mentoined above for saman bank calling center. 021 6422
Sample of type2(Without prefix/area code): 1565 is calling center of hi web internet provider. [Their website](http://hiweb.ir/en/contact-us/contact-info/headquarter)

Best Regards.
Amir Farsi.

**Comment by penmetsaa** [comment]
@afarsi,
Thanks for detailed inputs. :)

>> Note B:

We are checking on #1288 (updatable libphonenumber library on Android phone). We will update the issue accordingly. 

>> Note C:

Thanks for these suggestions. :) We have mentioned about demo site in [CONTRIBUTING.md](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

Regarding 4 digit and 5 digit numbers (excluding area codes):
We are able to connect to these numbers. We accept the issue and support 5 to 10 digit phone numbers (including area codes) as mentioned in ITU doc.

Regarding short code:
1. Please provide us authoritative evidence that 911 is emergency short code. This is mandatory to add emergency numbers to library
2. We are not able to find online evidences for 194, 121 and 122 short codes. Please help us in getting the same.
3. We accept the issue regarding 123 and 141 short codes and add support to them. These are mentioned in below ITU page.
https://www.itu.int/net/itu-t/inrdb/e129_important_numbers.aspx?country=111&pg_size=50
4. We will go ahead and add short code 1565 based on online reference you have provided. Please provide evidence about cost (toll-free, premium rate...etc) of this short code.
5. It will be great if we have range information for such 4 digit type 2 short codes (i.e can be dialed without area code). Is there any such evidence? If not available, provide us the individual numbers (along with online reference / evidence) which you would like to add to our library.

**Comment by afarsi** [comment]
Hello @padmaksha.

>1.  Please provide us authoritative evidence that 911 is emergency short code. This is mandatory to add emergency numbers to library
Pay attention: Main number for High EMERGENCY(SOS) in Iran is 112 (Like European countries), but if you call to 911, it will be redirected to 112 number and 911 is not official Emergency number in Iran.

As result, I haven't any official document about 911 but you can read about it in last lines of this article(Semnan University Website): https://translate.google.com/translate?hl=fa&sl=fa&tl=en&u=http%3A%2F%2Fwww.semnan.ac.ir%2Findex.aspx%3Ffkeyid%3D%26siteid%3D1%26pageid%3D151%26newsview%3D6876&sandbox=1

Pay attention: Number 147 which is in that article is not available today. Now National SOS number of Iran 112 and 911 will be redirected to 112 also. It seems libphonenumber now supporting 112 for iran. But it will be good if  you add 911 also.

In addition, in this wikipedia article also you can find Iran see this sentence: "911 is redirected to 112 on mobile phones". https://en.wikipedia.org/wiki/112_(emergency_telephone_number)

====================

> 2. We are not able to find online evidences for 194, 121 and 122 short codes. Please help us in getting the same.
List of necessary numbers from tct(Tehran Telecommunication Company) -You can find 194 and 121 and 122:
https://translate.google.com/translate?sl=fa&tl=en&js=y&prev=_t&hl=fa&ie=UTF-8&u=http%3A%2F%2F118.tct.ir%2Fnecnum.htm&edit-text=

A news about essential phone numbers(121 and 122 are included):
https://translate.google.com/translate?hl=fa&sl=fa&tl=en&u=http%3A%2F%2Fwww.hamshahrionline.ir%2Fdetails%2F251891%2FCity%2Fcity-affairs

> 4. We will go ahead and add short code 1565 based on online reference you have provided. Please provide evidence about cost (toll-free, premium rate...etc) of this short code.
I introduced this number only as sample for 4 Digit phone numbers which should be dialed without area code. The 1565 shout code is not important number and it's not toll-free or premium-rate. It's only a 4 digit short code for better remembering.  I said it's only a sample for 4 digit short codes without area. 1818 and  is another sample. I said in my last post: "As result, I think **we should change national=3 in shortcode tag in shortnumbers file to shortcode=4 and it's exampleNumber to 1565; but national=3 in emergency tag should be remain** What's your opinion?"

If you want to see sample of 4 digit short codes you can see here(Tehran telecommunication company): 

You can visit list of some of these numbers in Tehran telecommunication company) and find 1818. https://translate.google.com/translate?sl=fa&tl=en&js=y&prev=_t&hl=fa&ie=UTF-8&u=http%3A%2F%2F118.tct.ir%2Fnecnum.htm&edit-text=

>5. It will be great if we have range information for such 4 digit type 2 short codes (i.e can be dialed without area code). Is there any such evidence? If not available, provide us the individual numbers (along with online reference / evidence) which you would like to add to our library.
I answered this question in answer of number 4. Reference link also maintained.

**Comment by penmetsaa** [comment]
@afarsi,
Thanks so much for in detailed inputs. These things will help us :)
Note: I am maintaining same sequence for better reference.
1. Based on Wikipedia article and supporting online references we can add 911 to emergency shortcode list.
2. We will add support to 194, 121 and 122 shortcodes.
3. We can not change possible length from 3 digit to '3 or 4' digits unless we support some numbers of same length.
4. Thanks again for detailed inputs here. We will support the short codes listed in http://118.tct.ir/necnum.htm

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by afarsi** [comment]
@penmetsaa .
Thank you so much for your hearing and applying.
When you added this information, please inform me and let me to look at them and check if all of them are true, for although I'm sure most of that this information are true, but maybe some them needed to edit in your final applied lists. Thanks.

> Please let us know if you did not
intend to submit the information for such use.

This information is public on the internet on trustworthy websites or on my personal experiences. I only collected them.  As result, I don't see any problem for using this info with your open source policies.

**Comment by penmetsaa** [comment]
@afarsi,
Thanks for the confirmations. :)
We will update the bug once the fix is release.

**Comment by kkeshava** [comment]
Fixed in release 8.5.1.
