### ISSUE TITLE
Number appears as INVALID when is VALID

### ISSUE THREAD

**Issue by mcocaro** [googlei18n/libphonenumber#1153]
Hi - 

This number from St. Kitts is a valid number and received my SMS (+18697670964) - can you please fix why the lib returns invalid number?

Thanks,

**Comment by penmetsaa** [comment]
@mcocaro 
Thank you for taking the time to improve libphonenumber!

Fixed in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B18697670964
