### ISSUE TITLE
Correction towards Panji, Maharashtra 

### ISSUE THREAD

**Issue by sameerkhan2k1** [googlei18n/libphonenumber#1159]
Issue: 91832|Panji, Maharashtra (spelling incorrect, state marked incorrect)
Location: resources/geocoding/en/91.txt
Data Authenticity Verification: https://en.wikipedia.org/wiki/Panaji
Data to be corrected:
1. Panji to be corrected as Panaji
2. Panaji belongs to state "Goa" and not "Maharashtra"

Note: the entire state of Goa, India is marked under one STD code 0832 or 832. I understand that the existing data as been fetched from http://www.dot.gov.in/sites/default/files/nnp2003.pdf. However this NNP is due for amendments.

**Comment by penmetsaa** [comment]
@sameerkhan2k1 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

As per our online search some cities in Goa have STD code which is not 832.
Margao city in Goa state has STD code 08342.
Sanguem city in Goa state has STD code 0834.
You can check it on http://218.248.243.16/bsnl-web/stdSearch.seam
http://1min.in/telecom/stdcode/8345

We will correct the geocodings of these cities in Goa: 
91832|Panaji, Goa
91834|Sanguem, Goa
918342|Margao, Goa


Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by sameerkhan2k1** [comment]
@penmetsaa 
Thanks for accepting the change request.
As I mentioned in my note above, the entire state of Goa holds one code (0832) hence it would be good if we can change the entry as;
91832|Goa

I have listed all the major cities of Goa below and you will notice that all of them carry the same area/STD code of 0832.
https://en.wikipedia.org/wiki/Panaji
https://en.wikipedia.org/wiki/Margao
https://en.wikipedia.org/wiki/Vasco_da_Gama,_Goa
https://en.wikipedia.org/wiki/Mapusa

I am a native of this region and hence the information provided is correct.

**Comment by penmetsaa** [comment]
@sameerkhan2k1 
Thanks for providing all these details. We will make it as one entry.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.5 : https://libphonenumber.appspot.com/phonenumberparser?number=%2B918322170000
