### ISSUE TITLE
Validation issue with 0017183831111 (BD)

### ISSUE THREAD

**Issue by pduey** [googlei18n/libphonenumber#1163]
Country/region affected (e.g., "US"): BD

Example number(s) affected ("+1 555 555-1234"): 0017183831111

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): Any US number

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Any

The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

The failure case is how one would dial a US number from Bangladesh. The leading 00 should be removed, but it's removing the leading 001, so then the US country code is not matched.
[link to demo failure](http://libphonenumber.appspot.com/phonenumberparser?number=0017183831111&country=BD&geocodingLocale=und)

Example calling Norway from Bangladesh, where only the leading 00 is removed, and the country code is correctly extracted.
[link to demo success](https://libphonenumber.appspot.com/phonenumberparser?number=004748444555&country=BD&geocodingLocale=und)

**Comment by penmetsaa** [comment]
@pduey 

Thank you for taking the time to improve libphonenumber!

As per 2.1.3 section in below official documents, 001 and 002 can be used for International dialing covering toll quality and non-toll quality services in Bangladesh.
http://www.btrc.gov.bd/sites/default/files/national_numbering_plan_2005_0.pdf
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000120001MSWE.doc
Toll quality calls uses better compression of voice with same quality as normal calls.

So libphonenumber considering 001 as international dialling prefix (same as 00), and pick country code from the number after prefix 001. This is the reason why country code 1  is missed when US number is formatted in international dialing of Bangladesh. 0017183831111 

We want to check how carriers are interpreting these numbers that start with 001.

Please dial the number in below formats and let us know if you are able to connect or not.
1. 00 1 7183831111 (General way of calling US number. But this is overlapping with international toll quality call prefix 001.)
2. 001 1 7183831111 (Using international toll quality service for calling US number)
3. 002 1 7183831111 (Using international non-toll quality service for calling US number)

**Comment by penmetsaa** [comment]
Can anyone from Bangladesh can help us in testing above cases and share results?

**Comment by padmaksha** [comment]
Fixed in release 7.5.1
