### ISSUE TITLE
Invalid for Bahrain numbers: +973354XXXXX

### ISSUE THREAD

**Issue by zubchenok** [googlei18n/libphonenumber#1166]
Country/region affected (e.g., "US"): BH - Bahrain
Example number(s) affected ("+1 555 555-1234"): +97335470144
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +973 35 4XXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): n/a

http://libphonenumber.appspot.com/phonenumberparser?number=%2B97335470144

**Comment by padmaksha** [comment]
Thank you for taking the time to improve libphonenumber!

We were able to connect to +97335470144 but we can't find official evidence for the
actual ranges that are valid. We can't support single numbers, we need context
about the prefix that makes them valid.

Please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by bahtaxi** [comment]
See in the search the career name is VIVA BH 
http://bhr.areacodebase.com/node/21

other wise what kind of evidence link is needed , this is not clear for me

**Comment by padmaksha** [comment]
@bahtaxi 

The evidence provided by you in the [doc](http://bhr.areacodebase.com/node/21) states 355 as a valid prefix and provides no evidence for prefix 354.  We have found alternate  evidence of the 354 being a valid prefix and this issue will be fixed in the next release.

**Comment by padmaksha** [comment]
Fixed in release 7.4.4
http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.4.4
