### ISSUE TITLE
New Honduras phone numbers to be added to libphone

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1173]
Country: Honduras
Phone number examples: +504 2407 2226, +504 2407 2227, +504 2407 2228, +504 2407 2229, +504 2407 2230
Type: landline

These phone numbers should connect you to the Paradise Beach Hotel front desk in Honduras.

Can these be added to the libphone?

Thank you,
Ryan

**Comment by padmaksha** [comment]
@rzaryan 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Do you know what area this prefix covers?

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by rzaryan** [comment]
@padmaksha  I'm not 100% confident, but the hotel is located at this address: West Bay Beach, West Bay, Roatan IB3100, Honduras

**Comment by padmaksha** [comment]
Thanks for providing all the details. We have found evidence of the location as being Roatan, Bay Islands and will be adding it to geocode.

**Comment by padmaksha** [comment]
Fixed in release 7.4.4
http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.4.4
