### ISSUE TITLE
Make it easier to get a list of valid country codes

### ISSUE THREAD

**Issue by mcandre** [googlei18n/libphonenumber#1174]
Given a PhoneNumberUtil instance, I would like a method that returns a list/array/whatever of valid country codes.

**Comment by ThatKawaiiGuy** [comment]
I too would love this to be added.

**Comment by padmaksha** [comment]
@mcandre 

We are currently looking on the feasibility of this method. Will keep you updated on this.

Thanks

**Comment by penmetsaa** [comment]
This is fixed as part of 8.7.0. New API [PhoneNumberUtil.getSupportedCallingCodes()](https://github.com/googlei18n/libphonenumber/blob/e24208e0c63fd06d5cf9da26bb885d2977453c46/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L982) is added.

**Comment by sijovijayan** [comment]
List of valid country names and its code given in this [page](http://phpinterviewquestions.co.in/blog/ionic/googles-libphonenumber-library-supported-country-list) 
I got an error like the following when i used all country names as list in an ionic app

> Runtime Error
> Error in ./LoginPage class LoginPage – caused by: Cannot read property ‘getNationalNumber’ of null

**Comment by penmetsaa** [comment]
@sijovijayan ,
Thank you for using libphonenumber!

Yes, library does not support the regions listed under "this plugin not support the following countries" section in the [page](http://phpinterviewquestions.co.in/blog/ionic/googles-libphonenumber-library-supported-country-list) you shared. You can check [this FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported) to know more about this.

When you try to parse the number with these region codes (the ones listed in the page ), library throws error "Error: Invalid country calling code." You can check this behaviour at [libphonenumber JavaScript demo](http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
