### ISSUE TITLE
Validation issue with +1 607 323 7509 (US)

### ISSUE THREAD

**Issue by rossypamdev700** [googlei18n/libphonenumber#1175]
Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): +1 607 323 7509

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): premium rate 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!**

**Comment by penmetsaa** [comment]
@rossypamdev700

Thank you for taking the time to improve libphonenumber!

As per below official evidence, 607 range is assigned to New York. 
https://www.nationalnanpa.com/enas/geoAreaCodeNumberReport.do

We support this range as FIXED_LINE_OR_MOBILE. The type cannot be determined by their prefix, so the best our library can do is say that it's one or the other. 
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+607+323+7509

Below online references says these are normal phone numbers. These can be mobile or fixed-line. https://www.radisson.com/corning-hotel-ny-14830-2786/nycornin
http://www.bizexposed.com/New_York-USA/B/Celtic_Spirit_Inc-Stamford.php

We need more information to consider adding it to premium rate. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
@rossypamdev700 
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
