### ISSUE TITLE
Need to support +86 171XXXXXXXX

### ISSUE THREAD

**Issue by thefallentree** [googlei18n/libphonenumber#1176]
Hi,

Please add support for +86 171XXXXXXXX which is a valid cellphone number in china.

Thanks.

**Comment by penmetsaa** [comment]
@thefallentree
Thank you for taking the time to improve libphonenumber!

Wikipedia says 1718 and 1719 mobile ranges are assigned to China Unicom carrier.
https://en.wikipedia.org/wiki/Telephone_numbers_in_China

Please share with us fourth digit of the number 171XXXXXXXX and also the carrier of it if known.

**Comment by thefallentree** [comment]
Hi, Thanks
according to http://baike.baidu.com/view/12118274.htm , (in chinese)

1710 - 1719 are all assigned to CU.  they are further assigned to virtual carriers. 

So,anything starts with 171 / 170 should be valid phone numbers.

**Comment by penmetsaa** [comment]
@thefallentree 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.4.5: https://libphonenumber.appspot.com/phonenumberparser?number=%2B86+171-8222-0000

**Comment by thefallentree** [comment]
Thanks!

**Comment by thefallentree** [comment]
are you sure it is included in the release? We are unable to reproduce the
result.

**Comment by thefallentree** [comment]
pls ignore it was indeed fixed.

**Comment by penmetsaa** [comment]
Ok. Thanks for checking this. :)
