### ISSUE TITLE
Validation issue with 358500000 (FI)

### ISSUE THREAD

**Issue by scop** [googlei18n/libphonenumber#1179]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): FI

Example number(s) affected ("+1 555 555-1234"): 358500000

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 358XXXXXX, 358XXXXXXX (numbers with 6, 7, or 8 digits in national number, specified without leading + or 00, but with leading Finnish country code 358)

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

See already existing mobile->nationalNumberPattern in metadata for Finland.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=358500000&country=FI)

Consider a Finnish mobile number formatted as:
- International form, but without leading + or 00
- 6, 7 or 8 digits in the national number
- Examples: 358500000, 3585000000, 35850000000

When numbers like these are parsed using "FI" as the default region, an extra 358 prefix is prepended to them. Only numbers having 9 or more digits in the national number are parsed correctly without the extra prefix getting prepended.
- 358500000 results in country_code=358, national_number=358500000 but should result in  country_code=358, national_number=500000
- 3585000000 results in country_code=358, national_number=3585000000 but should result in  country_code=358, national_number=5000000
- 35850000000 results in country_code=358, national_number=35850000000 but should result in  country_code=358, national_number=50000000
- 358500000000 results in country_code=358, national_number=500000000 which is correct

It seems that for numbers formatted like this, national numbers having fewer than 9 digits get FROM_DEFAULT_COUNTRY as their source, and 9 or more digits in national number get FROM_NUMBER_WITHOUT_PLUS_SIGN. The latter is the one that produces correct results.

Numbers like these are found at least in the 35850xxxx (6 national digits) and 35850xxxxx (7 national digits) ranges; don't remember if I've seen one with 8 national digits. But as the existing metadata suggests (see mobile->nationalNumberPattern), they, as well as others starting with 4 might exist too.

**Comment by penmetsaa** [comment]
@scop,

Thank you for taking time to improve libphonenumber!

Without leading '+' or '00' in the input number, libphonenumber will not consider 358 as country code.
It considers it as part of the national number. 

If the number entered is too long (Ex: 35850000000), API tries to match the prefix with the country code of default country entered. If it is same, it trims the country code from input and try to parse it again. If it is in valid range (Ex: 358500000) 358 is considered as area code.

As per the evidence we have, the Finland phone numbers that start with 3 can have a max of 11 digits. This is the reason why your 12 digit input 358500000000 is parsed as Country code: 385, National number: 500000000, while fails for input less than 12 digits.

The input number should be in dialable formats (like e164 format, international format and national format) for the libphonenumber to parse it correctly. For more details, please refer java doc of [PhoneNumberUtil.parse()](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2772)

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
