### ISSUE TITLE
Support KW 566\d{5} as a valid mobile range for VIVA

### ISSUE THREAD

**Issue by wakiel** [googlei18n/libphonenumber#1190]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): KW

Example number(s) affected ("+1 555 555-1234"): +96556607933

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B96556607933&country=KW)

**Comment by keghani** [comment]
Thanks for reporting @wakiel!

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by wakiel** [comment]
hi ,when will be the coming release date ?

Date: Mon, 4 Jul 2016 04:52:10 -0700

**Comment by keghani** [comment]
Mid-next week. This is expected to be fixed in that release.

**Comment by wakiel** [comment]
dears when we will have a new MSISDN range , to which e mails or link we have to send to have that range defined fast and avoid any delay in activating new accounts for :-Twitter , face book , Whatsapp , ,, and other VoIP applications 

Date: Fri, 8 Jul 2016 06:57:59 -0700

**Comment by keghani** [comment]
If the information is public you can file an issue as you did this one.
Otherwise for private documents please sign the CLA and join the group for documentation sharing.

You can see detailed instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by wakiel** [comment]
Dear can you help us to get that issue solved by today or it will take more time :) ?

Date: Fri, 8 Jul 2016 06:57:59 -0700

**Comment by penmetsaa** [comment]
@wakiel,
This fix will be part of upcoming release. Mostly it will happen by tomorrow.

**Comment by keghani** [comment]
Fixed in 7.4.5
