### ISSUE TITLE
Ivory Coast number does not validate

### ISSUE THREAD

**Issue by tonyofrancis** [googlei18n/libphonenumber#1194]
The number + 225 89 74 57 91 does not validate with the library. It is a mobile number from the Ivory Coast.

**Reference from Wikipedia** 
To call in Ivory Coast, the following format is used:

    yy xxxxxx - calls within Ivory Coast
    +225 yy xxxxxx - calls from outside Ivory Coast to a landline
    +225 yy xxxxxx - calls from outside Ivory Coast to a mobile number

Thanks

**Comment by keghani** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

In particular, please provide us with:
- The range that you want added (for example, are all numbers beginning with 89 mobile numbers?)
- Who is the carrier for the range that you want added?
- Evidence (see guidelines linked above)

**Comment by padmaksha** [comment]
Fixed in release 7.5.1
http://libphonenumber.appspot.com/phonenumberparser?number=89+745791&country=CI
