### ISSUE TITLE
Validation issue with 110 (TW)

### ISSUE THREAD

**Issue by wmh** [googlei18n/libphonenumber#1195]
**This number is an emergency short code defined in ShortNumberMetadata.xml.**

Country/region affected (e.g., "US"): TW
Example number(s) affected ("+1 555 555-1234"): 110
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): **short code**
The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=110&country=TW&geocodingLocale=zh-TW)

**Comment by keghani** [comment]
Hi @wmh,

Sorry we never responded to this. The number is considered a valid short code, see our demo (`isValidShortNumber()`): http://libphonenumber.appspot.com/phonenumberparser?number=110&country=TW
