### ISSUE TITLE
Getting invalid mobile number for a valid India number also

### ISSUE THREAD

**Issue by Jayad** [googlei18n/libphonenumber#1201]
This is a valid India Number and with 7.4.4 version it is returning as invalid number

http://giggsey.com/libphonenumber/index.php?phonenumber=7287884288&country=IN&language=&region=

**Comment by giggsey** [comment]
@Jayad This is the project for Google's libphonenumber, not the PHP Port (which you appear to have linked to the demo of).

However, using the demo for Google's libphonenumber does return the same result: http://libphonenumber.appspot.com/phonenumberparser?number=7287884288&country=IN

**Comment by Jayad** [comment]
Hi ,
My bad, but basically it is using the Google's libphonenumber only for the check right?
This is a valid india number , but why it is not returning true for isValidNumber()? Any idea?

**Comment by giggsey** [comment]
@Jayad The PHP version is a port that *should* match the same as here. If it doesn't, it's a bug with the PHP version. As Google's actual demo is saying the number is invalid, it suggests that there is a metadata issue here.

I'm unable to help with this, but if you follow the [Contributing Guide](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue) that will help the issue get resolved.

**Comment by Jayad** [comment]
@giggsey : Hi, Both Google's actual version and PHP version returning same response, where as actually the number is in use and Provider is IDEA(India ).

**Comment by penmetsaa** [comment]
@Jayad ,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by padmaksha** [comment]
Fixed in release 7.5.1
http://libphonenumber.appspot.com/phonenumberparser?number=72878+84288&country=IN
