### ISSUE TITLE
Cannot dial parentheses

### ISSUE THREAD

**Issue by justechn** [googlei18n/libphonenumber#1203]
I am trying to use the phoneUtil.formatOutOfCountryCallingNumber function, but every time I pass in a US country code it returns the number with parentheses around the area code. 

According to the docs for the formatOutOfCountryCallingNumber function (https://github.com/googlei18n/libphonenumber) "You could also choose to format the number in the way it is dialed from another country:" This is suppose to represent the number as dialed. Since we don't dial parentheses or spaces on a phone can we get these removed? Or is there a way to get this number without them?

**Comment by justechn** [comment]
nevermind, the e164 number will give me what I need

**Comment by penmetsaa** [comment]
@justechn,

Thank you for taking the time to improve libphonenumber!

phoneUtil.formatOutOfCountryCallingNumber(PhoneNumber, RegionCode) just formats a phone number for out-of-country dialing purposes. If the country calling code of the number is the same as that of the region code where the number is from, the NATIONAL formatting will be applied. 

National format contains grouping and formatting characters  like parentheses, space..etc (This is how phone numbers are commonly represented in that country). This is the reason why you are getting O/P in 1 (213) xxx-xxxx format (213 is area code here).

More details in [java doc of this method.](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1337)
