### ISSUE TITLE
Mobile number portability was launched in Armenia

### ISSUE THREAD

**Issue by armleo** [googlei18n/libphonenumber#1209]
On April 1, 2014 Mobile number portability was launched in Armenia, which means that subscribers of mobile Operators can have any mobile network code by porting in from the host operator.

from [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Armenia)
I recomend adding information in readme or in documentation about mobile portability in general.

**Comment by keghani** [comment]
Thanks for letting us know @armleo!

We have documentation about number portability at https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-is-mobile-number-portability.

PhoneNumberUtil's isMobileNumberPortableRegion("AM") returns true, so the library's working as intended.

**Comment by armleo** [comment]
I mean add inormation about mobile portability in readme.md not in faq.md. And may be add link to faq.md. also please update demo cuz i cant see any usage of this function. (Maybe its just me)

**Comment by mizuni** [comment]
Hi @armleo - would you mind opening separate new requests for all these in order for us to triage each separate issue separately?
