### ISSUE TITLE
New phone number range from Megafon Tajikistan

### ISSUE THREAD

**Issue by Dilyamak** [googlei18n/libphonenumber#1211]

**Comment by penmetsaa** [comment]
@Dilyamak ,
Thank you for taking the time to improve libphonenumber!
Please mention the new range which is not supported.

Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by penmetsaa** [comment]
@Dilyamak ,
Thanks for raising separate issue #1216 and providing the details.
As there is nothing to do in this issue, closing it.
