### ISSUE TITLE
New Number range as one more operator introduce in INDIA i.e. Relience Jio.  RJ

### ISSUE THREAD

**Issue by rwalkover** [googlei18n/libphonenumber#1212]
New number series was introduce 

Here is the list.
7000,7001,7002,7003,7004,7005,7006,7007,7008,7009,7010,7710,7011,7012,7013,7014,7015,7016

please update this in your metadata regex.

**Comment by penmetsaa** [comment]
@rwalkover,

Thank you for taking the time to improve libphonenumber!

All the ranges mentioned above are already supported as mobile numbers in India.
Ex: https://libphonenumber.appspot.com/phonenumberparser?number=7016123456&country=IN

For range 7710 the carrier is returned as Airtel. For remaining ranges it is returned as Reliance. As per below official update 77100, 77108 and 77109 ranges are assigned to Airtel. http://www.dot.gov.in/sites/default/files/u10/MSC%20Code%20as%20on%2011052015%20%284%29_0.xls


Please share us the valid evidence that says whole 7710 range (or subrange of 7710)  belongs to Reliance. Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by penmetsaa** [comment]
@rwalkover ,
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.

**Comment by keghani** [comment]
Actually closing issue :)
