### ISSUE TITLE
Validation issue with +86 171-8222-0000

### ISSUE THREAD

**Issue by juliecain** [googlei18n/libphonenumber#1215]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +86 171-8222-0000

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B86+171-8222-0000)

**Comment by padmaksha** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. As shown in the demo is_valid() and is_possible() is set to true, which means the number/range 171  is valid range in our library. To check thelatest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

Thanks
