### ISSUE TITLE
New phone number range from Megafon Tajikistan

### ISSUE THREAD

**Issue by Dilyamak** [googlei18n/libphonenumber#1216]
Good day! The problem, that subscribers of mobile company Megafon Tajikistan can't sign in on twitter  When subscribers try to sign in with  such numbers there is message, that number is not correct. Can you add our number ranges  please?
These are our  number ranges;
+99290XXXXXXX
+99288XXXXXXX
+99255XXXXXXX
•Country/region affected (Republic of Tajikistan):
 •Example number(s) affected ("+992 907918185, +992881111599,  +992550053049"):
 •The phone number range(s) to which the issue applies ("++99290XXXXXXX
+99288XXXXXXX
+99255XXXXXXX)

 •The type of the number(s) (", "mobile", ".):

**Comment by padmaksha** [comment]
Hi Dilyamak,

Thank you for taking the time to improve libphonenumber!

With respect to ranges 88 and 90 (numbers  +992881111599, +992 907918185), these ranges are already supported by our library. Please see our demo http://libphonenumber.appspot.com/phonenumberparser?number=%2B992881111599 and http://libphonenumber.appspot.com/phonenumberparser?number=%2B992+907918185
When to try to validate the above two ranges(88 and 90) what error do you get , can you share a few screenshots? 
Please ask Twitter team to upgrade to the latest release of our library downloadable from http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.4.5/.

With regards to the other range 55 (number +992550053049) , we've accepted this issue and will fix this in an upcoming release.

Thanks

**Comment by padmaksha** [comment]
Fixed in release 7.5.1
http://libphonenumber.appspot.com/phonenumberparser?number=550053049&country=TJ
