### ISSUE TITLE
Validation of "short" numbers?

### ISSUE THREAD

**Issue by xbroak** [googlei18n/libphonenumber#1222]
For instance the number: 1250 in the UK is the "Mobile balance check" number for "Talk Mobile" a mobile operator. Should this number be validating or is there some other recommended practice for dealing with these?

**Comment by lararennie** [comment]
Yep, we should validate it. If it only works on that carrier, or goes to a
different location based on the carrier it should also be carrier specific.

19. jul. 2016 1.55 p.m. skrev "Joe Scott" <notifications@github.com>:

**Comment by xbroak** [comment]
OK, so this particular number is coming back as invalid! Any potential resolution?

**Comment by lararennie** [comment]
Can you provide a website showing this number? Then we can add support.

**Comment by xbroak** [comment]
Sorry, i'm an idiot. I've been searching for days. Only to realise, i meant "White Mobile" or "White Calling" not "Talk Mobile" here is the info:

https://www.whitecalling.com/sim-faq/#1457341105112-d88d53af-7ec0

Under "How do i check my balance"

**Comment by penmetsaa** [comment]
@xbroak 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 7.6.1
https://libphonenumber.appspot.com/phonenumberparser?number=1250&country=GB
