### ISSUE TITLE
isLeadingZeroPossible true/false for international premium-rates?

### ISSUE THREAD

**Issue by saidatta** [googlei18n/libphonenumber#1224]
Hello,

While I was playing with library and reading the unit tests I realized this particular scenario that left me puzzled. I would be much obliged if someone can shed some light?

**Scenario**
PhoneNumberUtilTest's testIsLeadingZeroPossible (Line 223) test case is testing whether isLeadingZero possible for 979 and it is asserting as false.
`    assertFalse(phoneUtil.isLeadingZeroPossible(979));  // International premium-rate
`
[here](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java#L223)

But, I noticed that the appropriate metadata for 979 in PhoneNumberMetadata.xml has
`    <territory id="001" countryCode="979" leadingZeroPossible="true">
`
[here](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L25626)

My question is if the metadata has the leadingZeroPossible has true, then shouldnt the test be assertTrue(...)?

Thank you

**Comment by keghani** [comment]
Thanks for asking @saidatta! Sorry this issue slipped our notice.
The tests are correct because they're actually testing another metadata file, [PhoneNumberMetadata*ForTesting*.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadataForTesting.xml).
