### ISSUE TITLE
New phone pattern in Montenegro(ME)

### ISSUE THREAD

**Issue by ildra** [googlei18n/libphonenumber#1236]
Hello!
In Montenegro (country code 382) libphone number doesn't validate number 063475356): 0038263475356. 
This is GSM number. Please add new phone pattern.
Thank you in advance.
Best regards! Dragan Ilic

**Comment by ildra** [comment]
Hello! 
This is filled template for metadata issue:
Country/region affected (e.g., "US"): ME
Example number(s) affected ("+1 555 555-1234"): +38163475356
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +381634XXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

BR! Dragan Ilic

**Comment by ildra** [comment]
Hello! 
I made mistake in previous post. So this is the corrected template
Country/region affected (e.g., "US"): ME
Example number(s) affected ("+1 555 555-1234"): +38263475356
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +382634XXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

BR! Dragan Ilic

**Comment by penmetsaa** [comment]
@ildra 
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by ildra** [comment]
Hello,
No problem. You can use this information for any purpouse also you could correct it. 
BR! Dragan

**Comment by penmetsaa** [comment]
This is fixed in release 7.5.2:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B38263475356

**Comment by ildra** [comment]
Thank you very much. Work fine.
BR! Dragan
