### ISSUE TITLE
Geocoding issue for number +16576234322

### ISSUE THREAD

**Issue by fabiomargarido** [googlei18n/libphonenumber#1237]
When invoking PhoneNumberToTimeZonesMapper.getTimeZonesForNumber() after parsing (and verifying with isValidNumberForRegion()) the number "+16576234322", I'm getting a list of timezones with 35 entries as a result.

Besides being long, the list seems pretty inconsistent as it includes timezones from both the west and east coasts of the US, as well as timezones in the caribbean and Canada. All the info I can get on the Internet points to this being a California area code, so it seems the results are wrong.

This is with libphonenumber 7.4.5 and geocoder 2.47.

Thanks.

**Comment by fabiomargarido** [comment]
Just an update: I've verified I get the same behavior with versions 7.5.0 and 2.48.

**Comment by penmetsaa** [comment]
@fabiomargarido,
Thank you for taking the time to improve libphonenumber!
This issue is similar to #991 and will be tracked there. Hence closing the issue here.
