### ISSUE TITLE
Protocol Buffer Dependency Issue

### ISSUE THREAD

**Issue by bjenning04** [googlei18n/libphonenumber#1239]
Is there any possibility of removing the protobuf-java dependency from the libs folder and have it pull transitively through Maven? Or possibly change the package name for those classes when using maven-shade-plugin? My team is running into an issue now where we have 2 third-party dependencies that have used the maven-shade-plugin to pull the classes from protobuf into their own jar, which is causing duplicate class definition errors for our project. Our only option at this point is to remove the protobuf classes from each jar and add them to the libs folder of our project.

**Comment by bjenning04** [comment]
Looks like this is related to https://github.com/googlei18n/libphonenumber/issues/913

**Comment by bjenning04** [comment]
Also, we were using 7.2.5, I see that the package name was changed for 7.4.0. This should be an acceptable workaround for my team until the stable version of protobuf-java is released.

**Comment by penmetsaa** [comment]
@bjenning04, 
Great that you found this out already, please sync past 7.4.0 to pick up the fix.
The long-term fix is tracked at #913, closing this.
