### ISSUE TITLE
Outdated carrier data for +27 (South Africa)

### ISSUE THREAD

**Issue by RyanZailab** [googlei18n/libphonenumber#1242]
Country/region affected (e.g., "US"): ZA
Example number(s) affected ("+1 555 555-1234"):
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +27 64 6XX XXXX, +27 64 7XX XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): Attached spreadsheet of South Africa's Number carrier mappings provided to us by the Number Portability company (http://www.number-portability.co.za/). These number ranges are defined by ICASA (https://www.icasa.org.za/LegislationRegulations/FinalRegulations/TelecommunicationsRegulations/NumberingPlan/tabid/160/ctl/ItemDetails/mid/2562/ItemID/12769/Default.aspx)
 and are managed by the company.

[Updated MNP Numbering Plan_25 July 2016@09h35.xls.xlsx](https://github.com/googlei18n/libphonenumber/files/396947/Updated.MNP.Numbering.Plan_25.July.2016.09h35.xls.xlsx)

**Comment by RyanZailab** [comment]
The un-updated number ranges are in the +27 6 range : +27 625... - +27 629 Cell C, +27 630... - +27 0635 MTN, +27 636... - +27 637 Vodacom, +27 638... - +27 640 MTN, +27 641... - +27 645 Cell C and +27 646... - +27 647 Cell C.

Updated resource file: [27.txt](https://github.com/googlei18n/libphonenumber/files/397165/27.txt)

**Comment by padmaksha** [comment]
@RyanZailab 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

In future when you contribute to any files in libphonenumber, like the carrier file for South Africa [27.txt](https://github.com/googlei18n/libphonenumber/files/397165/27.txt) please create [pull request](https://help.github.com/articles/creating-a-pull-request/) for same. 
We will take care of this update for carrier file provided by you.

Thanks

**Comment by RyanZailab** [comment]
Thank you @padmaksha for the help.

I have created pull request https://github.com/googlei18n/libphonenumber/pull/1250. 

Was my pleasure.

**Comment by padmaksha** [comment]
Thanks for creating the pull request. 
The ranges 646 and 647 are returned as valid ranges by library.
http://libphonenumber.appspot.com/phonenumberparser?number=646123456&country=ZA. We will update carrier details accordingly. Closing this issue here . Carrier updates will be tracked in #1250.
