### ISSUE TITLE
Numbers +251 98XXXXXXX not recognized for Ethiopia

### ISSUE THREAD

**Issue by Jessed1313** [googlei18n/libphonenumber#1247]
Country/region affected (e.g., "US"): **Ethiopia**
Example number(s) affected ("+1 555 555-1234"): **+255 985847389**
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): **+251 98 XXX-XXXX**, and maybe broader. See supporting evidence.
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): **"mobile"**
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence: The plan to use these numbers dates back to 2005, but the ability to actually use them is very recent. (https://github.com/users/Jessed1313/emails/24051083/confirm_verification/99408780b9ee1d1510ae27299a2dd63ca559e210, under point number 5), prefixes 98 are listed under valid numbers to be assigned in the future by EthioTelecom.

**Comment by padmaksha** [comment]
@Jessed1313 

Thank you for taking the time to improve libphonenumber!

We were able to connect to +255 985847389 but we can't find official evidence for the
actual ranges that are valid. We can't support single numbers, we need context
about the prefix that makes them valid. The link you provided as evidence (https://github.com/users/Jessed1313/emails/24051083/confirm_verification/99408780b9ee1d1510ae27299a2dd63ca559e210) seems to divert to settings page.

Thanks

**Comment by Jessed1313** [comment]
[73270_ww9.pdf](https://github.com/googlei18n/libphonenumber/files/403273/73270_ww9.pdf)

My apologies. I accidentally put in the incorrect link. Please see this link: http://www.itu.int/itudoc/itu-t/number/e/eth/73270.html. The document you can download from that page can be found in English, French, or Spanish. I have also attached the English version of the document, if you want that.

**Comment by padmaksha** [comment]
@Jessed1313 

There are no details about 98 prefix in ITU doc that is shared stating that it is a mobile range .
We have accepted this issue based on assumption that generally Ethiopia mobile numbers start with 9 and will fix this in an upcoming release..

With respect to the documents shared by you: 
Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

Thanks

**Comment by keghani** [comment]
Fixed in 7.6.0.
