### ISSUE TITLE
Validation issue with 0900003987 (TW)

### ISSUE THREAD

**Issue by singjie** [googlei18n/libphonenumber#1252]
Country/region affected (e.g., "US"): TW

Example number(s) affected ("+1 555 555-1234"): 0900003987

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 0900XXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): Not PREMIUM_RATE

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
- http://s3-ap-southeast-1.amazonaws.com/singjiecom/files/image%20(1).png
- http://mobile-phone.com.tw/0900/

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0900003987&country=TW)

Hi, I noticed the above number is rated as PREMIUM_RATE.

We have locals using the said number and is not a PREMIUM_RATE number but a normal mobile number. 

Please advise and attached documents.

**Comment by padmaksha** [comment]
@singjie 

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by singjie** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=0900003987&country=TW still shows "PREMIUM_RATE" instead of "MOBILE". 

Please advise.

**Comment by lararennie** [comment]
Yes, we'll mark this as fixed when it has been fixed. We have a fix in progress. Thank you for your patience.

**Comment by singjie** [comment]
Oops ok, sure and thanks!

**Comment by singjie** [comment]
Hi guys, any updates on this? Any estimated timeline? Otherwise, we will need to patch our app to assume premium_rate == mobile.

**Comment by kkeshava** [comment]
@singjie,

Sorry for the delay. Apart from this fix we are also updating few premium rate numbers and fixedline numbers based on Taiwan’s National numbering plan https://www.ncc.gov.tw/chinese/files/07080/265_1037_070808_1.doc This is a direct link to the PDF, could not find the source page.

We will be fixing and releasing it within the next two weeks.

**Comment by singjie** [comment]
New link found for 0900 if you guys are still interested: : http://www.fetnet.net/estore/number-NP/showNumberResultList

**Comment by penmetsaa** [comment]
@singjie ,
This is fixed in release 7.7.5:
https://libphonenumber.appspot.com/phonenumberparser?number=0900003987&country=TW (Category is now mobile)
