### ISSUE TITLE
Outdated carrier data for +86 (China)

### ISSUE THREAD

**Issue by mgoyal1** [googlei18n/libphonenumber#1259]
Country/region affected (e.g., "US"): China
Example number(s) affected ("+1 555 555-1234"): The issue applies to numbers starting with 861703, 861705, 861706, 86172, 8600, 861349
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A
Supporting evidence: Please find the attached IR21 provided by ChinaMobile and refer to the MSISDN Number range(s).
[IR21 China MobileCMI20160229 V1.23.pdf](https://github.com/googlei18n/libphonenumber/files/412827/IR21.China.Mobile.CMI.20160229.V1.23.pdf)

**Comment by mizuni** [comment]
@mgoyal1,

Thanks for providing all the details we need!

I see you have created PR #1260 for this. We can continue review process in that PR. 
We already support above mentioned ranges. And all we need to do is update carrier data.
Closing this issue here.
