### ISSUE TITLE
Validation Issue with +963959117182 android

### ISSUE THREAD

**Issue by daniaDlbani** [googlei18n/libphonenumber#1261]
`PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();      
                  Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse("+963959117182" , "");    
                    phoneUtil.isValidNumber(phoneNumber)`

I am getting false as result for validation.meanwhile with similar number I am getting true
 this one for example "+963956xxxxxx"

Country/region affected ("SYR"):
Example number(s) affected ("+963959xxxxxx"):
The type of the number(s) ("mobile"):

**Comment by penmetsaa** [comment]
@daniaDlbani ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.
Below wikipedia page is considered as evidence for this 959 range. 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Syria

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by daniaDlbani** [comment]
thanks for the fast replay and waiting the update.

**Comment by keghani** [comment]
Fixed in 7.6.0.
