### ISSUE TITLE
Validation issue with +221785446317

### ISSUE THREAD

**Issue by HeyBillFinn** [googlei18n/libphonenumber#1263]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): SL

Example number(s) affected ("+1 555 555-1234"): +221785446317

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +221 78 XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

https://www.numberingplans.com/?page=plans&sub=phonenr&alpha_2_input=SN&current_page=22

<img width="524" alt="screen shot 2016-08-11 at 8 15 25 am" src="https://cloud.githubusercontent.com/assets/987411/17593765/d6bbfac6-5f9b-11e6-8707-fbc092ce0c8e.png">

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B221785446317)

**Comment by penmetsaa** [comment]
@HeyBillFinn ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by keghani** [comment]
Fixed in 7.6.0.
