### ISSUE TITLE
Slovakia mobile phone number prefix - 0945

### ISSUE THREAD

**Issue by peter-veres** [googlei18n/libphonenumber#1266]
Hi, Slovak mobile operator Orange uses prefix 0945 for their cellphone services, could you please add it as valid.

Country/region affected (e.g., "US"): SK
Example number(s) affected ("+1 555 555-1234"): +421 945 111 222
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +421 945 XXX XXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): normal price

Assignment can be verified here:
https://www.ezd.sk/dbpc/databazacisel.php

Ine section Hľadanie prideleného čísla please select: 
(o) Hľadať podľa časti čísla (podľa zadaných počiatočných číslic)

In the input field please enter: 0945

The table shows which numbers are assigned (0945 000000  až  0945 999999), Podnik means to who this prefix is assigned (Orange Slovensko), Pridelene od means From which date it's assigned, Pridelene do means To which date it's assigned.

This document also proves (sort of) that Orange owns +421 945 XXX XXX phone numbers.

https://www.orange.sk/fileadmin/orange/user_uploads/dokumenty/onas/tlacove-centrum/pravne-dokumenty/05503-OR-zmluvy-EN_priloha1-Agree4Int-TrafficTermination.pdf

**Comment by peter-veres** [comment]
This document also proves (sort of) that Orange owns +421 945 XXX XXX phone numbers.

https://www.orange.sk/fileadmin/orange/user_uploads/dokumenty/onas/tlacove-centrum/pravne-dokumenty/05503-OR-zmluvy-EN_priloha1-Agree4Int-TrafficTermination.pdf

**Comment by padmaksha** [comment]
@peter-veres 

This looks like a bug. We'll fix it in an upcoming release.
Thanks for taking the time to improve libphonenumber!

**Comment by keghani** [comment]
Fixed in 7.6.0.
