### ISSUE TITLE
Morocco number validated as invalid

### ISSUE THREAD

**Issue by balgf** [googlei18n/libphonenumber#1267]
Morocco local prefix 5364 should be valid.
An existing number +212-5364-xxxxx is validated as invalid which we verified as an actual phone number.

**Comment by padmaksha** [comment]
@balgf 

We are not able to find  digit numbers with this prefix online or any official evidence that the range is valid. Please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Thanks

**Comment by balgf** [comment]
@padmaksha  Our client won't allow sharing of his number in public. If it's possible, can ring random number that starts with +2125364. Or I can send the actual number in private.

**Comment by padmaksha** [comment]
@balgf 

It would be great if you could provide some official evidence  or website links that lists numbers  with the range 5364. 

Thanks

**Comment by padmaksha** [comment]
Hi Bal,

You can send the actual number in private to libphonenumber-supporting-docs@googlegroups.com. Only our Google team has access to it.
Once we validate that the number is working we will add the range 5364 to our library.

Thanks

**Comment by padmaksha** [comment]
This issue is blocked on your  input. Please help us find evidence that 5364 range is valid, or provide an example number from a business website or similar or a valid phone number as stated above. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by padmaksha** [comment]
Thanks for providing all the details we need! We have found evidence that the range is valid. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by balgf** [comment]
Would appreciate if you guys don't publicize the number i sent. Since you guys verified the issue, please find another number to publicly attach to this issue. Respectfully. Thank you

**Comment by padmaksha** [comment]
Hi Bal,

We will not publicize your number as we have got other evidence.

Thanks

**Comment by lararennie** [comment]
This was fixed in release 7.6.1
