### ISSUE TITLE
Observation with India phone number parsing

### ISSUE THREAD

**Issue by saketanisha** [googlei18n/libphonenumber#1268]
`var region = 'IN';
var phone = '4155216849';
var phoneNumber = phoneUtil.parse(phone, region);

console.log(phone + ' isValid ' + phoneUtil.isValidNumber(phoneNumber));
console.log(phone + ' number type ' + phoneUtil.getNumberType(phoneNumber));
console.log(phoneUtil.format(phoneNumber, PNF.INTERNATIONAL));`

Output:

    4155216849 isValid true

    4155216849 number type 0

    +91 4155 216 849

I tried dialing this number in India and seems its not a valid number in India.

Few references:

https://en.wikipedia.org/wiki/Telephone_numbers_in_India
https://en.wikipedia.org/wiki/Mobile_telephone_numbering_in_India

**Comment by padmaksha** [comment]
@saketanisha 

We don't support single numbers per say , and validation of the number is based on the ranges/prefixes and not the actual validity of number itself. As range 415 is valid range in India so the number 4155216849 is returned as valid.

Thanks

**Comment by saketanisha** [comment]
I believe 415XXXXXXX is not a valid series in India. Can you please provide a valid number in Inida starting with 415.

**Comment by saketanisha** [comment]
[Here](http://dot.gov.in/sites/default/files/nnp2003.pdf) is the numbering scheme from [Department of Telecommunication](http://dot.gov.in/). I spent a good amount of time matching the various combination of the number but don;t find any match. I believe the 91 reg ex needs a fresh look.
