### ISSUE TITLE
New operator code for Claro Colombia

### ISSUE THREAD

**Issue by cindy8** [googlei18n/libphonenumber#1269]
Hi,

I have a few cases of new mobile numbers for Claro Colombia, Claro has recently added a new operator code `323` but they haven't announce it officially, I contacted them via Twitter to check if the number was valid for their carrier, they confirmed it but I have not official document, does the twitter message is support enough to add it to the library? 

Country/region affected: CO
Example number(s) affected: +57 323 482 7533
The phone number range(s) to which the issue applies: +57 323 XXX XXXX
The type of the number(s): mobile
The cost, if applicable: -

You currently support the codes: `310, 311, 312, 313, 314, 320, 321, 322` for Claro Colombia.

Thank you for your help.

**Comment by padmaksha** [comment]
@cindy8 

Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the [demo]( http://libphonenumber.appspot.com/phonenumberparser?number=323+482+7533&country=CO) (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

Thanks

**Comment by cindy8** [comment]
Thanks so much @padmaksha, and my apologies I tried the demo a few weeks back and went to Claro to get a confirmation from them before posted the issue, but I'm glad you included it already.

Thanks.
