### ISSUE TITLE
Add BR carrier mappings for Algar Telecom or CTBC Celular

### ISSUE THREAD

**Issue by MarcusAdriano** [googlei18n/libphonenumber#1276]
I'm developing an app and its use the libphonenumber.
In any tests in Brazil, the libphonenumber, show carrier name invalid, like null name or carrier name who was deprecated! Example, the carrier name of the number +55 34 99870-6657 (NATIONAL number, region MG in Brazil) is Algar Telecom or CTBC Celular and in the execution, the library return "Telemig Celular", in others cases, the result is null and the phone numbers are valid.

For more information:
https://www.numberingplans.com/?page=plans&sub=phonenr&alpha_2_input=BR&current_page=12120

**Comment by MarcusAdriano** [comment]
Country/region affected (e.g., "US"): BR

Example number(s) affected ("+1 555 555-1234"): 34998706657

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=34998706657&country=BR&geocodingLocale=pt-BR)

**Comment by keghani** [comment]
Thanks for reporting @MarcusAdriano!

Indeed, we have no support for Algar Telecom or CTBC Celular currently. Could you please provide details as to which ranges they own? For example, are all numbers beginning with "34 98", "34 998" for this carrier? Any others? To provide evidence please see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

We have another problem whereby numbers with the 9th digit did not update the carrier mapping. I filed #1284 to track this.

Separately still, we have numbers which we consider valid and mobile who carrier mapping is unknown to us (so we're not returning anything as you mentioned, e.g. [34 9870 6657](http://libphonenumber.appspot.com/phonenumberparser?number=34+9870+6657&country=BR)). If you have these details please provide those mappings.

**Comment by MarcusAdriano** [comment]
@keghani I got in touch with the support of ALGAR operator and I am waiting for the reply

**Comment by keghani** [comment]
@MarcusAdriano Any update on which ranges are owned by  Algar Telecom or CTBC Celular? We can't fix the issue without this information :(

**Comment by MarcusAdriano** [comment]
@keghani Sorry for the delay, but no awnser yet! I'll try contact Algar Telecom again.

**Comment by MarcusAdriano** [comment]
@keghani Sorry for the delay again. So, I change my project and start other project using this lib, but the result is same. In first time, the Telemig Celular not exists more and in any states of Brazil are add a ninth digit in mobile phone numbers, i.e. in Minas Gerais some the ninth digit was add a short time ago then when I verified on the lib, the result is Telemig, but using without ninth digit, the result is correct operator. Sorry, but how you learn about the numbers and operators in Brazil or others country?

**Comment by keghani** [comment]
The 9-digit issue is a known one, please see my comment from Aug 22, 2016 for a summary of the different issues we've been discussing.

I would expect the result to be the same since we didn't fix this issue.

In this issue (#1276) we're tracking the addition of Algar Telecom and CTBC Celular ranges, which is blocked on more information. Please help us find this (see [that comment](https://github.com/googlei18n/libphonenumber/issues/1276#issuecomment-241367371) for details), otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by keghani** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
