### ISSUE TITLE
Validation issue with +1 268 73X XXXX from Antigua and Barbuda (AG)

### ISSUE THREAD

**Issue by pbakondy** [googlei18n/libphonenumber#1291]
+1 268 7XX XXXX are mobile phone numbers in Antigua and Barbuda
+1 268 72X XXXX numbers are accepted by this library.
+1 268 73X XXXX numbers are invalid

Reproducible:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+268+736+1000

see the contacts of this company:
https://www.digicelgroup.com/ag/en/mobile/contact-us.html

Extra info
- http://www.howtocallabroad.com/results.php?callfrom=united_states&callto=antigua_barbuda
- http://www.searchyellowdirectory.com/reverse-phone/1268/

**Comment by kkeshava** [comment]
Thank you for taking the time to improve libphonenumber!

Could you please provide evidence which says either complete 73 range is valid or specific subranges of 73 (like 731,732..). See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Generally Antigua and Barbuda releases its mobile ranges defining first 3 digits. Earlier official announcement: http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000080001MSWE.doc. As per existing evidences we can add only 736 sub range.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by pbakondy** [comment]
Sadly I could not found any newer official document about the area codes. The referenced document from 2003 is obviously deprecated.

I found a Yellow Pages-like site with phone numbers:

http://www.antiguanice.com/v2/directory.php

There are phone numbers listed with 732, 734, and 736.

I also found these area codes (not listed in the document): 465, 720, 776, 783, 785, 788.

**Comment by penmetsaa** [comment]
Fixed in release 7.6.1
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+268+736+0000

**Comment by pbakondy** [comment]
I think it is only a partial fix.

What about these numbers?

> There are phone numbers listed with 732, 734, and 736.
> I also found these area codes (not listed in the document): 465, 720, 776, 783, 785, 788.

**Comment by penmetsaa** [comment]
@pbakondy 
True, it is only partial fix. We missed your latest additions.
We will be supporting 732 and 734 ranges also in an upcoming release based on numbers provided in http://www.antiguanice.com/v2/directory.php.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in 7.7.1: https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+%28268%29+732-0059
