### ISSUE TITLE
Doubt about Spanish numbering plan

### ISSUE THREAD

**Issue by coxnegative** [googlei18n/libphonenumber#1293]
I see this comment in PhoneNumberMetadata[1]

> The ranges 969060900 to 969061099 and 973900000 to 973909999 are mobile according to
>            information received from Lleida Networks.

Would you mind sharing this info ? I do not think this is valid, as the numbering plan for Spain [2] is quite clear: Mobile numbers starts with 6 or 7 and the prefix 9 has always designated geographic numbers.

Doing a query against the mobile phone database [3] gives an error indicating that the number 969060900 is not a valid mobile phone.

Doing the same query against the fixed phone database [4] returns that the phone is valid and registered to Lleida

> Resultado de la consulta del número:  969060900
> Operador propietario: LLEIDA NETWORKS SERVEIS TELEMATICS, S.A.
> Fecha consulta: 25-ago-2016 12:05:37

Thanks.
Luis

[1] https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L7080

[2] http://www.minetur.gob.es/telecomunicaciones/es-ES/Servicios/Numeracion/Documents/14-10_Descripcion_PNN.pdf

[3] http://www.cmt.es/pmovil/SelectOption.do

[4] http://www.cmt.es/pfija/SelectOption.do

**Comment by kkeshava** [comment]
Hi, 
Thank you for taking the time to improve libphonenumber!

We emailed syniverse and clxnetworks to clarify and they both confirmed that they were mobile, so we are following this for now. We will also try to email Lleida networks and see if they can reconfirm.

**Comment by kkeshava** [comment]
Hi,

Leida networks has confirmed that these numbers are mobile with 2-way IP sms services. 
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
