### ISSUE TITLE
Joining libphonenumber-discuss Google Group

### ISSUE THREAD

**Issue by calebcase** [googlei18n/libphonenumber#1299]
I can't seem to join the discussion mailing list from either of the recommended methods in the CONTRIBUTING.md or reference in JavaDoc.

Visiting http://groups.google.com/group/libphonenumber-discuss/about redirects to https://groups.google.com/forum/#!aboutgroup/libphonenumber-discuss which results in a 658 error.

Visiting http://groups.google.com/group/libphonenumber-discuss redirects to https://groups.google.com/forum/#!forum/libphonenumber-discuss which results in a 418 error.

How should new users join this list?

**Comment by lararennie** [comment]
Both links work for me. That is exactly the right way to do it. 
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error - these are very weird errors to be getting!
Can you try again? Can you go to groups.google.com and search for libphonenumber-discuss from there?

**Comment by calebcase** [comment]
Those aren't HTTP status codes, they are application error codes I see in the Google Groups UI. I've also tried searching for `libphonenumber-discuss`, but no results show up (both logged into google and not).

**Comment by calebcase** [comment]
The exact application messages it is giving are:

"You do not have permission to access this content. (#658)"
You do not have permission to access this content. (#418)

**Comment by kushmansingh** [comment]
I get the same error as @calebcase. 
![screen shot 2016-08-29 at 12 40 35 pm](https://cloud.githubusercontent.com/assets/12158241/18059200/df9fa978-6de5-11e6-9618-375cf28082dc.png)

**Comment by lararennie** [comment]
Thanks for letting us know! We haven't changed anything recently and people do join from time to time, so I'm not sure what's happened. I have in any case changed a setting to make it easier to find the group, I don't know if this will make any difference?

**Comment by calebcase** [comment]
Thanks @lararennie ! That appears to have fixed it. I was able to find the list and send a request to join.

**Comment by lararennie** [comment]
OK! Great!
