### ISSUE TITLE
Validation issue with +448778630000 (GB)

### ISSUE THREAD

**Issue by makoo93** [googlei18n/libphonenumber#1303]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected : GB

Example number(s) affected : 
+448778630000
+448778580000
+448778760000
+448662200000

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
+ 44 877 XXX XXXX
+44 866 XXX XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): UNKNOWN

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B448778630000&country=GB)

**Comment by giggsey** [comment]
Neither [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Kingdom), nor [Ofcom](http://www.ofcom.org.uk/static/numbering/#special) have 0877x or 086x as valid numbers.

Do you have a source of these being used?

**Comment by penmetsaa** [comment]
@makoo93,

Thank you for taking the time to improve libphonenumber!

We are also not able to find any official evidences that support these ranges.
And are not able to connect to any of the numbers provided / that are found online.
https://www.google.co.in/#q=%22%2B44+877%22

At present we need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by makoo93** [comment]
Thanks for your help.
We are searching official évidences that these numbers exists.

**Comment by keghani** [comment]
@makoo93 How did you come by these numbers? What makes you think they're valid?

**Comment by makoo93** [comment]
Our customer use them and it works. We are searching where they bought them.

**Comment by penmetsaa** [comment]
@makoo93,
As we are not able to find any official evidences for these ranges, can you send us the actual numbers that are working in private to libphonenumber-supporting-docs@googlegroups.com ?

Only our Google team has access to it. Once we validate that the number is working we will add support to respective ranges.

**Comment by makoo93** [comment]
Hello,

Our Customer who used these phone numbers didn't send us official evidences that support these ranges.
They didn't use them anymore. We think it was test or fake numbers.

Sorry about the waisted time.

We are closing this issue.

**Comment by penmetsaa** [comment]
@makoo93 
Thanks for the update :)
In future you can upfront ask these details to your customers for quick turn around / fix.

**Comment by penmetsaa** [comment]
@makoo93 
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
