### ISSUE TITLE
Validation issue with +6285100042009

### ISSUE THREAD

**Issue by heriihadiian** [googlei18n/libphonenumber#1304]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"): +6285100042009

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Carrier Name : Telkomsel

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B6285100042009)

**Comment by lararennie** [comment]
What is the issue specifically? That we don't have the carrier name?

**Comment by heriihadiian** [comment]
yes, there's n 62851 on

https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/62.txt#L667

**Comment by penmetsaa** [comment]
@heriihadiian,
Thanks for providing the details! Below wikipedia page also confirms same.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Indonesia
We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
