### ISSUE TITLE
India STD codes 8342, 8343, 8345, 8346 removed but BSNL still shows as valid

### ISSUE THREAD

**Issue by Ketan-Desai** [googlei18n/libphonenumber#1311]
Sir,

The above mentioned STD codes still exist, at least as per following BSNL website
http://dq.ndc.bsnl.co.in/bsnl-web/stdSrchByCode.seam

8342 - Margao, Maharashtra
8343 - Ponda, Maharashtra
8345 - Sanguem, Maharashtra
8346 - Canacona/Quepem, Maharashtra

Thanks

**Comment by kkeshava** [comment]
Hi Ketan Desai,
Thank you for taking the time to improve libphonenumber!

834[2356] codes were removed as per #1159. All the places, i.e Margao Ponda, Sanguem and Canacona/Quepem, belong to Goa, not Maharastra. We also verified by dialing few of the numbers that we got online, but none of them seem to work. 
Please share any publicly available phone numbers which work or evidence that you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by Ketan-Desai** [comment]
Sir,
Thanks for your dedicated efforts.

Please correct following STD code area...

**253 = Nasikcity, Maharashtra**
> Nasik City

**291 = Jodhpur Jodhpur, Rajasthan**
> Jodhpur, Rajasthan

**7266 = Jalgaonjamod, Maharashtra**
> Jalgaon/Jamod???

Also, **7265 - Nandura, Maharashtra** is removed, any reason?

Thanks

**Comment by Ketan-Desai** [comment]
Sir,

Thanks for your dedicated efforts.

Please correct following STD code area...

*253 = Nasikcity, Maharashtra*
> Nasik City

*291 = Jodhpur Jodhpur, Rajasthan*
> Jodhpur, Rajasthan

7266 = Jalgaonjamod, Maharashtra
> Jalgaon/Jamod???

Also, *7265 - Nandura, Maharashtra *is removed, any reason?

Thanks

**Comment by kkeshava** [comment]
@Ketan-Desai,
Sorry for the delay. Thanks for providing all the details we need! We will correct the names for area codes for 253, 291 and 7265, but currently we will not be doing changes to 7266 = Jalgaonjamod, Maharashtra as we found many online evidences which mentions it as Jalgaonjamod and not Jalgaon/Jamod.
http://www.mapsofindia.com/std/india/maharashtra/jalgaonjamod.html
http://www.stdcodelookup.com/maharashtra/jalgaonjamod/
http://www.dot.gov.in/sites/default/files/nnp2003.pdf

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
The change is done as part of 8.1.0 release.
