### ISSUE TITLE
+48568753358

### ISSUE THREAD

**Issue by siematypie1** [googlei18n/libphonenumber#1322]
Country/region affected (e.g., "PL"):
    Example number(s) affected ("+48567753358"):
    The phone number range(s) to which the issue applies ("+48567753358"):
    The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
    The cost, if applicable ("toll-free", "shared cost"):
    Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): s

Provide supporting evidence

**Comment by padmaksha** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
