### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [googlei18n/libphonenumber#1325]
Hello @lararennie ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I am not sure which files are needed to be grab.
I think the main file is `javascript/i18n/phonenumbers/phonenumber.pb.js`, isn't it?
And are there any other dependency files needed to be grab?
Please help me confirm that.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7805

**Comment by lararennie** [comment]
That is not the main file, but you'll need it :)
phonenumberutil.js is what I'd consider the "main" file. If you want everything but not the tests or demo, you need:

asyoutypeformatter.js
metadata.js
phonemetadata.pb.js
phonenumber.pb.js
phonenumberutil.js

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by kennynaoh** [comment]
Thanks @lararennie

**Comment by PeterDaveHello** [comment]
I have a question, don't we need metadatalite.js?

**Comment by lararennie** [comment]
You only need one or the other; metadatalite.js is the same as metadata
without example numbers present.

2016-11-11 10:19 GMT+01:00 Peter Dave Hello <notifications@github.com>:

**Comment by lararennie** [comment]
(I don't know if you include both how users will decide which one they
want, but if it's possible for them, you could include both.)

2016-11-11 10:31 GMT+01:00 Lara Rennie <lararennie@google.com>:

**Comment by PeterDaveHello** [comment]
Yes we should include both and let the users decide what they'll like to use.
