### ISSUE TITLE
Validation issue with number containing braces eg format (U.S) 00 1 (765) XXX-XXXX

### ISSUE THREAD

**Issue by yoda89** [googlei18n/libphonenumber#1326]
The library is not able to validate a number having format like 00 1 (765) XXX-XXXX, stored on the phone.
The number is of US. However it is stored on the phone in India (So default country code passed is IN). The number is a valid number, but library is not able to validate this number.

**Comment by keghani** [comment]
+17651230000 is a valid US number and our demo says so:

**Comment by keghani** [comment]
Sorry, made a mistake the first time!

+17651230000 would be a possible phone number in the US in E164 format but to dial this from India you need to put "001" in front of the country calling code, so 001 1 7654 123 0000 (there are two 1s).

In this case indeed we consider the range invalid in the US, see our demo: http://libphonenumber.appspot.com/phonenumberparser?number=%2B17651230000&country=US

Please provide evidence that this is a valid range. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by lararennie** [comment]
Actually it depends on the value of XXX-XXXX. We don't accept it if the first X is a 1, which is the link Keghani provided.

Your example works perfectly fine, if I put a 2 in.

http://libphonenumber.appspot.com/phonenumberparser?number=00+1+%28765%29+222-2222&country=IN

Brackets are fine. Are you perhaps using isValidForRegion, not isValid? Read the javadocs to see more info about when isValidForRegion is appropriate (hint: usually not.)

I'll close this as it is not an issue with our library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.

**Comment by yoda89** [comment]
All right thanks, I was indeed using isValidNumberForRegion, will change it to isValidNumber check.
The range is correct it actually starts with 4. There is no issue with it when when I call.
