### ISSUE TITLE
Validation issue with 0651082308 (TH)

### ISSUE THREAD

**Issue by singjie** [googlei18n/libphonenumber#1331]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): TH

Example number(s) affected ("+1 555 555-1234"): 0651082308

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +6665XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): MOBILE

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

http://s3-ap-southeast-1.amazonaws.com/singjiecom/files/IMG_0312.jpg

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0651082308&country=TH)

**Comment by kkeshava** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.7.1: https://libphonenumber.appspot.com/phonenumberparser?number=0651082308&country=TH
