### ISSUE TITLE
Please dont refer to https://github.com/erezak/libphonenumber-csharp anymore

### ISSUE THREAD

**Issue by Danthar** [googlei18n/libphonenumber#1332]
This project is dead. PR's for metadata updates go ignored. Comments on issues are from everybody except the original owner.

https://github.com/aidanbebbington/libphonenumber-csharp seems like a reasonable alternative, but im not sure. Recommendations are appreciated.

**Comment by mizuni** [comment]
Thanks for reporting this! Our team is going to look into this alternative before any updates.
