### ISSUE TITLE
Issue validating many PG numbers

### ISSUE THREAD

**Issue by craigafox** [googlei18n/libphonenumber#1333]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): PN

Example number(s) affected ("+1 555 555-1234"): +6752764280

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +675 276 XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): SATELLITE

The cost, if applicable ("toll-free", "premium rate", "shared cost"):

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): 
ITU: http://www.itu.int/oth/T02020000A4/en
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000A40003PDFE.pdf

On the PDF you can see this range on page 5, but it appears that many (all?) of the ranges on pages 4 and 5 do not validate.

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We support only VSAT Systems in ‘Special services access’ column given in the ITU doc. We support them as VOIP numbers.

To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines (https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

Radio Paging Terminals, Radio Paging, TeliSat and DomSat numbers are not supported intentionally.

We in libphonenumber only accept ranges that a human might call or send an SMS to.
Looks like Radio Paging Terminals, Radio Paging, TeliSat and DomSat numbers violate this assumption, similar to M2M numbers. Please check:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please reopen the issue if you are able to find any valid evidence which says that these numbers can be called or able to send SMS to them.
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by craigafox** [comment]
The number provided in this issue +6752764280 is a valid number and is answered by the company in question.
You can see the number on their website: http://www.k92mining.com/contact-2/

**Comment by craigafox** [comment]
@kkeshava How do I go about getting this re-opened?

**Comment by lararennie** [comment]
Tada :)

Qn for you: do you know if these numbers have sms capability? I saw one listed as "mobile" on a website but mostly very neutrally as "telephone" or "fax".

Thanks!

**Comment by craigafox** [comment]
It is my understanding that these are voice only (and internet).

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=%2B6752764280
