### ISSUE TITLE
/test/phonenumbers/phonenumberutil_test.cc some compilers need ULL values

### ISSUE THREAD

**Issue by arboz** [googlei18n/libphonenumber#1334]
googlei18n/libphonenumber/master/cpp/test/phonenumbers/phonenumberutil_test.cc

contains a few instances of numbers which should be set to ULL for some older compilers

In particular, I used Macports port libphonenumber-cpp on Mac OSX 10.5.8 darwin 9.8.0 386

apparently older gcc needs the LONG values to be marked explicitly ULL

I created a patch to demonstrate what was changed.
in order to complete compiling

[patch-src-phonenumberutil_test.cc.diff.txt](https://github.com/googlei18n/libphonenumber/files/471324/patch-src-phonenumberutil_test.cc.diff.txt)

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.1.
