### ISSUE TITLE
German number formatting is adding the country code even when the input included the country code

### ISSUE THREAD

**Issue by xcelling** [googlei18n/libphonenumber#1335]
Using https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Input Phone Number: 491510189151
Input Default Country: DE

Output:
****Parsing Result:****
{"country_code":49,"national_number":491510189151,"raw_input":"491510189151","country_code_source":20,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: DE
Result from getNumberType(): FIXED_LINE

****Formatting Results:**** 
E164 format: **+49491510189151**
Original format: 491 510189151
National format: 0491 510189151
International format: +49 491 510189151
Out-of-country format from US: 011 49 491 510189151
Out-of-country format from Switzerland: 00 49 491 510189151

****AsYouTypeFormatter Results****
Char entered: 4 Output: 4
Char entered: 9 Output: 49
Char entered: 1 Output: 491
Char entered: 5 Output: 4915
Char entered: 1 Output: 49151
Char entered: 0 Output: 491510
Char entered: 1 Output: 4915101
Char entered: 8 Output: 49151018
Char entered: 9 Output: 491510189
Char entered: 1 Output: 4915101891
Char entered: 5 Output: 49151018915
Char entered: 1 Output: 491510189151

**Comment by giggsey** [comment]
Have a look at https://github.com/googlei18n/libphonenumber/issues/1067#issuecomment-209477436.

**Comment by sokke90** [comment]
This is a similar problem that I encountered when submitting #1264 

The German numer formatting is not quite right, as when I type 312345 (which could be a landline number from landline phone) will be processed as +49 312345 which is wrong.

**Comment by lararennie** [comment]
Thanks @giggsey for finding the already existing bug with a good answer for this one :)
