### ISSUE TITLE
About the version tag

### ISSUE THREAD

**Issue by kennynaoh** [googlei18n/libphonenumber#1362]
Hello @lararennie ,
I am the same guy of [cdnjs](https://github.com/cdnjs/cdnjs) project.
https://github.com/googlei18n/libphonenumber/issues/1325

I think it's better to use `x.x.x` except `libphonenumber-x.x.x` as git tag.
It will be easy for us to add auto-update config  to automatically update new version when you publish new release.
So, could you change the new naming scheme for git tag in the future?
Thanks for your contribution.

https://github.com/cdnjs/cdnjs/issues/7805
https://github.com/cdnjs/cdnjs/pull/8944

**Comment by keghani** [comment]
I see [on stackoverflow](http://stackoverflow.com/questions/2006265/is-there-a-standard-naming-convention-for-git-tags) that one standard is to use vX.Y.Z, would this also work for you?

**Comment by kennynaoh** [comment]
Yes
So you will change the tag format in the future?

**Comment by keghani** [comment]
Yes @kennynaoh, this sounds like a reasonable change.
Given other requirements it may take a bit of time, just to manage expectations.

**Comment by kennynaoh** [comment]
@keghani 
Please let me know if you publish new version with new git tag `vX.Y.Z`
Thanks!

**Comment by keghani** [comment]
Will do :) We'll update this issue. Thanks for your patience!

**Comment by keghani** [comment]
Hi!

I can prioritize this in time for the next release.
Do I understand the scope correctly? Will I be fixing the issue completely if I make the next tag (and so forth) [here](https://github.com/googlei18n/libphonenumber/tags) look like `v7.7.4`?

**Comment by kennynaoh** [comment]
`v7.7.4` is great, thanks!

**Comment by keghani** [comment]
Fixed in 7.7.4.

**Comment by kennynaoh** [comment]
Thank you so much
