### ISSUE TITLE
Validate 589\d{5} in Mauritius (MU, +230)

### ISSUE THREAD

**Issue by bennyscetbun** [googlei18n/libphonenumber#1363]
Hi Thanks for your awesome lib.

We ve got problem with mauritius user reporting that their phone number are rejected in our application
http://libphonenumber.appspot.com/phonenumberparser?number=%2B23058956870

Could you help us on this ? (we arent from mauritius... so i dont know what the exact new format.. But i can tell you that this phone number is valid :) )

**Comment by penmetsaa** [comment]
@bennyscetbun 
Thank you for taking the time to improve libphonenumber!

We found official IR.21 doc that says 589 xxxxx mobile range belongs to Mahanagar Telephone. We've accepted this issue and will fix this as soon as possible.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.7.2: https://libphonenumber.appspot.com/phonenumberparser?number=%2B230+589+56870
