### ISSUE TITLE
Correct format for a Mexican phone number on a website

### ISSUE THREAD

**Issue by Wombel** [googlei18n/libphonenumber#1366]
Hi,

I have a question concerning the way I should put  Mexican phone numbers on my website. Is what libphonenumber gives me as national format: 	01 667 260 0290

Or is it what I see in some directories 	667 260 0290

It is especially important for us, as our users search for phone numbers on the web to get on our site, so formatting the number correctly is very importat. 

Can someone please help me?

**Comment by keghani** [comment]
Thanks for asking @Wombel!

Our library will parse both "[01 667 260 0290](http://libphonenumber.appspot.com/phonenumberparser?number=01+667+260+0290&country=MX)" and "[667 260 0290](http://libphonenumber.appspot.com/phonenumberparser?number=667+260+0290&country=MX)" as the same number in Mexico. Follow those links to see the demo, where both inputs have the same "Parsing Result" (except raw_input, which is expected).

What do you really need to know? Which format is more likely to be entered into a search engine? Which format are web crawlers more likely to recognize as phone numbers? These are all interesting but unfortunately outside the scope of the library and I don't know the answer to them.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
