### ISSUE TITLE
Validation issue with 684-622-7100 (AS)

### ISSUE THREAD

**Issue by bankamohit** [googlei18n/libphonenumber#1369]
The result given by libphone is 

PhoneNumberOfflineGeocoder Result sLocation American Samoa
PhoneNumberToTimeZonesMapper Results Time zone(s)   [America/Chicago]

**The time zone should have been Samoa Time Zone (UTC-11:00) but it is giving America/Chicago (UTC-06:00) as timezone. Is this issue fixed. How can I get the correct timezone.**

Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): 684-622-7100

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=684-622-7100&country=US)

**Comment by keghani** [comment]
The affected region is AS, not US.

Someone from the team should look at this shortly.

**Comment by keghani** [comment]
Sorry no one responded to this!

We update timezones semi-automatically and only once in a while, sorry for the delay.
We're mapping 1684 to Pacific/Pago_Pago and this should go out in the next release. Thanks for your patience!

**Comment by kkeshava** [comment]
Fixed in release 8.3.1.
