### ISSUE TITLE
Issue with CONTRIBUTING instructions

### ISSUE THREAD

**Issue by marado** [googlei18n/libphonenumber#1370]
Hi,

At https://github.com/googlei18n/libphonenumber/blame/master/CONTRIBUTING.md#L41 there are instructions on how to sign in into libphonenumber-supporting-docs. However, visiting that link, this message appears:
``` libphonenumber-supporting-docs
You must be a member of this group to view and participate in it. Membership is by invitation only.

This group is invite only, so you may not apply for membership.

However, you may contact the owner.
```

**Comment by keghani** [comment]
This is intended. The instructions don't say to sign in to the group to view the content, but to send emails to that email address. libphonenumber-supporting-docs is an internal mailing list visible only to team members, where reporters may share private information like their personal phone number as evidence that a range is valid. As mentioned in the contribution guidelines: "Only the core libphonenumber team has access to view emails sent to this mailbox."

The [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) is public.
