### ISSUE TITLE
Validation issue with 234-567-8901 x123 (US)

### ISSUE THREAD

**Issue by sphairo** [googlei18n/libphonenumber#1375]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): 234-567-8901 x123

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=234-567-8901+x123&country=US&geocodingLocale=en-US)

**Comment by keghani** [comment]
Thanks for filing this issue! It's not clear what we should fix though, can you please clarify?

- We say it's valid, is this wrong?
- Timezone?
- Location?
- Type? Currently this is FIXED_LINE_OR_MOBILE
- Something else?

**Comment by keghani** [comment]
@sphairo
This issue is blocked on your or other GitHub contributors' input. Please provide us with the requested information.. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
