### ISSUE TITLE
 can not receive the sms for verification account

### ISSUE THREAD

**Issue by Borana1** [googlei18n/libphonenumber#1379]
Dear Colleagues,

One of your colleague Crystal has informed me to submit directly to this page.
I work in a telco company in Albania. My Operator name is PLUS Communication Albania. We have received some complaints from our subscribers that can not receive the verification code for Gmail. The issue happen only for ported numbers in PLUS. For PLUS number, the sms is received.
Find below the numbers that we have tested this issue:
355698393552 - Vodafone Albania ported in PLUS
355688128659 - Telekom Albania ported in PLUS

We have two hubs if this information helps you : BICS and SAP.

**Comment by mizuni** [comment]
Thanks for getting in touch with us through our other colleague!

However, the problem doesn't seem to be with our repository as they're considered valid mobile numbers. For example, see this result: http://libphonenumber.appspot.com/phonenumberparser?number=355688128659&country=AL

However, if there are other numbers being marked invalid, please share any official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence)

And to check the latest
result for a given number, see our demo at https://libphonenumber.appspot.com.

**Comment by Borana1** [comment]
Dear Colleague,

The issue is not related if the numbers are valid or not. The problem consists for sms for verification code from Gmail. As I explained before, the sms is not received from ported number in PLUS. Please check the routing from Gmail toward ported number in PLUS.

**Comment by mizuni** [comment]
I'll close this as it's not an issue with the library, but I'll attempt to the find the right owner on the Gmail team and point them to these examples.

**Comment by Borana1** [comment]
Dear Mike,

Can you please inform me if you have escalate the issue #1379?

Br,
Borana

**Comment by mizuni** [comment]
Hi Borana,
I received an update today, and my colleague you talked with initially is going to reach out to you again privately since this is out of libphonenumber's scope. Thanks for your patience!
