### ISSUE TITLE
Validation issue for +50932477804406 (Haiti)

### ISSUE THREAD

**Issue by guillaumev** [googlei18n/libphonenumber#1383]
The phone number +50932477804406 does not validate, even though it's a valid phone number for Haiti.

**Comment by penmetsaa** [comment]
@guillaumev ,

Thank you for taking the time to improve libphonenumber!
We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
@guillaumev This issue is blocked on your or other GitHub contributors' input. Please help
us find the information that @penmetsaa requested. Otherwise we don't have enough information to
fix the issue and may have to close it as infeasible.

**Comment by penmetsaa** [comment]
@guillaumev 
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
