### ISSUE TITLE
Validation issue with satellite phone +882393257001527

### ISSUE THREAD

**Issue by popenoej** [googlei18n/libphonenumber#1384]
Country/region affected: GB in this case, but really world-wide for satellite international phones
Example number affected: +882393257001527

The phone number range to which the issue applies: ("882-39-XXXXXXXXXXX")

The type of number(s) : "Mobile" (international mobile satellite phone)

The cost, if applicable: "shared cost"

(Using 00 for exit code GB):
http://libphonenumber.appspot.com/phonenumberparser?number=00882393257001527&country=GB

Supporting evidence:
http://www.networkinv.com/how-to-dial-satellite-phone/
https://en.wikipedia.org/wiki/Satellite_phone

**Comment by penmetsaa** [comment]
@popenoej,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B882393257001527
