### ISSUE TITLE
Validation issue for +18765245411

### ISSUE THREAD

**Issue by palodelincak** [googlei18n/libphonenumber#1386]
Hello,

number +18765245411 is marked as not valid, but user says it's valid Jamaica number.

Country/region affected : Jamaica
Example number(s) affected : 18765245411
The phone number range(s) to which the issue applies : Unsure
The type of the number(s) : Mobile
The cost, if applicable: N/A
Supporting evidence - NPAnxxsource.com/nalennd.php

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by palodelincak** [comment]
@kkeshava Thanks for information. Do you know when you're going to make this release?

**Comment by kkeshava** [comment]
@palodelincak  We have a release tomorrow so will try to push this fix else you might have to wait for another 2 weeks. We'll update this thread when it's released.

**Comment by palodelincak** [comment]
Hello, any news about this issue? 2 weeks passed and it looks like it has not been released?

**Comment by lararennie** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=+%2B18765245411 -- seems it has been?

**Comment by lararennie** [comment]
Yep, seems this was fixed in release 7.7.3. Apologies for not letting you know.
