### ISSUE TITLE
Validating phone numbers for just one country

### ISSUE THREAD

**Issue by custa1200** [googlei18n/libphonenumber#1395]
Hi I am wanting to just validate Australian phone numbers, without the extra download heft of every other country. Is there an easy way to just include AU +61 validations?

**Comment by keghani** [comment]
This is not a feature we want to provide in our library, as many API functions would not work if only the Australian metadata were available.
For example, the library would say "false" for isValid(usNumber).

Clients are welcome to make changes in their own fork.

* Is this Java? Then you can leave out the non-+61 metadata in [java/libphonenumber/src/com/google/i18n/phonenumbers/data](https://github.com/googlei18n/libphonenumber/tree/master/java/libphonenumber/src/com/google/i18n/phonenumbers/data). Note that +61 is shared among AU (Australia), CC (Cocos Islands), and CX (Christmas Islands).
* It this C++ or JS? Then you can edit [PhoneNumberMetadata.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml) to filter out the other regions. It should be easy to automate updates of just the +61 metadata from this repository.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by custa1200** [comment]
This seems odd to me that if somebody is just wanting to validate Australian only phone numbers and mark all others as invalid that instead of downloading a couple hundred kb of javascript and just downloading ~10kb that would not be a feature you would not want to include/investigate. This would be the payload on the first screen of a signup form and would lessen the chance of customer abandonment due to slow loading. Cleave.js does a good job at somehow splitting up the countries for the client side formatting library based on this library https://nosir.github.io/cleave.js/

**Comment by keghani** [comment]
Thanks for the question @custa1200!

Requiring that users have a phone number in the region where a product operates is not consistent with user expectations. For example, while visiting Istanbul I wanted to make a reservation, but the website would only accept phone numbers from Turkey, and I only had a Swiss number. See number 21, "The country or area code of a phone number indicates the user's location, place of residence, time-zone, or preferred language", in [Falsehoods Programmers Believe About Phone Numbers](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md)

Therefore from an internationalization point of view, validating only +61 phone numbers is not behavior we would recommend in most products. Still, if it's important for you, you're welcome to fork the repository and have a custom build. It's trivial to do this, and we can't prioritize and support it from our end.

As for loading, this already happens per region; see [MultiFileMetadataSourceImpl.java](https://github.com/googlei18n/libphonenumber/blob/62714f59125c8f8bbbc3bc6ee15b239acec9923e/java/libphonenumber/src/com/google/i18n/phonenumbers/MultiFileMetadataSourceImpl.java#L100). If you're using the latest version you should have the latest loading improvements that we released over the summer.

I don't usually follow closed issues, and this isn't an issue; if you would like to follow up please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).
