### ISSUE TITLE
Validation issue for +9779846246155

### ISSUE THREAD

**Issue by pradipbasnet** [googlei18n/libphonenumber#1399]
It is a genuine phone number but doesn't validate

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the [demo] (http://libphonenumber.appspot.com/phonenumberparser?number=%2B9779846246155) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
