### ISSUE TITLE
Validation issue with 84664163 (CN)

### ISSUE THREAD

**Issue by coderji** [googlei18n/libphonenumber#1401]
Dear Sir:
com.google.i18n.phonenumbers.PhoneNumberUtil
PhoneNumber parse(“84664163”, “CN”) fail
PhoneNumber parse(“025 84664163”, “CN”) success

In China, when incoming call, the phone number always display such as '025 84664163', '0755 84664163', we parse success. But if we make a outgoing call, always no need area code like '025' '0755', only '84664163', then we parse fail.
So, can you help us change the rule file? 

Thank you!

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber!

The libphonenumber library does not validate numbers in local format, and that’s intended. It is not possible for us to canonicalize a number without the area code.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by coderji** [comment]
Dear Sir:
OK. Thank you.
