### ISSUE TITLE
New number prefix in Spain land lines

### ISSUE THREAD

**Issue by raycoarana** [googlei18n/libphonenumber#1403]
Landlines for Madrid and Guipúzcoa are going to accept a new prefix number (919 for Madrid and 8437 for Guipúzcoa), is pending to be approved but is going to happen shortly.

Country/region affected:  (e.g., "US"): **ES**
Example number(s) affected ("+1 555 555-1234"): **919 99 99 99** and **843 72 34 67**
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): **919XXXXXX** and **8437XXXXX**
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): **fixed-line**
The cost, if applicable ("toll-free", "premium rate", "shared cost"): **normal landline cost**
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://blog.cnmc.es/2016/10/25/nuevos-prefijos-para-madrid-y-guipuzcoa

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

As per CNMC site provided by you it states that *it will be soon possible to call Madrid marking the 919 prefix and Guipuzcoa in 8437 before the fixed number*, however there is no information on when this will be operational. 
Is it possible for you to find out/confirm when the decision will be known, so that we can implement these new ranges once they are approved?

**Comment by raycoarana** [comment]
Hi!

Not sure about that, some says that should be before the end of year. I will update the issue when we know something new.

Thanks!

**Comment by raycoarana** [comment]
Hi again, the government resolution is now out. Starting tomorrow, there could be phones with that new numbers ranges. So, it's time to support it :-).

http://www.boe.es/diario_boe/txt.php?id=BOE-A-2016-10756

**Comment by kkeshava** [comment]
@raycoarana,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.7.5:
https://libphonenumber.appspot.com/phonenumberparser?number=919+99+99+99&country=ES
