### ISSUE TITLE
Mauritius phone number not validating

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1406]
Mauritius phone number is returning as not valid but when I call it I am able to reach the business operating the phone number.

In this case, the business is a hotel called the Waterlovers Beach Resort. They use a Mauritius phone number to accept bookings over the phone. I called this number myself from a USA landline phone and was able to reach the business.

Would it be possible to add this number to the valid range within the libphone? Please let me know if you need anything else from me.

Country/region affected: MU - Mauritius
Example number: +23058442172
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line
The cost, if applicable ("toll-free", "premium rate", "shared cost"): normal landline cost
Hotel's website: http://www.waterlovers.it/lang-eng/contacts.php

**Comment by samuel-cloete** [comment]
I have the same issue with the following number:
Country/region affected: MU - Mauritius
Example number: +23058447181
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile  (as I've been told)

**Comment by lararennie** [comment]
Thanks for a second report!

Re the first report: are you sure it is fixed-line, not mobile? Or is this just an assumption? The website itself just lists it as a telephone.

**Comment by kkeshava** [comment]
Re the first report: According to our investigation this appears to be a mobile range. We'll support prefix 584 as mobile for now unless we hear back otherwise.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=%2B23058442172
