### ISSUE TITLE
Validation issue with +2347071928105 (NG)

### ISSUE THREAD

**Issue by LightSystem** [googlei18n/libphonenumber#1408]
This number was considered valid in previous version (tested with 7.0.2).

Country/region affected (e.g., "US"): NG

Example number(s) affected ("+1 555 555-1234"): +2347071928105

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://www.naijatechguide.com/2008/10/reltel-rebrands-to-zoom-mobile-launches.html

**IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B2347071928105&country=NG)

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We were able to connect to +2347071928105. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=%2B2347071928105
