### ISSUE TITLE
UAE cell phone +97158...

### ISSUE THREAD

**Issue by blanchonvincent** [googlei18n/libphonenumber#1412]
Hey

As written there https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates
The code "58" is not supported in United Arab Emirates section as phone number.

**Comment by lararennie** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.4
https://libphonenumber.appspot.com/phonenumberparser?number=058-2110000&country=AE
