### ISSUE TITLE
Validation issue with +992427822912 (Tajikistan, Dushanbe landline number)

### ISSUE THREAD

**Issue by EugenW7** [googlei18n/libphonenumber#1414]
This number was considered invalid, but this is a valid Tajikistan, Dushanbe landline number

Country/region affected (e.g., "US"): TJ

Example number(s) affected ("+1 555 555-1234"): +992427822912

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line

The cost, if applicable ("toll-free", "premium rate", "shared cost"):

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We were able to connect to +992427822912. We can't support single numbers, we need
context about the prefix that makes them valid.
 
Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
Sorry, the above request is incorrect. We are able to understand the granularity but we can't find official evidence. Could you please suggest the reason why you think this is a fixed-line range (and not mobile for example) by providing evidence.

See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information).
Please re-open if you respond so we pick up on it.
