### ISSUE TITLE
validation error for French mobile number +337XXXXXXXX

### ISSUE THREAD

**Issue by someoneinthe** [googlei18n/libphonenumber#1417]
Country/region affected : FR
Example number(s) affected : + 33 7XX XX XX XX
The phone number range(s) to which the issue applies : + 33 7XX XX XX XX
The type of the number(s): mobile
Phone number starting by 07 (national) , + 33 7 (international) are not valid mobile phone number.

According to http://www.arcep.fr/index.php?id=8146, number starting by "073" to "079" are mobile phone valid numbers.
Completes specifications are available here : http://www.arcep.fr/uploads/tx_gsavis/12-0855.pdf (page 17)

**Comment by lararennie** [comment]
Actually, please see #438 for discussion over arcep and what it is really saying. Do you have a particular phone number  that is diallable that we mark as invalid? The doc you reference is from 2012, no? If something has changed recently we're happy to update but we need real evidence that our conclusion from last time is wrong.
