### ISSUE TITLE
The demo site show carrier name as ??? when locale is fa

### ISSUE THREAD

**Issue by afarsi** [googlei18n/libphonenumber#1419]
Hi there.
I checked the demo site of libphonenumber with fa locale. It can show English names of carriers. But It can't show carrier name when locale is fa(Persian/Farsi). You can check [here](https://libphonenumber.appspot.com/phonenumberparser?number=05112345678&country=IR&geocodingLocale=fa) and [here](https://libphonenumber.appspot.com/phonenumberparser?number=05112345678&country=IR&geocodingLocale=en) and compare Location Field of them.

I think it's because encoding of html page which is not UTF-8! Please fix it.

**Comment by lararennie** [comment]
Yes, we know ;)  Thanks for the report; we'll try and fix this although our metadata updates have priority right now, so it might have to wait a short time.

**Comment by keghani** [comment]
This was fixed with https://github.com/googlei18n/libphonenumber/issues/1646
