### ISSUE TITLE
Google Hangouts Phone Numbers invalid

### ISSUE THREAD

**Issue by JulianSchneider** [googlei18n/libphonenumber#1423]
If you use the google hangouts caller, the caller id will be something like e.g.: +266696687 

This is marked as invalid by the lib (tested with the python implementation)

**Comment by penmetsaa** [comment]
@JulianSchneider,

It looks like the number you have mentioned +266 696 687 (6 digit) belongs to Lesotho but not a complete number. We are not able to connect to this number.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B266696687 

We support +266 6xxx xxxx (8 digit) mobile numbers in Lesotho.

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
@JulianSchneider ,
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
