### ISSUE TITLE
Barbados new prefix validation issues (+1 246-367)

### ISSUE THREAD

**Issue by agri0026** [googlei18n/libphonenumber#1424]
We are trying to validate some phone numbers originating from Barbados using the +1 246-367 extension and unfortunately the library is not recognizing the said numbers.

The link below is the official documentation provided by the ITU.
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000130002PDFE.pdf 

The link below is a proof of existence for the said number types
https://www.cibcfcib.com/fcib/about-us/locations/barbados.html

![image](https://cloud.githubusercontent.com/assets/5612762/20065783/a217870e-a50f-11e6-8ace-e177e399804f.png)

**Comment by kkeshava** [comment]
Hi,

Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 7.7.5:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+%28246%29+367+6700
