### ISSUE TITLE
validate 956\d{7} in Philippines (PH +63)

### ISSUE THREAD

**Issue by bennyscetbun** [googlei18n/libphonenumber#1431]
Hi Thanks for your awesome lib.

We ve got problem with Philippines user reporting that their phone number are rejected in our application
http://libphonenumber.appspot.com/phonenumberparser?number=%2B639561343365

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Philippines says that 956 seems valid and our user report us the right provider.

Thanks for the help :)

**Comment by penmetsaa** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by govindss** [comment]
Hello, We are running into this issue as well? Will this be fixed, anytime soon. Are you folks okay with it, if I submit a PR?

**Comment by penmetsaa** [comment]
Hi,
Sorry for not updating this bug. We have fixed this in release 7.7.5
https://libphonenumber.appspot.com/phonenumberparser?number=%2B63+956+1340000
Please upgrade to the latest release.

**Comment by ETrunhome** [comment]
Hi,
Thank you for keeping this up to date and great!
We have a problem in Colombia with the prefix 323 which is used by Claro, the largest mobile carrier.
We have seen this problem in many services and would be great if you could add it. 
(examples (in Spanish: 
https://www.facebook.com/help/community/question/?id=1173347736039631
https://productforums.google.com/forum/#!topic/gmail-es/6Qmz_gwhJiY )

I have submitted this information with the knowledge that you
may use, modify, reproduce, publicly display, and distribute the information in
accordance with your open source policies.

**Comment by bennyscetbun** [comment]
Hi @ETrunhome
First you should double check your issue on http://libphonenumber.appspot.com
if the problem is still there: you should open a new issue with your problem and  add a link using http://libphonenumber.appspot.com to show what number isnt working.

**Comment by penmetsaa** [comment]
@bennyscetbun ,
Thanks for responding on this.

@ETrunhome ,
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
@ETrunhome ,
As mentioned by bennyscetbun@, please raise separate issue with required details.

**Comment by esnani** [comment]
pla help me guys, my newly buyed 2nd hand iPhone 6 can't send messages with +63 numbers ao the tendency my measaging app will creat 2 inbox one for my sent messages and the aecond one the reply of my reciver. pls help or kung taga pinas ka tawagan mo ako 09959582696 tagal kog pinag ipunan po taa gnito pa :( pla help

**Comment by esnani** [comment]
pls help me guys, my newly buyed 2nd hand iPhone 6 can't send messages with +63 numbers so the tendency my measaging app will create 2 inbox, one for my sent messages and the second one is the reply of my reciver. pls help or kung taga pinas ka tawagan mo ako 09959582696 tagal kung pinag ipunan po taa gnito pa :( pls help

**Comment by penmetsaa** [comment]
@esnani,
The problem is not with our repository. May be you need to check with apple on this issue. Please check our [GitHub page](https://github.com/googlei18n/libphonenumber) to know about our library and its usage.
