### ISSUE TITLE
Add Armenia mobile number (+37444 xx xx xx)

### ISSUE THREAD

**Issue by jaimefrites** [googlei18n/libphonenumber#1449]
Armenian mobile operator Ucom started to sell numbers with prefix +374 44 since  9 november.

Some news sites have written about it

* [geek.am](http://geek.am/tech/5415__ucom-%D5%AB-%2B374-44-00-00-00-%D5%A2%D5%BB%D5%BB%D5%A1%D5%B5%D5%AB%D5%B6-%D5%B0%D5%A5%D5%BC%D5%A1%D5%AD%D5%B8%D5%BD%D5%A1%D5%B0%D5%A1%D5%B4%D5%A1%D6%80%D5%A8-%D5%BE%D5%A1%D5%B3%D5%A1%D5%BC%D5%BE%D5%A5%D5%AC-%D5%A7-%D5%BC%D5%A5%D5%AF%D5%B8%D6%80%D5%A4%D5%A1%D5%B5%D5%AB%D5%B6-15-%D5%B4%D5%AC%D5%B6-%D5%A4%D6%80%D5%A1%D5%B4%D5%B8%D5%BE__1011160005415.html)

* [newsarmenia.am](http://newsarmenia.am/news/armenia/armyanskiy-sotovyy-operator-prodal-nomer-telefona-po-tsene-dzhipa-/)

Also new numbers are specified in [Wikipedia article about Ucom](https://ru.wikipedia.org/wiki/Orange_Armenia).

**Comment by kkeshava** [comment]
Hi,

Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 7.7.5.
