### ISSUE TITLE
Validation issue with 7895468XX (ES)

### ISSUE THREAD

**Issue by Pitus660** [googlei18n/libphonenumber#1450]
The problem is with numbers starting with 7

I hid the last two digits for privacy, but with numbers from 1 to 9

Country/region affected (e.g., "US"): ES

Example number(s) affected ("+1 555 555-1234"): 7895468XX

**Comment by penmetsaa** [comment]
@Pitus660 
Thank you for taking the time to improve libphonenumber! We were able to find the numbers online,  but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.

We also need to know the type of the number. Ex: Mobile, Landline,... Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
@Pitus660 ,
As per online search results and [Wikipedia] (https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain), 78 is mobile number range. So we fixed it in release 8.0.0. 
Please see the [demo] (http://libphonenumber.appspot.com/phonenumberparser?number=789541234&country=ES) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md))
