### ISSUE TITLE
Validation Issue with 1522XXXX (KR)

### ISSUE THREAD

**Issue by yatopark** [googlei18n/libphonenumber#1452]
The problem is that 1522XXXX number parsed unknown type number.
This number pattern is valid in Republic of Korea.

Country/region : kr
isValidNumber : false
getNumberType() : UNKNOWN

**Comment by penmetsaa** [comment]
@yatopark ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.0.0.
