### ISSUE TITLE
Validation issue with 051xxxxxxx, 053xxxxxxx, 057xxxxxxx and 059xxxxxxx (AE)

### ISSUE THREAD

**Issue by ssajjad** [googlei18n/libphonenumber#1454]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): AE

Example number(s) affected ("+1 555 555-1234"): 051xxxxxxx, 053xxxxxxx, 057xxxxxxx, 059xxxxxxx

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!**

**Comment by penmetsaa** [comment]
Thank you for taking the time to improve libphonenumber!

The ranges 51, 53 , 57 and 59 are not mentioned in any of the official documents.
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000DC0001PDFE.pdf
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates

Are these new mobile ranges? We are not able to find any valid numbers online which are under these ranges.

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ssajjad** [comment]
Dear @penmetsaa, I asked the person to provide the evidence for this. As soon as I received it I will share with you. But there is one more issue when I am using your web demo for 058xxxxxxx it is working fine. But my code in Android is not working for this number. Please check the code below.

public static boolean isValidUAENumber(String number) {
        return isValidNumber(number, "AE");
    }

    public static boolean isValidNumber(String number, String countryCode) {
        PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
        try {
            Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse(number,
                    countryCode.toUpperCase(Locale.US));
            if (phoneNumber != null) {
                return phoneUtil.isValidNumber(phoneNumber);
            }
        } catch (NumberParseException e) {
            Crashlytics.logException(e);
        }
        return false;
    }

**Comment by ssajjad** [comment]
After updating libphonenumber version the above issue resolved. I will create another issue once I got the proof of other codes.
