### ISSUE TITLE
Mobile Number not supported for a new provider - (Reliance Jio, India)

### ISSUE THREAD

**Issue by dhruvbalhara** [googlei18n/libphonenumber#1465]
This mobile number was activated on 29 November, 2016

Steps to reproduce

Specify Reliance Jio mobile number in Phone Number : 8319486897 
Specify a Default Country : IN

Expected behaviour

Validation Results:
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: IN
Result from getNumberType(): MOBILE

Actual behaviour

Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: IN
Result from getNumberType(): UNKNOWN

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We were able to connect to 8319486897 so we will support this number as mobile.
However we were not able to find carrier details for this range. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well. 

Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by ashish1405** [comment]
As per Department of Telecom of India below are the links to support evidence 

[83200-83209](http://www.dot.gov.in/sites/default/files/RJIL%208112016.pdf?download=1)

[83180-83189,83190-13199](http://www.dot.gov.in/sites/default/files/DoT%20to%20RJIL%20Allocation%20of%20MSC%20code%20to%20RJIL%20-UP%28East%29%20and%20MP%20LSA%2004.1....pdf?download=1)

[83600-83609](http://www.dot.gov.in/sites/default/files/MSC%20Code%20PB%2C%20RJ%2C%20KTK%2C%20TN%20%281%29.pdf?download=1)

**Comment by kkeshava** [comment]
@ashish1405,

Thanks for providing the details. We are able to access the first link for the 83200-83209 range and the last link for the 83600-83609 range but are unable to access the second link provided by you. Could you please recheck and send us the correct link? Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

We have accepted the 83200-83209 & 83600-83609 ranges for now and will fix these in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by ashish1405** [comment]
@kkeshava 

that is strange, If I click the link it showing me the pdf. Posting the link again

http://www.dot.gov.in/sites/default/files/DoT%20to%20RJIL%20Allocation%20of%20MSC%20code%20to%20RJIL%20-UP%28East%29%20and%20MP%20LSA%2004.1....pdf?download=1


or 
go to
http://www.dot.gov.in/accessservices/msc-codes-mp-e-rjil
and click download

**Comment by kkeshava** [comment]
@ashish1405 

Thanks for providing the link. We are able to access now, may be there was some proxy issue earlier :). So we will be supporting all the above ranges mentioned.

**Comment by dhruvbalhara** [comment]
@ashish1405  , @kkeshava  - Thank you for the prompt response.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
