### ISSUE TITLE
Validation issue with 0858965471 (ZA)

### ISSUE THREAD

**Issue by FrikkieRetro** [googlei18n/libphonenumber#1469]
Country/region affected (e.g., "US"): ZA

Example number(s) affected ("+1 555 555-1234"): 0858965471

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): All numbers starting with 085 (+2785)

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

https://en.wikipedia.org/wiki/Telephone_numbers_in_South_Africa

Network providers, Vodacom and MTN can give out numbers starting with 085- (+2785) and should therefor be marked as valid.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0858965471&country=ZA)

**Comment by penmetsaa** [comment]
Thank you for taking the time to improve libphonenumber!

We found evidence that 85 range is valid mobile range. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by FrikkieRetro** [comment]
@penmetsaa Thanks for the feedback, any update on when this will be deployed?

**Comment by penmetsaa** [comment]
@FrikkieRetro 
We have a release planned in for next couple of days. This fix will be part of it. We will update this bug once it is done.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
