### ISSUE TITLE
Add geocoding for LY

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#147]
Imported from [Google Code issue #147](https://code.google.com/p/libphonenumber/issues/detail?id=147) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2012-06-16T02:30:30.000Z:

---

Data does not exist.
Available at http://www.itu.int/oth/T020200007A/en

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by keghani** [comment]
Fixed in v8.3.0
