### ISSUE TITLE
Validation issue with +234906180XXXX (NG)

### ISSUE THREAD

**Issue by twisstosin** [googlei18n/libphonenumber#1471]
Country/region affected : NG

Example number: +2349061804869

The phone number range to which the issue applies ("+234 90 6XXX-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B2349061804869&country=NG)

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
