### ISSUE TITLE
Validation issue with 2335578589XX (GH)

### ISSUE THREAD

**Issue by tonymobster** [googlei18n/libphonenumber#1475]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): GH

Example number(s) affected ("+1 555 555-1234"): +2335578589XX

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +23355XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): (https://en.wikipedia.org/wiki/Telephone_numbers_in_Ghana) 
MTN Ghana recently added 055 to their existing 054

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=2335578589XX&country=GH)

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We already support ranges 55[3-6] as Mobile, but we can't find official evidence for prefix 557 or any other ranges in it (i.e 550, 551, 552, 558 and 559). 
We cannot consider wiki as the official evidence. Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that +2335578589XX is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by tonymobster** [comment]
Hi, sorry for the late reply. Unfortunately there are no official evidence put out by either MTN Ghana or the NCA here. This code seems to be relatively new so I haven't found any business using it yet. I'll visit an MTN shop and ask for a new SIM with the number in that range and take a snapshot of the SIM starter pack with the number printed on it. I don't know if that would be good enough.

**Comment by kkeshava** [comment]
@tonymobster,

Thanks a lot for your effort in finding the evidence for us :). Yes, we do accept the snapshot of the SIM pack as an evidence for supporting the number. Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
We found evidence that 557 is valid: http://coastlineghana.com/contact

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 8.1.0
https://libphonenumber.appspot.com/phonenumberparser?number=%2B233+557+232+397
