### ISSUE TITLE
Validation/Formatting issue with 6328027000 (Phillipines)

### ISSUE THREAD

**Issue by amarveersingh** [googlei18n/libphonenumber#1477]
Thank you for the lovely library

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Checking Javascript
6328027000 - Country Code PH - e164 returned as Invalid.
6324152272 - Country Code PH - e164 returned as Invalid

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

Could you please confirm if 63 is area code or country code in your input 6328027000 / 6324152272?  
The country code for Phillipines is 63 and it is also one of the area codes in fixed line numbers. If the length of the digits are as per E. 164 standard we go ahead and parse the number but if it is not then the number is considered invalid.
 
So if you meant 63 as country code then please add ‘+’ or ‘00’ in front of the number. 

See how the library treats when +6328027000 is given as input:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B6328027000

**Comment by amarveersingh** [comment]
The numbers are stored in customer database and we want to dial them out, so we use the API to give us an E164 format back, but in this case it fails and returns invalid.  So we want to API to determine that if we pass 6328027000 should it return back +6328027000 or +636328027000. This is what we are trying to achieve.

By the way, the same problem with Italy, Itlay has a country code of 39 and an area Monza which has area code as 39.

**Comment by kkeshava** [comment]
@amarveersingh ,
In cases like these the library can not take any decision whether the prefix is country code or not. It has to be clear in the input format itself i.e either in E.164 format (+63 28027000) or national format.

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
