### ISSUE TITLE
Add geocoding for ML

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#148]
Imported from [Google Code issue #148](https://code.google.com/p/libphonenumber/issues/detail?id=148) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2012-06-16T02:33:59.000Z:

----
Data does not exist.
Numbering Plan as of 19.V.2010 contains it.
http://www.itu.int/oth/T0202000083/en

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by penmetsaa** [comment]
Fixed in release 7.3.2:  https://libphonenumber.appspot.com/phonenumberparser?number=%2B22320200000
