### ISSUE TITLE
Validation issue with +22579XXXXXX (CI)

### ISSUE THREAD

**Issue by samskeller** [googlei18n/libphonenumber#1487]
Country/region affected : CI

Example number: +22579559511

The phone number range to which the issue applies: 22579XXXXXX

The type of the numbers: mobile

Supporting evidence: +22579559511 is an Orange phone number currently in use and is able to connect

[link to demo](https://libphonenumber.appspot.com/phonenumberparser?number=22579559511&country=CI)

Thanks!

**Comment by kkeshava** [comment]
Hi,

Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by samskeller** [comment]
Great, thanks, @kkeshava! Do you have an estimate for which release the fix will go into and when that release is expected to go out?

**Comment by kkeshava** [comment]
@samskeller,
We are planning to have a release this week. We will be updating the bug once it is fixed.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
