### ISSUE TITLE
Validation issue with +77087702446 (KZ)

### ISSUE THREAD

**Issue by p-hells** [googlei18n/libphonenumber#1488]

**Comment by penmetsaa** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
Ex: https://libphonenumber.appspot.com/phonenumberparser?number=%2B77087702446
