### ISSUE TITLE
Add geocoding for NE

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#149]
Imported from [Google Code issue #149](https://code.google.com/p/libphonenumber/issues/detail?id=149) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2012-06-16T03:02:51.000Z:

---

http://www.itu.int/oth/T020200009B/en
Has fixed line rules with geolocation data.
Data file does not exist.

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by keghani** [comment]
Fixed in v8.0.0.
