### ISSUE TITLE
Validation issue with +117755555555 (+11 interpreted as +1)

### ISSUE THREAD

**Issue by yodasan** [googlei18n/libphonenumber#1492]
Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): +117755555555

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +11 XXX XXX-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): ALL

The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): 

The country code "+11" is invalid, but instead of coming back as invalid, it seems like the library is interpreting "+11" as "+1". 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B117755555555)

**Comment by penmetsaa** [comment]
@yodasan ,
Thank you for taking the time to improve libphonenumber!
When the input is in E.164 format i.e "+ <country+code> <National Significant number>", library tries to match the digits after "+" against valid country codes.  This is the reason why "1" is considered as country code, not "11" or "117"..  The digits after valid country code is considered as phone number. Ex: 17755555555 in this case.

This is how all telephone routing / exchange system works.

**Comment by yodasan** [comment]
So, what you're saying is that telephone routing / exchange systems do a digit by digit check to find the valid country code, so the first valid country code that is found in the lookup is "+1". I can understand why the library chooses "+1" as a valid country code. If that is the case, I would expect the parsing result from the demo link I posted to parse the country_code as "1" and national_number as "17755555555" (as you mentioned should be in this case). Instead, the parsed national_number is "7755555555" without the extra "1". As an alternative example, using the number "+127755555555" instead of "+117755555555" does in fact result in an error out with a "TOO_LONG" error (http://libphonenumber.appspot.com/phonenumberparser?number=%2B127755555555). This is the error I would expect a provided "+11" to return, as well. I'm trying to understand why the extra "1" is thrown out from the parsing result and seen as a valid number instead of a "TOO_LONG" error being returned.

**Comment by penmetsaa** [comment]
@yodasan,
Thanks so much for noting all the details. These are very good questions. :)
1. Why national_number is 17755555555 instead of 7755555555 in case of + 117755555555 ?
In US "1" is used as country code and also as national prefix. So the "1" in 17755555555 is considered as national prefix (Prefix which is used for long distance calls).  This is why the extra "1" is removed from the parsing result.
2. Why +127755555555 is considered as "TOO_LONG"?
In this case national_number is 27755555555. All mobile and landline numbers in US are of length 10 digits and this number is of length 11 digits.

**Comment by keghani** [comment]
There doesn't seem to be an issue here, closing.
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further, and for future discussions.
