### ISSUE TITLE
Validation of PG numbers for nubmbers for "Morobe" region +675 47X XXXX fail

### ISSUE THREAD

**Issue by craigafox** [googlei18n/libphonenumber#1498]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): PG

Example number(s) affected ("+1 555 555-1234"): +675 472 1033
+675 474 3299
+675 472 2745
+675 475 9988
+675 472 2340
+675 474 5211

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +67 547 XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): FIXED-LINE

The cost, if applicable ("toll-free", "premium rate", "shared cost"):

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
ITU: http://www.itu.int/oth/T02020000A4/en
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000A40003PDFE.pdf
See page 5 Enga
Please see the directory of PNG top 100 companies: http://www.businessadvantagepng.com/papua-new-guinea-top-100-companies/
There are 6 companies with phone numbers in this range

**Comment by penmetsaa** [comment]
@craigafox ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

ITU mentions about the range "547 XXXX" and not "47 XXXX". I think you have mixed it up with country code "675". We have found below official document that states 47X XXXX PSTN numbers are assigned to "Morobe" region.
http://nicta.gov.pg/component/simplefilemanager/?task=download&id=233 (Page 21)

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.
