### ISSUE TITLE
countries with same code

### ISSUE THREAD

**Issue by AliNaranjeeSani** [googlei18n/libphonenumber#1501]
Hi
phone number is : +1 684 123 456 75

how to know it's for USA or American Samoa or Canada ,?
+1 is for all of them .

Thanks!

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber!

US, Canada, American Samoa and few other countries come under NANPA (North American Numbering Plan Administration) and they all share same country code i.e ‘+1’. All phone numbers in NANPA countries (except US and Canada) are differentiated based on the leading digits: e.g. ‘+1 684 123 456 7’ - leading digits 684 belongs to American Samoa and ‘+1 876’ - leading digits 876 belongs to Jamaica.
Phone numbers in US and Canada do not have the same ranges with each other: e.g. +1 2032000000 belongs to US and +1 2042000000 belongs to Canada. You can verify the country in ‘Phone Number region’ column from [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+684+123+456+7) link.

**Comment by keghani** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by lararennie** [comment]
(And the answer is use getRegionCodeForNumber after parsing the number)
