### ISSUE TITLE
Validation Issue with 831041876540 (SA)

### ISSUE THREAD

**Issue by akfernun** [googlei18n/libphonenumber#1503]
Country/region affected: "SA"
Example number(s) affected:
- 831041876540
- 831043189394

The type of the number: "Personal Number"

### Supporting Evidence:

By clicking on the link below, and navigating to page 3, you will be able to see that (831) is a valid non-geographic national destination code for Saudi Arabia. 

http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000B70002PDFE.pdf

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber!

We can't connect to 831041876540 and 831043189394. As per the ITU doc 831 is assigned to ‘Non Geographic Numbers Public Mobile Data’ but you mentioned that it is ‘Personal Number’, could you please clarify if it’s mobile or personal number or non-geographic number used for only data purpose? 
It seems like this range is used for mobile data. We do not support numbers which are assigned to data transmission or network routing, we only support numbers to those we can connect or send SMS.

**Comment by akfernun** [comment]
Thank you for getting back to me. I can confirm that this is a non-geographic area code. Thank you.

**Comment by kkeshava** [comment]
Hi,
As mentioned in comment#2, we do not support numbers which are assigned to *data* transmission. We only support numbers to which we can dial/connect or send an SMS.

We are unable to connect to both the numbers provided by you. Would you be able to send any other working numbers and also evidence for those numbers? 

Could you please explain what do you mean by *non-geographic area code*? We want to know the category of the number (i.e mobile or personal number etc) and evidence for it as the ITU doc does not mention it clearly.

**Comment by kkeshava** [comment]
Hi,
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open the issue if you find any additional evidence.
