### ISSUE TITLE
Add geocoding for GQ

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#151]
Imported from [Google Code issue #151](https://code.google.com/p/libphonenumber/issues/detail?id=151) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2012-06-16T03:26:26.000Z:

---

Doesnt Exist.
Available At http://www.itu.int/oth/T0202000041/en

Although it's a bit more complicated, in that the fixed line network is in the format  3xx y z ssss; where y is the Region Identifier
So, it would be wagered that a full listing of 
24033309|Bioko
24033319|Bioko
24033329|Bioko
24033308|Litoral
24033318|Litoral
24033328|Litoral
... etc, since only that final digit is significant in the location lookup....

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by keghani** [comment]
Fixed in v8.0.0.
