### ISSUE TITLE
Update docs to specify that getNumberType only returns an answer IFF the number is valid

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlei18n/libphonenumber#1512]
So that calling this function to check if a given string is of a mobile phone - won't need to also call "isValidNumber" :

```
public static boolean isValidMobileNumber(String phone) {
    if (TextUtils.isEmpty(phone))
        return false;
    final PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
    try {
        PhoneNumber phoneNumber = phoneNumberUtil.parse(phone, Locale.getDefault().getCountry());
        PhoneNumberUtil.PhoneNumberType phoneNumberType = phoneNumberUtil.getNumberType(phoneNumber);
        return phoneNumberType == PhoneNumberUtil.PhoneNumberType.MOBILE;
    } catch (final Exception e) {
    }
    return false;
}
```

?

**Comment by lararennie** [comment]
Yep, you're right: if you ask for the type, and you get MOBILE, it is also
valid.

2017-01-18 9:47 GMT+01:00 AndroidDeveloperLB <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
So no need to call isValidNumber , right?
Can you please update the docs about it?

**Comment by lararennie** [comment]
Correct, no need.

Which docs would you like us to update in particular? Where did you look
for an answer?

2017-01-18 9:59 GMT+01:00 AndroidDeveloperLB <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
For "getNumberType" ...

**Comment by lararennie** [comment]
Feasible: in e.g. the US we can't tell, so we return FIXED_LINE_OR_MOBILE.

**Comment by lararennie** [comment]
Changed this to an issue so we can track it.

In future, for questions please join the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) and send an email there.

**Comment by AndroidDeveloperLB** [comment]
Can you also update the docs to have a note about the US issue (or in general) ?
Does it occur only for US phones?

**Comment by lararennie** [comment]
US, CA, some other countries, yes. There is a comment on the enum itself about this.

**Comment by AndroidDeveloperLB** [comment]
So this is why you wrote "whenever feasible" ? Because sometimes it's not possible to know?

**Comment by lararennie** [comment]
Yes, because sometimes we don't know if it's mobile or fixed-line, so we can't return MOBILE, so we return FIXED_LINE_OR_MOBILE.

**Comment by AndroidDeveloperLB** [comment]
I see. That's too bad. Is there any way to overcome this?

**Comment by lararennie** [comment]
Not using libphonenumber but you could try a pay-per-use option like
Pathfinder

18. jan. 2017 4.27 p.m. skrev "AndroidDeveloperLB" <notifications@github.com

**Comment by AndroidDeveloperLB** [comment]
Any option by Google? After all, Google has tons of information....

**Comment by lararennie** [comment]
Nope.

2017-01-19 9:09 GMT+01:00 AndroidDeveloperLB <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
Too bad. Can you show the website of "PathFinder", please?

**Comment by keghani** [comment]
Hi @AndroidDeveloperLB, I did a Google search for "pathfinder phone numbers" and this was the second result: https://www.neustar.biz/communications/address-and-routing/pathfinder. Hope it's helpful!

I'd like to focus this issue on updating the javadoc, so if there are other non-issue questions please post them on the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

**Comment by AndroidDeveloperLB** [comment]
@keghani  OK thank you. Wonder what their prices are. I was told that it's very expensive. 
Anyway, thanks.

**Comment by keghani** [comment]
Re-opening to track the javadoc.

**Comment by penmetsaa** [comment]
The javadoc is updated as part of release 8.7.0.
Hence closing this as fixed.
