### ISSUE TITLE
Validation issue with 918368463039 (IN)

### ISSUE THREAD

**Issue by chaitanm** [googlei18n/libphonenumber#1516]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 918368463039

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=918368463039&country=IN)

**Comment by keghani** [comment]
Thank you for taking the time to improve libphonenumber!

We need evidence to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Also, who is the carrier?

**Comment by keghani** [comment]
Hi @chaitanm 

I found evidence that Idea was recently assigned the ranges 83670 and 83672-83677, so I'll validate those in the next release of the library.

I can't find anything about mobile numbers beginning with 83684, so I can't validate the number you shared. Is that an actual number in use?

**Comment by kkeshava** [comment]
Hi,
We were able to connect to  8368463039 now and also verified that this belongs to Reliance Jio in India as per www.jio.com. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
We have added support for 83670 and 83672-83677 mobile range in release 8.1.0
https://libphonenumber.appspot.com/phonenumberparser?number=%2B91+8367420000.

We will add support for 83684 mobile range in an upcoming release.

**Comment by SumathiSundara** [comment]
Fixed in release 8.2.0
