### ISSUE TITLE
Update 711 carrier in Afghanistan to AWCC (AF, +93)

### ISSUE THREAD

**Issue by uppaljs** [googlei18n/libphonenumber#1518]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): "AF"

Example number(s) affected ("+1 555 555-1234"): "+93711805114"

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): "+93711XXXXXX"

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  "mobile"

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
National Numbering Plan:
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000010002PDFE.pdf

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=93711805114&country=AF)

**Comment by kkeshava** [comment]
@uppaljs,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=93711805114&country=AF) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by uppaljs** [comment]
Hi,

The problem is with the Carrier , The Carrier is AWCC as per the numbering plan attached- but in the demo its showing up as empty.

**Comment by kkeshava** [comment]
@uppaljs, 
Thanks for pointing it out :). We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 8.1.0
https://libphonenumber.appspot.com/phonenumberparser?number=%2B93711805114
