### ISSUE TITLE
Validation issue with "Reliance JIO" mobile numbers in IN

### ISSUE THREAD

**Issue by rahularora1993** [googlei18n/libphonenumber#1520]
Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 
1. 8369568224
2. 8248095746
3. 8368136624
4. 8310242788

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):  
This issue seems to be applying for the new area codes that have been introduced recently. Customers are able to successfully create accounts with old area codes ( for example : 8074803846, 7715041133 etc)

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=8369568224&country=IN)

**Comment by kkeshava** [comment]
@rahularora1993,
We are able to conclude that all the above are mobile numbers and is assigned to Reliance Jio in India as per www.jio.com. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by srirambandaru** [comment]
@kkeshava Would you be able to provide a timeline on when the fix will be available for public?

**Comment by lararennie** [comment]
Validation issues are our highest priority, so this should be in the next release. We aim to release ~ every two weeks.

**Comment by RMK19** [comment]
@lararennie Also include phone numbers that start with 87788 range. Which is also a Reliance JIO number.

**Comment by kkeshava** [comment]
@rahularora1993,

Thanks for reporting!
Would you be able to provide any working numbers or official evidence for 87788 range? Also 
please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well.

**Comment by RMK19** [comment]
@kkeshava 
Example number: +91 8778892860 
Country/region affected (e.g., "US"): IN

**Comment by penmetsaa** [comment]
@RMK19 ,
We accept the issue. For new issues like this please create new GitHub issue instead of reopening old closed issues. This helps us in tracking the issues better. Created #1544 for supporting 87788 range.
