### ISSUE TITLE
Croatian shortcode 13977 for the provider Bonbon isn't accounted for in the regexp

### ISSUE THREAD

**Issue by kpuljek** [googlei18n/libphonenumber#1538]
Country/region affected: Croatia
Example number(s) affected: 13977
The type of the number(s): short code
The cost, if applicable: toll-free

My provider uses 13977 for checking account and balance information so I can't send an SMS through Signal which uses libphonenumber. It doesn't get recognized as a shortcode and gets the +385 prefix for 
Croatia which obviously doesn't work.

I've been sent here from my original report: 
https://github.com/WhisperSystems/Signal-Android/issues/6077

Let me know if I can provide any additional information.

**Comment by penmetsaa** [comment]
@kpuljek,
Thanks for providing the details! We have found below carrier page mentioning about this short code. We've accepted this issue and will fix this in an upcoming release.
 http://www.bonbon.hr/ponuda/pretplata/paketi/

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.2.0
