### ISSUE TITLE
Valid numbers from Togo are failing isValidNumber validation

### ISSUE THREAD

**Issue by anyanany1** [googlei18n/libphonenumber#1540]
Hello,

Thanks for the great lib. 

I have a sim card I bought from Moov (network operator) in Togo.
The sim's number is: +22897155196. 
Calling isValidNumber() returns false on the above number. Also, I can't sign up for a google account.

![image](https://cloud.githubusercontent.com/assets/15209518/22418265/f4fa1c30-e6e0-11e6-93b8-afe4e3c6f32a.png)

I know you need a document, I found this one (hope it's good enough):
http://ftp.premiumtlc.com/downloads/CL_AS_OF_JAN_10_2017_0001.xls

It is on line #1985. (Maybe you can add the other prefixes for Moov operator too).

Thank you.

## UPDATE

All Togo numbers starting with +22897 & +22896, fail validation. 
You can find the numbers in the above file in line numbers:  1978 - 2012.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
