### ISSUE TITLE
New mobile number prefix for TJ

### ISSUE THREAD

**Issue by jbenua** [googlei18n/libphonenumber#1541]
Country/region affected: TJ
Example number(s) affected: 99277700XXXX (mobile)
The phone number range(s) to which the issue applies: 99277\d+
The type of the number(s): mobile
Supporting evidence: I've got the letter from TCell representative Shahnoza Okhunjonova (Shahnoza.Okhunjonova@tcell.tj) reporting about incorrect number type detection by the library

**Comment by penmetsaa** [comment]
@jbenua 
Thank you so much for taking the time to improve libphonenumber!

We were able to connect to +992 77 7000072, but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.

We mailed Shahnoza.Okhunjonova@tcell.tj to provide us IR.21 document of Tcell which mentions this range. Please check our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence) for more details.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.

**Comment by jbenua** [comment]
Thanks!
