### ISSUE TITLE
Fails to find numbers with missing "0" prefix

### ISSUE THREAD

**Issue by n1mda** [googlei18n/libphonenumber#1545]
If I have a Swedish mobile phone number like "0701234567" but it has been entered "incorrectly", with the missing 0 prefix: "701234567".

```java
final PhoneNumber number = phoneUtil.parse(rawValue, countryCode);
```

Finds a result 👍 

But:
```java
Iterable<PhoneNumberMatch> phoneNumberMatches = phoneUtil.findNumbers("701234567", "SE");
```

Fails to find any result.

**Comment by lararennie** [comment]
This is WAI. findNumbers doesn't want to find too many false positives, and Swedish numbers online are typically entered with a country code or a national prefix. For countries where they are commonly written without, we have a flag so we can find them regardless: but to our knowledge, adding such a flag for Sweden would result in very little additional recall, and a loss of precision.

findNumbers is supposed to be called on a larger piece of text. If you think you've got a phone number, use parse.

**Comment by n1mda** [comment]
We are using `findNumbers` on a larger piece of text that contains phone numbers written without the "0" prefix.

```Hi, my name is xx and you can call me on 701234567 or 701234568```

**Comment by n1mda** [comment]
Using
`phoneUtil.findNumbers("Hi, my name is xx and you can call me on 701234567 or 701234568", "SE", PhoneNumberUtil.Leniency.POSSIBLE, Long.MAX_VALUE);`

seems to have the effect I want.

**Comment by lararennie** [comment]
Yep, if you want to reduce precision but increase recall, you can change the leniency level e.g. to POSSIBLE.
