### ISSUE TITLE
Validate 323 prefix in Colombia (CO +57)

### ISSUE THREAD

**Issue by ETrunhome** [googlei18n/libphonenumber#1549]
HI Again,
Thank you for keeping this up to date and great!
We have a problem in Colombia validating numbers with the prefix 323 which is used by Claro, the largest mobile carrier.
http://libphonenumber.appspot.com/phonenumberparser?number=3233670090&country=CO
References:
https://www.facebook.com/help/community/question/?id=1173347736039631
https://productforums.google.com/forum/#!topic/gmail-es/6Qmz_gwhJiY )

I have submitted this information with the knowledge that you
may use, modify, reproduce, publicly display, and distribute the information in
accordance with your open source policies.

**Comment by penmetsaa** [comment]
@ETrunhome ,
Thanks for reporting this issue.
libphonenumber library already considers number (+57 323 3670090) as valid mobile number. Please upgrade to the latest release if this is not the case in your product. http://libphonenumber.appspot.com/phonenumberparser?number=3233670090&country=CO

Regarding carrier name:
Yes we are not returning carrier name for mobile prefix 323. We will update it as Claro. We've accepted this issue and will fix this in an upcoming release.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
