### ISSUE TITLE
Pattern 06 47 XX XX XX for the Réunion island (RE) should not be recognized as valid

### ISSUE THREAD

**Issue by jblezoray** [googlei18n/libphonenumber#1552]
**What steps will reproduce the problem?**
Format a phone number like 06 47 XX XX XX for the Réunion island (RE)

**What is the expected output? What do you see instead?**
Expected : This phone number should not be recognized as valid.
But was : valid. (E164 format +262647000000)

**What version of the product are you using? On what operating system?**
Libphonenumber demo :
[https://libphonenumber.appspot.com/phonenumberparser?number=0647000000&country=RE]

**Please provide any additional information below.**
See this authoritative document from the ARCEP
http://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf
On page 23 (labeled 7), there is a table that Réunion island has only 692 and 693. Moreover, 647 is never mentionned.

I traced the introduction of this information. It dates back from the initial commit in feb 2010 :
`^a7c6c36 (Shaopeng Jia 2010-02-10 17:54:46 +0000 4048) <nationalNumberPattern>6(?:9[23]|47)\d{6}</nationalNumberPattern>`

**Comment by kkeshava** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
