### ISSUE TITLE
India reliance JIO number not supporting

### ISSUE THREAD

**Issue by AshishAccedo** [googlei18n/libphonenumber#1553]
This is the new number of Reliance JIO India number
8218822313
Please add this.

**Comment by penmetsaa** [comment]
@min2dev 
Thanks for providing the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by gauravverma-accedo** [comment]
used the same number with https://libphonenumber.appspot.com/ and its working. Thus what update we can expect ?

**Comment by kkeshava** [comment]
Yes this was fixed in release 8.3.0.
