### ISSUE TITLE
7.1.0 reject as invalid, while 8.1.0 marks as valid

### ISSUE THREAD

**Issue by yjain3326** [googlei18n/libphonenumber#1556]
Some numbers are marked as Invalid by 7.1.0 but 8.1.0 marks them as valid.

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

This is intended, we make metadata updates almost every release.

Could you please specify in detail those numbers which you think should not be considered valid in 8.1.0?

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
