### ISSUE TITLE
Add geocoding/iw/972.txt

### ISSUE THREAD

**Issue by avimar** [googlei18n/libphonenumber#1557]
Not sure how the localization works, but Israel's area codes is easily available on wikipedia in hebrew:

https://he.wikipedia.org/wiki/%D7%A7%D7%99%D7%93%D7%95%D7%9E%D7%AA_%D7%98%D7%9C%D7%A4%D7%95%D7%9F_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C#.D7.A7.D7.99.D7.93.D7.95.D7.9E.D7.95.D7.AA_.D7.90.D7.96.D7.95.D7.A8.D7.99_.D7.94.D7.97.D7.99.D7.95.D7.92_.D7.94.D7.92.D7.90.D7.95.D7.92.D7.A8.D7.A4.D7.99.D7.99.D7.9D

https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/972.txt
=> language "he" would simply be this: (leave out אזור חיוג = "dialing area")

9722|ירושלים
9723|תל אביב-יפו והמרכז
9724|חיפה והצפון
9728|השפלה והדרום
9729|השרון

**Comment by avimar** [comment]
Sorry, the point of saying "easily available" was an attempt to avoid contribution paperwork.

Or should I just sign it and submit a PR?

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We can track adding of 972 geocoding in iw (Hebrew), but please be advised that metadata updates are top priority and considering our large backlog we may take a while to get to this.

If it's important to you we'd be happy to review a PR. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Tracking at https://github.com/googlei18n/libphonenumber/pull/1563
