### ISSUE TITLE
Mauritius mobile number validation

### ISSUE THREAD

**Issue by samuel-cloete** [googlei18n/libphonenumber#1558]
In relation to this ticket: https://github.com/googlei18n/libphonenumber/issues/1406

I've been told the following mobile numbers are also valid:
Country/region affected: MU - Mauritius
Example number: +23058436686
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

Country/region affected: MU - Mauritius
Example number: +23058493073
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

**Comment by sperelson** [comment]
👍 

Also, +23058438478
https://libphonenumber.appspot.com/phonenumberparser?number=%2B23058438478
Says it is an invalid number

**Comment by samuel-cloete** [comment]
Regex that will work for 5843 and 5849:
`/5(?:2[59]\\d|4(?:2[1-389]|4\\d|7[1-9]|9\\d)|7\\d{2}|8(?:[0-25689]\\d|4[3479]|7[15-8])|9[0-8]\\d)\\d{4}/`

**Comment by SumathiSundara** [comment]
We can't connect to +23058436686 , +23058493073 and +23058438478.

Please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by sperelson** [comment]
Thank you @SumathiSundara 

These numbers come from our Mauritian associates and we took them on good faith. We have requested that they try dialling them in country to verify them. I am assuming that it is possible that these numbers are only available within Mauritius.

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
