### ISSUE TITLE
Confusing wiki 

### ISSUE THREAD

**Issue by GitHubMurt** [googlei18n/libphonenumber#1560]
Hey why you posted on wiki  your fancy, imagine lib 
`compile group: 'com.google.protobuf.nano', name: 'protobuf-javanano', version: '3.0.0-alpha-7'`
???????? I wast my time on looking the right one!

It should be
`compile 'com.googlecode.libphonenumber:libphonenumber:8.2.0'`
also you should include it on your MAIN  page in **README**

**Comment by keghani** [comment]
The wiki is editable by open-source :)
So you can go ahead and edit that, and we didn't add the nano bit there. We don't compile with Gradle so don't know how to maintain that documentation.

**Comment by GitHubMurt** [comment]
<img width="510" alt="zrzut ekranu 2017-02-08 o 15 37 32" src="https://cloud.githubusercontent.com/assets/12357195/22741739/894f2c10-ee14-11e6-89f6-d3fc2398fd4e.png">
don't you? (compile)

**Comment by keghani** [comment]
What I meant is that no one on our team uses Gradle to compile day-to-day. libphonenumber may be compiled with Gradle however.
