### ISSUE TITLE
Missing mobile ranges +1868267XX in Trinidad and Tobago

### ISSUE THREAD

**Issue by ArtemTkachuk** [googlei18n/libphonenumber#1566]
These are mobile phone numbers, not fixed line
It is possible deliver messages there eg from Twilio
Please add

![264575377350654 lb6q4avah0wryv304orf_height640](https://cloud.githubusercontent.com/assets/25585615/22822628/3ff88e20-ef91-11e6-8428-4481ed3fc930.png)

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
