### ISSUE TITLE
+247 (AC) MetaData

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#157]
Imported from [Google Code issue #157](https://code.google.com/p/libphonenumber/issues/detail?id=157) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2012-06-16T05:43:15.000Z:

----
As of ITU Bulletin 01.VI.2012 http://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.1005-2012-OAS-PDF-E.pdf
Ascension Island's numbering plan has changed.
See Also: http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000AF0001PDFE.pdf

This is not yet reflected in the meta-data

Phone Numbers (Non-Geographic) have been introduced.
These are 6 digits vs the national 4 digit supported.
Valid numbers have yet to be confirmed with Justin Stevens, Operations Officer, Ascencion Island Cable and Wireless.

At the very least, possibleNumber should be changed from \d{4} to \d{4}(?:\d{2})
And National to support [5890]\d{5}

**Comment by keghani** [comment]
All mentioned ranges have been fixed. E.g. http://libphonenumber.appspot.com/phonenumberparser?number=+247560085&country=AC
