### ISSUE TITLE
Request to update name of area [VN]

### ISSUE THREAD

**Issue by DayiJung** [googlei18n/libphonenumber#1574]
*   Country/region affected (e.g., "US"):  VN
*   Example number(s) affected ("+1 555 555-1234"):  022 ->0 212
Make a call to 022 8567234: show Son La
Make a call to 0212 8567234: not show Son La
*   The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 022 ->0 212
*   The type of the number(s) ("fixed-line", "mobile", "short code", etc.):
*   The cost, if applicable ("toll-free", "premium rate", "shared cost"):
*   Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): mobile carrier

[Telephone area code changing_ English.pdf](https://github.com/googlei18n/libphonenumber/files/779103/Telephone.area.code.changing_.English.pdf)

**Comment by lararennie** [comment]
Thanks very much for bringing this to our attention!  We've accepted this issue and will fix this as soon as possible.

**Comment by kkeshava** [comment]
Fixed in release 8.3.1.

**Comment by DayiJung** [comment]
I checked with 8.3.1
But Vietnamese is not applied.
before display : 'Sơn La' 
now : 'Son La province'
Please update language also.
