### ISSUE TITLE
Getting UNKNOWN number on existing numbers in Slovakia

### ISSUE THREAD

**Issue by martin-ad** [googlei18n/libphonenumber#1578]
Please correct patterns for fixed lines in Slovakia.

*   Country/region affected (e.g., "US"): SK
*   Example number(s) affected ("+1 555 555-1234"): +421 51 17000, all number which are 5 digits long - 17XXX and have region code longer than 1 digit - [3-5][1-8] (51, 52...)
*   The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +421 [3-5][1-8] 17XXX
*   The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line (short number for special purposes, e.g. taxis)
*   Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
http://www.teleoff.gov.sk/index.php?ID=202
This is website of Slovak telecommunication regulator. It's only available in Slovak language, may be you can use google translate. If you scroll little bit down, you will find this paragraph:
"(8)               Skrátené päťmiestne čísla z množiny 16xxx a 17xxx sú určené na regionálne informačné služby všeobecne prospešného charakteru ako sú špeciálne informačné a podporné služby pre zdravotne postihnutých ľudí, služby humanitárneho charakteru, dopravné služby a informácie určené najmä zahraničným návštevníkom. V geograficky určenej číslovacej oblasti vlastného národného cieľového kódu volajúci účastník volí číslo bez národného rozlišovacieho čísla „0“ a bez národného cieľového kódu. Mimo geograficky určenej číslovacej oblasti vlastného národného cieľového kódu volajúci účastník volí číslo s národným rozlišovacím číslom „0“ a s národným cieľovým kódom."

It means that 16XXX and 17XXX numbers are numbers for regional informational services. And area code for regions in Slovakia is "2" for Bratislava region and [3-5][1-8] for all other regions. 

You can also scroll little bit down and you will find table which defines all codes for Slovak numbers.

You can find my modifications to pattern in the file attached. It's for php, but the pattern should be similar here as well.
[PhoneNumberMetadata_SK.php.zip](https://github.com/googlei18n/libphonenumber/files/785809/PhoneNumberMetadata_SK.php.zip)

Thank you.
Martin

**Comment by penmetsaa** [comment]
@martin-ad ,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by martin-ad** [comment]
Thank you. Of course, I submitted this issue so all others can have this issue fixed. :)

**Comment by SumathiSundara** [comment]
Fixed in release 8.3.2.
