### ISSUE TITLE
Israeli "mobile fax" numbers are not supported

### ISSUE THREAD

**Issue by dleshem** [googlei18n/libphonenumber#1579]
As described by Hebrew Wikipedia's [article on Israeli phone number prefixes](https://he.wikipedia.org/wiki/%D7%A7%D7%99%D7%93%D7%95%D7%9E%D7%AA_%D7%98%D7%9C%D7%A4%D7%95%D7%9F_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C), Israel has a new "153" mobile fax prefix.

International format: ‎+972 153-X(X) XXX-XXXX
Local format (within Israel): ‎153-X(X) XXX-XXXX

Actual example: 153 52 588 8536

**Comment by penmetsaa** [comment]
@dleshem ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.3.2.
