### ISSUE TITLE
Add support for 74 prefix in Ivory Coast (+225)

### ISSUE THREAD

**Issue by adic-connectik** [googlei18n/libphonenumber#1584]
*   Country/region affected: CI
*   Example number(s) affected : +22574937777
*   The phone number range(s) to which the issue applies : +22574xxxxxx
*   The type of the number(s) : Mobile MTN
*   The cost, if applicable ("toll-free", "premium rate", "shared cost"): same as other MTN prefixes

link to demo:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B22574937777&country=CI

it is a valid number, but it failing as not valid number.

**Comment by penmetsaa** [comment]
@adic-connectik ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.3.2.
