### ISSUE TITLE
Validation Issue with +354 7XX XXXX (IS)

### ISSUE THREAD

**Issue by steiza** [googlei18n/libphonenumber#1593]
*   Country/region affected: IS
*   Example number(s) affected: +354 766 3373
*   The phone number range(s) to which the issue applies: +354 76X XXXX, +354 77X XXXX, +354 78X XXXX
*   The type of the number(s): mobile
*   The cost, if applicable ("toll-free", "premium rate", "shared cost"): N/A
*   Supporting evidence: "The Icelandic numbering plan" linked off of https://www.pfs.is/english/telecom-affairs/numbering/; rows 924 to 953

Thank you!

**Comment by penmetsaa** [comment]
@steiza ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.3.2.
