### ISSUE TITLE
Request to update name of area [VN]

### ISSUE THREAD

**Issue by DayiJung** [googlei18n/libphonenumber#1599]
Please refer to https://github.com/googlei18n/libphonenumber/issues/1574
I checked with 8.3.1
But Vietnamese was not applied yet.

 before : 'Sơn La'
 now : 'Son La province'

Could you update VN language also?

**Comment by kkeshava** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
