### ISSUE TITLE
Update Carrier Mapping for Ghana and Namibia

### ISSUE THREAD

**Issue by ninjahza** [googlei18n/libphonenumber#1608]
Country: GH
Example number: +233540575250
Phone number range: + 23354 XXX XXXX
The type of the number: mobile
Carrier: MTN
Links: https://en.wikipedia.org/wiki/Telephone_numbers_in_Ghana

Country: NA
Example number: +264856747050
Phone number range: + 26485 XXX XXXX
The type of the number: mobile
Carrier: Cell One
Links: https://en.wikipedia.org/wiki/Telephone_numbers_in_Namibia

Country: NA
Example number: +264812745278
Phone number range: + 26481 XXX XXXX
The type of the number: mobile
Carrier: MTC
Links: https://en.wikipedia.org/wiki/Telephone_numbers_in_Namibia

Country: NA
Example number: +264608999078 
Phone number range: + 26460 XXX XXXX
The type of the number: mobile
Carrier: Telecom Switch
Links: https://en.wikipedia.org/wiki/Telephone_numbers_in_Namibia

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
The carrier name for Cell One has been changed to tn mobile, so we will be updating the same.
https://en.wikipedia.org/wiki/TN_Mobile

**Comment by ninjahza** [comment]
All good :) Thanks you!

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
