### ISSUE TITLE
Update Fixed Number Allocations in Botswana

### ISSUE THREAD

**Issue by Moahi** [googlei18n/libphonenumber#1609]
Please update the fixed allocation numbers for Gaborone area, Botswana to include
the following number range.

Number Range: 311 XXXX
Example Phone Number: 311 1000
Area: Gaborone Area
Country Calling Code: +267
Country: Botswana
Reference Link: https://en.wikipedia.org/wiki/Telephone_numbers_in_Botswana

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
