### ISSUE TITLE
Montenegro new patterns 

### ISSUE THREAD

**Issue by ildra** [googlei18n/libphonenumber#1611]
Hello!
Could you please add these patterns for Montenegro mobile phones:
Country/region affected (e.g., "US"): ME
Example number(s) affected ("+1 555 555-1234"): +38266010042, +38263010042, +38267911742
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +382660XXXXX , +382630XXXXX, +3826791XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
Thank you and best regards!
Dragan

**Comment by kkeshava** [comment]
@ildra,
Thank you for taking the time to improve libphonenumber!

We were able to connect to +38266010042, +38263010042, +38267911742. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by ildra** [comment]
Thank you for your answer . I don' t mind if you use  information from my request to your purpose.
 
BR! Dragan

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.

**Comment by ildra** [comment]
Thank you very much, I'll check.
BR! Dragan

**Comment by ildra** [comment]
Works perfect.
Thank you very much..
