### ISSUE TITLE
Validation issue with 0666600132 (TH)

### ISSUE THREAD

**Issue by vincent284** [googlei18n/libphonenumber#1612]
Country/region affected (e.g., "US"): TH

Example number(s) affected ("+1 555 555-1234"): 0666600132

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 066XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): Not PREMIUM_RATE

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

- https://dl.dropboxusercontent.com/u/8378106/066_doc.png (The document is in Thai, the description is translated as: "allow to use the prefix number 066 for temporary technical test  60,000 numbers")

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0666600132&country=TH)

Please advise. Thanks!

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We found evidence that 066XXXXXXX is valid.

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
