### ISSUE TITLE
New range Umniah Jordan

### ISSUE THREAD

**Issue by Umniah2017** [googlei18n/libphonenumber#1617]
Dear Colleagues

Appreciate to add the below new range to your database

Country: JO
New Phone number range:
•	+962 782 XX XXXX
•	The type of the number: mobile
•	Carrier: Umniah Mobile Company

**Comment by penmetsaa** [comment]
@Umniah2017 
Thanks for providing the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by Umniah2017** [comment]
@penmetsaa thank you for your reply

Could you please advice when will be the upcoming release

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
