### ISSUE TITLE
Validation missing for this countries

### ISSUE THREAD

**Issue by rharikrishnan84** [googlei18n/libphonenumber#1619]
Phone number missing for following countries.

AQ	ANTARCTICA
BV	BOUVET ISLAND
TP	EAST TIMOR
FX	METROPOLITAN FRANCE
TF	FRENCH SOUTHERN TERRITORIES
HM	HEARD AND MCDONALD ISLANDS
PN	PITCAIM
UM	UNITED STATES MINOR OUTLYING ISLANDS
YU	YUGOSLAVIA
ZR	ZAIRE
XM	ST. MAARTEN
KV	KOSOVO

**Comment by lararennie** [comment]
a) Kosovo is XK. It isn't using its country calling code yet, but instead multiple different ones. See #1486.
b) St Maarten is SX. Where are you getting your region codes from?
c) Issue #76 covers why we won't add Pitcairn Island, TF, UM, BV, AQ etc
d) Zaire and Yugoslavia have not existed for years. They have no valid numbers. So we will never add them.
e) East Timor is TL and we do support it. Again, your source of region codes is wrong.
