### ISSUE TITLE
Validation issue with 0556117772 (IL)

### ISSUE THREAD

**Issue by 3LOK** [googlei18n/libphonenumber#1621]
See [here](https://he.wikipedia.org/wiki/%D7%A7%D7%99%D7%93%D7%95%D7%9E%D7%AA_%D7%98%D7%9C%D7%A4%D7%95%D7%9F_%D7%91%D7%99%D7%A9%D7%A8%D7%90%D7%9C#.D7.A7.D7.99.D7.93.D7.95.D7.9E.D7.95.D7.AA_.D7.91.D7.90.D7.96.D7.95.D7.A8_.D7.94.D7.97.D7.99.D7.95.D7.92_.D7.9C.D7.98.D7.9C.D7.A4.D7.95.D7.A0.D7.99.D7.9D_.D7.A0.D7.99.D7.99.D7.93.D7.99.D7.9D_05
).

Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IL

Example number(s) affected ("+1 555 555-1234"): 0556117772

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0556117772&country=IL)

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We can't connect to +972 556117772. Did you have a typo?

We found evidence that 5561XXXXX is valid.

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Hi,

We can't connect to +972 556117772. Could you please share any other working number?

The wiki link provided by you is very generic and lenient. Sorry the evidence we found earlier is also very generic. We follow ITU document to do the updates as it is more accurate. We could not find any working numbers online so we cannot support 5561xxxxx unless we get evidence.
Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 5561 is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Comment by 3LOK** [comment]
Thanks. This was a bug that was reported to us by one of our customers. We've told them to give us a working phone number with this prefix, but they haven't responded. We will re-open if they ever respond.
