### ISSUE TITLE
How determine whether a code is mobile  or phone

### ISSUE THREAD

**Issue by michealyq** [googlei18n/libphonenumber#1622]
I am using libphonenumber(Java)
String Str = "+1－201－123－4567"; (it is phone)
String Str2 = "+1－1234567890"; (it is mobile)
How to judge it 

Best Regard ,
Michael qiang

**Comment by penmetsaa** [comment]
@michealyq ,

Thank you for using libphonenumber!

You can use PhoneUtil.getNumberType(PhoneNumber) API to know the type of the input phone number. Sample code: 
```
// Parse the number.
PhoneNumber phoneNumber1 = phoneUtil.parse("+1－201－123－4567", "AR");
// Get the enum of the type.
PhoneNumberType type = phoneUtil.getNumberType(phoneNumber1);
```

For more details please check java doc of [PhoneNumberUtil.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2061)
Closing this issue as the query is answered.

**Comment by michealyq** [comment]
**@penmestsaa**
 Thank you for your prompt reply

**source code**:

> public enum PhoneNumberType {
>     FIXED_LINE,
>     MOBILE,
>     // In some regions (e.g. the USA), it is impossible to distinguish between fixed-line and
>     // mobile numbers by looking at the phone number itself.
>     FIXED_LINE_OR_MOBILE,
>     // Freephone lines
>     TOLL_FREE,
>     PREMIUM_RATE,
>     // The cost of this call is shared between the caller and the recipient, and is hence typically
>     // less than PREMIUM_RATE calls. See // http://en.wikipedia.org/wiki/Shared_Cost_Service for
>     // more information.
>     SHARED_COST,
>     // Voice over IP numbers. This includes TSoIP (Telephony Service over IP).
>     VOIP,
>     // A personal number is associated with a particular person, and may be routed to either a
>     // MOBILE or FIXED_LINE number. Some more information can be found here:
>     // http://en.wikipedia.org/wiki/Personal_Numbers
>     PERSONAL_NUMBER,
>     PAGER,
>     // Used for "Universal Access Numbers" or "Company Numbers". They may be further routed to
>     // specific offices, but allow one number to be used for a company.
>     UAN,
>     // Used for "Voice Mail Access Numbers".
>     VOICEMAIL,
>     // A phone number is of type UNKNOWN when it does not fit any of the known patterns for a
>     // specific region.
>     UNKNOWN
>   }
> 

**Test**
CASE1:

> // Parse the number.
> PhoneNumber phoneNumber1 = phoneUtil.parse("+1－201－123－4567", "AR");
> // Get the enum of the type.
> PhoneNumberType type = phoneUtil.getNumberType(phoneNumber1);
> result: type.name=UNKNOWN

CASE2:

> // Parse the number.
> PhoneNumber phoneNumber1 = phoneUtil.parse("1-626-202-3379", "AR");
> // Get the enum of the type.
> PhoneNumberType type = phoneUtil.getNumberType(phoneNumber1);
> result: type.name=FIXED_LINE_OR_MOBILE

CASE3:

> // Parse the number.
> PhoneNumber phoneNumber1 = phoneUtil.parse("+86-20-8202-3379", "AR");
> // Get the enum of the type.
> PhoneNumberType type = phoneUtil.getNumberType(phoneNumber1);
> result: type.name=FIXED_LINE

**conclusion**
That's to say, 
FIXED_LINE must be phone,  
FIXED_LINE_OR_MOBILE may be phone or mobile,  
MOBILE must be mobile
while UNKNOWN means not fit any of the known patterns
is it?

**Comment by penmetsaa** [comment]
Yes, if it does not fit any of the known patterns, we consider it as invalid number and return PhoneNumberType.UNKNOWN as type of the number. It is better to check whether the number is valid or not before you check the type of the number, API: ```PhoneNumberUtil.isValidNumber()```

Sorry, forgot to mention this earlier. You can raise issue on GitHub if library is not behaving as expected for any input number.

**Comment by michealyq** [comment]
Yes, i am aware of the method:

> PhoneNumberUtil.isValidNumber(). 

. 
My **idea** is like this: 

- Firstly, determine whether it is isValidNumber
- Secondly, judge  the number :mobile  or phone
- Lastly, in the case of the number is phone, i extract the extension number

**eg**:
"+86-20-8202-3379-100"
It is a validnumber and country code:86
Belongs to phone
Finally, extract the extension number:100

I will give feedback as soon as meeting other issues

**Comment by lararennie** [comment]
How are you extracting the extension and why?
If you want to format the number without it, you can format in E164 format.

Note also that to judge if something is mobile you want to check MOBILE,
FIXED_LINE_OR_MOBILE and depending on your use-case you may want to
consider PAGER too.

10. mar. 2017 9.06 a.m. skrev "michealyq" <notifications@github.com>:

Yes, i am aware of the method:

PhoneNumberUtil.isValidNumber().

.
My *idea* is like this:

   - Firstly, determine whether it is isValidNumber
   - Secondly, judge the number :mobile or phone
   - Lastly, in the case of the number is phone, i extract the extension
   number

*eg*:
"+86-20-8202-3379-100"
It is a validnumber and country code:86
Belongs to phone
Finally, extract the extension number:100

I will give feedback as soon as meeting other issues

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1622#issuecomment-285604029>,
or mute the thread

**Comment by michealyq** [comment]
**@lararennie** 

"How are you extracting the extension and why?"
purpose:Split phone number into four fields: country code,  mobile, phone, extention number.
For querying with multi conditions

Thanks for you reminding  E164 format. I should have better understand of it

Our extention number in Specified format

**Comment by lararennie** [comment]
I don't understand how you can split a phone number into "phone and mobile"
-> this seems orthogonal?

In any case, use getNationalSignificantNumber if you want the national
number part, never just use getNationalNumber() on the phone number object
itself.

2017-03-10 9:31 GMT+01:00 michealyq <notifications@github.com>:

**Comment by michealyq** [comment]
To be frank , sort all the phone numbers into format exactly  just by PhoneNumberUtil class, it may be a little difficult. Most of phone numbers are in defined format, we deal with it in method mentioned . As for phone number that is not good to distinguish, we use default field for to fit phone number （with secondary treatment）.**Pre-Processing and splitting this up into cases**， that is my simple way.

**Comment by keghani** [comment]
Thanks @michealyq! This is not an issue with the library and we've closed it on GitHub. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
