### ISSUE TITLE
Host JavaDoc

### ISSUE THREAD

**Issue by ggrochow** [googlei18n/libphonenumber#1626]
It would be really nice if as a developer I didn't have to download the entire repo at the version I want, just to view the docuemtation for how to use this library. 
even it was just the most recent release, it would be super helpful.

**Comment by lararennie** [comment]
Hi,

Thanks for the feature request!

You don't need to download the repo, you can just read the doc via the source files on github, but I get your point that online javadoc would be nicer. I note also we have javadoc on github, but it's two years out of date, and horrible to read.

The javadoc jar is on maven too:
https://search.maven.org/#search%7Cga%7C1%7Clibphonenumber

We'll look into how to do this.

**Comment by koral--** [comment]
Browseable javadoc for all artifacts published to maven central is available at javadoc.io.
Eg. https://javadoc.io/doc/com.googlecode.libphonenumber/libphonenumber/8.3.3

**Comment by lararennie** [comment]
Wow! Thanks for letting us know!! We should link to this from our README
then ;)

14. mar. 2017 10.17 p.m. skrev "Karol Wrótniak" <notifications@github.com>:
