### ISSUE TITLE
miss 991: Trial of a proposed new international service, shared code,

### ISSUE THREAD

**Issue by jiafu1115** [googlei18n/libphonenumber#1631]
miss 991: Trial of a proposed new international service, shared code,
refer to https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164C-2011-PDF-E.pdf

**Comment by penmetsaa** [comment]
Closing this as working as intended. More details in PR #1627.

**Comment by penmetsaa** [comment]
@jiafu1115 ,
We do not support all the country codes mentioned in ITU documents unless there are numbers assigned under that country code / do have numbering plan. Please take a look at our 
[FAQ page #why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported). Please feel free to reopen this bug with supporting evidences.
