### ISSUE TITLE
where is the country code TA from?

### ISSUE THREAD

**Issue by jiafu1115** [googlei18n/libphonenumber#1636]
`
		listWithRegionCode = new ArrayList(2);
		listWithRegionCode.add("SH");
		listWithRegionCode.add("TA");
		countryCodeToRegionCodeMap.put(Integer.valueOf(290), listWithRegionCode);
`

which reference is the country code TA from?

there is no country code for TA refer to https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2. 
also no search result for https://www.iso.org/obp/ui/#search

just notice:

SH-AC* Ascension
 SH-HL* Saint Helena
 SH-TA* Tristan da Cunha

**Comment by lararennie** [comment]
Tristan da Cunha.

http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html

16. mar. 2017 6.48 a.m. skrev "stroller" <notifications@github.com>:

**Comment by lararennie** [comment]
I will update the docs for this, sorry for the confusion!

**Comment by jiafu1115** [comment]
I am still not sure if it is right to place TA in the class consider iso has no TA. Whatever.3ks for your feedback.

**Comment by lararennie** [comment]
New docs will make it clear. We don't follow ISO standard, we follow CLDR standard, which lists TA.

**Comment by keghani** [comment]
Fixed in #1638, released in 8.4.0.
