### ISSUE TITLE
Not able to save phone number with 83.. series

### ISSUE THREAD

**Issue by sunnychaudhari** [googlei18n/libphonenumber#1641]
I'm trying to store phone number +918369232477 using django phone number field which is a wrapper of libphonenumber, as I have installed this in my django project but this number is not getting stored. Currently this is the new series numbers that reliance jio providers in India have launched with. Giving me error as its not valid phone number. Apart from this all other 10 digit numbers are getting saved such as +919899999999 , +917699889898, ...etc

I think this library doesn't support this series of phone numbers. Please help me in this issue.

**Comment by kevin-brown** [comment]
In theory this should have been corrected in https://github.com/googlei18n/libphonenumber/pull/1629.

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
