### ISSUE TITLE
Request: update mobile carrier from Vietnam

### ISSUE THREAD

**Issue by nguyenanhung** [googlei18n/libphonenumber#1644]
Hey,

Currently Vietnam has updated a number of new numbers, but I have not seen it here. Can you update it to the library?

I have listed a sample array of data: [https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/84.txt](https://github.com/googlei18n/libphonenumber/blob/master/resources/carrier/en/84.txt)

> 84120|MobiFone
84121|MobiFone
84122|MobiFone
84123|Vinaphone
84124|Vinaphone
84125|Vinaphone
84126|MobiFone
84127|Vinaphone
84128|MobiFone
84129|Vinaphone
84162|Viettel
84163|Viettel
84164|Viettel
84165|Viettel
84166|Viettel
84167|Viettel
84168|Viettel
84169|Viettel
84186|Vietnamobile
84188|Vietnamobile
84199|Gmobile
84868|Viettel
8488|Vinaphone
8489|MobiFone
8490|MobiFone
8491|Vinaphone
8492|Vietnamobile
8493|MobiFone
8494|Vinaphone
8496|Viettel
8497|Viettel
8498|Viettel
84992|VSAT
84993|Gmobile
84994|Gmobile
84995|Gmobile
84996|Gmobile
84997|Gmobile
84998|Indochina Telecom
84999|Indochina Telecom

Very hope you update :)

Source: [https://vi.wikipedia.org/wiki/M%C3%A3_%C4%91i%E1%BB%87n_tho%E1%BA%A1i_Vi%E1%BB%87t_Nam#.C4.90.E1.BA.A7u_s.E1.BB.91_.C4.91i.E1.BB.87n_tho.E1.BA.A1i_di_.C4.91.E1.BB.99ng](https://vi.wikipedia.org/wiki/M%C3%A3_%C4%91i%E1%BB%87n_tho%E1%BA%A1i_Vi%E1%BB%87t_Nam#.C4.90.E1.BA.A7u_s.E1.BB.91_.C4.91i.E1.BB.87n_tho.E1.BA.A1i_di_.C4.91.E1.BB.99ng)

Very thanks

HungNA from Vietnam with love :)

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.4.2.

**Comment by ropeko90** [comment]
Hi

The parsing of mobile phone numbers from Vietnam starting with 0 instead of +84 does not work with version 8.5.2. See https://en.wikipedia.org/wiki/Telephone_numbers_in_Vietnam#Mobile_telephone_numbers for the possible mobile phone number formats.
In my example it was a number of format 0125xxxxxx.

Best regards
Roger

**Comment by lararennie** [comment]
That number is too short, according to the page you linked. If a number is
already too short, we won't assume the 0 is a national prefix.

2017-07-11 10:29 GMT+02:00 ropeko90 <notifications@github.com>:

**Comment by ropeko90** [comment]
Sry, there is a missing "x" in the example phone number: 0125xxxxxxx. This is then again according to the format 01yy xxx-xxxx of the linked page ;)

**Comment by lararennie** [comment]
Then it works fine.
See demo:
http://libphonenumber.appspot.com/phonenumberparser?number=0125+123-1234&country=VN

Please always verify with the demo before reporting a problem (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by ropeko90** [comment]
Ah yes, when the phone number comes from contacts it has the correct defaultRegion and if the user enters the mobile number manually, we use a wrong defaultRegion. Thank you for the fast answers! Next time I will first check with http://libphonenumber.appspot.com/
