### ISSUE TITLE
Please Update Tanzania Career Prefix

### ISSUE THREAD

**Issue by Clabybite** [googlei18n/libphonenumber#1645]
I have a number 0735368524, it is not showing carrier, it should be reading TTCL
also 0677700800, supposed to be tiGO

[Telephone numbers in Tanzania - Wikipedia.pdf](https://github.com/googlei18n/libphonenumber/files/852791/Telephone.numbers.in.Tanzania.-.Wikipedia.pdf)

Prefix	Usage and operator
61	Cellular mobile Sasatel(Dovetel) [new for year 2009]
62	Cellular mobile Halotel (Viettel) [new for year 2015]
66	Cellular mobile Smile Communications Tanzania Limited
67	Cellular mobile TIGO (Mobitel) [MIC Ltd]
72	[reserved for future mobile services]
73	digital mobile CDMA; Tanzania Telecommunications Company Ltd
74	cellular mobile GSM; Vodacom (Celtel)
*74 2	cellular mobile; Tritel [formerly 812, as of 2000-10-31].
*76 1	cellular mobile; Adesemi [formerly 821, as of 2000-10-31].
77	cellular mobile GSM; Zantel (Zanzibar Telecom Ltd) [keeps existing code in year 2000 changes].
79	digital mobile CDMA; Benson Informatics Ltd

https://en.wikipedia.org/wiki/Telephone_numbers_in_Tanzania

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by Clabybite** [comment]
Hi Sumathi, help me out. When I test the number 0735368524 I get Tanzania Telecom which is correct and also 0678452616 gives tiGO which is also correct. http://libphonenumber.appspot.com/phonenumberparser?number=+0678452616&country=TZ

Now my problem is in my project they do not work, I get blank (carrier name) for those numbers

In my library I have
carrier-1.9.jar
prefixmapper-2.66.jar
libphonenumber-8.3.3.jar

what am I missing? are there latest versions of those and where do I get them?

Thanks,
Clarence

**Comment by Clabybite** [comment]
Here is part of my code

PhoneNumber pNumber=phoneUtil.parse(log.number,"TZ");
String providerName=p2c.getNameForNumber(pNumber,Locale.ENGLISH)+pNumber.getRawInput();
provider.setText(providerName);
Log.i("MainActivity",log.name+", "+log.number+", "+providerName);

Then for some numbers (log.number) I get empty providerName, though most of them work well except those two numbers

**Comment by keghani** [comment]
Hi @Clabybite,

The carrier jar is indeed outdated. To see the current versions of the different jars, I'd go to the versioned GitHub tag and look up `pom.xml`. E.g. go to https://github.com/googlei18n/libphonenumber/find/v8.3.3 and type `pom.xml`, and it will show you all the pom.xml files as they were with the 8.3.3 release.

The `java/carrier/pom.xml` file that shows up has version `1.56`. Does using that solve your problem?

Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss), these kinds of questions would be great to have there :)

**Comment by Clabybite** [comment]
Hi @keghani 

I managed to solve the problem using the method you shared. Thank you!

Sorry, I'm just a newbie in the platform :)

**Comment by keghani** [comment]
Great that the problem is solved, thanks for confirming!
