### ISSUE TITLE
German prefix 152 is invalid

### ISSUE THREAD

**Issue by Hopreeeenjust** [googlei18n/libphonenumber#1647]
Hello.
Seems like +49 152 XXXX XXX phone numbers are defined as not valid by the library.
But in fact these are valid numbers: https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany#Non-geographic_numbering

Can you please fix as some customers complain they could not register their phone number?
Thanks in advance.

**Comment by SumathiSundara** [comment]
We support 11 digit long numbers for the prefix 152 while the specified number is 10 digits long.

Here is our official evidence: https://en.wikipedia.org/wiki/Telephone_numbers_in_Germany#Non-geographic_numbering which states that numbers starting with 15 are 11 digits long.

We are not able to find 10 digit numbers with this prefix online.

Please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by Hopreeeenjust** [comment]
Here is quote from customers report:
"We have a user with phone number +49 152 864 5558 who cannot register in the app with that phone number. The error message is "invalid phone number"."

So, this phone number is

**Comment by Hopreeeenjust** [comment]
Can you please check with the existing number: +49 152 864 5558 ?

**Comment by SumathiSundara** [comment]
We can't connect to +49 152 864 5558. we dialled this number from Switzerland and the response "The number you just called hasn't been assigned."

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
Please check with your customers if they have a typo.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss)
if you'd like to discuss this further.
