### ISSUE TITLE
Validation issue with +80052323111

### ISSUE THREAD

**Issue by dbarwacz** [googlei18n/libphonenumber#1648]
Example number(s) affected: +80052323111

(http://libphonenumber.appspot.com/phonenumberparser?number=%2B80052323111)

Please note country code, '800' does not seem to be valid country code (or 001 valid region)

**Comment by lararennie** [comment]
Yes it is.

https://en.wikipedia.org/wiki/Toll-free_telephone_number#Universal_International_Freephone_Service

001 is "world" and we use it for all non-geographical entities that assign phone numbers, like +800.
