### ISSUE TITLE
Mobile number type shown as fixed_line

### ISSUE THREAD

**Issue by AbhishekR-webonise** [googlei18n/libphonenumber#1649]
![mobile number as fixed line](https://cloud.githubusercontent.com/assets/18273111/24100110/95960252-0d98-11e7-908d-5087b976fe3f.png)

Hello Team,
I am using [Phonelib](https://github.com/daddyz/phonelib) gem which uses Google libphonenumber in my ruby on rails project.
When i'm trying to validate +917701232342
**Currently** 
Type returned is fixed_line
**Expected**
Type returned should be mobile.

**Comment by SumathiSundara** [comment]
We can't connect to +917701232342.

Please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
We haven't received a response from you yet about official evidence See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Would it be possible for you to provide an update in order for us to move
forward with fixing this issue?

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
