### ISSUE TITLE
Austrian Numbering Plan - VPN is not 5

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#165]
Imported from [Google Code issue #165](https://code.google.com/p/libphonenumber/issues/detail?id=165) created by [denis.knauf](https://code.google.com/u/108923986674080676884/) on 2012-07-04T13:24:15.000Z:

----
Hi,

+43 5 is not part of the Austrian Numbering Plan[1].  There are some destination coded with begins with 5 (eg. 50x),  but 5 alone is not valid and nobody use it.

Example:
  +43 505 1234567  (VPN)
  +43 512 1234567  (Insbruck)
  +43 5212 1234567 (Seefeld in Tirol)
  +43 57 1234567   (VPN)

At A1 Telekom Austria AG employee-numbers it's really common to write +43 50 664 xxxxx,  because it has the mobile number destination code +43 664.  It would be nice if you provide these numbering, too.  It isn't part of the Austrian Numbering Plan,  it's only usefull to remember.
Example: +43 50 664 12345

Please change it. Thanks!

Greets
Denis Knauf

[1] Austrian Numbering Plan: http://www.rtr.at/en/tk/E129

**Comment by christophhermann** [comment]
I'm not quite sure if the information provided here is correct. According to the Austrian telecommunications regulation agency, there is an area code 5 (please refer to https://www.rtr.at/en/tk/privateN). These networks are called a private networks. 
Companies with various locations use this sort of numbers. Examples with correct formatting in the international format are

+43 5 17661000 
+43 5 0514

Further examples can be found here: https://www.rtr.at/en/tk/Rufnummernsuche?S=05&art=d.

**Comment by roes** [comment]
Hi,
We support all these numbers as UAN, and the formatting has been updated for a long time as well, so I'm closing this.

Please reopen if something still isn't right.

**Comment by christophhermann** [comment]
Thanks for clarification. Then maybe demos in the README file link to wrong versions. They don't correctly format this kind of number.

The demo
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
formats +43 5 1766 incorrectly as following:

```
****Parsing Result:****
{"country_code":43,"national_number":51766,"raw_input":"+43 5 1766","country_code_source":1,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: AT
Result from getNumberType(): UAN

****Formatting Results:**** 
E164 format: +4351766
Original format: +43 5 1766
National format: 51766
International format: +43 51766
Out-of-country format from US: 011 43 51766
Out-of-country format from Switzerland: 00 43 51766

****AsYouTypeFormatter Results****
Char entered: + Output: +
Char entered: 4 Output: +4
Char entered: 3 Output: +43 
Char entered:   Output: +43 
Char entered: 5 Output: +43 5
Char entered:   Output: +43 5 
Char entered: 1 Output: +43 5 1
Char entered: 7 Output: +43 5 17
Char entered: 6 Output: +43 5 176
Char entered: 6 Output: +43 5 1766
```

According to the regulation agency, the national format for the number is 05 1766 and therefore the international format should be +43 5 1766 (see https://www.rtr.at/en/tk/Rufnummernsuche?S=05&art=d or the screenshot below for reference)
![image](https://cloud.githubusercontent.com/assets/3696338/6869772/f3bc5396-d496-11e4-8fd6-978241976382.png)

In my opinion the validation results are correct.

**Comment by christophhermann** [comment]
The regulation agency contradicts itself. According to https://www.rtr.at/en/tk/nationaleRufnummern the current formatting is correct.
![image](https://cloud.githubusercontent.com/assets/3696338/6872239/2fc8f068-d4a8-11e4-8a75-9dd60b7aa68d.png)
