### ISSUE TITLE
New mobile prefix for Fiji (+679)

### ISSUE THREAD

**Issue by sonnguyenwebtools** [googlei18n/libphonenumber#1658]
Hello,

Since 2016 new additional mobile number prefixes were introduced in Fiji by Vodafone Fiji and Digicel.

Vodafone  Fiji prefix
58 (examples 5880004, 5883849 and 5891666)
Digicel prefix:
50 (example: 5086080)
51

Those number ranges are not valid in the current library. Could you please update?

Please refer to https://en.wikipedia.org/wiki/Telephone_numbers_in_Fiji

Thanks

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.4.0
