### ISSUE TITLE
Issue with natural number regex for PH

### ISSUE THREAD

**Issue by ammireddy9** [googlei18n/libphonenumber#1660]
regex: 2\d{5,7}|[3-9]\d{7,9}|1800\d{7,9}
for number: 6322852824 it shows true, while actually 63 is country code. so it should show as false

**Comment by kkeshava** [comment]
Hi,

Thank you for taking the time to improve libphonenumber!
If user inputs the number like +6322852824 or 022852824 the library will parse and remove +, 0 or country code to get the actual subscriber number i.e 22852824. So this is a valid fixedline number. Please see [demo.](http://libphonenumber.appspot.com/phonenumberparser?number=%2B6322852824) 

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by ammireddy9** [comment]
6322852824 what if the user entered only like this and given PH as default location.On Mar 27, 2017 4:11 PM, kkeshava <notifications@github.com> wrote:Hi,
Thank you for taking the time to improve libphonenumber!
If user inputs the number like +6322852824 or 022852824 the library will parse and remove +, 0 or country code to get the actual subscriber number i.e 22852824. So this is a valid fixedline number. Please see demo.
I'll close this as it's not an issue with the library. Please consider joining the discussion group if you'd like to discuss this further.

**Comment by lararennie** [comment]
We can actually handle this a bit better. Re-opening for tracking.

**Comment by kkeshava** [comment]
This issue has been fixed. If you feel something is not fixed still, we invite you to file issues in Google's new [Issue Tracker](https://b.corp.google.com/issues/new?component=192347&template=829703), which we're currently testing.
