### ISSUE TITLE
Vietnam prefix mobile 0886

### ISSUE THREAD

**Issue by camkhonlien** [googlei18n/libphonenumber#1662]
Dear team,

0886682011 (prefix 0886) must be Mobile number. However, I see demo return it FIXED_LINE. I'm using this lib in our TopPay app. In this app mobile is username. So we cannot support user with prefix 0886

Could you please updating the lib to support this prefix?

I'm appreciate your help. Thanks

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by camkhonlien** [comment]
Hi kkeshava,

Could you share with me timeline of next release? We will arrange time to support our users asap. Thanks

**Comment by kkeshava** [comment]
Hi @camkhonlien,
We normally cut our release every 2 weeks, but how long it takes to complete depends on factors sometimes outside our control. We cannot commit to completing the next release at a specific date. However we have our next planned release in the second week of April.

**Comment by penmetsaa** [comment]
This is fixed as part of release 8.4.1
https://libphonenumber.appspot.com/phonenumberparser?number=%2B84886680000
