### ISSUE TITLE
Validation issue with 1189830119 (BR)

### ISSUE THREAD

**Issue by fallemand** [googlei18n/libphonenumber#1675]
Country/region affected: BR

Example number(s) affected: +55 11 89830119

The phone number range(s) to which the issue applies ("+55 11 8XXXXXXX): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Wikipeadia: http://prntscr.com/erwrf1
Link: https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=1189830119&country=BR)

**Comment by penmetsaa** [comment]
Thank you for using libphonenumber!

As per the ITU doc listed below, 11 XXXX XXXX mobile numbers have been migrated to 11 9XXXX XXXX from 29 July 2012.
https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0003PDFE.pdf (Page 1).


So now we support 11 9XXXX XXXX as a mobile range. We are not able to connect to the number provided by you (+55 11 89830119). Could you please provide any valid official evidence or working 10 digit mobile numbers that starts with "118". See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by fallemand** [comment]
That number is a cellphone from Claro.
Here you can see some recharges made to that number.
This screenshot is from [MercadoPago](https://www.mercadopago.com.br).
![2017-04-04](https://cloud.githubusercontent.com/assets/16105726/24676631/1b741694-195a-11e7-987d-f088b7686660.png)

**Comment by penmetsaa** [comment]
@fallemand,

Thanks for sharing the screenshots.

We are not able to connect to the number "+55 11 89830119" but we are able to connect to it when we add 9 after "11" i.e +55 11 9 89830119. This is in line with phone number migrations that took place in Brazil. More details about this have been shared in the ITU doc in my previous response.

Looks like the migration has already occurred for this range. There is a chance that the portal mercadopago.com.br is not in line with recent migrations and displaying the number in old format.

**Comment by penmetsaa** [comment]
We don't have enough information to fix the issue. Please feel free to reopen with valid evidences. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).
