### ISSUE TITLE
Validation issue with 22586055856 (CI)

### ISSUE THREAD

**Issue by achiang** [googlei18n/libphonenumber#1676]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): CI

Example number(s) affected ("+1 555 555-1234"): +22586055856

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +225 86 XX XX XX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

Sorry, I can't find any public evidence on this range; however, we have seen these phone numbers in the wild, seemingly belonging to MTN.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=22586055856&country=CI)

**Comment by penmetsaa** [comment]
@achiang,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 8.4.1
https://libphonenumber.appspot.com/phonenumberparser?number=%2B22586055856
