### ISSUE TITLE
Is that possible to validate without specifying default country?

### ISSUE THREAD

**Issue by wingliu0** [googlei18n/libphonenumber#1677]
Im going to accept phone numbers from any country. 
Is that possible to validate a number without specifying default country?
It would be better if it can even return the possible country codes too..

**Comment by lararennie** [comment]
No, unless it was entered in E164 or international format, with a leading plus. Many numbers are valid in very many regions so it's best for you to tell us what you think it is. If you think it's either country A or country B then you could parse and validate with both options, but you'll end up with a different number in each case and it could be valid for both.

This isn't an issue with the library so I'll close it now; of you want to discuss it further, please join [libphonenumber-discuss](http://groups.google.com/ forum/#!forum/libphonenumber-discuss).
