### ISSUE TITLE
Not accepting any number of INDIA STARTING WITH 8920

### ISSUE THREAD

**Issue by anki1427** [googlei18n/libphonenumber#1682]
Hello,
Please fix the issue with number starting with 89208 with prefix of India (91)

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library. http://libphonenumber.appspot.com/phonenumberparser?number=%2B918920120000
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by anki1427** [comment]
please try number starting with 89208

**Comment by SumathiSundara** [comment]
I found this number is also working http://libphonenumber.appspot.com/phonenumberparser?number=%2B918920810000
