### ISSUE TITLE
Not accepting any number of INDIA STARTING WITH 89208

### ISSUE THREAD

**Issue by anki1427** [googlei18n/libphonenumber#1683]
Hello,
LibsPhonenumber is not validating the number starting from 89208 of INDIA Prefix 91.
Please fix this issue asap.

--Thanks

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library http://libphonenumber.appspot.com/phonenumberparser?number=%2B918920810000. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
