### ISSUE TITLE
Indian JIO number verification issue

### ISSUE THREAD

**Issue by ajitjati** [googlei18n/libphonenumber#1684]
Country region - INDIA (+91) 
Number series not working - "89208" 
Example number - 8920892643
Telecom - Reliance Jio Infocomm, Delhi/NCR

Please fix this.

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library http://libphonenumber.appspot.com/phonenumberparser?number=%2B918920892643. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
