### ISSUE TITLE
Invalid at number series 89208

### ISSUE THREAD

**Issue by ankita-arora** [googlei18n/libphonenumber#1686]
Using library: 
compile 'com.googlecode.libphonenumber:libphonenumber:7.1.1' 
Code:
 PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
        String isoCode = phoneNumberUtil.getRegionCodeForCountryCode(Integer.parseInt(countryCode));
        Phonenumber.PhoneNumber phoneNumber = null;
        try {
            phoneNumber = phoneNumberUtil.parse(phNumber, isoCode);
            Logger.LogError("fjfjfjf",phoneNumber+"");
        } catch (NumberParseException e) {
            numConnect.setEnabled(true);
            Logger.LogError("djdjjjjj", "invalidNumber" + e.getCause());
            Toast.makeText(mContext, R.string.invalidNumber, Toast.LENGTH_SHORT).show();
        }
        boolean isValid = phoneNumberUtil.isValidNumber(phoneNumber);
        Logger.LogError("isValid",isValid+"");
        if (isValid) {
            numConnect.setEnabled(true);
            String internationalFormat = phoneNumberUtil.format(phoneNumber, PhoneNumberUtil.PhoneNumberFormat.E164);
            myPrefs.setMobileNumber(internationalFormat);
            otpSending(internationalFormat);
        } else {
            numConnect.setEnabled(true);
            Logger.LogError("djdjjjjj", "invalidNumber");
            Toast.makeText(mContext, R.string.invalidNumber, Toast.LENGTH_SHORT).show();
        }
isValid is always false with the phone number starting with 89208.

**Comment by ankita-arora** [comment]
![screenshot from 2017-04-11 12 37 19](https://cloud.githubusercontent.com/assets/27265470/24896711/c88b7c38-1eb3-11e7-88b0-fa8665e4dd5a.png)
![screenshot from 2017-04-11 12 37 30](https://cloud.githubusercontent.com/assets/27265470/24896712/c89424d2-1eb3-11e7-92f1-6fa0f752849c.png)

Please check the screenshots attached.

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by lararennie** [comment]
Note: you should specify IN as the default country. Not +91. See the link beside the box saying CLDR two-letter region code? That's showing you what to enter, and links to a list of them.

**Comment by lararennie** [comment]
(http://libphonenumber.appspot.com/phonenumberparser?number=8920892643&country=IN)
