### ISSUE TITLE
Mobile currently showing as FIXED_LINE 0869004031 (VN)

### ISSUE THREAD

**Issue by vincent284** [googlei18n/libphonenumber#1693]
Country/region affected (e.g., "US"): VN

Example number(s) affected ("+1 555 555-1234"): 0869004031

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 086XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile (currently showing as FIXED_LINE, which is wrong)

The cost, if applicable ("toll-free", "premium rate", "shared cost"): Not PREMIUM_RATE

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0869004031&country=VN)

Please advise. Thanks!

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by lararennie** [comment]
https://en.wikipedia.org/wiki/Telephone_numbers_in_Vietnam#Mobile_telephone_numbers agrees that 8 is a valid prefix for mobile phones.
It isn't in the ITU doc unfortunately. It also has more specific Ho Chi Minh prefixes which allow us to distinguish better.

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.4.2.
