### ISSUE TITLE
Validation issue with 651200002 (LU)

### ISSUE THREAD

**Issue by pschartz** [googlei18n/libphonenumber#1694]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): LU

Example number(s) affected ("+1 555 555-1234"): 651200002

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=651200002&country=LU)

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.4.2.
