### ISSUE TITLE
Argentina phone numbers are invalid.

### ISSUE THREAD

**Issue by tsx** [googlei18n/libphonenumber#1697]
A range of perfectly reachable numbers in Argentina (+54) appear as invalid in international and e164 format.

Here's an example: [+5450490000](http://libphonenumber.appspot.com/phonenumberparser?number=%2B5450490000) (An actual phone number I have is a few last digits different from that example to avoid disclosing personal information). The issue appears across a large range of numbers +5499999999 - +5400000000.

**Comment by lararennie** [comment]
Can you give an example based on our demo of what you see and what you expect? Please see our contribution guidelines: this number appears to be valid to me.

**Comment by lararennie** [comment]
Oh I see. You link it explicitly to the demo; Gmail automatically linkifies phone numbers so I thought it had recognised it.

Seems it's missing an area code? Numbers are ten digits long and yours is eight. Internally it's diallable but not from overseas?

**Comment by lararennie** [comment]
(Also note our library should output E164 format just fine; we just don't on our demo for invalid numbers.)

**Comment by tsx** [comment]
@lararennie it reports completely the same "invalid" result if I add two or three more zeroes at the end. And also `isPossibleShortNumber()` is `false` for both +5400000000 (eight without country code) and +545049000000 (ten without country code). (nine throws `TOO_SHORT` though.

**Comment by lararennie** [comment]
That's not how you add an area code.
You add an area code by putting 11 in it, for Buenos Aires, for instance.
http://libphonenumber.appspot.com/phonenumberparser?number=%2B54+11+50490000+

Is this a mobile, or a fixed-line number? What province is it for?

**Comment by keghani** [comment]
We don't have enough information to fix this, it's unclear what the issue is.
Please follow @lararennie's guidelines to provide the information we need if you reopen this issue.
