### ISSUE TITLE
Validation issue with +630956138XXXX (63) & +63956138XXXX (63)

### ISSUE THREAD

**Issue by bargangilo** [googlei18n/libphonenumber#1710]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 63

Example number(s) affected ("+1 555 555-1234"): +63 0 956 138 1234, +63 956 138 1234

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +63 0 956 138 XXXX, +63 956 138 XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): Number has been changed to avoid publicly posting but the issue is still persistent with valid registered phone number. 

[link to demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B6309561381234&country=63)

[link to demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B639561381234&country=63)

**Comment by penmetsaa** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. The number is already considered as a valid Philippines mobile number by libphonenumber. See the [demo output](https://libphonenumber.appspot.com/phonenumberparser?number=%2B6309561381234&country=63) that you have already mentioned. Please reopen if you think that the demo results are not right.
