### ISSUE TITLE
Change Java Util Logging to SLF4J 

### ISSUE THREAD

**Issue by hth** [googlei18n/libphonenumber#1713]
Currently library is using Java Util Logging. Is there a plan to move to SFL4J?

**Comment by mizuni** [comment]
Hi,

Apologies for the delay. No, we currently don't have any plans to move to SFL4J.

To help us understand this a bit better, what's your current issue with java.util.logging that makes you want to know about plans for moving to SFL4J?

**Comment by hth** [comment]
No worries. Its just that I would like to have the control to turn On and Off logging based on the environment.

**Comment by mizuni** [comment]
OK, thanks for additional context!
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
