### ISSUE TITLE
Some Lebanese phone numbers are invalid.

### ISSUE THREAD

**Issue by b0b-k** [googlei18n/libphonenumber#1715]
The new Lebanese phone numbers that start with 78,79 and 82 return as invalid yet they must be valid.
Here's an example of a valid phone number: 96171123456
![screen shot 2017-05-02 at 3 21 01 pm](https://cloud.githubusercontent.com/assets/9265278/25617560/85c18a5c-2f4b-11e7-8786-44464c0eb3bd.png)

and Here's an example of another valid phone number: 96178123456 - but it is being returned as invalid

![screen shot 2017-05-02 at 3 21 18 pm](https://cloud.githubusercontent.com/assets/9265278/25617581/a9e7edb8-2f4b-11e7-8027-a934a0569d09.png)

Thanks for your efforts.

**Comment by SumathiSundara** [comment]
We can't connect to + 96178123456.

We are not able to find  781 digit numbers with this prefix online.

Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by b0b-k** [comment]
The prefix is 78 and not 781.
Here's the full list : https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000770002PDFE.pdf
found on the international telecommunication union: http://www.itu.int/oth/T0202000077/en

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
We support 10 digit long numbers for the prefix 78 http://libphonenumber.appspot.com/phonenumberparser?number=7812345&country=LB  while the specified number is 11 digits long.

Here is our official evidence: https://www.itu.int/dms_pub/itut/oth/02/02/T02020000770002PDFE.pdf

I'll close this as it's not an issue with the library. Please consider joining the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
