### ISSUE TITLE
Validation issue with 016-23299692 (MY)

### ISSUE THREAD

**Issue by ElvantoStewart** [googlei18n/libphonenumber#1724]
Country/region affected (e.g., "US"): MY

Example number(s) affected ("+1 555 555-1234"): 016-23299692

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 01Y-ZXXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[Malaysian Numbering and Electronic Addressing Plan (NEAP)](https://www.mcmc.gov.my/skmmgovmy/media/General/pdf/MCMC_NEAP-2016_3.pdf)

In particular Figure 9.1 

![screen shot 2017-05-04 at 10 07 11 am](https://cloud.githubusercontent.com/assets/11205211/25686432/7b5a0ce4-30b1-11e7-96ce-bc50047b04b6.png)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=016-23299692&country=MY)

According to the linked documents, the number provided should indeed match the required format.

```
016-23299692
01Y-ZXXXXXXX
```

**Comment by SumathiSundara** [comment]
We can’t connect to +601623299692

We support 9 digit long numbers for the prefix 16 while the specified number is 10 digits long.

RAEX tool also only has 9 digit numbers for prefix 16. Carrier: Digi (https://en.wikipedia.org/wiki/Digi_Telecommunications).

We are not able to find 10 digit numbers with this prefix online.

Please share any working numbers or evidence for this specific number to be assigned that you may have like details of the operator provided SIMs / numbers in this range? E.g. the SIM package which lists the number. Websites  (e.g. for a business) which list a telephone number in this range would be useful. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
We haven't received a response from you yet about evidence for this specific number to be assigned.
Would it be possible for you to provide an update in order for us to move forward with fixing this issue?

**Comment by ElvantoStewart** [comment]
Feel free to close for now - I'm awaiting verification of the phone number.

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
