### ISSUE TITLE
New Sierra Leone Area Code

### ISSUE THREAD

**Issue by knappador** [googlei18n/libphonenumber#1725]
http://libphonenumber.appspot.com/phonenumberparser?number=232+80+123456&country=SL

I've been informed that 80 is a valid mobile area code (123456 placeholder) but we can't use any numbers from there.

**Comment by penmetsaa** [comment]
@knappador ,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 8.5.0
http://libphonenumber.appspot.com/phonenumberparser?number=232+80+123456&country=SL
