### ISSUE TITLE
Validation issue with +947 542 20XXXX

### ISSUE THREAD

**Issue by pravmahe** [googlei18n/libphonenumber#1732]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): Israel

Example number(s) affected ("+1 555 555-1234"): +947 542 20XXXX, +947 542 20XXXX, +947 546 57XXXX, +947 538 28XXXX, +947 549 25XXXX

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): NA

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B919970951357)

**Comment by kkeshava** [comment]
Hi,
 
Thank you for taking the time to improve libphonenumber!
 
Would you please recheck the number given? Israel's country code is +972 and not +947. In fact +947 is not assigned to any country but +94 is assigned to Sri Lanka. If you meant +972 542 20XXXX then we are already supporting all those ranges, see the[demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B972542201234)

**Comment by kkeshava** [comment]
Hi,
This issue is blocked on your or other GitHub contributors' input. Could you please respond to the question addressed in comment 2. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
