### ISSUE TITLE
Voip vs. Mobile

### ISSUE THREAD

**Issue by daveharig** [googlei18n/libphonenumber#1733]
Hi,
Using the prefix is it possible with this library to distinguish between major mobile carriers in each country vs. landline carriers and VOIP providers?

**Comment by kkeshava** [comment]
@daveharig,
Thank you for using libphonenumber!

Libphonenumber can not provide the category / carrier details based on the prefix. You need to provide complete number to know whether it is valid / not, category, carrier..etc. 
We provide carrier details for only mobile numbers.
More details on these APIs in [javadoc of PhoneNumberUtil.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java)

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
