### ISSUE TITLE
Upcoming area code 332 not supported

### ISSUE THREAD

**Issue by ll-david-le** [googlei18n/libphonenumber#1740]
According to NANPA [https://www.nationalnanpa.com/enas/plannedNpasNotInServiceReport.do], the New York area code 332 is planned to come into service on June 10th, 2017.  Currently libphonenumber doesn't support this area code yet.  It would help to get support for this area code before it comes into service so it doesn't cause any interruptions.

**Comment by kkeshava** [comment]
@ll-david-le,
Thanks for taking the time to improve libphonenumber!
We are already tracking this issue from our end. We'll update this thread when it's released.

**Comment by penmetsaa** [comment]
This is fixed in release 8.5.0
https://libphonenumber.appspot.com/phonenumberparser?number=%28332%29+234+0000&country=US
