### ISSUE TITLE
Validation issue with 112 (BR)

### ISSUE THREAD

**Issue by jlasley** [googlei18n/libphonenumber#1744]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): BR

Example number(s) affected ("+1 555 555-1234"): 112

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +55 XX XXXX-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): short code

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!**

The 112 emergency short code should return as a  isValidShortNumber(): True and isValidShortNumberForRegion() : True.
112 is a valid short code in Brazil that redirects to 190.

https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil#Public_utility 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=112&country=BR)

112 should return the same results as 911 currently does. 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=911&country=BR)

**Comment by penmetsaa** [comment]
@jlasley ,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is fixed in release 8.5.0
http://libphonenumber.appspot.com/phonenumberparser?number=911&country=BR

**Comment by penmetsaa** [comment]
http://libphonenumber.appspot.com/phonenumberparser?number=112&country=BR

**Comment by jlasley** [comment]
Thanks for the fix.
