### ISSUE TITLE
'iw' -> 'he'

### ISSUE THREAD

**Issue by doublex** [googlei18n/libphonenumber#1746]
The iso-639 code for hebrew is 'he' ('iw' = old code).
The folder in 'resources/geocoding/iw' should be renamed to 'resources/geocoding/he'

**Comment by lararennie** [comment]
True, but the Android and Java official language code is iw.

We should document the exceptions better in parts of the API that take a
string.

What problem is this causing you?



17. mai 2017 3.59 p.m. skrev "doublex" <notifications@github.com>:

**Comment by lararennie** [comment]
Closing this now because we have improved documentation, in 8.5.2 (https://github.com/googlei18n/libphonenumber/pull/1776 )
