### ISSUE TITLE
Validation issue with number starting with 7 for India

### ISSUE THREAD

**Issue by prathameshtal** [googlei18n/libphonenumber#1747]
returning false at line
`getNumberTypeHelper(nationalSignificantNumber, metadata) != PhoneNumberType.UNKNOWN`

**Comment by penmetsaa** [comment]
@prathameshtal 
Thank you for taking the time to improve libphonenumber!
We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by prathameshtal** [comment]
"+" symbol was missing in my input. Thanks @penmetsaa
