### ISSUE TITLE
Overseas french departments

### ISSUE THREAD

**Issue by micapi** [googlei18n/libphonenumber#1748]
Were are using the lib for validating phone numbers input.

There seems to be a problem with the validation of phone numbers from overseas french departments.

One example that have been brought to me is +596696600024 (which is from french Guiana). The phone number is considered invalid but according to the ARCEP it is well affected to a phone operator.

I read some documentation online (mostly on the arcep website) and i've updated some rules on my side.

Is an update planned for supporting correctly this regions ?

For information here is what i have now in `PhoneNumberMetaData.xml` for country codes 594, 590 and 596 :

```xml
    <territory id="GF" countryCode="594" internationalPrefix="00" nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <fixedLine>
        <nationalNumberPattern>
          594(?:
          0[0-9]|
          1[01]|
          2[0-9]|
          3[0-9]|
          4[0346-9]|
          5[6-9]|
          6[0-3]|
          9[014]
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>594101234</exampleNumber>
      </fixedLine>

      <mobile>
        <nationalNumberPattern>
          694(?:
          [01249][0-9]|
          3[0-48]|
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>694201234</exampleNumber>
      </mobile>

    </territory>

    <territory id="GP" countryCode="590" internationalPrefix="00" mainCountryForCode="true" nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      
      <fixedLine>
        <nationalNumberPattern>
          590(?:
          0[0-9]|
          1[0123]|
          2[0-9]|
          3[01289]|
          4[01246-9]|
          5[0-9]|
          6[0189]|
          7[07]|
          8[0-9]|
          9\d
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>590201234</exampleNumber>
      </fixedLine>

      <mobile>
        <nationalNumberPattern>
          690(?:
          [0-9]\d
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>690301234</exampleNumber>
      </mobile>

    </territory>

    <territory id="MQ" countryCode="596" internationalPrefix="00" nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">

      <fixedLine>
        <nationalNumberPattern>
          596(?:
          0[0-7]|
          10|
          2[78]|
          3[05-9]|
          4[01246-8]|
          [5-7]\d|
          8[09]|
          9[4-8]
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>596301234</exampleNumber>
      </fixedLine>

      <mobile>
        <!-- 6965[2-4] were found in use online. -->
        <nationalNumberPattern>
          696(?:
          [0-4789]\d|
          5[0-6]|
          6[0-4]
          )\d{4}
        </nationalNumberPattern>
        <possibleLengths national="9"/>
        <exampleNumber>696201234</exampleNumber>
      </mobile>

    </territory>
```

**Comment by penmetsaa** [comment]
@micapi,

Thanks for using libphonenumber!

596 is country code of Martinique region. You have mentioned "+596696600024 (which is from french Guiana)" but are you reffering to Martinique region only here (?). Mobile numbers in Martinique starts with 696 whereas French Guiana mobile numbers start with 694. Please let us know if you are reffering to French Guiana only.

We were able to connect to number +596 696 60 00 24. Based on these details we will support 696 60 mobile ranges in Martinique region in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
@micapi,
Support for 696 60 mobile ranges in Martinique region in added in release 8.5.0
We are not accepting pull requests for such metadata updates at this time. See
our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

Please raise a new issue to fix the other issues (that you have fixed in above code).
