### ISSUE TITLE
+14141110011 wrong isValidNumber() result

### ISSUE THREAD

**Issue by cristianmagurean** [googlei18n/libphonenumber#1750]
+14141110011 is a valid Milwaukee number, but the isValidNumber() returns false

**Comment by SumathiSundara** [comment]
We can't connect to +14141110011. Did you have a typo?

We already support +1 414[2-9] phone numbers in US while the specified number is +1 4141.
We are not able to find +1 4141 with this prefix online.

Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by cristianmagurean** [comment]
Hi Sumathi

You are right. thanks
Still have a list of numbers for that the library returns area code = 0:
4570143064, 4589870902, 6477880117, 13462310292, 14378869111,
18002099202, 18442391552, 18552759006, 18662095866, 18772501561,
18882024955, 31852084920, 34911236750, 43720815479, 61879057085,
302111980723, 448000885036, 611300133085, 611800728898





[image: Aurea] <http://www.aurea.com/>

*Cristian Magurean | *Software Engineering Manager
cristian.magurean@aurea.com | Skype: cmagurean
www.aurea.com

**Comment by lararennie** [comment]
Can you please read our guidelines? We need you to check the demo link for these numbers.

Also I think you need to read the javadoc of the methods you are calling. You are talking about "area code" which makes me think you are trying to use a method like getLengthOfGeographicalAreaCode. This explains that it is only for *geographical* numbers. A toll-free number like +18002099202 is NOT geographical and doesn't have one. Most if not all of these numbers look non-geographical to me.

You might want to use getLengthOfNationalDestinationCode.

Closing this as WAI. If you indeed have numbers that are valid that we don't think are, please read the guidelines Sumathi linked and file a bug about them (ideally one bug per country)
