### ISSUE TITLE
Meta data: +1 671-480-xxxx (Guam) should be validate

### ISSUE THREAD

**Issue by dryice** [googlei18n/libphonenumber#1752]
According to https://www.area-codes.com/exchange/exchange.asp?npa=671&nxx=480, this is a valid area code. E.g, a working number +1 671-480-6765

On 8.4.3, is_valid_number returns False. 

Please update the meta data. Thanks!

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by dryice** [comment]
Thanks!

**Comment by kkeshava** [comment]
Fixed in release 8.5.1.
