### ISSUE TITLE
Issues with real number 852-307xxxxx

### ISSUE THREAD

**Issue by treeicnliu** [googlei18n/libphonenumber#1760]
hi,

for number 852-30794461 it shows invalid number.

**Comment by kkeshava** [comment]
@treeicnliu,
Hi,
Thank you for using libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.
 
We can't connect to +852-30794461.
 
As per Hong Kong official numbering plan http://www.ofca.gov.hk/filemanager/ofca/en/content_311/no_plan.pdf, prefix 307xxxxx are Access codes used for External telecommunications services. Currently we are not supporting these numbers. To support these numbers we need more information. We would like to know what type these numbers are: are they used for mobile phones, or customer service centres, or are they normal home fixed-line numbers? 
 
We are unable to find any working numbers online. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by treeicnliu** [comment]
@kkeshava
Hi,
Thanks for your reply. It's the calling number displayed on the phone. According to the information you provided, perhaps it is not a working number.
