### ISSUE TITLE
Using trunk code from outside the contry returns isValidNumber

### ISSUE THREAD

**Issue by RodrigoCapa** [googlei18n/libphonenumber#1764]
Hello,

First, correct me if I haven't understood the behaviour of isValidNumber. Shouldn't it be true when the number can be reached from the region if dialed as the given number?. I've searched on references about behaviour of isValidNumber but without success.

Given the case that isValidNumber means that the number it's reachable from a region, I've found that numbers with trunk code called from another country returns true, but this it's not right, they can't be reached.

ie:
http://libphonenumber.appspot.com/phonenumberparser?number=004402034912345&country=ES
The number can't be reached from at least three Spanish providers.

The returned formatted numbers are corrected and valid to be called, but this doesn't imply that the value of the parameter number can be used as it's given.

If this is the intended behaviour,  I suggest to expand the documentation about isValidNumber, specifying that it's true whenever the number it's recognised as valid but doesn't mean that can be called as the given parameter.

Cheers,
Rodrigo

---------------
Country/region affected (e.g., "US"): ES
Example number(s) affected ("+1 555 555-1234"): 004402034912345
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line
The cost, if applicable ("toll-free", "premium rate", "shared cost"):

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=004402034912345&country=ES)

**Comment by lararennie** [comment]
No. isValidNumber doesn't take in a region parameter, it doesn't care where it is being dialled from. What is happening is that "parse" is called, and this changes the number into a region-neutral number, then "isValidNumber" is called on that.

The javadoc for both methods tries to convey this: for example "It only
   * verifies whether the parsed, canonicalised number is valid: not whether a particular series of
   * digits entered by the user is diallable from the region provided when parsing. For example, the
   * number +41 (0) 78 927 2696 can be parsed into a number with country code "41" and national
   * significant number "789272696". This is valid, while the original string is not diallable."

What particular change would you suggest to make this clearer?

Two other related points:
- we have canBeInternationallyDiallable to cover the case of numbers that are valid in-country but not externally
- https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md discusses what it means for a number to be valid, which means that for some numbers we say they are valid but they won't connect to an end user.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
