### ISSUE TITLE
request: flow types

### ISSUE THREAD

**Issue by rbalicki2** [googlei18n/libphonenumber#1765]
Hello,
I'd love for there to be flow types for this library! Thank you.
Typescript def files are cool too, since I should be able to convert those relatively painlessly.

-R

**Comment by lararennie** [comment]
Thanks for your feedback!

We already use Closure type annotation and the lint and compiler tools so won't be switching to another framework at this point. However there are a few other JS ports out there - not sure what they are doing but maybe one uses typescript or Flow?

Closing this but feel free to join the discussion group of you want to ask the community if they have solutions around this.
