### ISSUE TITLE
why print 0 for first time with national number

### ISSUE THREAD

**Issue by champrocks3190** [googlei18n/libphonenumber#1766]
i m retriving contact book i want to check national number with adding implicitely (country code example : 61,91 ) according to country region of number checking by method isValidNumberForRegion() BUT IT gives 0 for first time ., 

i want to check for each region code and nation number with adding country dial code 61,91 if true i want to add ,it to database else not so each number will have right dial code added and identity of number remain same . 

if im in india i want to add number of Australian user with  national number it should ad with 61 is it posible with this method im explaining? 

![screen shot 2017-05-31 at 11 55 21 pm](https://cloud.githubusercontent.com/assets/11179802/26647816/297bef6a-465e-11e7-9132-d4dc076b51d1.png)
![screen shot 2017-05-31 at 11 56 18 pm](https://cloud.githubusercontent.com/assets/11179802/26647818/29d4b37a-465e-11e7-991c-5c6ebbfc31a7.png)
![screen shot 2017-06-01 at 12 00 13 am](https://cloud.githubusercontent.com/assets/11179802/26647817/29d40056-465e-11e7-892e-08778c170b4c.png)

**Comment by lararennie** [comment]
Hi,

I'm not sure quite what you are asking, but this code has some problems.
a) The same number will be valid in many different regions. What do you want to do when something is valid in more than one country - which will you assume?
b) You don't want to drop the country code when formatting, or you will get bogus results. This will make the number not diallable in most cases - it won't know whether to have the "0" there when dialling or not for instance.
c) Your code snippet doesn't call isValidNumberForRegion anyway?

If you are in India, and you want to add an Australian number, you can either parse the number in national format with AU as the region, or parse it with "+61" at the front. If you want to have a number that is diallable from India, you can either call formatOutOfCountryCallingNumber, or you can format the number in INTERNATIONAL format.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
