### ISSUE TITLE
UK Ofcom-unallocated-TEST-mobile numbers render INVALID in v8.4.3

### ISSUE THREAD

**Issue by robertr0** [googlei18n/libphonenumber#1768]
they used to work in v7.0.2, so regression to me...

07700 900000 - 07700 900999

resource:
https://www.ofcom.org.uk/phones-telecoms-and-internet/information-for-industry/numbering/numbers-for-drama
=> expand 'Notes' section

**Comment by giggsey** [comment]
I had a question about these Drama numbers back in #341. That might help answer your question.

Personally, I would like to see them included, and used as example numbers. It's a shame to use one of these drama numbers somewhere, and not have it format etc. because it's 'invalid'.

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.
 
As mentioned in #341, we will not be supporting unallocated numbers as they will not be allocated for live telephone service and also it's not worth altering the metadata to that level of granularity. However, invalid numbers should be parsed okay and formatting works for these unallocated drama numbers as well.
 
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
