### ISSUE TITLE
PhoneNumber hasCountryCode method incorrect

### ISSUE THREAD

**Issue by davidozersky** [googlei18n/libphonenumber#1771]
Hello,  

I'm using the hasCountryCode method to determine whether it's possible to extract a country code.  I have a number that starts with 647 in it's area code.  It's only 10 digits long, yet it reads the first 2 digits of the area code as a country code. 

What's going on here?

**Comment by penmetsaa** [comment]
@davidozersky,

Thank you for using libphonenumber!

The way the number is interpreted depends on what the default country was that you passed in when calling "parse". Can you share the exact arguments you passed in to [PhoneNumberUtil.parse()](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3039) API or a snippet of code ?

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by davidozersky** [comment]
Hello,

Thanks for the quick reply, I've added the method code below. We're setting
the default country to blank to avoid the scenario where the user has the
wrong region set up on their device; and therefore gets the wrong result.
We're trying to use the device SIM card to get the region instead.  The
problem is with a number that starts with 647 area code, (which is a
Toronto area code).  hasCountryCode && getCountryCode returns with 64,
which is a New Zealand country code.

One possible solution I'm considering is getting the SIM card region, and
then setting it as the default region before we start parsing the number.
Does that seem right?

Thank you,
David

    private String analyzeNumberForCCAndNational(final String number) {
     String cC;
     String areaCodeNational;

     PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
     Phonenumber.PhoneNumber processedNumber;


     try {
      // Try to parse the number as passed in. Depending on what the user
has entered and
      // country of the number this usually works. The default region "" is
sent in as we
      // can't use the locale to set the country, we don't know what it
will be and some
      // users do not change from the default "US" in some cases. "" is
indicating parsing.
      processedNumber = phoneNumberUtil.parse(number, "");
     } catch (final NumberParseException e) {

      // Error in parsing, the country code is invalid, important as BBM
needs the country
      // code to match contacts.
      if (e.getErrorType() ==
NumberParseException.ErrorType.INVALID_COUNTRY_CODE) {
       if (number.startsWith("#") || number.startsWith("*")) {
        return "";
       }

       //Remove
       final TelephonyManager tm = 

       try {
        // Prefix the "+", this will attempt to parse the number in the
E164 analyzeNumberForCCAndNational, as
        // some numbers (as found out in field) do not have the "+" in the
contact card.
        // This should cover the case where the number is valid, but the
util cannot parse
        // due to the "". Note, on the construction of this class, the e164
is pulled from
        // the local db, but android removes "+" in some cases.
        final String plusNumber = "+" + number;
        processedNumber = phoneNumberUtil.parse(plusNumber, "");
       } catch (final NumberParseException ignore) {
        try {
         // Attempt to use the SIM to get the country code for partial
numbers
         String CC = tm.getSimCountryIso();
         processedNumber = phoneNumberUtil.parseAndKeepRawInput(number, CC);
        } catch (final NumberParseException ignore2) {
         Ln.w("Could not parse: " + ignore2.getErrorType());
         processedNumber = null;
        }
       }

      } else {
       Ln.w("The number is not valid");
       return "";
      }
     }

     if (processedNumber != null) {
      boolean hasCC = processedNumber.hasCountryCode();
      boolean hasNational = processedNumber.hasNationalNumber();

      cC = hasCC ? Integer.toString(processedNumber.getCountryCode()) : "";
      areaCodeNational = hasNational ?
Long.toString(processedNumber.getNationalNumber()) : "";

      // If we have everything analyzeNumberForCCAndNational and send.
      if (hasCC && hasNational) {
       return cC + "-" + areaCodeNational;
      }

      if (hasNational) {
       // Have a a number, but know CC code, so will attempt to get one.
       if (Alaska.getInstance() != null) {
        final TelephonyManager tm = 
        String CC = tm.getSimCountryIso();
        return CC + "-" + areaCodeNational;
       }
      }
     } else {
      Ln.w("The phone number is not valid");
     }

     return "";
    }

**Comment by davidozersky** [comment]
Hello, 

Thanks for the quick reply, I've added the method code below. We're setting the default country to blank to avoid the scenario where the user has the wrong region set up on their device; and therefore gets the wrong result.  We're trying to use the device SIM card to get the region instead.  The problem is with a number that starts with 647 area code, (which is a Toronto area code).  hasCountryCode && getCountryCode returns with 64, which is a New Zealand country code. 

One possible solution I'm considering is getting the SIM card region, and then setting it as the default region before we start parsing the number.  Does that seem right? 

Thank you, 
David 
`
    private String analyzeNumberForCCAndNational(final String number) {
     String cC;
     String areaCodeNational;

     PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
     Phonenumber.PhoneNumber processedNumber;


     try {
      // Try to parse the number as passed in. Depending on what the user has entered and
      // country of the number this usually works. The default region "" is sent in as we
      // can't use the locale to set the country, we don't know what it will be and some
      // users do not change from the default "US" in some cases. "" is indicating parsing.
      processedNumber = phoneNumberUtil.parse(number, "");
     } catch (final NumberParseException e) {

      // Error in parsing, the country code is invalid, important as BBM needs the country
      // code to match contacts.
      if (e.getErrorType() == NumberParseException.ErrorType.INVALID_COUNTRY_CODE) {
       if (number.startsWith("#") || number.startsWith("*")) {
        return "";
       }

       //Remove
       final TelephonyManager tm = 

       try {
        // Prefix the "+", this will attempt to parse the number in the E164 analyzeNumberForCCAndNational, as
        // some numbers (as found out in field) do not have the "+" in the contact card.
        // This should cover the case where the number is valid, but the util cannot parse
        // due to the "". Note, on the construction of this class, the e164 is pulled from
        // the local db, but android removes "+" in some cases.
        final String plusNumber = "+" + number;
        processedNumber = phoneNumberUtil.parse(plusNumber, "");
       } catch (final NumberParseException ignore) {
        try {
         // Attempt to use the SIM to get the country code for partial numbers
         String CC = tm.getSimCountryIso();
         processedNumber = phoneNumberUtil.parseAndKeepRawInput(number, CC);
        } catch (final NumberParseException ignore2) {
         Ln.w("Could not parse: " + ignore2.getErrorType());
         processedNumber = null;
        }
       }

      } else {
       Ln.w("The number is not valid");
       return "";
      }
     }

     if (processedNumber != null) {
      boolean hasCC = processedNumber.hasCountryCode();
      boolean hasNational = processedNumber.hasNationalNumber();

      cC = hasCC ? Integer.toString(processedNumber.getCountryCode()) : "";
      areaCodeNational = hasNational ? Long.toString(processedNumber.getNationalNumber()) : "";

      // If we have everything analyzeNumberForCCAndNational and send.
      if (hasCC && hasNational) {
       return cC + "-" + areaCodeNational;
      }

      if (hasNational) {
       // Have a a number, but know CC code, so will attempt to get one.
       if (Alaska.getInstance() != null) {
        final TelephonyManager tm = 
        String CC = tm.getSimCountryIso();
        return CC + "-" + areaCodeNational;
       }
      }
     } else {
      Ln.w("The phone number is not valid");
     }

     return "";
    }
`

**Comment by lararennie** [comment]
If you add the + then this is unambiguously a NZ number.

What you are trying to do doesn't work. The SIM card region sounds a much
better idea, won't work 100% of the time (it's possible someone has
overseas numbers in national format and just changes their sim card to dial
them for instance) but it's a pretty good estimate.

2017-06-06 16:52 GMT+02:00 davidozersky <notifications@github.com>:

**Comment by sijovijayan** [comment]
This is a list of supported countries 
http://phpinterviewquestions.co.in/blog/ionic/googles-libphonenumber-library-supported-country-list
