### ISSUE TITLE
Validation issue with Indian numbers 9980-XXXXX

### ISSUE THREAD

**Issue by sabrinaj** [googlei18n/libphonenumber#1772]
Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 998000000

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +91 - 9980 - XXXXX

See
http://www.searchyellowdirectory.com/reverse-phone/91998000000/ 
https://ind.areacodebase.com/taxonomy/term/25052

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=998000000&country=IN)

**Comment by kkeshava** [comment]
@sabrinaj,
Thank you for using libphonenumber!
For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We can't connect to +91 998000000.
Indian Mobile numbers are of 10 digits but the example number mentioned by is 9 digits. The evidence provided is also contradictory, the first site has 9 digits and the second site has 10 digits. We have not received any information about the 9 digit mobile numbers being made available in India. Please provide any working numbers or official evidence that you may have to support 9 digit Mobile numbers. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

We are already supporting 10 digit 99800 range, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=9980000000&country=IN).

**Comment by kkeshava** [comment]
@sabrinaj,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 9 digit mobile numbers are valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
