### ISSUE TITLE
Validation issue with 130000724 (AU)

### ISSUE THREAD

**Issue by valerio-brew** [googlei18n/libphonenumber#1781]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): AU

Example number(s) affected ("+1 555 555-1234"): 130000724

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): toll-free

The cost, if applicable ("toll-free", "premium rate", "shared cost"):  toll-free

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=130000724&country=AU)

As part of the company handling this phone number I can guarantee the number is valid.

**Comment by penmetsaa** [comment]
Hi,
 
Thank you for taking the time to improve libphonenumber!
 
We can't connect to +61 1300 00724.
 
We support 10 digit long numbers for the prefix 1300 while the specified number is 9 digits long.
https://libphonenumber.appspot.com/phonenumberparser?number=1300007243&country=AU
 
As per the official numbering plan of Australia all 1300 range numbers are 10 digit in length and these are standard rate.
https://www.thenumberingsystem.com.au/#/number-register/search
 
Closing this as WAI for now; if you would like to reopen it, please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).
