### ISSUE TITLE
Wrong invalidation of Nigerian numbers

### ISSUE THREAD

**Issue by biodunalfet** [googlei18n/libphonenumber#1782]
Nigerian numbers that start with 0701 xxxx xxx, 0902 xxxx xxx, 0903 xxxx xxx, 0905 xxxx xxx, 0908 xxxx xxx & 0909 xxxx xxx are marked as invalid by this library. Here's evidence to show these are valid numbers http://ncc.gov.ng/documents/652-national-numbering-plan-mobile-number-allocations/file

**Comment by penmetsaa** [comment]
@biodunalfet 

Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
