### ISSUE TITLE
Senegalese phone number not recognized

### ISSUE THREAD

**Issue by achiang** [googlei18n/libphonenumber#1783]
*   Country: Senegal
*   Example number(s) and/or range(s): +22177623745
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: observed in the wild
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B22177623745&country=SN

I do not have authoritative evidence; however, this number came directly from a mobile money provider in Senegal (Wari), and so we know that numbers with these prefixes do exist in the wild.

**Comment by penmetsaa** [comment]
@achiang,
 
Thank you for taking the time to improve libphonenumber!
 
We can't connect to +221 776 23745.
 
We support 9 digit long numbers for the prefix 776 while the specified number is 8 digits long.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B221+776+237450
 
As per the official numbering plan of Senegal all 776 mobile range numbers are 9 digit in length.
http://www.artpsenegal.net/images/documents/document_Structure_plan_national_de_numerotation_PNN_2012_231.pdf

Not able find any working numbers online. Closing this as WAI for now; if you would like to reopen it, please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).
