### ISSUE TITLE
PhoneNumberOfflineGeocoder not available?

### ISSUE THREAD

**Issue by arya6000** [googlei18n/libphonenumber#1784]
I'm using libphonenumber within Java using the following maven dependency

```
		<dependency>
			<groupId>com.googlecode.libphonenumber</groupId>
			<artifactId>libphonenumber</artifactId>
			<version>8.5.1</version>
		</dependency>
```

But I can not use PhoneNumberOfflineGeocoder. Is PhoneNumberOfflineGeocoder not included?

**Comment by lararennie** [comment]
It's a separate dependency.
https://mvnrepository.com/artifact/com.googlecode.libphonenumber/geocoder/2.72
 <dependency>
      <groupId>com.googlecode.libphonenumber</groupId>
      <artifactId>geocoder</artifactId>
      <version>2.72</version>
    </dependency>

And you'll need the prefixmapper as well (also 2.72)
