### ISSUE TITLE
libphonenumber-6.2.2.jar worked for Germany 12 digit mobile number, latest jar does not support.

### ISSUE THREAD

**Issue by onkarshamra** [googlei18n/libphonenumber#1789]
libphonenumber-8.5.0 jar does not support to validate Germany 12 digit mobile number.
whereas libphonenumber-6.2.2.jar having the support for Germany 12 digit mobile number validation.

latest jar should support what libphonenumber-6.2.2.jar support.

This issue should be fix.

**Comment by onkarshamra** [comment]
libphonenumber-8.5.0 jar does not support to validate Germany 12 digit mobile number.
whereas libphonenumber-6.2.2.jar having the support for Germany 12 digit mobile number validation.

latest jar should support what libphonenumber-6.2.2.jar support.

This issue should be fix.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Actually, I think this is working as intended.

We update the metadata frequently, and it is expected that different versions will validate different ranges.

@onkarshamra Did you mean a specific range that we should be validating now that we aren't? For that yes, we would need more information, see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Basically: the latest jar doesn't have to support what libphonenumber-6.2.2.jar supports.

**Comment by onkarshamra** [comment]
Thanks,  actually 49+4digit+6 digit their certain series for 4digit, using that libphonenumber_8.5.1.jar validation not working

**Comment by keghani** [comment]
Could you let us know which ranges in more detail? And provide evidence that they should be considered valid in the latest jar?
8.5.1 isn't the latest jar anymore.

Please see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md), they have all the details about how to confirm whether something is an issue. Without this information it's infeasible for us to add the new ranges.

**Comment by SumathiSundara** [comment]
We update the metadata frequently, and it is expected that different versions will give different results.

If there is a specific range that you think we should validate and don't do so in the latest release, please file an issue with all the details. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to determine whether something is a real issue, and the details we need to be able to fix it.

**Comment by fnordfish** [comment]
I'd like to reactivate this issue and point to the official "Numbering plan for the numbering space for public telecommunications" issued by the _Bundesnetzagentur_ which allows a total of 13 digits for national numbers.

English: https://www.bundesnetzagentur.de/SharedDocs/Downloads/EN/Areas/Telecommunications/Companies/NumberManagement/numbering_space/NP_numbering_space_2016.pdf?__blob=publicationFile&v=1

German: https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/NP_Nummernraum.pdf?__blob=publicationFile&v=5

**Comment by keghani** [comment]
We do validate 13-digit national numbers in Germany: http://libphonenumber.appspot.com/phonenumberparser?number=4012345678901&country=DE

We also validate 12-digit national numbers in Germany (from the issue title): http://libphonenumber.appspot.com/phonenumberparser?number=401234567890&country=DE

Again, what ranges do you think we should support that we don't?
Please read the contribution guidelines to provide the details we need so we can quickly fix any issues.

**Comment by fnordfish** [comment]
Interesting. Sorry, here is an example based on a real number (not the actual thing) https://libphonenumber.appspot.com/phonenumberparser?number=%2B49157555511111&country=DE&geocodingLocale=de-DE

**Comment by SumathiSundara** [comment]
We can't connect to +49 157 555 511 111.

We support 11 digit long numbers for the prefix 157 while the specified number is 12 digits long.

We are not able to find 12 digit numbers with this prefix online.

Closing this as WAI; if you would like to reopen, please share any working
numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by keghani** [comment]
@fnordfish Maybe the actual number does not include the last digit?
Sometimes, depending on how you're connecting to a number, trailing digits are ignored and the number ends up reaching the same endpoint. See [our FAQ on this](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#but-my-dialled-number-connected-so-isnt-it-valid).

That doesn't make it valid by our definition.

We are validating that number without the last digit: http://libphonenumber.appspot.com/phonenumberparser?number=%2B49+157+555+511+11
