### ISSUE TITLE
Add support for +91-86698 number series

### ISSUE THREAD

**Issue by preeteshjain** [googlei18n/libphonenumber#1792]
*   Country: India
*   Example number(s) and/or range(s): 8669800000
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   Where or whom did you get the number(s) from: Personal number
*   Authoritative evidence (e.g. national numbering plan, operator announcement): [Letter](http://www.dot.gov.in/sites/default/files/MSC%20030417.pdf) from the DoT, Ministry of Communications, Government of India
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=8669800000&country=IN

**NOTE**: This number series has been allocated to _Reliance Jio, Maharashtra Circle_.

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in 
Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.5.2
