### ISSUE TITLE
Phone number not valid after upgrading to 8.5.1

### ISSUE THREAD

**Issue by anishtim** [googlei18n/libphonenumber#1794]
What 
- After upgrading our library to 8.5.1 , a certain phone number does not work and throws the error "Not a valid phone number"

Any reason why this may be happening ?

**Comment by kkeshava** [comment]
Hi,
Thank you for using libphonenumber!
We need more information to fix the issue. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
We update the metadata frequently, and it is expected that different versions will give different results.

If there is a specific range that you think we should validate and don't do so in the latest release, please file an issue with all the details. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to determine whether something is a real issue, and the details we need to be able to fix it.

**Comment by keghani** [comment]
Closing as it's not an issue. Please re-open if you respond so we're notified.
