### ISSUE TITLE
Letters in a number are valid?

### ISSUE THREAD

**Issue by obkdev** [googlei18n/libphonenumber#1798]
I am using c# port of this library, but am able to reproduce in the demo here:

**+4072d3800439**
http://libphonenumber.appspot.com/phonenumberparser?number=%2B4072d3800439

**+40721eeasd0**
http://libphonenumber.appspot.com/phonenumberparser?number=%2B40721eeasd0

Although this number can be parsed, I wouldn't expect that `Result from isValidNumber()` would be `true`

**Comment by kkeshava** [comment]
@obkdev
Thank you for using libphonenumber!
 
We have scenarios where phone numbers are alphanumeric for eg. 1800 MICROSOFT which is 1800 102 1100. Each character corresponds to specific number on the dialpad hence we parse and validate such phone numbers too.

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
