### ISSUE TITLE
French mobile phone starting by 07 are not matched

### ISSUE THREAD

**Issue by strokyl** [googlei18n/libphonenumber#1802]
Since 2010 we have mobile phone that can start by 07 instead of 06.

**Comment by kkeshava** [comment]
@strokyl,

Thank you for taking the time to improve libphonenumber! 
For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

As per French numbering plan https://www.arcep.fr/index.php?id=8146, we are actually supporting mobiles numbers which start with 07 (i.e ranges 073 to 079). To check the latest behavior for
yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B447624306466)(instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
Eg: http://libphonenumber.appspot.com/phonenumberparser?number=731234567&country=FR

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
