### ISSUE TITLE
Validation issue with +989991234567 (IR)

### ISSUE THREAD

**Issue by jy0tsna** [googlei18n/libphonenumber#1803]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IR

Example number(s) affected ("+1 555 555-1234"): +989991234567

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 
+98999
+98998

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): Iran has added two new prefixes since 1 month. Please add support for the same
+98999
+98998

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B989991234567&country=IR)

**Comment by kkeshava** [comment]
@jy0tsna,

Thank you for using libphonenumber!

We can't connect to +989991234567. 

As per the ITU doc https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000660005PDFE.pdf, we currently support only 998 10, 999 00, 999 11, 999 98 and 999 99. We need evidence to support remaining numbers in 998 and 999 range.

Please share any working numbers or any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by jy0tsna** [comment]
Thanks for explaination. Per your answer above, +989981001473 should return positive results, but it is not. It is a valid number. Could you please check and advise further ?

Thanks

**Comment by kkeshava** [comment]
@jy0tsna,
As mentioned in comment#2 we are already supporting prefix 99810 as Mobile in Iran. This is working correctly so please download the latest jar. 

The demo link was not fully updated in the last release that is the reason why it says invalid number.
We'll update this thread when the demo link is updated.

**Comment by kkeshava** [comment]
@jy0tsna,
Demo is updated now. Please see http://libphonenumber.appspot.com/phonenumberparser?number=%2B989981001473

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
