### ISSUE TITLE
Use animal-sniffer to ensure Java 1.5 compatibility

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#181]
Imported from [Google Code issue #181](https://code.google.com/p/libphonenumber/issues/detail?id=181) created by [candrewsintegralblue](https://code.google.com/u/114215788913124607468/) on 2012-08-19T03:59:46.000Z:

----
libphonenumber seems to strive for Java 1.5 compatibility, and it's really easy to accidentally use something from &gt; Java 1.5 and not find out about it until you actually test on a Java 1.5 VM.

animal-sniffer scans the output bytecode and checks to make only APIs you want to be used are used.

To use it, simply add this block to https://code.google.com/p/libphonenumber/source/browse/trunk/java/pom.xml :

            &lt;plugin&gt;
                &lt;groupId&gt;org.codehaus.mojo&lt;/groupId&gt;
                &lt;artifactId&gt;animal-sniffer-maven-plugin&lt;/artifactId&gt;
                &lt;version&gt;1.8&lt;/version&gt;
				&lt;executions&gt;
					&lt;execution&gt;
					    &lt;phase&gt;test&lt;/phase&gt;
						&lt;goals&gt;
							&lt;goal&gt;check&lt;/goal&gt;
						&lt;/goals&gt;
					&lt;/execution&gt;
				&lt;/executions&gt;
                &lt;configuration&gt;
                    &lt;signature&gt;
                        &lt;groupId&gt;org.codehaus.mojo.signature&lt;/groupId&gt;
                        &lt;artifactId&gt;java15&lt;/artifactId&gt;
                        &lt;version&gt;1.0&lt;/version&gt;
                    &lt;/signature&gt;
                &lt;/configuration&gt;
            &lt;/plugin&gt;

**Comment by keghani** [comment]
Closing as this does not seem to be an issue with the library. Consider joining [the discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

**Comment by keghani** [comment]
@lararennie corrected me, this might be related to the library :) Reopening.

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by keghani** [comment]
Fixed in 7.4.4, released last week.
