### ISSUE TITLE
update Telephone numbers in Iran

### ISSUE THREAD

**Issue by shahab331** [googlei18n/libphonenumber#1810]
Dear Colleagues,

this is to update below resource of this project:
 libphonenumber/resources/carrier/fa/98.txt

as I checked in that file you are getting list of number prefixes from below URL:
# Prefixes from http://en.wikipedia.org/wiki/%2B98.

also based on below ITU references you need to update resource file with new numbering plan of Iran: 
https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000660005PDFE.pdf

but the latest version of  "libphonenumber/resources/carrier/fa/98.txt" is not match with this URL "http://en.wikipedia.org/wiki/%2B98".

there are some new mobile ranges such as "+989981XXXXXX" which is not in the resource file.

how we should update it?
thanks for your support.

regards,
Shahab Eftekhari

**Comment by kkeshava** [comment]
Hi,
Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Sorry for the delay in responding to your query. Support for number “+989981XXXXXX” was given in 8.5.2 release.
We will be updating the carrier files for both en/98.txt and fa/98.txt based on wikipedia. We've accepted this issue and will fix this in an upcoming release.

**Comment by kkeshava** [comment]
Hi,
The number reported by you i.e +989981XXXXXX is MVNO numbers as per [wiki](https://en.wikipedia.org/wiki/Telephone_numbers_in_Iran#Mobile_phones). Sorry but we also need official evidence to support the carriers for these virtual numbers. We cannot support them only based on wiki.
Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
@shahab331,
As per ITU doc the only valid range in prefix 9981 is +9899810xxxxx. So as mentioned in second comment we are already supporting it. Please see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B989981012345).

However ITU does not provide carrier details. For updating the carrier for these we need official evidence. We cannot support them only based on wiki. Please share any official evidence you may have. See our guidelines.

**Comment by kkeshava** [comment]
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence to update carrier details. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
