### ISSUE TITLE
Android platform updates

### ISSUE THREAD

**Issue by alexcohn** [googlei18n/libphonenumber#1811]
On Android platform, libphonenumber is exposed to app developers through the [PhoneNumberUtils](https://developer.android.com/reference/android/telephony/PhoneNumberUtils.html) class. It is also used for essential system services.

I see that the library is [regularly updated](https://android.googlesource.com/platform/external/libphonenumber/+log/master). But these updates only effect new devices and system upgrades. I believe that locking the version of libphonenumber on older devices/systems not only cripples user experience, but also has security consequences.

Today, many apps are forced to include their own copy of libphonenumber because they cannot trust the system library to be up-to-date. But this practice requires regular updates (every two weeks, [more or less](https://github.com/googlei18n/libphonenumber/blob/master/release_notes.txt)) of the app just to keep in sync with the updates to region codes, etc. This may be a sugnificant burden on a indie developer. This may also cause extra data costs for end-users, who will need to update many apps frequently.

IMO, this can be managed better.

We already use [Google Play Services](https://developers.google.com/android), which is updated separately, system-wide, even for older versions of the OS. If up-to-date libphonenumber were made a part of Google Play Services, this would be a great improvement for both end-users and app developers.

**Comment by keghani** [comment]
HI @alexcohn,

Thanks for reporting, I agree this could be managed better. We're already tracking the Google Play Services idea at #1288. About the libphonenumber version no longer getting updated in older versions, perhaps you could file an issue with the relevant repository?

I'll close this and we'll keep tracking Google Play Services at the duplicate.
