### ISSUE TITLE
Email addresses with numbers in domain pass validation and return a number

### ISSUE THREAD

**Issue by bhavdeepsingh** [googlei18n/libphonenumber#1813]
*   Country: US
*   Example number(s) and/or range(s): dummyename@mba2012.hsk.edu
*   Number type ("fixed-line", "mobile", "short code", etc.): NA
*   For short codes, cost and dialing restrictions: NA
*   Where or whom did you get the number(s) from: NA (email address
*   Authoritative evidence (e.g. national numbering plan, operator announcement): NA
*   Link from demo (http://libphonenumber.appspot.com) showing error:  http://libphonenumber.appspot.com/phonenumberparser?number=dummyename%40mba2012.hsk.edu&country=US

**Comment by kkeshava** [comment]
@bhavdeepsingh,

Thanks for reporting this! This is actually addressed in our documentation:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits

As a result, we'll close this issue, but let us know if we may clarify the answer and update documentation.
