### ISSUE TITLE
Validation issue with 004-92-58-76-11 (FR)

### ISSUE THREAD

**Issue by ebonnot** [googlei18n/libphonenumber#1815]
Country/region affected (e.g., "US"): FR

Example number(s) affected ("+1 555 555-1234"): 004-92-58-76-11

Unexpected result : +492587611

Expected result : +33492587611

Notes : 
- input number has an unexpected leading zero (should have been 04-92-58-76-11)
- default country has been set to FR but unexpected result is identified from DE

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=004-92-58-76-11&country=FR&geocodingLocale=fr-FR)

**Comment by kkeshava** [comment]
@ebonnot,
Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

00 is the international prefix in France i.e it is used to dial the numbers outside the country. So while parsing the number, 00 is trimmed off by the library ex: To construct the E.164 format. The next two digits in the input i.e 49 matches with the country code for Germany hence the library will identify it as DE and not FR. 

So to check the validity it is recommended to give the number in national format i.e 04-92-58-76-11 or in E164 format i.e +33 4-92-58-76-11 only. Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=04-92-58-76-11&country=FR).

I'll close this as it's not an issue with the library. Please consider joining the discussion group if you'd like to discuss this further.
