### ISSUE TITLE
Validation issue with +38669699699

### ISSUE THREAD

**Issue by gregabostjancic** [googlei18n/libphonenumber#1817]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "SI"): 
Example number(s) affected ("+1 555 555-1234"): +38669699699
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):+38669XXXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

Link to Hofer Telekom contact page, where the demo phone was taken from
https://www.hot.si/kontakt-hot.html

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B38669699699)

**Comment by kkeshava** [comment]
@gregabostjancic ,
We are already supporting prefix 69[69] as Mobile in Slovenia. This is working correctly so please download and use the latest jar.
The demo link was not fully updated in the last release that is the reason why it says invalid number.
We'll update this thread when the demo link is updated.

**Comment by kkeshava** [comment]
@gregabostjancic ,
Demo is updated now. Please see http://libphonenumber.appspot.com/phonenumberparser?number=%2B38669699699

I'll close this as it's not an issue with the library. Please consider joining the discussion group if you'd like to discuss this further.
