### ISSUE TITLE
Validation issue with +380721036177

### ISSUE THREAD

**Issue by lugacom2015** [googlei18n/libphonenumber#1819]
Country/region affected (e.g., "SI"): UA
Example number(s) affected ("+1 555 555-1234"): +380721036081
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +38072XXXXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"): shared cost

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): announcement from mobile carrier 

IMPORTANT - anything posted here is made public. Read the guidelines first!

Link
http://lugacom.su/
Contacts
+38 (072) 103-61-77
+38 (072) 103-60-88
+38 (0642) 33-11-10

Link to Hofer Telekom contact page, where the demo phone was taken from
http://lugacom.su/dlya-biznesa/kontaktnaya-informatsiya_biz/

http://libphonenumber.appspot.com/phonenumberparser?number=%2B38072106081

**Comment by kkeshava** [comment]
@lugacom2015,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.6.0
