### ISSUE TITLE
Validation issue with +522211020232 (MX)

### ISSUE THREAD

**Issue by fallemand** [googlei18n/libphonenumber#1824]
Country/region affected: MX

Example number(s) affected: +52 221 1020 232

The phone number range(s) to which the issue applies ("+52 221 XXXX XXX): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line

This is a new areaCode that has been added to the one that exits right now (222).
We are looking for some documents, but you can try calling that number.

Place: Ciudad de Puebla, Estado de Puebla, Mexico.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=2211020232&country=MX)

**Comment by gsakhardande** [comment]
@fallemand Possible to add a PR?

**Comment by gauravsak** [comment]
@fallemand Possible to create a PR?

**Comment by lararennie** [comment]
Please don't create a PR, we don't accept PRs for metadata changes of this type.

However, we've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Thanks for providing all the details we need!

**Comment by penmetsaa** [comment]
This is fixed in release 8.7.0
https://libphonenumber.appspot.com/phonenumberparser?number=%2B522211020232
