### ISSUE TITLE
PhoneNumberUtil thread safety?

### ISSUE THREAD

**Issue by JC3** [googlei18n/libphonenumber#1835]
Is the instance returned by PhoneNumberUtil.getInstance() (Java) thread-safe?

Thanks

**Comment by penmetsaa** [comment]
@JC3,
Thanks for asking us about this!

[PhoneNumberUtil.getInstance()](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1070) is an synchronized API. And this class is written to be thread safe. However [PhoneNumberUtil.findNumbers()](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3098) is not guaranteed to work in a threaded environment as it uses [PhoneNumberMatcher.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatcher.java#L41) API. This is mentioned in the java doc. Other methods should be thread safe.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
