### ISSUE TITLE
Validation issue with 659xxxxxxx (US)

### ISSUE THREAD

**Issue by JC3** [googlei18n/libphonenumber#1836]
We have a user with a valid (confirmed) US phone number in area code 659 that is reported as invalid. I noticed 659 does not appear on area code lists, yet, it does appear to exist, and works.

**Comment by penmetsaa** [comment]
@JC3,
Thank you for taking the time to improve libphonenumber!

This area code (659) is listed in "Planned NPAs Not Yet in Service" list.
https://www.nationalnanpa.com/enas/plannedNpasNotInServiceReport.do
This area code is planned to overlay 205 area code but there is no "In Service Date" / "Status" mentioned for this range (similar to other ranges). Looks like the area code is not yet active.

Source: https://www.nationalnanpa.com/reports/reports_npa.html

Only few numbers of this range are found online and none of them are getting connected as well. Can you please share any valid number ? Or please share any authoritative evidence that says this area code is valid and active. Looks like library is working as intended here. Please re-open the issue if you have evidence to the contrary. Ex: A working number. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by JC3** [comment]
I can now confirm this is a non-issue. Turns out the user had intended to enter a Singapore number (country code 65 + 8 digits) and had forgotten to prefix it with a + sign, and it was parsed as a US number.
