### ISSUE TITLE
CPP Readme for dll build is out of date

### ISSUE THREAD

**Issue by volearix** [googlei18n/libphonenumber#1856]
https://github.com/googlei18n/libphonenumber/blob/master/cpp/README

Instructions are out of date and don't seem to be working, any chance of getting an update to get this installed? Seems some of the links are broken or using out of date software that may not be around now.

**Comment by keghani** [comment]
Sorry you're having trouble!

I don't see anything when I search for "dll", did you mean the Windows (Visual Studio) instructions?

Would you mind contributing a patch for this? We actually don't have a Windows setup and can't test that part. But you'd need to find someone to help you review and test (see the part about Windows in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-code-issue)).

**Comment by penmetsaa** [comment]
@volearix ,
This issue is blocked on your or other GitHub contributor's input. Otherwise we don't have enough setup to test/fix the instructions and may have to close this issue as infeasible.

**Comment by penmetsaa** [comment]
As mentioned above, we do not have setup / testing resources to check the issue. Closing this issue as we have not heard back from contributors. Please reopen if patch is created for this fix.
