### ISSUE TITLE
Validation issue with +64 22 XXX XXX

### ISSUE THREAD

**Issue by SimonRobinson** [googlei18n/libphonenumber#1857]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): NZ

Example number(s) affected ("+1 555 555-1234"): +6422000111

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +64 22 XXX XXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

2Degrees allow 6 digit mobile numbers but is rare. NZ Vodafone (+6421 XXX XXX)  6 digit numbers work fine.
[NZ Dial Plan info](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000990001PDFE.pdf)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B6422000111)

**Comment by penmetsaa** [comment]
@SimonRobinson ,
We can't connect to +64 22 000 111.

As per information provided in ITU doc, we already support 9,10 digit 22 range numbers in mobile. https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000990001PDFE.pdf 

We are not able to find any working 8 digit 22 XXX XXX numbers online. If these 2degrees 8 digit 22 range numbers doesn't always work, by [our definition](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-does-it-mean-for-a-phone-number-to-be-valid) they are not valid. Is this what you meant by "2Degrees allow 6 digit mobile numbers but is rare"? That they don't always work? Maybe it depends on the carrier?

Please provide us any official evidence or working number which can conclude that these numbers are possible. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SimonRobinson** [comment]
@penmetsaa 
Hi thanks for your response - you are correct.
Turns out this number range was reported to us in error closing issue.
