### ISSUE TITLE
make[2]: PROTOC_BIN-NOTFOUND: Command not found

### ISSUE THREAD

**Issue by olesyaksyon** [googlei18n/libphonenumber#1864]
I have this error during the building package, although I installed protobuf and protobuf compiler. version of protobuf > 2.6.

**Comment by keghani** [comment]
Thanks for reporting!

What package are you trying to build?

It would also be helpful to have exact commands.

**Comment by keghani** [comment]
Also see https://github.com/googlei18n/libphonenumber/issues/1807

**Comment by olesyaksyon** [comment]
hi! thank you for your answer! i decided problem by installing with apt-get)
