### ISSUE TITLE
Italy: from 480 to 484 maximum lenght

### ISSUE THREAD

**Issue by Raffaele74** [googlei18n/libphonenumber#1868]
Hi.
I'm new, sorry if I'm not exact.
I want to say you that maximum lenght of numbers +39480 to +39484 is almost 7 (not 5 as ITU document.
You can view here (screen mirror or link bottom).
Windgroup is the first (number of users) mobile-operator in Italy.

Screen Mirror (with notes, it is clearer):
![wind](https://user-images.githubusercontent.com/24221053/28527614-5a228b7c-708b-11e7-88e7-0ddc1bcffcc9.png)

Link (to be shure):
http://www.windgroup.it/it/media/comunicati/comunicato/article/wind-lancia-per-prima-in-italia-il-servizio-twitterR-sms-1/?no_cache=1&cHash=464a8398c392dd52b2225a7737cef859

**Comment by SumathiSundara** [comment]
The range which you are referring is 'From 480 to 484' . Please check the below line which says 'From 485 to 489' in the [ITU doc](https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200006B0001PDFE.pdf) .
Prefix 488 is already supported in [our library](http://libphonenumber.appspot.com/phonenumberparser?number=4880804&country=IT) as ShortNumber.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
