### ISSUE TITLE
Wrong behavior when parsing 00 instead of + in countrycode prefix.

### ISSUE THREAD

**Issue by ori424** [googlei18n/libphonenumber#1870]
I'm using the Java library.
When trying to parse the number (I randomly selected it):
+15417543010, parsing works (i.e: country code is 1, national number is 5417543010 and phoneUtil.getLengthOfGeographicalAreaCode(phoneNumber) is 3

However, when trying to parse
0015417543010 (which is equivelant, in manner of calling the same number), it produces
phoneUtil.getLengthOfGeographicalAreaCode(phoneNumber) is *0*

**Comment by keghani** [comment]
00 is not an IDD in every region, i.e. it's not equivalent to +.
What region code are you passing as the default when parsing 0015417543010?

E.g. if parsing [as if dialled from the US](http://libphonenumber.appspot.com/phonenumberparser?number=0015417543010&country=US), the national number is parsed as 15417543010.
Ascension Island, however, does have 00 as an international prefix, so I'd expect 00 to work there same as +: http://libphonenumber.appspot.com/phonenumberparser?number=0015417543010&country=AC

You can try [the demo](http://libphonenumber.appspot.com/) for more regions. Also look at `internationalPrefi` in [`resources/PhoneNumberMetadata.xml`](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml).

I'll close this as it's not an issue, but if you wish to discuss it further we can continue in the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss). Thanks for using the library!
