### ISSUE TITLE
Get country code from phone number.The phone number have without "+" symbol  with country code 

### ISSUE THREAD

**Issue by ArockiaJerald** [googlei18n/libphonenumber#1872]
I am using google phone lib .I have problem in partial/full search in following scenario .
The phone number saved in DB as National number ( Ex: 7324569871) .
The search number have country code without + symbol  (Ex: 17324  or 17324569871)
now try to get the country code from given number(Ex: 17324  or 17324569871) .is this scenario can we get country code?  I tied but  I can't achieve this by  any lib methods.

**Comment by penmetsaa** [comment]
@ArockiaJerald,

Thank you for using libphonenumber!

To get the country code of a given number first you need to [parse()](https://github.com/googlei18n/libphonenumber/blob/e24208e0c63fd06d5cf9da26bb885d2977453c46/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3030) the input number first. If the input number to ```parse()``` API is not in E.164 format (i.e having +) , you need to provide the region from which it is being dialed.

Java code snippet:
```
PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
PhoneNumber phoneNumber = phoneNumberUtil.parse("17324569871", "US");
int countryCode = phoneNumber.getCountryCode();
```

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
