### ISSUE TITLE
Area code 564 is not supported

### ISSUE THREAD

**Issue by Silenthillnight** [googlei18n/libphonenumber#1875]
According to NANPA, the 564 area code will be going into service in Washington state on August 28, 2017 but is not yet supported in libphonenumber.

**Comment by kkeshava** [comment]
Hi,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.7.1
