### ISSUE TITLE
Montenegro new pattern: 382513

### ISSUE THREAD

**Issue by ildra** [googlei18n/libphonenumber#1886]
Hello!
Could you please add these patterns for Montenegro fixed line phones:
Country/region affected (e.g., "US"): ME
Example number(s) affected ("+1 555 555-1234"): +38251353381
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +382513XXXXX 
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): FIXED_LINE
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
Thank you and best regards!
Dragan

**Comment by kkeshava** [comment]
Hi,
Thank you for contributing to libphonenumber!

We can't connect to +38251353381. Did you have a typo? 
We can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 513 is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
