### ISSUE TITLE
Support for "special numbers" in China

### ISSUE THREAD

**Issue by epatey** [googlei18n/libphonenumber#1890]
Chinese customers are complaining that we do not consider [special numbers](https://en.wikipedia.org/wiki/Telephone_numbers_in_China#Others) valid. i.e. `+86-114` for directory assistance.

These special numbers seem not to be in the ITU data. Any recommendations?

**Comment by kkeshava** [comment]
@epatey,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We cannot make this change based on the provided evidence. The statements need to be supported by official sources (eg. ITU doc, national numbering plan). Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that Special numbers are valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
