### ISSUE TITLE
Charging stations in Germany using new phone format for SMS sending

### ISSUE THREAD

**Issue by marmor7** [googlei18n/libphonenumber#1891]
We got a report from a user in Germany that he's not able to send SMS messages using our app to new electric charging stations in Germany.

An example phone number is **841122**.
calling `PhoneNumberUtil.formatNumberForMobileDialing` with region **DE** and phone number **841122** returns **0841122**, which causes the SMS message to fail.

I'm using version 8.7.1

I assume this is a new phone format in **DE**, if I'm doing something wrong, please let me know.

Thanks.

**Comment by kkeshava** [comment]
@marmor7,
Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We are validating 841122 as fixedline number based on [ITU doc](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510004PDFE.pdf) pg 108, see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=841122&country=DE). So the user is unable to send SMS to this number.  If you still feel that this number is mobile and national prefix ‘0’ should not be added to it, then please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by marmor7** [comment]
Thanks for the quick response.

This is a report by a user, I don't live in Germany, or have any official verification of this phone format.

Just though I'll let you guys know about this, I hope someone could give you the docs you need to complete this fix.

Thanks anyway
