### ISSUE TITLE
Validation issue with 23777551513 (CM)

### ISSUE THREAD

**Issue by anandsork** [googlei18n/libphonenumber#1896]
The Issue comes for a valid Cameroon country Number. It gives  E164 format as invalid.
I tried 23777551513. Also with or without country code (237) and passed CountryCode as CM. I even tried prefixing "+" to the number.. Still E164 format comes as invalid.
---
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): CM

Example number(s) affected ("+1 555 555-1234"): 23777551513

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): All Camroon

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  Not Sure

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B23777551513&country=CM)

**Comment by kkeshava** [comment]
@anandsork,
Thank you for using libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We can't connect to + 237 77551513. Did you have a typo?

As per the official [ITU plan](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000240001PDFE.pdf), fixedline numbers start with prefix 2 and mobile numbers start with prefix 6 and both have 9 digit length.  No numbers with prefix 7 is mentioned for Cameroon. Also the number provided by you is 8 digit in length. 
We need working numbers or official evidence with category details (i.e fixedline/mobile) to support this range. Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by anandsork** [comment]
I realized that this is not an issue with the library but of WhatsApp. When user saves the number from WhatsApp, Cameroon numbers are provided by WhatsApp in old format. So the number is saved in old format & fails in the library. 
Thanks for the support and sorry for the trouble. I shall close this & take care in my code specifically. 

BTW, if I have to modify the library (instead of my code, so that phone number validations are at single place), where should I look into?
