### ISSUE TITLE
Validation issue with club 908 conyers (US)

### ISSUE THREAD

**Issue by RyanLee77** [googlei18n/libphonenumber#1898]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): club 908 conyers

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=club+908+conyers&country=US)

**Comment by kkeshava** [comment]
@RyanLee77,
Thank you for contributing to libphonenumber! For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Could you explain what club 908 conyers mean? Are you referring to numbers starting with prefix 908? We are already supporting 908[2-9]XXXXXX numbers in US, see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B19082345678). 
If not please specify the prefix/range for which you are facing validation issue along with official evidence that you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by RyanLee77** [comment]
Thank you for your quick response. "club 908 conyers" is a club in Conyers, GA. Our system uses this lib to recognize phone number and I'm wondering why it takes "club 908 conyers", which seems not a phone number, as a valid phone number. Thanks!

**Comment by kkeshava** [comment]
@RyanLee77,
We have scenarios where phone numbers are alphanumeric for eg. 1800 MICROSOFT which is 1800 102 1100. Each character corresponds to specific number on the dialpad hence we parse and validate such phone numbers too.

**Comment by RyanLee77** [comment]
Ok, thanks.

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
