### ISSUE TITLE
Australian Phone numbers in the range “+618 25 Riverland, Murraylands” and “+618 58 Albany” showing invalid

### ISSUE THREAD

**Issue by ravikirannukala** [googlei18n/libphonenumber#1899]
Australian Phone numbers in the range “+618 25 Riverland, Murraylands” and “+618 58 Albany” showing invalid

**Comment by kkeshava** [comment]
@ravikirannukala,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We are unable to find any official evidence or online working numbers for prefixes 8 25 and 8 58 apart from [wiki](https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#cite_note-new2008-4).  Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ravikirannukala** [comment]
The only source I found was in wiki.

**Comment by kkeshava** [comment]
@ravikirannukala,
We cannot make this change based on the provided evidence. The statements need to be supported by official sources (like ITU doc, a national numbering plan).
If no official evidence or an example number from a business website or similar can be found then we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by ravikirannukala** [comment]
What is your source for Australian numbers?

Ravi

**Comment by kkeshava** [comment]
@ravikirannukala, 
We refer [ITU doc](https://www.itu.int/oth/T020200000D/en) and national numbering plan provided by [Australian Government](https://www.thenumberingsystem.com.au/#/number-register/search).

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Comment by ravikirannukala** [comment]
That's fine thanks
