### ISSUE TITLE
Phone is valid using a wrong number

### ISSUE THREAD

**Issue by vincentchalamon** [googlei18n/libphonenumber#1907]
When I use `0612345678` french number, it's considered as valid. But if I use `061234dgfs` it's still valid but it shouldn't. It becomes invalid only if phone number is too long.

I checked on the [JavaScript demo](http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) using the same wrong phone number, here is the result:
```
****Parsing Result:****
{"country_code":33,"national_number":612343437,"raw_input":"061234dgfs","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: FR
Result from getNumberType(): MOBILE

****Formatting Results:**** 
E164 format: +33612343437
Original format: 061234dgfs
National format: 06 12 34 34 37
International format: +33 6 12 34 34 37
Out-of-country format from US: 011 33 6 12 34 34 37
Out-of-country format from Switzerland: 00 33 6 12 34 34 37

****AsYouTypeFormatter Results****
Char entered: 0 Output: 0
Char entered: 6 Output: 06
Char entered: 1 Output: 061
Char entered: 2 Output: 06 12
Char entered: 3 Output: 06 12 3
Char entered: 4 Output: 06 12 34
Char entered: d Output: 061234d
Char entered: g Output: 061234dg
Char entered: f Output: 061234dgf
Char entered: s Output: 061234dgfs
```

**Comment by SumathiSundara** [comment]
We have scenarios where phone numbers are alphanumeric for eg. 1800 MICROSOFT which is 1800 102 1100. Each character corresponds to specific number on the dialpad hence we parse and validate such phone numbers too.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by keghani** [comment]
BTW There is an explanation for this behavior in our Frequently Asked Questions: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits
