### ISSUE TITLE
Ivory Coast number validation

### ISSUE THREAD

**Issue by sommerluk** [googlei18n/libphonenumber#1909]
Country/region affected (e.g., "US"): CI

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +225

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): all

The cost, if applicable ("toll-free", "premium rate", "shared cost"): all

This is a spin-of from #1685 

Please update the validation data for Ivory Coast.

# Normal number format

+225 NN xx xx xx (eight digits).

Valid values for NN:

**Landline:**

20 Abidjan Plateau
21 Abidjan-sud
22 Abidjan Cocody
23 Abidjan Banco
24 Abidjan Abobo
30 Yamoussoukro
31 Bouaké
32 Daloa
33 Man
34 San-Pédro
35 Abengourou
36 Korhogo

Source: http://www.artci.ci/images/stories/pdf/numerotation/plan_de_numerotation_2014.pdf page 4.

**Mobile numbers (ordered by carrier):**

Orange: 07, 08, 09, 47, 48, 49, 57, 58, 59, 77, 78, 79, 87, 88, 89
MTN: 04, 05, 06, 44, 45, 46, 54, 55, 56, 74, 75, 76, 84, 85, 86
Moov: 01, 02, 03, 40, 41, 42, 43, 51, 52, 53, 71

Source: I got this list by asking directly the carriers (by Facebook for MTN and Orange, the the local office for Moov). The list is up-to-date (2017-03).

# Special numbers

The special numbers won’t work for E164 format.

**Free of charge**

- 80 xx xx xx

**Special charge**

- 90xxxxxx special charge
  - 905xxxxx Internet dial-up
- 98xxx numbers with five digits

**Emergency and other very short numbers**

Format: Either three digits or four digits. The first digit is always “1”. (However, I’ve never seen a four-digit-number in real-world usage.) These numbers are sometimes free of charge, and sometime with charge.

- 1xx
  - most important ones:
  - 175 Dépannage Sodeci (water company)
  - 179 Dépannage CIE (electricity company)
  - 180 Sapeurs pompiers (fire workers)
  - 185 Service Samu (emergency, accident)
  - The full list (from year 2014) is available here: http://www.artci.ci/images/stories/pdf/numerotation/plan_de_numerotation_2014.pdf page 10
- 1xxx

Source: http://www.artci.ci/images/stories/pdf/numerotation/plan_de_numerotation_2014.pdf page 10

# Carrier-specific short numbers
- 555 (not a classic short number, it’s a service number of the mobile/landline carrier MTN, works only for customers of MTN)
- 0707 (Service number of the mobile/landline carrier Orange for individuals, works only for customers of Orange)
- 0808 (Service number of the mobile/landline carrier Orange for enterprices, works only for customers of Orange)
- 2442 (Service number of the mobile/landline carrier Orange for individuals, works only for customers of Orange)

# Out-of-service numbers

The other old mobile carriers are out of service since 2016. Their license was invalidated definitivly by the gouvernment. So their numbers 50, 60, 61, 65, 66, 67, 69 do not work anymore.

Source: http://www.financialafrik.com/2016/04/05/cote-divoire-pourquoi-comium-koz-greenn-warid-et-cafe-mobile-ont-ils-perdu-leurs-licences-2/#.WK_eXhpBrDc

**Comment by mizuni** [comment]
Hi,

Thank you for taking the time to improve libphonenumber!

For mobile ranges 52 and 71, we see that you said in the other issue that you "got this list by asking directly the carriers (by Facebook for MTN and Orange, the the local office for Moov). The list is up-to-date (2017-03)" but we still need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by sommerluk** [comment]
CLA is filled out.

**Comment by mizuni** [comment]
Thanks! We're still missing the authoritative evidence as per the contribution guidelines.
While the French Wikipedia page says 52 and 71 are mobile, the underlying linked evidence does not. 

So we would thus need evidence from the government or carriers/operators (e.g. national numbering plan, operator announcement).

**Comment by blazenko** [comment]
i wish i could submit the logs of thousands of sms messages that our company (a leading provider of B2B messaging, with clients like Facebook, Instagram, LinkedIn... ) succesfully sends each day to the above-mentioned numbers...

**Comment by sommerluk** [comment]
> 52 and 71

Both are numbers from the company “Moov”.

As I explained above: 

> I got this list by asking directly the carriers ([…] the local office for Moov)

 I did this because the numbering plan that I could find from official of Ivory Coast is old. In the meantime new number blocks have been assigned. At moov.com there is no official announcement either. So simply asking in the local office was the only way.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

In particular, we request a publicly available URL or that you sign the CLA and (after getting whitelisted) share non-public evidence with the mailing list only readable by core team members.

**Comment by sommerluk** [comment]
I tried it again on the official Facebook account of Moov and got this answer:
![screenshot 2](https://user-images.githubusercontent.com/6830724/29778092-b1ec3c3a-8bfd-11e7-9a58-10e8412c535a.png)
Is that enough?

**Comment by SumathiSundara** [comment]
Thank you for continuing to take the time and effort to identify a source online! This source you've provided is still insufficient as it's not a formal authoritative source such as a numbering plan.

Since we can't find evidence either, we are closing this issue, but please reopen if you're able to find an official source as per our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
