### ISSUE TITLE
Make generate_geocoding_data.cc platform independent

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#191]
Imported from [Google Code issue #191](https://code.google.com/p/libphonenumber/issues/detail?id=191) created by [schaefer.hutter](https://code.google.com/u/106800386305347776424/) on 2012-09-14T19:06:41.000Z:

---

I know that geocoding for cpp seems yet to be released, but i noticed that generate_geocoding_data.cc is Linux/Unix-specific.

At least for the public available version i may suggest using boost_filesystem as in the patch below (beware: function of the patch may not be 100% identical to the original version, but IWFM and you get the idea...).

Regards,
Peter

BTW: As far as i can tell, the proposed cpp version of PhoneNumberOfflineGeocoder works well (i picked the patches from the review-board).

 ---8&lt;----SNIP-----

--- generate_geocoding_data.cc      Thu Aug 23 22:31:35 2012
+++ generate_geocoding_data_new.cc  Fri Sep 14 20:57:37 2012
@@ -34,6 +34,8 @@

 #include &quot;base/basictypes.h&quot;

+#include &quot;boost/filesystem.hpp&quot;
+
 namespace i18n {
 namespace phonenumbers {

@@ -94,38 +96,23 @@

 // Lists directory entries in path. &quot;.&quot; and &quot;..&quot; are excluded. Returns true on
 // success.
-bool ListDirectory(const string&amp; path, vector&lt;DirEntry&gt;\* entries) {
+bool ListDirectory(const boost::filesystem::path&amp; path, vector&lt;DirEntry&gt;\* entries) {
   entries-&gt;clear();
-  DIR\* dir = opendir(path.c_str());
-  if (!dir) {
-    return false;
-  }
-  AutoCloser&lt;DIR&gt; dir_closer(&amp;dir, closedir);
-  struct dirent entry, *dir_result;
-  struct stat entry_stat;
-  while (true) {
-    const int res = readdir_r(dir, &amp;entry, &amp;dir_result);
-    if (res) {
-      return false;
-    }
-    if (dir_result == NULL) {
-      return true;
-    }
-    if (strcmp(entry.d_name, &quot;.&quot;) == 0 || strcmp(entry.d_name, &quot;..&quot;) == 0) {
-       continue;
-    }
-    const string entry_path = path + &quot;/&quot; + entry.d_name;
-    if (stat(entry_path.c_str(), &amp;entry_stat)) {
-      return false;
-    }
-  if (!boost::filesystem::exists(path) ) return false;
-  printf(&quot;%s\n&quot;, path.string().c_str());
-  boost::filesystem::directory_iterator it(path);
-  boost::filesystem::directory_iterator end_it;
-  for (; it != end_it; ++it ) {
-    if ((it-&gt;path().leaf().string() == &quot;.&quot;) || (it-&gt;path().leaf().string() == &quot;..&quot;)) continue;
   DirEntryKinds kind = kFile;
-    if (S_ISDIR(entry_stat.st_mode)) {
-    if (boost::filesystem::is_directory(it-&gt;status())) {
     kind = kDirectory;
-    } else if (!S_ISREG(entry_stat.st_mode)) {
-    } else if (!boost::filesystem::is_regular(it-&gt;status())) {
     continue;
   }
-    entries-&gt;push_back(DirEntry(entry.d_name, kind));
-    entries-&gt;push_back(DirEntry(it-&gt;path().leaf().string().c_str(), kind));
  }
-  return true;
  }
  
  // Returns true if s ends with suffix.
  @@ -560,7 +547,8 @@
  map&lt;string, string&gt; prefix_vars;
  map&lt;int32, set&lt;string&gt; &gt; country_languages;
  vector&lt;DirEntry&gt; entries;
-  if (!ListDirectory(data_path, &amp;entries)) {
-  boost::filesystem::path datapath = data_path;
-  if (!ListDirectory(datapath, &amp;entries)) {
   fprintf(stderr, &quot;failed to read directory entries&quot;);
   return false;
  }
  @@ -570,7 +558,8 @@
     continue;
   }
   // Enumerate country calling code files.
-    const string dir_path = data_path + &quot;/&quot; + it-&gt;name();
-    boost::filesystem::path dir_path = datapath;
-    dir_path /= it-&gt;name();
   vector&lt;DirEntry&gt; files;
   if (!ListDirectory(dir_path, &amp;files)) {
     fprintf(stderr, &quot;failed to read file entries\n&quot;);
  @@ -587,10 +576,11 @@
     if (!StrToInt(country_code_str, &amp;country_code)) {
       return false;
     }
-      const string path = dir_path + &quot;/&quot; + fname;
-      boost::filesystem::path path = dir_path;
- ```
   path /= fname;
  ```
  
     map&lt;int32, string&gt; prefixes;
-      if (!ParsePrefixes(path, &amp;prefixes)) {
-      if (!ParsePrefixes(path.string(), &amp;prefixes)) {
       return false;
     }

**Comment by keghani** [comment]
I can't find the original reporter on GitHub.
Is this a problem for anyone currently using the GitHub repository? Would you be able to help us understand the issue and possibly test? We develop on Linux.

**Comment by keghani** [comment]
This is infeasible to fix at this point due to our development environment, and no one coming forward about this affecting them.

Please re-open if this still affects you.
