### ISSUE TITLE
NZ format 07 6XXX XXX isValidNumberForRegion returning false

### ISSUE THREAD

**Issue by tntim96** [googlei18n/libphonenumber#1918]
The code below sets `valid` to false, however, when the `6` is replaced with `7` or `5`, `valid` is true.

```Java
    PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
    Phonenumber.PhoneNumber phoneNumber = phoneUtil.parseAndKeepRawInput("07 6000 000", "NZ");
    boolean valid = phoneUtil.isValidNumberForRegion(phoneNumber, "NZ");
```

I've tested this on versions `8.3.2` and `8.8.0`.

Relevant code seems to be at https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberAlternateFormats.xml#L1536

**Comment by SumathiSundara** [comment]
As per [ITU doc](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000990001PDFE.pdf), 07 6 does not mention as a valid number.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
