### ISSUE TITLE
Get level of subdivision in offline geocoder

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#192]
Imported from [Google Code issue #192](https://code.google.com/p/libphonenumber/issues/detail?id=192) created by [candrewsintegralblue](https://code.google.com/u/114215788913124607468/) on 2012-09-16T02:20:37.000Z:

----
In my application, I need to know if PhoneNumberOfflineGeocoder.getDescriptionForNumber(PhoneNumber number, Locale languageCode) returned a description at the city, state/region, or country level.

For example, the geocoder could return &quot;Boston&quot; or &quot;Massachusetts&quot; or &quot;USA&quot; - knowing what level it returned is useful information. There is currently no way to tell.

**Comment by keghani** [comment]
The offline geocoder will return a subdivision, not the country. E.g. see https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/1.txt, there's no "USA".

The country itself is the phone number's region. E.g. see http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+412+535+0000.

We don't plan to get more detialed, e.g. saying whether the subdivision is a "state" or "county".
