### ISSUE TITLE
Mention Phoneword (namedialing?) in Falsehoods Programmers Believe... ?

### ISSUE THREAD

**Issue by RobThree** [googlei18n/libphonenumber#1921]
Maybe it's worth mentioning [phonewords](https://en.wikipedia.org/wiki/Phoneword) under in [Falsehoods Programmers Believe About Phone Numbers](https://github.com/googlei18n/libphonenumber/blob/master/FALSEHOODS.md)? I think it would be worth a mention in .17 at least.

**Comment by keghani** [comment]
That's a good point. I'll send something out.

**Comment by keghani** [comment]
Resolved with https://github.com/googlei18n/libphonenumber/pull/1924
