### ISSUE TITLE
Example number generated for Panama is someone's personal phone number

### ISSUE THREAD

**Issue by TM4RT** [googlei18n/libphonenumber#1922]
I have a web design client that asked me to look into this issue for him. He keeps seeing his personal cell phone number appear as the example/placeholder number in tel inputs on apps and websites (+507 6001-2345) and also regularly receives calls from the users of these apps and sites, many times they are angry and looking for support. I found that Jack O'Connor's [intl-tel-input](https://github.com/jackocnr/intl-tel-input) plugin was displaying this number, contacted him, and he said the number is generated by libphonenumber.

The correct number for Panama should be +507 6000-1234, I've tested it and it is disconnected.

**Comment by SumathiSundara** [comment]
Thank you for bringing this to our attention!

We regret the inconvenience and will fix this ASAP.

We do our best to avoid this from happening by, for example, sourcing our
example numbers from ITU docs where such numbers are provided by the region's
telecom authority. Where this is not present, we have to resort to fake numbers
that fit the valid ranges, and at the time of addition, we try to ensure these
are unassigned.

Sometimes these numbers do get assigned later, and at that point it is through
such reports that we know to take action.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

Thanks for using the library!

**Comment by SumathiSundara** [comment]
Fixed in release 8.8.2.
