### ISSUE TITLE
Carrier switched from AT&T to Digicel in release 8.8.1

### ISSUE THREAD

**Issue by 4nt01ne** [googlei18n/libphonenumber#1923]
Language: Java.
I have a unit test running daily and testing the carrier for a given number.
We are always using the last release version of **libphonenumber**
With release 8.8.1, the number 17585198712 switched from AT&T to Digicel.

Code
`Phonenumber.PhoneNumber phoneNumber = PhoneNumberUtil.getInstance().parse("17585198712", "US");`
`String carrier = PhoneNumberToCarrierMapper.getInstance().getNameForNumber(phoneNumber, Locale.ENGLISH);`

Until version 8.8.0 carrier was AT&T.
Since 8.8.1  it is Digicel.

Is this expected? 
I don't know how to verify if the change in the Carrier range is a conscious update or a bug?

**Comment by SumathiSundara** [comment]
We update the metadata frequently, and it is expected that different versions will give different results.

If there is a specific carrier change that you think it’s different and don't do so
in the latest release, please file an issue with all the details. See our
[contribution guidelines ](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to determine whether something is a real issue, and the details we need to be
able to fix it.

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
