### ISSUE TITLE
ilibphonenumber:UAE area code 054 and 058 are not allowed. When would these be added. 

### ISSUE THREAD

**Issue by Ashwini-12** [googlei18n/libphonenumber#1925]
I am using ilibphonenumber for validation of phone numbers. UAE area code 054 and 058 are not allowed. When would these be added.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by Ashwini-12** [comment]
Please refer following Wikipedia link. As per the Wiki article 054 and 058 are new area codes for UAE and ilibphonenumber should consider them as valid. May be needs to be added to area code table ? 

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_United_Arab_Emirates

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
