### ISSUE TITLE
Area Code 223 is not supported and going into service on Sept. 26, 2017

### ISSUE THREAD

**Issue by Silenthillnight** [googlei18n/libphonenumber#1926]
According to the NANPA website, the Pennsylvania area code 223 is going into service on September 26th, 2017.  However, libphonenumber does not currently support this number.  Link to the planned area codes below.

https://www.nationalnanpa.com/enas/plannedNpasNotInServiceReport.do

**Comment by kkeshava** [comment]
@Silenthillnight,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Fixed in release 8.8.2.
