### ISSUE TITLE
[PH] Update library phone numbers for philippines

### ISSUE THREAD

**Issue by melvin-shopee** [googlei18n/libphonenumber#1930]
Dear libphonenumber master,

There are several phone numbers prefix has not been updated for Philippines:
- 63978
- 63940
- 63992
- 63911
- 63913
- 63981
- 63951
- 63970
- 63941
- 63944
- 63924
- 63931
Can kindly update these phone numbers? Thanks!

Complete List:
![image](https://user-images.githubusercontent.com/31874162/30306695-47b43790-97ac-11e7-92b5-30e90002973c.png)

**Comment by kkeshava** [comment]
@melvin-shopee,
Thank you for taking the time to improve libphonenumber!

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

We cannot accept screenshots as evidence. In particular, we request a publicly available URL or that you sign the CLA and (after getting whitelisted) share non-public evidence with the mailing list only
readable by core team members.

**Comment by melvin-shopee** [comment]
Hi @kkeshava!
Thanks for replying. I get the lists from here: [http://www.prefix.ph/smart-users/updated-complete-list-mobile-prefixes-philippines-2017/] 
Is this enough for the evidence? 

Thanks!
Regards, 
Melvin Fonda

**Comment by kkeshava** [comment]
@melvin-shopee,
We need official evidence like a national numbering plan, announcements from mobile carriers, news articles etc. Please see our guidelines for [provide authoritative evidence](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-authoritative-evidence).

**Comment by penmetsaa** [comment]
@melvin-shopee 
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
