### ISSUE TITLE
0 is a valid phoneNumber

### ISSUE THREAD

**Issue by KoMiToRaY** [googlei18n/libphonenumber#1931]
Hi everybody,

i check if the phone number in a form is correct with 'isValidNumber'

but when i put only a 0 i get an error -> The string supplied did not seem to be a phone number

and so my isValidNumber is not called. it is normal ?

if the string supplied did not seem to be a phone number why isValidNumber does not return false ?

Thx for help

**Comment by kkeshava** [comment]
Hi,

Before PhoneNumberUtil.isValidNumber() API is called the phone number string has to be successfully parsed (using PhoneNumberUtil.parse()) first. 0 fails to parse. parse() returns Error type: NOT_A_NUMBER with message "The string supplied did not seem to be a phone number."
