### ISSUE TITLE
PhoneNumberToCarrierMapper not included in libphonenumber-8.8.1.jar

### ISSUE THREAD

**Issue by iamtrojan** [googlei18n/libphonenumber#1932]
The class and the carrier data is not available in the jar downloaded here:

http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/8.8.1/libphonenumber-8.8.1.jar

**Comment by iamtrojan** [comment]
Hi,
The carrier and geocoder have their own jars, which is why you can't find them in the libphonenumber.jar

Unfortunately the sorting for the jars is a bit unintuitive, but the latest ones are there;
Carrier http://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/1.10/
Geocoder http://repo1.maven.org/maven2/com/googlecode/libphonenumber/geocoder/2.20/

https://github.com/googlei18n/libphonenumber/issues/670#issuecomment-94401767

Thanks @roes

**Comment by keghani** [comment]
That's correct, thanks for finding that thread with @roes' comment.
You can also read more about how the different versions correspond to each other in our [FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#which-versions-of-the-maven-jars-should-i-use).

**Comment by iamtrojan** [comment]
@keghani Yeah. Also can you please add all the libraries into readme ? http://repo1.maven.org/maven2/com/googlecode/libphonenumber/

**Comment by keghani** [comment]
We already have the FAQ, which is easier than having to maintain a list of all libraries I think?
The link to the Maven repository is already at https://github.com/googlei18n/libphonenumber#java-code
