### ISSUE TITLE
NZ 11 Digit 029 number not valid

### ISSUE THREAD

**Issue by crispkiwi** [googlei18n/libphonenumber#1933]
I'm having some trouble getting any 11 digit 029 number to validate. As far as I can tell there are active 11 digit Vodafone numbers in NZ.

*   Country: NZ
*   Example number(s) and/or range(s): 029 XXX XXXXX
*   Number type ("fixed-line", "mobile", "short code", etc.): Mobile
*   Where or whom did you get the number(s) from: Vodafone New Zealand
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
http://www.nad.org.nz/number-register/ Code 02XY, max digits 11,
http://www.nad.org.nz/list/6/Consumer Code 029(0-9) all registered to Vodafone New Zealand.
http://www.tnzi.com/numbering-plan Code (0)29, max digits 10 (not including leading 0) 
*   Link from demo (http://libphonenumber.appspot.com) showing error: https://libphonenumber.appspot.com/phonenumberparser?number=02912345678&country=NZ

I have valid 11 digit 029 numbers but I cannot share them in a public forum.

**Comment by crispkiwi** [comment]
Apologies. On requesting permission to get a valid example number my client could not produce one that would connect. It seems that they are invalid numbers.

**Comment by penmetsaa** [comment]
@crispkiwi,
Thanks for following up on this and closing the issue.

For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.
