### ISSUE TITLE
Question : Which format/check you are using for validating US phone/mobile numbers

### ISSUE THREAD

**Issue by dbhattacharjee** [googlei18n/libphonenumber#1939]
Hi There,

We are using this bundle in our Symfony 2.x application from a long time and it worked for very well.
Recently, one of the customer reported that below numbers are not being recognized as valid US phone numbers.

**Example :** 8618601970643, 35796444692, 8613811212437,59169611818,555181404269, 440790375,
358440482158, 64210620096

We are curious to know what exact format/validation/checks you are using for validating US phone/mobile numbers.
Please do not consider this an issue, rather just a query.

**Comment by penmetsaa** [comment]
@dbhattacharjee,

Thanks for reporting this! This is actually addressed in our documentation:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#where-do-we-get-information-from-to-determine-if-a-number-range-is-valid

As a result, we'll close this issue, but let us know if we may clarify the
answer and update documentation. Please consider joining the
[discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
