### ISSUE TITLE
Issue with german Number

### ISSUE THREAD

**Issue by lowki93** [googlei18n/libphonenumber#1941]
I try to parse this number : `493030808459`
I have  `+49493030808459`
I should have `+493030808459`

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

http://libphonenumber.appspot.com/phonenumberparser?number=%2B49493030808459

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
