### ISSUE TITLE
Validation issue with 308131996

### ISSUE THREAD

**Issue by maas2908** [googlei18n/libphonenumber#1945]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): KR

Example number(s) affected ("+1 555 555-1234"): 308131996

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):

The cost, if applicable ("toll-free", "premium rate", "shared cost"):

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): IMPORTANT - anything posted here is made public. Read the guidelines first!

**Comment by penmetsaa** [comment]
@maas2908 ,

We can't connect to phone number that you have shared. Please share any working number and also details about the category(Ex: fixed-line) along with supporting evidence. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by penmetsaa** [comment]
This issue is blocked on your or other GitHub contributors' input. Please help
us find evidence that 308 XXX XXX is valid, or provide an example number from a
business website or similar. Otherwise we don't have enough information to
fix the issue and may have to close it as infeasible.

**Comment by maas2908** [comment]
Apologies,  I was provided a truncated number.  The correct number that has a validation issue is 82 00 308131996

**Comment by penmetsaa** [comment]
@maas2908,
Thanks for providing the input details.

The '+' sign is missing before the country code in the input you have provided. The number has to be in right dialing format. Ex: 
- National format (0 00 308131996): 
https://libphonenumber.appspot.com/phonenumberparser?number=0+00+308131996&country=KR
- E.164 format (+82 00 308131996): https://libphonenumber.appspot.com/phonenumberparser?number=%2B82+00+308131996

This phone number is returned as valid KR toll-free number. See above demo results.
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
