### ISSUE TITLE
Some way to get MCC and MNC by MSISDN

### ISSUE THREAD

**Issue by fabianomichels** [googlei18n/libphonenumber#1954]
I did not found any way to get MCC and MNC from MSISDN using libphonenumber.
My question is if there is some way to get that informations. The string returned by 'name for number' can be different in other lib, so the correlation is too difficult.

**Comment by penmetsaa** [comment]
@fabianomichels, 
Thanks for using libphonenumber!

We do not maintain MCC and MNC map against MSISDN. 

Closing this issue as it is out of scope of the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
