### ISSUE TITLE
latest version does not validate defaultRegion

### ISSUE THREAD

**Issue by andrewtran634** [googlei18n/libphonenumber#1956]
i've updated the `pom.xml` of my project to use version 8.8.3, however this is what the `checkRegionForParsing()` method looks like
```
private boolean checkRegionForParsing(CharSequence numberToParse, String defaultRegion) {
        return this.isValidRegionCode(defaultRegion) || numberToParse != null && numberToParse.length() != 0 && PLUS_CHARS_PATTERN.matcher(numberToParse).lookingAt();
    }
```

the github version has it as, which makes sure to check validity of defaultRegion first AND the numberToParse
```
  private boolean checkRegionForParsing(CharSequence numberToParse, String defaultRegion) {
    if (!isValidRegionCode(defaultRegion)) {
      // If the number is null or empty, we can't infer the region.
      if ((numberToParse == null) || (numberToParse.length() == 0)
          || !PLUS_CHARS_PATTERN.matcher(numberToParse).lookingAt()) {
        return false;
      }
    }
    return true;
  }
```

**Comment by keghani** [comment]
Hi @andrewtran634,

Thanks for using our library!

This doesn't seem to be an issue with our repository. At v8.8.3, `PhoneNumberUtil.java#checkRegionForParsing(CharSequence, String)` is https://github.com/googlei18n/libphonenumber/blob/v8.8.3/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2968

I can't find any version where this was not of this form. The method was introduced in commit 9b5fab1 and looked a lot the way it is now, i.e. with the checks.

I don't know why your copy does not look that way. Maybe you had some local commits?
I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like help from the community.
