### ISSUE TITLE
Validaton issue (GE)

### ISSUE THREAD

**Issue by Dmatafonov** [googlei18n/libphonenumber#1959]
**Tested here**
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Try to input Georgia phone number: +995 91706162

We get error: 

****Formatting Results:**** 
E164 format: invalid
Original format: +995 91706162
National format: 91706162
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

But it is valid mobile number in Georgia.

**Comment by penmetsaa** [comment]
@Dmatafonov ,
Thank you for taking the time to improve libphonenumber!

We can't connect to +995 91706162. However able to connect the number +995 5 91706162. The mobile phone numbers in Georgia have been renumbered i.e all mobile numbers are now prefixed with digit 5. See https://en.wikipedia.org/wiki/Telephone_numbers_in_Georgia_(country)#Mobile_networks

The library already supports +995 5 91706162, demo result: https://libphonenumber.appspot.com/phonenumberparser?number=%2B995+5+91706162. 

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
