### ISSUE TITLE
Metadata compatibility with older releases

### ISSUE THREAD

**Issue by patric-r** [googlei18n/libphonenumber#1960]
Question:

Can I take most recent metadata files and use them with older releases (e.g. 7.4.5)?
If not, how to find out if a specific metadata version is compatible with a release?

Thank you.

**Comment by keghani** [comment]
That is currently not supported.

We upgrade the major version number for backwards-incompatible changes, so e.g. v8.y.z metadata has less of a chance of being readable by v7.y.z  code. You can see more about backwards-incompatibility at https://github.com/googlei18n/libphonenumber#versioning-and-announcements

Also release notes are at https://github.com/googlei18n/libphonenumber/blob/master/release_notes.txt, which may help you check all changes between the versions you care about to see if the metadata format changed.

I'm curious though, why would you want to work with older releases? They miss functionality and bug fixes found in newer ones. Maybe there's some other way we can solve your issue?

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
