### ISSUE TITLE
New operator code KG

### ISSUE THREAD

**Issue by jaynakus** [googlei18n/libphonenumber#1970]
Please add new operator code 99650[0-9]123123 for Kyrgyzstan

**Comment by kkeshava** [comment]
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B996509123123) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
