### ISSUE TITLE
Validation issue with +13104503

### ISSUE THREAD

**Issue by erikdaniel** [googlei18n/libphonenumber#1975]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"):  CA

Example number(s) affected ("+1 555 555-1234"): +13104503  This number is marked as a valid Canadian phone number, and it is not.

The phone number range(s) to which the issue applies:  +1 310 XXXX"

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): n/a

The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B13104503)

Canadian numbers have a 3 digit area code, 3 digit exchange, and a four digit station code (Bell system).  https://en.wikipedia.org/wiki/Telephone_numbers_in_Canada#cite_note-1

**Comment by keghani** [comment]
Thanks for reporting @erikdaniel!

We're validating the +1 310 XXXX range as toll-free.
This seems consistent with e.g. https://www.tripadvisor.ca/Travel-g153339-s605/Canada:Telephones.html

Do you think this is incorrect?

**Comment by erikdaniel** [comment]
I'm sorry!  I didn't see that when I was looking for this exchange. Seems like it's valid.  Thanks for responding!

**Comment by keghani** [comment]
Actually we found evidence that this range does not work for all carriers in Canada, and is not "a true toll-free":

> In Canada, toll-free numbers are drawn from the US SMS/800 database. A seven-digit number 310-xxxx (not a true toll-free, but may be called from anywhere in its home area code at local rates from certain, but not all, carriers) is available in Bell Canada and Telus territories. From a landline, these are free. From cell phones, airtime is not covered, but there are no long distance charges.
from https://en.wikipedia.org/wiki/Toll-free_telephone_number

We're invalidating it given our FAQ, [What about numbers that are only valid for a set of subscribers?](https://en.wikipedia.org/wiki/Toll-free_telephone_number)

It should be fixed in the next release.

**Comment by erikdaniel** [comment]
Thanks for the follow-up.
Your FAQ link goes to the wiki, I think you meant [What about numbers that are only valid for a set of subscribers?](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-numbers-that-are-only-valid-for-a-set-of-subscribers "FAQ")

**Comment by keghani** [comment]
I did, thanks for correcting that :)

**Comment by penmetsaa** [comment]
This is fixed in release 8.8.5. We are no mores supporting +1 310 XXXX range.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+310+1234&country=CA
