### ISSUE TITLE
Validation issue with +56 02 6167 6408 (CL)

### ISSUE THREAD

**Issue by sleopardo** [googlei18n/libphonenumber#1977]
Country/region affected: CL

Example number(s) affected: +56 02 6167 6408

The phone number range(s) to which the issue applies ("+56 02 XXXX XXX):

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line

The correct area code is 02 [Link to validate area codes](http://cl.portaltelefonico.com/codigos-de-area-de-chile), but I need to use area code 09 to get a validate phone number.

Place: La Cisterna, Santiago, Metropolitana De Santiago

[link to demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B560261676408)

**Comment by keghani** [comment]
Thanks for reporting @sleopardo!

We actually do validate 2 as an area code in Chile. See for example, [+56 2 2123 4567](http://libphonenumber.appspot.com/phonenumberparser?number=%2B56+2+2123+4567&country=CL) on the demo.

We need evidence about the range that would make +56 2 6167 6408 valid, e.g. is it all the numbers beginning with 2616? or 261? 26?  Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) for the kind of evidence we need.

**Comment by penmetsaa** [comment]
@sleopardo,

We can't connect to +56 2 6167 6408

This issue is blocked on your or other GitHub contributor's input. Please help us find evidence that the range (like 2616? or 261? or 26?) is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
