### ISSUE TITLE
Morrocan Number starting with 7 is not passing

### ISSUE THREAD

**Issue by subarnajit** [googlei18n/libphonenumber#1980]
Hi Team,
I'm using the latest 8.8.4 version to validate Moroccan phone number. Now, Morocco has recently started giving the phone numbers starting with 7 (e.g. +2127********). However, a similar phone number is failing on validation with libphonenumber8.8.4.

Please can you fix the issue and publish a latest version. Please let me know further.

Thanks & Regards
Subarnajit Das
subarnaunlimited@gmail.com

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
We already support specific 7XX mobile ranges based on below official doc. Ex: 0770XXXXXX. 
https://www.anrt.ma/sites/default/files/blocs_de_numeros_par_operateur_juillet_2016.pdf

No valid 7XX phone number ranges are found online which are not part of this doc. I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Comment by anyanany1** [comment]
@penmetsaa Hey, it seems that the doc you referenced is outdated. 
Here is an updated one (was hard to find):
https://www.anrt.ma/sites/default/files/blocs_de_numeros_par_operateur_juin_2017.pdf

Diffing the versions, these are the new prefixes we found:
0766XXXXXX
0767XXXXXX
0706XXXXXX

**Comment by penmetsaa** [comment]
@subarnajit ,
Thanks for providing all the details we need! We've accepted this issue and
will fix this as soon as possible.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
