### ISSUE TITLE
Finland phone numbers

### ISSUE THREAD

**Issue by alan-grixti** [googlei18n/libphonenumber#1981]
We're having issues parsing numbers coming from Finland, based on the following numbers below. 

https://hasanpartners.fi/contact/ : +358 424 6711
http://www.metsagroup.com/en/Contact/Pages/default.aspx : +358 10 4601
http://www.meyerturku.fi/en/meyerturku_com/kontakt_4/kontakt_4.jsp : +358 010 6700

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We were able to connect to +358 424 6711, +358 10 4601 and +358 010 6700, but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need
context about the prefix that makes them valid.

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by alan-grixti** [comment]
Our claims were based on mostly [this](http://www.wtng.info/wtng-358-fi.html) and [this](http://www.wtng.info/ccod-35.html#CC358).

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We did find online numbers but we consider the official numbering plan to be reliable source.

 "+358 424 6711" conflicts with the official numbering plan of Finland: https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000490003PDFE.pdf classifies 4 followed by 
 0-8 as non-geographic and with length of minimum 8 to maximum 10.

However, "+358 424 6711" is 7 digits long & not sure of category (appears to be fixed-line). Source:  https://hasanpartners.fi/contact/. 

Could you please clarify the category for the prefix 42 of length 7 digits?
We will reach out to the Finnish communications regulatory authority to see if we can clarify the situation.

**Comment by alexanderpas** [comment]
FINLAND'S E.164 NUMBERING PLAN

https://www.viestintavirasto.fi/attachments/muutpaatokset/Suomen_numerointisuunnitelma.pdf

As found on:

https://www.viestintavirasto.fi/internetpuhelin/puhelinverkonnumerointi.html

Take note of the following:

> Number length information is valid for new assignments. However, N(S)N length of 5 digits are still in use for older assignments.

**Comment by alexanderpas** [comment]
From: https://en.wikipedia.org/wiki/Telephone_numbers_in_Finland

> Finnish mobile numbers start with 04x, 0457 or 050. The format for mobile telephone numbers is 04x 123 45 67 or 0457 123 45 67 or 050 123 45 67. When called from a different country, the format is + 358 4x 123 45 67 or + 358 50 123 45 67. Most commonly 7 digits are used for subscriber number, with normal range being from 4 to 8 digits.

> The first three digits previously indicated the mobile operator but mobile number portability has been implemented and any prefix can now be associated with any operator, 040 (was owned by TeliaSonera) and 050 (was owned by Elisa, formerly Radiolinja) are most common prefixes. 042 and 045 0 were also owned by TeliaSonera, [...]

This seems to indicate that the 42 prefix indicates a mobile number given out originally by TeliaSonera with the 5-digit subscriber number of 46711

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347),
which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
