### ISSUE TITLE
Validation issue with 9861071221 (IN)

### ISSUE THREAD

**Issue by PallaviSripada** [googlei18n/libphonenumber#1983]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 9861071221

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=9861071221&country=IN)

Hi ,

I would like to bring it to your notice that , I tried using the api provided as below : 
http://libphonenumber.appspot.com/phonenumberparser?number=9861071221&country=IN 

The number which I used was a "Reliance" Carrier.But it got ported to another network("Aircel").
I didn't find the ported carrier,instead found the same carrier with which the user has purchased initially.

I tried with another phone number as well. 
http://libphonenumber.appspot.com/phonenumberparser?number=8984524285&country=IN 
Carrier shown = "Tata Docomo"
Carrier to be shown ="Vodafone" (This has been ported ).

Thanks,
Pallavi

**Comment by penmetsaa** [comment]
@Pallavi,
Thank you for using libphonenumber!

This is actually working as intended. Library return's original carrier for the supplied number. For more information, check out [this FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#since-its-possible-to-change-the-carrier-for-a-phone-number-how-is-the-data-kept-up-to-date)
