### ISSUE TITLE
New South African prefix

### ISSUE THREAD

**Issue by eugenesmal** [googlei18n/libphonenumber#1993]
We need the a new Carrier extension to be added for South Africa.
The 0660 - 0665: Cellular: Used by Vodacom extention is not seen as a valid extension. 
It has just recently been added. I've included the wikipedia reference for confirmation.

A example number:+27 66 635 2071 

Your help will be greatly appreciated.

**Comment by penmetsaa** [comment]
@eugenesmal,

Thanks for providing all the details we need! We'll add the carrier details for 0660 - 0665 cellular ranges. We already support "+27 66 635 2071" as valid mobile number in South Africa. See the [demo result](https://libphonenumber.appspot.com/phonenumberparser?number=%2B27+66+635+2071).

For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by eugenesmal** [comment]
Great. Thank you for your quick reply. We will update to the latest version and retest.

**Comment by penmetsaa** [comment]
@eugenesmal,
We will fix this in an upcoming release and close this issue at the same time. Reopening to track it.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
