### ISSUE TITLE
GB numbers leading zero is removed

### ISSUE THREAD

**Issue by lxknvlk** [googlei18n/libphonenumber#1999]
For example we have a number (+44) 07921******

The PhoneNumberUtil.parse("07921******", locale) method parses the number incorrectly to 
7921****** removing the leading zero, which is incorrect. 

Tested on the latest version 8.8.5

**Comment by giggsey** [comment]
What are you using to get the number result?

In the PhoneNumber object, the national_number would be without a leading zero.

![image](https://user-images.githubusercontent.com/305730/32451095-f21b21d0-c30d-11e7-98fd-fdf1c4e9e968.png)

When formatting it, the leading zero will be added back.

**Comment by niklassletteland** [comment]
I am not getting the leading 0 added back upon formatting the number. I am using the node port (https://github.com/ruimarinho/google-libphonenumber) but this appears to be the core issue; I can post an issue there if it would be more appropriate.

The code is:
```
var phoneUtil = require('google-libphonenumber').PhoneNumberUtil.getInstance();

var phoneNumberRaw = '(+44) 079 2112 3456';
var parsed = phoneUtil.parse(phoneNumberRaw, 'UK');
var formatted = phoneUtil.format(parsed, 'AU');

console.log(formatted);
```

This outputs `7921 123456` - without the leading 0. Is the 0 meant to be added back when using the `format` function?

**Comment by giggsey** [comment]
I don't think the second argument for format is a country code, but instead
a number format enum.

**Comment by niklassletteland** [comment]
Gotcha - that makes sense. Thanks for the quick reply @giggsey

**Comment by kkeshava** [comment]
Thanks @giggsey.

Closing this issue. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](https://b.corp.google.com/issues/new?component=192347&template=829703), which we're currently testing.
