### ISSUE TITLE
Macau Phone numbers issue

### ISSUE THREAD

**Issue by michaelnlindsay** [googlei18n/libphonenumber#2004]
The validation for Macau phone numbers incorrectly not matching 853-81X-XXXX

https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadata.js#L4733

Should be: ,[,,"(?:28[2-57-9]|8[*1*-57-9]\\d)\\d{5}",,,,"28212345"]

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber! You have mentioned in the phone number as 81X-XXXX which is 7 digits but fixedline numbers in Macau are 8 digit long. We guess you had a typo.

We've accepted this issue and will fix 81XX-XXXX (8 digit) fixed line number in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
As per the official source http://telecommunications.ctt.gov.mo/web/tc/generalinfo/allocatednum/allocatednum-8 we will be supporting only prefix 811. Please provide any official evidence/working numbers if you think whole of 81 range is valid.

**Comment by michaelnlindsay** [comment]
The number I was attempting to support was an 811 number (and 8 digits) [(853) 8113 0388].  Thanks for adding this!

**Comment by SumathiSundara** [comment]
Fixed in release 8.8.6.
