### ISSUE TITLE
Valid Zambia number incorrectly recognized as invalid

### ISSUE THREAD

**Issue by bineyame** [googlei18n/libphonenumber#2007]
Hello,

I have posted the below in the python implementation and have been referred to raise the issue here.Thank you.

Valid Zambia number is not recognized as such
`In [2]: n='+260956439422'

In [3]: m=phonenumbers.parse(n,'ZM')

In [4]: phonenumbers.is_possible_number(m)
Out[4]: True

In [5]: phonenumbers.is_valid_number(m)
Out[5]: False

In [6]: phonenumbers.version
Out[6]: '8.8.5'
`

**Comment by kkeshava** [comment]
@bineyame,
Thank you for taking the time to improve libphonenumber!

We were able to connect to +260956439422, but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by dinebennett** [comment]
@bineyame I am running into the same issue, I bought a Zamtel SIM with number +260956459559 but libphonenumber says it's invalid.
I will see if I can find "evidence" to support this...

**Comment by bineyame** [comment]
@kkeshava 
Thank you ,the number belong to Zamtel  ( CCMNC +26095), I am not sure if the latest updated IR21 document could be requested from the operator which I think is the evidence.
Thank you @dinebennett ,it seems their updated IR21 is not shared across the telecom community.

**Comment by dinebennett** [comment]
@bineyame @kkeshava 
ZICTA shared with me the Zambian National Number Plan: https://www.zicta.zm/Downloads/Numbering%20Plan.pdf

The numbering plan specifies that the format for mobile numbers is 09N XXX XXXX, where N is any number from 4 to 9, and no limitation is placed on X. (See section 3.5.1 of the numbering plan).

**As per the guidelines, here are the details of the issue:**
*   Country: Zambia
*   Example number(s) and/or range(s): 26 095 000 0000 - 26 095 9999999 (for example 260956459559)
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile (Zamtel)
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: From a Zamtel SIM card I purchased and owned
*   Authoritative evidence (e.g. national numbering plan, operator announcement): https://www.zicta.zm/Downloads/Numbering%20Plan.pdf
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B260956459559

**Comment by kkeshava** [comment]
@dinebennett @bineyame @
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by dinebennett** [comment]
Fantastic, thank you @kkeshava

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
