### ISSUE TITLE
Spanish number seen as valid in France and vice versa

### ISSUE THREAD

**Issue by AKFourSeven** [googlei18n/libphonenumber#2010]
Hi, I noticed that when country code was set to France some Spanish phone number could be valid in France. In instances where you absolutely need a local phone number this can prove to be a bit of an issue.

*   Country: FR
*   Example number(s) and/or range(s): 915211201 (ES number), 0123456789 (FR number)
*   Number type ("fixed-line", "mobile", "short code", etc.): "fixed-line" and "mobile" (only ones tested)
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: they were both invented, based on the form of French and Spanish phone numbers
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=915211201&country=FR&geocodingLocale=fr-FR

**Comment by kkeshava** [comment]
@AKFourSeven,

The 'defaultCountry' means the country from where you are calling the number. When dialling 915211201 from Spain, it connects to local fixed-line number. 915211201 is a valid fixed-line number in Spain. See https://en.wikipedia.org/wiki/Telephone_numbers_in_Spain#Area_codes

Similarly for France 915211201 is a valid VOIP number. See https://en.wikipedia.org/wiki/Telephone_numbers_in_France

The numbers can overlap between the regions. It depends on from where you are dialing. 

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by AKFourSeven** [comment]
Okay but from a French standpoint this particular number "915211201" as it is, is viewed as incorrect whereas this one "0915211201" would be correct!
Is there an option to ensure the trunk prefix or force during the validation ?

**Comment by kkeshava** [comment]
@AKFourSeven,
Here '0' is the nationalPrefix and '915211201' is the subscriber number in France. While parsing we are lenient and remove country code, nationaPrefix, internationalPrefix etc. So to validate a number we only use the subscriber number. You can check 'Formatting Results' in [demo](http://libphonenumber.appspot.com/phonenumberparser?number=915211201&country=FR&geocodingLocale=fr-FR) to understand all the different formats.
No, there is not a way to tell the API to require the national-prefix when parsing.
