### ISSUE TITLE
new mobile numbers prefixes in Iran doesn't support

### ISSUE THREAD

**Issue by hfm-android** [googlei18n/libphonenumber#2012]
There are some new mobile numbers prefixes in Iran which libPhoneenumber doesn't support them.
International Communication Union Provides a document in this link :
http://www.itu.int/oth/T0202000066/en
for example 9944 or (09944) is one of them. note that 0 is National Prefix, read general information section.
another numbers are :
99999
99998
...
We need to libPhoneenumber  support all of the valid mobile number prefixes in Iran. Thank you.

**Comment by kkeshava** [comment]
@hfm-android,
Thank you for taking the time to improve libphonenumber! 

We are already supporting 9944, 99999 and 99998 ranges. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).
9944 - http://libphonenumber.appspot.com/phonenumberparser?number=%2B98+9944000000
99998 - http://libphonenumber.appspot.com/phonenumberparser?number=%2B98+9999800000
99999 - http://libphonenumber.appspot.com/phonenumberparser?number=%2B98+9999900000

However there are few other new prefixes that needs to be supported like 991, 993 etc. We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by afarsi** [comment]
For more info, please visit my pull rquest: https://github.com/googlei18n/libphonenumber/pull/2022
Thanks.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
