### ISSUE TITLE
Belarusian life and maxiphone carrier

### ISSUE THREAD

**Issue by mikhailyaskou** [googlei18n/libphonenumber#2016]
*   Country: Belarusian BY
*   Example number(s) and/or range(s): +375 25 333 33 33
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: http://life.com.by
*   Authoritative evidence (e.g. national numbering plan, operator announcement): 
*   Link from demo (http://libphonenumber.appspot.com) showing error:

Hello. There a phone numbers +375 25 xxx xx xx (BY - region) Belarus.
25 - code "life" mobile carrier - does not recognized.
http://life.com.by

and +375 24 xxx xx xx 
24 - code "mixaphone" mobile carrier - does not recognized.
http://www.maxiphone.by

**Comment by kkeshava** [comment]
@mikhailyaskou,
Hi,
Thank you for contributing to libphonenumber!

We can't connect to +375 25 333 33 33. Did you have a typo?

As per official evidence of Belarus http://www.beltelecom.by/en/subscribers/phone-codes we support only 25[5679] prefixes in Mobile and 24[9] prefix as VOIP https://www.beltelecom.by/chasto-zadavaemye-voprosy. 

We need valid evidence to support the remaining prefixes i.e 24[0-8] and 25[0-48]. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
@mikhailyaskou,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 24[0-8] and 25[0-48] are valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
