### ISSUE TITLE
Hong Kong mobile number starting with 4

### ISSUE THREAD

**Issue by eidng8** [googlei18n/libphonenumber#2023]
First, I'm not sure if this is a "bug".

We've having problem with phone numbers starting with `4`, coming from Hong Kong. It seems that the local Authority has release the prefix (such as `4330`, as of http://www.ofca.gov.hk/filemanager/ofca/en/content_311/no_plan.pdf ).

Any suggestion?

**Comment by penmetsaa** [comment]
@eidng8,

Thank you for taking the time to improve libphonenumber!

- As per the above doc from OFCA, only 4647 and 4649 mobile ranges are assigned to specific operators. So we will add support to these mobile range.
- Presently, we do not support Machine-to-Machine numbers. See: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers
- 433 mobile range is mentioned as spare. Do you say that these are already assigned?
As per this doc, "Spare" means the applications of the number resources concerned have already been determined and these number resources are made available for future allocation/assignment
- Not sure of category of phone numbers that are mentioned as "Other". So we have not added support to these.

We need more information to fix this (last two point). Please share any working numbers or evidence you may have. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by eidng8** [comment]
Thank you for your clarification. We'll close this issue for the moment. We'll submit a working number here again, when we got one.

**Comment by penmetsaa** [comment]
@eidng8,
As mentioned in my last comment, we will add support to 4647 and 4649 mobile ranges.
Reopening this issue to track same. Will update and close this issue once the fix is released.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
