### ISSUE TITLE
Metadata for Guam numbers +1 671-682-XXXX

### ISSUE THREAD

**Issue by tanelsuurhans** [googlei18n/libphonenumber#2024]
It looks like some Guam numbers are still not validating properly, like ones starting with 671-682.
As per https://www.area-codes.com/exchange/exchange.asp?npa=671&nxx=682 it is a valid code.

Based on the online demo it returns these numbers to be invalid.

Seems like the metatdata needs an update.

**Comment by penmetsaa** [comment]
@tanelsuurhans,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This is now fixed as part of release 8.8.7.
