### ISSUE TITLE
Validation issue with 0116685122 (MY)

### ISSUE THREAD

**Issue by nichucs** [googlei18n/libphonenumber#2025]
PhoneNumberUtil.isPossibleNumber - returns - true
But
PhoneNumberUtil.isValidNumber - returns - false
Country - Malaysia
Could you please inspect?

**Comment by penmetsaa** [comment]
@nichucs,
Thank you for taking the time to improve libphonenumber!

We can't connect to number provided. Did you have a typo? We can't support single numbers, we need context about the prefix and category that makes them valid. Please share any valid evidence which mentions this range. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Note: We already support 10 digit 116[1-9]X and 1160[5-9] ranges under mobile based on the below official sources.
1. Mobile (10 digits): https://www.mcmc.gov.my/skmmgovmy/media/General/pdf/Mobile-Numbers-(3-8)-2017.pdf
2. Mobile (9 digits): https://www.mcmc.gov.my/skmmgovmy/media/General/pdf/Mobile-Numbers-(3-7)-2017.pdf

**Comment by nichucs** [comment]
Ok.. got it. 0116685122 is not a real number. Thought only the number of digits is what makes the number valid. Sorry for the trouble. You can close the ticket.

**Comment by penmetsaa** [comment]
@nichucs,
Thanks for checking and closing the issue :)
