### ISSUE TITLE
International Dialing QRG

### ISSUE THREAD

**Issue by DorisRES** [googlei18n/libphonenumber#2031]
Hello,

Do you possibly have a quick reference guide for international dialing rules that are exceptions? For example, Italy landline codes use a zero after the country code, but Italian cellular/SMS do not . Mexico requires a 1 after the country code to call a cellular phone but not for a landline call or SMS.

Thanks,
Doris

**Comment by keghani** [comment]
Hi @DorisRES,

We don't have comprehensive guidelines for all regions. We aim to solve everything in the library where possible so users of the library don't need this knowledge. For example, we will automatically format numbers as expected, and have methods such as [formatNumberForMobileDialing](https://github.com/googlei18n/libphonenumber/blob/v8.8.6/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1373) for specific use cases.

For the cases we can't solve in our library, we provide a [FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-is-this-number-from-argentina-ar-or-mexico-mx-not-identified-as-the-right-number-type).

I'll close this as it's not an issue with library. Please consider posting further questions to the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

**Comment by DorisRES** [comment]
Thanks very much Keghani -- for both the response and the direction on the discussion group for future reference.

**Comment by DorisRES** [comment]
Thanks very much Keghani -- for both the response and the direction on the discussion group for future reference.
