### ISSUE TITLE
Validation issue for 116123 in GB

### ISSUE THREAD

**Issue by oksanaut** [googlei18n/libphonenumber#2032]
Samaritans provides suicide prevention support, their helpline number in IE and GB is 116123. 

[Samaritans.org helpline number FAQ](https://www.samaritans.org/how-we-can-help-you/samaritans-free-call-helpline-number-faqs)

From [demo](http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html):

IE/GB:
```
****Parsing Result:****
{"country_code":44,"national_number":116123,"raw_input":"116123","country_code_source":20}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: null
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: 116123
National format: 116123
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

****AsYouTypeFormatter Results****
Char entered: 1 Output: 1
Char entered: 1 Output: 11
Char entered: 6 Output: 116
Char entered: 1 Output: 1161
Char entered: 2 Output: 11612
Char entered: 3 Output: 116123
```

edit: confusing country codes 🌵

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

This is actually working as intended; 116123 is already marked by the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=116123&country=GB) as a
valid *short* number. For more information, check out [this FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-phonenumberutil-return-false-for-valid-short-numbers)
