### ISSUE TITLE
Validation issue with +254747585134 (KENYA)

### ISSUE THREAD

**Issue by cronogit** [googlei18n/libphonenumber#2037]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): KENYA

Example number(s) affected ("+1 555 555-1234"): +254747585134

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +254 747 xxx

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B254747585134&country=KENYA&geocodingLocale=kenya)

**Comment by SumathiSundara** [comment]
I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
