### ISSUE TITLE
Libraries getting installed in lib64 by default

### ISSUE THREAD

**Issue by ilovezfs** [googlei18n/libphonenumber#2044]
It seems lib64 rather than lib has suddenly become the default as of 8.8.7. I understand that this may be useful on Linux as an option, but it's rather odd default behavior for macOS. Is this something we need to override manually downstream or has something gone awry with the defaults?

Ref https://github.com/Homebrew/homebrew-core/pull/21274

**Comment by ilovezfs** [comment]
Note that it appears MacPorts is using a downstream patch to hack around this already: https://github.com/macports/macports-ports/blob/master/devel/libphonenumber-cpp/files/patch-cpp-CMakeLists.txt.diff

In Homebrew, that is not something we will do unless the patch is actually going to be upstreamed, and at least in its current form that doesn't appear possible since it's unconditionally setting FIND_LIBRARY_USE_LIB64_PATHS FALSE, which wouldn't be the expected behavior on :penguin:. CC @dbevans

**Comment by ilovezfs** [comment]
I've opened https://github.com/googlei18n/libphonenumber/pull/2045 with a suggested fix.

**Comment by andyst** [comment]
Hi @ilovezfs, a C++ expert gave me the following advice:

> This is unfortunately not as simple as choosing between lib/ and lib64/, if for example someone of you happens to have a fresh install of gLinux Rodete I guess you'd find your 64-bit libraries in lib/x86_64-linux-gnu/ there instead.
> 
> This isn't logic that I think you should try to implement yourself. Instead, I'd recommend you to rewrite your CMakeLists.txt to use the CMake standard module GNUInstallDirs, introduced in CMake v2.8.5, and get the value of LIBDIR from there:
> 
> https://cmake.org/cmake/help/v2.8.5/cmake.html#module:GNUInstallDirs
> 
> (That'd require you to bump the minimum required CMake version from v2.8 to v2.8.5 but considering that this still is an over 6 years old release and the latest CMake release now is v3.10.0 that is still to offer a lot of backward compatibility.)
>
>  By depending on the LIBDIR value from GNUInstallDirs for the name of you libraries directory any user with a sufficiently updated CMake ought to get the correct path (including things like lib/x86_64-linux-gnu/ for Rodete).

What do you think? That'd be a more robust fix. Can you implement the proposal?

Thank you!

**Comment by ilovezfs** [comment]
@andyst I have updated https://github.com/googlei18n/libphonenumber/pull/2045 to implement that proposal.
