### ISSUE TITLE
New Number Prefixes for Philippines

### ISSUE THREAD

**Issue by ekimual** [googlei18n/libphonenumber#2046]
I am currently using this library and I guess its really helped me a lot in validating mobile phone numbers. I guess some should be updated and in PH we have some new prefixes, refer to list in the [link](https://www.prefix.ph/smart-users/updated-complete-list-mobile-prefixes-philippines-2017/)

Thanks!

**Comment by kkeshava** [comment]
Thank you for taking the time to improve libphonenumber!

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

In particular, we request you to provide a national numbering plan, announcements from mobile carriers, news articles etc. We cannot consider https://www.prefix.ph/smart-users/updated-complete-list-mobile-prefixes-philippines-2017/ as official document. It looks like an app for android and ios phones to sort out contacts according to network.

**Comment by kkeshava** [comment]
We are now tracking this via Google's Issue Tracker at the following URL as
we are (slowly) transitioning to this platform for tracking issues:

https://issuetracker.google.com/issues/70914492
