### ISSUE TITLE
OSGI Buncle packaging

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#205]
Imported from [Google Code issue #205](https://code.google.com/p/libphonenumber/issues/detail?id=205) created by [reda.bendiar](https://code.google.com/u/112954534242903792131/) on 2012-10-17T17:03:31.000Z:

----
Is it possible to have the java version packaged as osgi bundle ?

**Comment by keghani** [comment]
I don't know whether a CLA was signed for that patch, or whether it's enough for the process to be automatic along with our regular releases.
I'll close this issue as there hasn't been interest or contributions since we moved to GitHub.
Please re-open if you can help!

**Comment by frett** [comment]
I'm looking to utilize this library in an OSGi environment, so I resurrected the patch and made a couple minor adjustments
