### ISSUE TITLE
Togo Togo Cell new prefix - 7 -  is not recognized 

### ISSUE THREAD

**Issue by mcmell** [googlei18n/libphonenumber#2052]
Togo Cell added a new prefix +228 70 prefix. 
This prefix is not being recognized. 

Can you update this issue in the next version?

Document: 
http://lavoixdelanation.info/tag/70-sintroduit-dans-la-numerotation-de-togocel/
http://news.alome.com/h/96707.html#

**Comment by kkeshava** [comment]
Hi,
Thank you for contributing to libphonenumber!

We can't find official evidence for the actual ranges that are valid under prefix 70. We can't support single numbers, we need context about the prefix that makes them valid. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by mcmell** [comment]
Thats an article from a news website:

http://news.alome.com/h/96707.html#

**Comment by kkeshava** [comment]
@mcmell,
We actually need more evidence. Would you mind sharing any working number that you may have with a photo of SIM card as evidence?

**Comment by mcmell** [comment]
Hi kkeshava, 

SIM card proof: 
![new prefix](https://user-images.githubusercontent.com/34334791/33840982-1c3efed0-de9f-11e7-8580-a030afcf8b21.jpeg)

**Comment by penmetsaa** [comment]
@mcmell,
Thanks for providing all the details we need! We've accepted this issue;
however, we are now in a release freeze period and won't be releasing this
before second week of January 2018.

Please note that you have submitted this information with the knowledge that
we may use, modify, reproduce, publicly display, and distribute the information
in accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by mcmell** [comment]
Hi @penmetsaa , 

Yes, please use the following number as an evidence and help us to recognize this new prefix.

**Comment by penmetsaa** [comment]
This will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.
