### ISSUE TITLE
Incorrect country code for Netherlands Antilles

### ISSUE THREAD

**Issue by gourisar** [googlei18n/libphonenumber#2053]
Incorrect country code for Netherlands AntillesHi,
We are using libphonenumber to fetch the list of the country codes. We are getting the country code for Netherlands Antilles as +0 however the correct country code for this is +599.
Has something changed recently?
Let me know if I am missing something here.

**Comment by kkeshava** [comment]
@gourisar,
Thank you for taking the time to improve libphonenumber!

We do not have a region for 'Netherlands Antilles' in our library as it was dissolved in [10th October 2010](https://en.wikipedia.org/wiki/Netherlands_Antilles). So [getCountryCodeForRegion](https://github.com/googlei18n/libphonenumber/blob/8e2f1d2c87a19299a5c3bfce44e62dc2ba32a5b6/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2353) method will not return country code for it. We have maintained separate regions for 'Curaçao (CW)' and 'Bonaire, Sint Eustatius & Saba (BQ)', and these use the country code +599. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
