### ISSUE TITLE
Relience Jio number is not validating using PhoneNumberUtils plugin

### ISSUE THREAD

**Issue by aroonkv** [googlei18n/libphonenumber#2055]
Hi,

I am using libphonenumber-7.7.5, but the issue still exists. My number is 8848154508.
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
PhoneNumber numberProto = phoneUtil.parse(phone, phoneUtil.getRegionCodeForCountryCode(Integer.parseInt(phoneCallingCode)));
phoneUtil.isValidNumber(numberProto) returns false.

Please help me to resolve this issue.

**Comment by kkeshava** [comment]
@arnoonkv,
As mentioned in #1420, this is actually working as intended; 8848154508 is already marked by
our library as MOBILE. Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=8848154508&country=IN).

Please upgrade to the latest release (8.8.8), this is not a live issue. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by aroonkv** [comment]
Thank you so much for the reply.

The demo application is using phoneUtil.parseAndKeepRawInput() method. But I think this method is not available in libphonenumber-7.7.5 jar. So in which version of plugin parseAndKeepRawInput()  is available?

**Comment by penmetsaa** [comment]
@aroonkv,

Thank you for using libphonenumber!

[PhoneNumberUtil.parseAndKeepRawInput() API](https://github.com/googlei18n/libphonenumber/blob/3db7670b42c4c03c3d69d9ed43cfe15fde978c5e/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3043) is part of the libphonenumber jar. It is same as [PhoneNumberUtil.parse() API](https://github.com/googlei18n/libphonenumber/blob/3db7670b42c4c03c3d69d9ed43cfe15fde978c5e/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3013) except that it saves the raw input in the proto. However these parsing APIs have nothing to do with validation of the phone numbers in this case. 

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the [demo results](http://libphonenumber.appspot.com/phonenumberparser?number=8848154508&country=IN). See instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md). Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by aroonkv** [comment]
Thank you so much. It is working fine after upgrading to version 8.8.8.
