### ISSUE TITLE
libphonenumber can format some mobile prefixes but cannot understand they are valid

### ISSUE THREAD

**Issue by hfm-android** [googlei18n/libphonenumber#2057]
Hi, the libphonenumber can format numbers with these mobile prefixes by  format method : 

//99810 - 099999 - 099998 - 099914 - 09991

`PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();`
`Phonenumber.PhoneNumber pn = phoneUtil.parse( ... , "IR");`
`phoneUtil.format(pn, PhoneNumberUtil.PhoneNumberFormat.E164);`

but when I use isValid method, it returns false.

`phoneUtil.isValidNumber(pn)`

The prefixes related to some of Iranian MVNO and I sure some of them like 099999 and 099998 added to libphonenumber in last release. 
Please see this link :
https://github.com/googlei18n/libphonenumber/pull/2022

**Comment by penmetsaa** [comment]
@hfm-android,
Thank you for taking the time to improve libphonenumber!

We already support "99810 - 099999 - 099998 - 0999140" ranges. See our demo results at https://libphonenumber.appspot.com/phonenumberparser?number=99810+12345&country=IR Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the demo portal.

Reg range 9991:
We do support 9991[14] mobile ranges based on the official evidences found. Do you say that all 9991 mobile ranges are assigned? Please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by hfm-android** [comment]
Hi @penmetsaa , I double check my unit tests, and you're right.please close this issue. I try to find out why 9991 doesn't in ITU documnet and then open a new issue for that prefix. thank you so much.

**Comment by penmetsaa** [comment]
@hfm-android,
Thanks so much for quick checks. :)

For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.
