### ISSUE TITLE
ArgumentOutOfRangeException when testing UK mobile number without country code

### ISSUE THREAD

**Issue by obkdev** [googlei18n/libphonenumber#2059]
When attempting to find the country code of a UK mobile number with no country code, an ArgumentOutOfRange exception is thrown. I would have expected a result of 0.

```
var number = "07545454545";
var builder = new PhoneNumber.Builder();
var numberToFill = new StringBuilder();
var phoneUtil = PhoneNumberUtil.GetInstance();
var countryCode = phoneUtil.MaybeExtractCountryCode(number, PhoneMetadata.DefaultInstance, numberToFill, true, builder);
```

**Comment by andyst** [comment]
What's the environment, which programming language do you use?

**Comment by andyst** [comment]
Closing it for now due to inactivity. Feel free to reopen it if you have more context (see my question above).

BTW: The issue tracker will be turned off for the holiday season.
See: https://groups.google.com/d/msg/libphonenumber-discuss/8dqzzlE2FMo/a4cnfWCdCwAJ
