### ISSUE TITLE
Exctracting country calling code with AsYouTypeFormatter 'on the fly'

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#206]
Imported from [Google Code issue #206](https://code.google.com/p/libphonenumber/issues/detail?id=206) created by [cyrille.voluter](https://code.google.com/u/108603864444827375268/) on 2012-10-23T12:24:26.000Z:

----
Presently, AsYouTypeFormatter can format phone number 'on the fly' but it can't extract country calling code in same conditions.

**Comment by keghani** [comment]
The AYTF is only intended for formatting.
For parsing and getting the country calling code (or national number or something else) of a phone number, use [PhoneNumberUtil](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java).
