### ISSUE TITLE
Duplicate namespace in metadatafortesting.js

### ISSUE THREAD

**Issue by jamesspencer** [googlei18n/libphonenumber#2060]
The [metadatafortesting.js](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadatafortesting.js#L24) file uses the same namespace as the production data file [metadata.js](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/metadata.js#L24).

This can cause test data to be used when building for production using Google Closure Compiler.

**Comment by andyst** [comment]
That's working as intended.

https://github.com/googlei18n/libphonenumber/blob/64e4d0ca94e5ddd3cad6b0f963661229aef10b88/javascript/build.xml

In tests which use dummy data, you will include metadatafortesting.js (e.g. see javascript/i18n/phonenumbers/phonenumberutil_test.html and javascript/build.xml).

And in prod code you include the real metadata.js.

Feel free to reopen if this doesn't answer the issue. Please include more context / details how this is causing an issue for you in that case.
