### ISSUE TITLE
Validation Issue with Icelandic Number +354 837 xxxx

### ISSUE THREAD

**Issue by throwanexception** [googlei18n/libphonenumber#2061]
*   Country: Iceland
*   Example number(s) and/or range(s): +354 837 xxxx (e.g. +354 837 1234)
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   Authoritative evidence (e.g. national numbering plan, operator announcement): 
Icelandic Numbering Plan:
https://www.pfs.is/library/Skrar/Tidnir-og-taekni/Numeramal/ISL-ENSKT%20Q_ISL_EN_1-909102017.xlsx
https://www.pfs.is/english/telecom-affairs/numbering/

A Google search for "+354 837" shows a couple Icelandic businesses actively using this scheme.

I also have a customer with a number that starts with "+354 837" which is what lead me to file this in the first place.

*   Link from demo (http://libphonenumber.appspot.com) showing error:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B354+837+1234

**Comment by throwanexception** [comment]
I'm happy to submit a pull request - I did not create one as per CONTRIBUTING.md

**Comment by penmetsaa** [comment]
@throwanexception,
Yes, we do not accept pull requests for validation, formatting, or timezone metadata updates.

Thanks for providing all the details we need! We've accepted this issue; however, we are now in a release freeze period and won't be releasing this before third week of January.

Please note that you have submitted this information with the knowledge that
we may use, modify, reproduce, publicly display, and distribute the information
in accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.
