### ISSUE TITLE
Validation issue with +9779880038640 (NP)

### ISSUE THREAD

**Issue by binokaryg** [googlei18n/libphonenumber#2064]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): NP

Example number(s) affected ("+1 555 555-1234"): +9779880038640

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +977 988 XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
"An NTA source said Smart Telecom has also been given two numbers—8 and 9. These two numbers come after 98. This means mobile numbers of those subscribing to Smart Telecom will begin from 988 and 989."
Source: http://kathmandupost.ekantipur.com/news/2013-09-27/smart-telecom-to-get-new-frequency-number.html

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B9779880038640&country=NP)

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

As we have found IR 21 doc for 988 and will support the same. However, we were unable to get any official evidence for prefix 989 apart from the news article that you have given, and there are no online working numbers were found. 

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
Prefix 988 will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss)
to be notified of the Maven release's completion, or watch the GitHub repository
at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.
