### ISSUE TITLE
It didn't support the 198 section for Chinese mobile 

### ISSUE THREAD

**Issue by songxk** [googlei18n/libphonenumber#2076]
*   Country: China(CN)
*   Example number(s) and/or range(s): 86-19810101010
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions: 
*   Where or whom did you get the number(s) from:
*   Authoritative evidence (e.g. national numbering plan, operator announcement): https://www.chahaoba.com/198
*   Link from demo (http://libphonenumber.appspot.com) showing error:

I just fixed it in my fock repository of libphonenumber(https://github.com/songxk/libphonenumber/commit/b7ab0481e557856b2bcebbd50706d7c4d5d47ca7), can  I send a pull request ?

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We can't connect to 86-19810101010, as well we are unable to find official evidence
for the actual ranges that are valid. We can't support single numbers, we need
context about the prefix that makes them valid.

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

We are not accepting pull requests for such metadata updates at this time. See
our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by songxk** [comment]
http://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057709/n3057716/c5757773/content.html

http://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057709/n3057716/c5757773/part/5757781.pdf
中国工信部的官方资料

**Comment by songxk** [comment]
86-19810101010  this is not a true number,  i have no one with 198 prefix

**Comment by SumathiSundara** [comment]
This will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.
