### ISSUE TITLE
Invalid number in Honduras with correct format  +504 2509 XXXX

### ISSUE THREAD

**Issue by victorpy** [googlei18n/libphonenumber#2080]
Country/region affected (e.g., "US"): Honduras
Example number(s) affected ("+1 555 555-1234"): +504 2509-3300
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +504 2509 - XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line
The cost, if applicable ("toll-free", "premium rate", "shared cost"): n/a
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):
Valid rule for calling honduras with vonage, reference:
http://blog.vonage.com/international-calling/how-to-call-honduras-from-the-us/

also the number of a real company in Choloma, Honduras, reference:
http://concentradosaliansa.com/nuestras-oficinas/

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We were able to connect to +504 2509-3300, but we can't find official evidence
for the actual ranges that are valid. We can't support single numbers, we need
context about the prefix that makes them valid.

Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
We are now tracking this via Google's Issue Tracker at the following URL as
we are (slowly) transitioning to this platform for tracking issues:

https://issuetracker.google.com/issues/70914401
