### ISSUE TITLE
Chile's National phone number format is preceded with zero for Mobile Number Type

### ISSUE THREAD

**Issue by jyotsnagaddam** [googlei18n/libphonenumber#2089]
Please refer https://www.howtocallabroad.com/forums/topic/chile-telephone-numbering-changes (last section)

Changes in the way Chileans dial phone numbers nationally

Over the past several years the Chilean Telecom Authority has implemented some important changes to the country's telephone system.

Here are the changes:

Geographic area codes are now part of the local phone number (this change was implemented in 2014); one can no longer dial just the local number to call locally.
There is no need to use a carrier code to dial between different regions of the country
The trunk code (zero) formerly used to dial phone numbers nationwide has been eliminated

As a conclusion, today all calls dialed within Chile use the 9 digit format.

**Some examples:**

local call to a landline in Arica region
before the change: xxx xxxx
today: 58 xxx xxxx
phone call from Santiago to Arica
before the change: 058 xxx xxxx
today: 58 xxx xxxx
calls between cell phones
before the change: xxxx xxxx
today: 9 xxxx xxxx
call from landline/VoIP to cell phone
before the change: 09 xxxx xxxx
now: 9 xxxx xxxx

Thanks,
Joshna.

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We need official evidence to make the said changes. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Comment by jyotsnagaddam** [comment]
Hi @kkeshava,

Sorry for the delay in the reply. Can you please look into the details provided below if anything helps to address the issue?

*   Country:Chile (CL)
*   Example number(s) and/or range(s):(56) 9 9249 1328
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: Chile yellow pages (http://www.amarillas.cl/b/restaurantes/) I took the first result. (see phone)
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
http://www.subtel.gob.cl/ministro-de-transportes-y-telecomunicaciones-anuncia-el-fin-de-la-larga-distancia-nacional-para-todo-el-pais/
http://nuevaformademarcar.cl/nueva-forma-de-marcar/
https://en.wikipedia.org/wiki/Trunk_prefix#Countries_no_longer_using_a_national_trunk_prefix
https://en.wikipedia.org/wiki/Telephone_numbers_in_Chile
http://personas.entel.cl/PortalPersonas/appmanager/entelpcs/personas?_nfpb=true&_pageLabel=P53800170611354890764416&c=1#faq-box
Please see both sections:
How to call cell Phones?
How to make national phones?
Note: Took the reference of Subtel.cl and entel.cl as they are mentioned in https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200002A0002PDFE.pdf
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2856%29+9+9249+1328&country=CL
Please see the 'National format' under 'Formatting Results' table which is 09 9249 1328, it should be 9 9249 1328 based on the evidence provided here.

Thanks,
Joshna.

**Comment by jyotsnagaddam** [comment]
@kkeshava, based on the above comments can you please reopen the issue, I am not seeing an option to do so.

Thanks,
Joshna.

**Comment by kkeshava** [comment]
@jyotsnagaddam,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by jyotsnagaddam** [comment]
@kkeshava,

Thanks for validating the information provided and taking it further to include the fix in the next release. I have quick follow-up question about the next release. I see it is mentioned that releases will happen fortnightly that means this fix will come between Feb 21 to 23 time frame right?

Thanks,
Joshna.

**Comment by kkeshava** [comment]
@jyotsnagaddam,
This will be part of our next release i.e March 6th - 8th, 2018.

**Comment by jyotsnagaddam** [comment]
Thanks for the update @kkeshava

**Comment by kkeshava** [comment]
Fixed in release 8.9.1.
