### ISSUE TITLE
Validation issue for number +252 41874120

### ISSUE THREAD

**Issue by aleksvu** [googlei18n/libphonenumber#2091]
According to the metadata this phone number shouldn't exist, but we have received some phone calls from it. It seems like (considering the behavior of the call) some IP phone number used for fraud. 
However this number should be validated as possible.

**Comment by kkeshava** [comment]
Thank you for taking the time to improve libphonenumber!

We were unable to connect to +252 41874120 and also can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.
Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by mimckenna** [comment]
+1 on the response. We rely on the libphonenumber validation and have found several bot-generated numbers that "look" right, but went to invalid prefixes or city codes.  These are indeed used for fraud.

**Comment by kkeshava** [comment]
Hi,

As these numbers are used by some IP to make fraudulent calls, invalidating these numbers in our library seems right. May be the hackers are using some method to make use of these numbers for their fraud calls so the issue should be reported to the Somalia’s telecom authority. We will not be able to do anything in such scenarios.

I'll close this as it's not an issue with the library.
