### ISSUE TITLE
Valid phone number with non-number characters

### ISSUE THREAD

**Issue by JochemG** [googlei18n/libphonenumber#2092]
### Steps to reproduce
1.  https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
2.  Use the following string as a the phone number: "+32 475 qsdfqs"

### Expected behaviour
The number should be invalid

### Actual behaviour
The number is valid even though it clearly contains characters.

Is this a bug or feature? 

Kind regards.
-J

**Comment by kkeshava** [comment]
@JochemG,
Thanks for reporting this! This is actually addressed in our documentation:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits

As a result, we'll close this issue, but let us know if we may clarify the answer and update documentation.
