### ISSUE TITLE
Canada 1 800 numbers?

### ISSUE THREAD

**Issue by ahtremblay** [googlei18n/libphonenumber#2093]
Hello, it appears that all 1 800 numbers (even those originating from Canada) are displayed as US-incoming call. Thus, clients who receive such calls assume it is from a US company rather than a Canadian company. Thus, they become suspicious of the call - "why would their phone show a Canadian company as calling in from the US?".

Is this something that can be fixed? For example, is there a prefix following the 1 800 numbers that can be used to tag the call to the country? If so, what is this prefix?

I have quickly looked through the code and it appears to me that all 1 800 numbers are tagged to US.

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

All NANPA countries share the same non-geographic number ranges as US which includes toll free ranges i.e 800, 833, 844 etc, see https://www.nationalnanpa.com/enas/nonGeoNpaServiceReport.do. We do not have internal information of which particular prefixes are assigned to a particular country.

**Comment by kkeshava** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
