### ISSUE TITLE
Cape Verde : add +238 5 XXXXXX as mobile numbers

### ISSUE THREAD

**Issue by alfh** [googlei18n/libphonenumber#2095]
*   Country:
Cape Verde
*   Example number(s) and/or range(s):
 +238 5X XXXXX, but more specifially +238 53 XXXXX, and most specifically +23853048xx (last two digits removed for pricay reasons)
(I do not know the operator/carrier for the 23853 xxxxx range, I suspect it to be http://www.uniteltmais.cv, which seems to be the second operator in Cape Verde)
*   Number type ("fixed-line", "mobile", "short code", etc.):
mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from:
From log files.
*   Authoritative evidence (e.g. national numbering plan, operator announcement):
http://www.itu.int/oth/T0202000026/en (the same link as in the PhoneNumberMetadata.xml), has the following section:
"
Communication of 15.IV.2010:
The Agência Nacional das Comunicações (ANAC), Praia, announces the opening of a new level in
the National Numbering Plan (NNP) for the Mobile Cellular Service.
Until now the dialling code for the mobile cellular service of Cape Verde has been: +238 9X XXXXX. From
now on, the following new level will also be in force: +238 5X XXXXX
Operator Service Number series
CVMóvel Mobile 59 XXXXX
International dialling format for the mobile service: +238 5X XXXXX; +238 9X XXXXX 
"

*   Link from demo (http://libphonenumber.appspot.com) showing error:
http://libphonenumber.appspot.com/phonenumberparser?number=5304800&country=CV

From git
{code}
      <mobile>
        <possibleLengths national="7"/>
        <exampleNumber>9911234</exampleNumber>
        
        <nationalNumberPattern>
          (?:
            9\d|
            59
          )\d{5}
        </nationalNumberPattern>
      </mobile>
{code}

So the comment " It seems, contrary to their numbering plan, the entire 9X range is used for mobile
             phones. SMS messages has been successfully sent to numbers starting with 95 and 97 for
             example, and there are plenty of numbers on the internet that start with these
             prefixes."
seems invalid after the official documentation "Communication of 15.IV.2010:"

And the regexp only seems to cotain the "59 xxxxx" series listed in http://www.itu.int/oth/T0202000026/en. But I've seen the "53 xxxxx" in actual use.

**Comment by penmetsaa** [comment]
@alfh,
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This will be fixed as part of next release!

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion,
or watch the GitHub repository at https://github.com/googlei18n/libphonenumber
to be notified when we publish the new release notes there.
