### ISSUE TITLE
Issue with Palau (PW) Number Validation

### ISSUE THREAD

**Issue by ajpuglis** [googlei18n/libphonenumber#2096]
*   Country: PW / Palau
*   Example number(s) and/or range(s): Details Below
*   Number type ("fixed-line", "mobile", "short code", etc.): fixed-line and mobile
*   For short codes, cost and dialing restrictions: N/A
*   Where or whom did you get the number(s) from: Customer
*   Authoritative evidence (e.g. national numbering plan, operator announcement): http://www.itu.int/oth/T02020000A2/en
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B6807762132&country=PW

**Numbers and Ranges that are incorrect according to the authoritative evidence:**

The following NDC / NSNs for Mobile Telephony Services are missing: 770, 771, 772, 773, 776, 880, 881, 882 ,883, 884

The NDC / NSN for Fixed Telephony Services is missing: 900 
900 is for `PNCC/Operator Services`

Finally, it appears that the first regex for Mobile Numbers may be incorrect: 

> 6[234689]0

 as I'm not seeing any NDC/NSN in the numbering plan according to the authoritative evidence.

**Comment by penmetsaa** [comment]
@ajpuglis,
This will be fixed as part of next release.

Please remember to join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.
