### ISSUE TITLE
Cape Verde numbers starting with 5

### ISSUE THREAD

**Issue by qinxi-microsoft** [googlei18n/libphonenumber#2100]
Currently, the numbers for Cape Verde that start with 5 (valid since 2010 according to [the ITU documentation](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000260001PDFE.pdf)), except those starting with 59, are being recognized as invalid by libphonenumber-csharp. I wonder if this is an issue in libphonenumber and libphonenumber-csharp alike, and if yes, whether this could be fixed in the near future. Thanks in advance! (Also I've posted the same issue in libphonenumber-csharp, without receiving any reply.)

**Comment by penmetsaa** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in next release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.

We do not maintain libphonenumber-csharp third party port of libphonenumber, they need
to update their library after our next release.

As a result, we'll close this issue, and we encourage you to reach out to the
third party port owner, which can be found in our section on [Third Party Ports](https://github.com/googlei18n/libphonenumber#third-party-ports).
