### ISSUE TITLE
Validation issue with +60184694328 (MY)

### ISSUE THREAD

**Issue by titanium29** [googlei18n/libphonenumber#2102]
Fail to validate this valid mobile number

**Comment by penmetsaa** [comment]
Thank you for using libphonenumber!

This is actually working as intended; +60184694328 is already marked by
our library as valid. To check the latest behavior for yourself  (we update metadata
frequently), see the [demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B60184694328 (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

If there is a specific range that you think we should update and don't do so
in the demo highlighted above, please file a new issue with details. See our
[contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to determine whether something is a real issue, and the
details we need to be able to fix it.
