### ISSUE TITLE
NumberPlan changes from 01-Feb-2018

### ISSUE THREAD

**Issue by jbogdanov** [googlei18n/libphonenumber#2103]
[NumberPlan Changes 01-Feb-2018.xlsx](https://github.com/googlei18n/libphonenumber/files/1664467/NumberPlan.Changes.01-Feb-2018.xlsx)

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

In particular, we request a publicly available URL or that you sign the CLA and
(after getting whitelisted) share non-public evidence with the mailing list only
readable by core team members.

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
