### ISSUE TITLE
use libphonenumber get a carrier name which is not supported now

### ISSUE THREAD

**Issue by Chen-Luo** [googlei18n/libphonenumber#2106]
I use `PhoneNumberToCarrierMapper.getInstance().getNameForNumber` to get the carrier name.
When the number is belong to Côte d'Ivoire which country code is 225, and then start by 65, 66 or 67, the method will return "Koz" which is not working anymore.
22567|Orange
22568|Orange
22569|Orange
22564|MTN
22565|MTN
22566|MTN
Should it be changed or how can I change the operator name reutrned by myself?

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.
