### ISSUE TITLE
New mobile ranges for GP

### ISSUE THREAD

**Issue by jice** [googlei18n/libphonenumber#2111]
*   Country: Guadeloupe, Saint-Martin, Saint-Barthélemy (GP, MF, BL)
*   Example number(s) and/or range(s): +590691
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: synthesized from correct format
*   Authoritative evidence (e.g. national numbering plan, operator announcement): National Numbering Plan https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf  (see table on page 23)
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B590691000000

**Comment by kkeshava** [comment]
@jice,
Thank you for taking the time to improve libphonenumber!

We are already supporting few ranges under prefix 691 i.e 6912[29] and 6913[0-5] based on XL sheet given in ITU doc https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000580002PDFE.pdf. The XL sheet is also from arcep.fr which is the official numbering authority. 
The evidence provided by you is very generic. If you want us to support remaining sub ranges, we request you to provide online working numbers or official evidence. Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by jice** [comment]
@kkeshava 
Sorry, I didn't realize this library was keeping track of every allocation made to operators.

The spreadsheet you refer to is indeed the official source for allocation to operators (which can be tedious to keep track of as it is updated twice a month). The ranges you list do cover every allocation in the 691 prefix to this day.
Thanks

**Comment by kkeshava** [comment]
@jice,
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
