### ISSUE TITLE
New mobile ranges for MQ

### ISSUE THREAD

**Issue by jice** [googlei18n/libphonenumber#2112]
*   Country: Martinique (MQ)
*   Example number(s) and/or range(s): +596697
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: synthesized from correct format
*   Authoritative evidence (e.g. national numbering plan, operator announcement): National Numbering Plan https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf  (see table on page 23)
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B596697000000

**Comment by kkeshava** [comment]
@jice,
Thank you for taking the time to improve libphonenumber!

We are already supporting 69727 based on XL sheet given in ITU doc https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000860002PDFE.pdf. The XL sheet is also from arcep.fr which is the official numbering authority.
The evidence provided by you is very generic. If you want us to support remaining sub ranges, we request you to provide online working numbers or official evidence. Please see our guidelines.

**Comment by jice** [comment]
@kkeshava 
Sorry, I didn't realize this library was keeping track of every allocation made to operators.

If you are already tracking the spreadsheet you referred to for changes, then it's all good. You are correct about the fact that 69727 is the only allocated sub-range allocated in the 697 range at this time.

**Comment by kkeshava** [comment]
@jice,
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
