### ISSUE TITLE
Personal (fixed-line) number ranges in GP, MQ, GF, RE

### ISSUE THREAD

**Issue by jice** [googlei18n/libphonenumber#2113]
*   Country: Guadeloupe, Saint-Martin, Saint-Barthélemy (GP, MF, BL), French Guiana (GF), Martinique (GF), Reunion, Mayotte (RE, YT)
*   Example number(s) and/or range(s): +590976, +594976, +596976, +262976
*   Number type ("fixed-line", "mobile", "short code", etc.): fixed-line
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: synthesized from correct format
*   Authoritative evidence (e.g. national numbering plan, operator announcement): National Numbering Plan https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf  (see table on page 43)
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B590976000000
http://libphonenumber.appspot.com/phonenumberparser?number=%2B594976400000
http://libphonenumber.appspot.com/phonenumberparser?number=%2B596976600000
http://libphonenumber.appspot.com/phonenumberparser?number=%2B262976200000

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

The French territory numbers in our metadata are based on the sheet which is also from arcep.fr linked in ITU Doc https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000580002PDFE.pdf as it clearer. The doc given by you mentions the numbers as non geographic numbers even though they are fixedline / geographic numbers which is contradicting.

Also the input given by you in the demo seems to be wrong. For eg. Guadeloupe’s country calling code (CC) is +590 and the national destination code (NDC) is also 590 for fixed-line numbers (690 and 691 for mobile), so the input should be +590 590 976 000 which is already a valid number in our library. Please see demo http://libphonenumber.appspot.com/phonenumberparser?number=%2B590+590+976+000

Same applies for other french territories as well.
Martinique: CC - 596 NDC - 596 (for fixed-line), +596 596 976 000 http://libphonenumber.appspot.com/phonenumberparser?number=%2B596+596+976+000
Réunion: CC - 262 NDC - 262 (for fixed-line), +262 262 976 000 http://libphonenumber.appspot.com/phonenumberparser?number=%2B262+262+976+000

**Comment by jice** [comment]
The ITU Doc you referred to describes the correct format.

https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000580002PDFE.pdf

There is no extra '590' to add after the country code for those numbers. Those NSNs start with 976 and are 9-digit long, as indicated in the table from the ITU Doc. Thus the resulting international format is indeed +590 976 XXXXXX.

There is no contradiction between fixed-line and non-geographic. A number can be a fixed-line and be non-geographic (i.e. bear no geographic indication in its structure), like is the case for 976 numbers. Mobile numbers on the other hand are always non-geographic in the French numbering plan.

You can find allocations made by ARCEP in the 976 range in their spreadsheet (currently at lines 24350 to 24385) and notice in columns "Tranche_Debut" (Beginning of block) and "Tranche_Fin" (End of block) that they are indeed 10-digit numbers  (9-digit NSNs).

https://extranet.arcep.fr/portail/LinkClick.aspx?fileticket=PBA1WK-wnOU%3d&tabid=217&portalid=0&mid=850

Adding an extra '590' after the country code would be in contradiction with the ITU Doc, and would cause the E.164 number to be 16 digits in length, which is forbidden by the E.164 specification.

**Comment by mizuni** [comment]
Hi jice,
We've moved the issue to here: https://issuetracker.google.com/issues/74517446
I've migrated the history, too.
