### ISSUE TITLE
Formatting error for GP numbers

### ISSUE THREAD

**Issue by jice** [googlei18n/libphonenumber#2114]
*   Country: Guadeloupe, Saint-Martin, Saint-Barthélemy (GP, MF, BL)
*   Example number(s) and/or range(s): +590
*   Number type ("fixed-line", "mobile", "short code", etc.): fixed-line, mobile
*   For short codes, cost and dialing restrictions: n/a
*   Where or whom did you get the number(s) from: synthesized from correct format
*   Authoritative evidence (e.g. national numbering plan, operator announcement): common usage, the formatting rules for GP numbers should be consistent with the other French overseas territories (MQ, GF, RE), all managed by the same authority (ARCEP) under a common numbering plan https://www.arcep.fr/uploads/tx_gsavis/05-1085.pdf
*   Link from demo (http://libphonenumber.appspot.com) showing error:  

http://libphonenumber.appspot.com/phonenumberparser?number=%2B590590300000 (fixed-line)
is formatted as +590 590 30-0000
should be formatted as +590 590 30 00 00

http://libphonenumber.appspot.com/phonenumberparser?number=%2B590690000000 (mobile)
is formatted as +590 690 00-0000
should be formatted as +590 690 00 00 00

The following examples show the correct formatting for French overseas numbers (examples from Martinique, French Guiana, Reunion) that should be applied to Guadeloupe
http://libphonenumber.appspot.com/phonenumberparser?number=%2B596596300000
http://libphonenumber.appspot.com/phonenumberparser?number=%2B594594300000
http://libphonenumber.appspot.com/phonenumberparser?number=%2B262262300000

**Comment by kkeshava** [comment]
Hi jice, please follow this issue in Issue Tracker going forward as we are now closing GitHub: https://issuetracker.google.com/issues/74518936 Using Issue Tracker will enable to us to get back to you more efficiently as we align GitHub user issues with ones reported at Google.
