### ISSUE TITLE
Validation issue with 1-800-100-8731 (US)

### ISSUE THREAD

**Issue by hsyed11** [googlei18n/libphonenumber#2116]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): 1-800-100-8731

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=1-800-100-8731&country=US)

**Comment by kkeshava** [comment]
@hsyed11,
Thank you for taking the time to improve libphonenumber!

We can't connect to +1-800-100-8731. Did you have a typo? 

We support 800 [2-9]XX XXXX ranges as toll free numbers based on NANPA official website https://www.nationalnanpa.com/enas/nonGeoNpaServiceReport.do. 

Please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
