### ISSUE TITLE
Jio New Number ranges - pls update

### ISSUE THREAD

**Issue by DeepakGuptaRelianceJio** [googlei18n/libphonenumber#2119]
Hi 
New number ranges allocated to Jio. Please update yur systems

**Comment by kkeshava** [comment]
Hi,
Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

In particular, we request a publicly available URL or that you sign the CLA and (after getting whitelisted) share non-public evidence with the mailing list only readable by core team members.

Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by mizuni** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). For new issues, please use [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347). Thank you!
