### ISSUE TITLE
may be you can support some phone number ? I testing at 8.8.11 version

### ISSUE THREAD

**Issue by xufanghui** [googlei18n/libphonenumber#2124]
I testing at 8.8.11 version,some phone series type is UNKNOWN. 

I list your cannot support some phone series:

1. Brazil:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil
ten-digit is not support. it is local(fixed) phone number.
as:
+5597916772XX 
result:
phone type is UNKNOWN. 

2.Cameroon
https://en.wikipedia.org/wiki/Telephone_numbers_in_Cameroon
New Number  +237 7xxxxxxx  is not support
as:
+237 7xxxxxxx
result:
phone type is UNKNOWN. 

3.Philippines
https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Philippines
Mobile phone area codes 9xxxxxxxxx is not support
as:
+6399XXXXXXXX
result:
phone type is UNKNOWN. 

4.Mexico/Argentina
https://en.wikipedia.org/wiki/Telephone_numbers_in_Mexico
https://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina
Mexico/Argentina why not using FIXED_LINE?
as:
+529222567XXX
+541122591XXX

result:
phone type is FIXED_LINE. 

5.Sudan
https://en.wikipedia.org/wiki/Telephone_numbers_in_Sudan
9100XXXXXX is not support?
as:
+24910033XXXX
result:
phone type is FIXED_LINE. 

Thanks for your answer. I only just recommendation.

**Comment by kkeshava** [comment]
@xufanghui,
Thank you for taking the time to improve libphonenumber!
For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

1. Brazil
As per the [ITU doc Pg.4/7](https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0003PDFE.pdf), only 97[2-5] 10 digit ranges are valid. The number provided by you is 979 which is not given in the official doc. Please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

2. Cameroon 
As per [ITU Doc Pg. 2/8](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000240001PDFE.pdf) second example + 237 7X XX XX XX becomes + 237 6 7X XX XX XX for a mobile number of the MTN Cameroon network. So now all the numbers in Cameroon start with prefix 6. We do not consider Wikipedia has official evidence for all the countries as they might not have the updated information :)

3. Philippines
We are already supporting +63 99[4-9]XXXXXXX range. This is already inline with [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Philippines). For Philippines we have used Wikipedia as the source to update our library. Could you please mention the exact range that you are facing the issue with?

4. Mexico/Argentina
To understand about Mexico and Argentina phonenumbers, I request you to go through our [FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-is-this-number-from-argentina-ar-or-mexico-mx-not-identified-as-the-right-number-type) for better understanding :)

5. Sudan
As per the [ITU Doc](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C40002PDFE.pdf) fixedline with prefix 10 is not mentioned. As mentioned earlier we do not consider Wikipedia as the source to update phone numbers for all the countries. Also we were unable to find  any online numbers for the prefix 11. Please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
5. Sudan - We already have a bug for number starting with 1, please see #1554 for more updates.

**Comment by kkeshava** [comment]
Hi,
We haven't received a response from you yet about Brazil's prefix 979 and Philippines's exact ranges that needs to be supported. Would it be possible for you to provide an update in order for us to move forward with fixing this issue?

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
