### ISSUE TITLE
Validation issue with +5338947533

### ISSUE THREAD

**Issue by diwanshuster** [googlei18n/libphonenumber#2125]
Country/region affected: CU

Example number(s) affected: +5338947533

The type of the number(s): "mobile"

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B5338947533)

**Comment by kkeshava** [comment]
@diwanshuster,
We can't connect to +5338947533. Did you have a typo?

Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by diwanshuster** [comment]
Thanks for the reply. Got a query from a customer from this number so submitted this issue. Closing it for now.
