### ISSUE TITLE
Turkcell new 51616 mobile prefix may be considered

### ISSUE THREAD

**Issue by ahmetkarakaya** [googlei18n/libphonenumber#2128]
Country: Turkey / TR
Example number(s) and/or range(s): 905161608062
Number type ("fixed-line", "mobile", "short code", etc.): mobile
For short codes, cost and dialing restrictions:
Where or whom did you get the number(s) from: Candidate filled this number in his resume
Authoritative evidence (e.g. national numbering plan, operator announcement):
Plan: Previously Turkcell in Turkey released TCELL by prefix 9056161, new plan is to provide prefix 9051616 
Approved: 
Link from demo (http://libphonenumber.appspot.com) showing error:
http://libphonenumber.appspot.com/phonenumberparser?number=%2B905161608062

**Comment by penmetsaa** [comment]
@ahmetkarakaya,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release. For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion,
or watch the GitHub repository at https://github.com/googlei18n/libphonenumber
to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This will be fixed in our next release.

Join our discussion group to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.
