### ISSUE TITLE
National numbers issue (FR)

### ISSUE THREAD

**Issue by jice** [googlei18n/libphonenumber#2135]
Country/region affected (e.g., "US"): FR
Example number(s) affected ("+1 555 555-1234"): 0590290000
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 059029XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line
The cost, if applicable ("toll-free", "premium rate", "shared cost"): 
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://www.arcep.fr/index.php?id=8144&L=1
[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0590290000&country=FR)

This is an example of a French national number that is wrongly mapped to the +33 country code.  The international format translation produced by the library is incorrect and generally cannot be dialed successfully.

The French numbering plan is an integrated plan that covers multiple E.164 country codes (33, 262, 508, 590, 594, 596). When a national number is dialed within the contexts of a French territory (FR, RE, YT, PM, BL, MF, GP, GF, MQ), the first few digits following the 0 are used to determine the country code associated with the number to produce a correct international number.

In this example, 0590290000 dialed in the context of FR (or in the context of other French territories) is a number located in region 'BL' that is associated with the E.164 country code 590. Thus the correct E.164 number would be +590590290000 and not +33590290000.

**Comment by SumathiSundara** [comment]
In France the number 0590290000 is also considered valid number as result this number will be presented as +33590290000 .

If you would like to check for any of other French territories (RE, YT, PM, BL, MF, GP, GF, MQ), you can check by entering the respective region code. For the region BL, here is the [demo link](http://libphonenumber.appspot.com/phonenumberparser?number=590290000&country=BL) with the correct +590590290000 E.164 number.   

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by jice** [comment]
My issue is that the international number the library produces +33590290000 is an invalid E.164 number. Dialing or sending SMS to it will fail.

French E.164 country codes aren't interchangeable. Every prefix listed by ARCEP in https://extranet.arcep.fr/portail/LinkClick.aspx?fileticket=PBA1WK-wnOU%3d&tabid=217&portalid=0&mid=850 is associated with one, and only one E.164 country code. This E.164 country code is determined by the "Territoire" column of that file.

Dialing 0590290000 (i.e. in the national format) within the context of any French territory refers to the same number and that number is associated with the +590 country code exclusively.

I will raise the issue in the discussion group. Thanks.

**Comment by SumathiSundara** [comment]
Thanks for providing all the details we need! We've accepted this issue. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.
