### ISSUE TITLE
New number ranges for Reliance Jio Infocomm Limited

### ISSUE THREAD

**Issue by DeepakGuptaRelianceJio** [googlei18n/libphonenumber#2138]
Hi

Please update google systems with new nmber ranges allocated to Reliance Jio

Regards

Deepak Gupta
[RJIL_IR21-Document _19-02-2018.pdf](https://github.com/googlei18n/libphonenumber/files/1736069/RJIL_IR21-Document._19-02-2018.pdf)

**Comment by penmetsaa** [comment]
Thanks for taking time to improve libphonenumber.
We added supported to new Reliance JIO ranges. So closing this issue as fixed.
