### ISSUE TITLE
885 toll free are code not supported

### ISSUE THREAD

**Issue by vaibhavReachlocal** [googlei18n/libphonenumber#2141]
Dear team , 

885 area code is not supported. 

We are getting following result code for valid number . - 

Phone Number entered: 8856031919
defaultCountry entered: US
Language entered: en

Validation Results
Result from isPossibleNumber()	true
**Result from isValidNumber()	false**
Phone Number region	 
Result from getNumberType()	UNKNOWN

This number is valid for USA/CAN country

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by SumathiSundara** [comment]
We haven't received a response from you yet about official evidence.
Would it be possible for you to provide an update in order for us to move
forward with fixing this issue?

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
