### ISSUE TITLE
is_valid_number vs is_possible_number?

### ISSUE THREAD

**Issue by gitdjc** [googlei18n/libphonenumber#2147]
Please pardon me if this is a naive question -- I'm just beginning with this.

The source metadata file seems to contain the data to validate phone numbers down to the local allocated block. I'd like to know which call in "phonenumbers" to use to perform this validation on given numbers, with maximally specific result. Does "is_valid_number" do this?  "is_possible_number" doesn't: it appears to check only the pattern and length of a number. (On a particular impossible fictional Swiss number I just tried -- +4111nnnnnnn -- is_valid_number returned false and is_possible_number true.)

What information am I actually getting from these two routines?

**Comment by SumathiSundara** [comment]
Thank you for using libphonenumber!

The is_valid_number indicates the number might be valid and you may be able to reach the correct destination if the number exists. Please see our FAQ for more details:

https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#validation-and-types-of-numbers

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
