### ISSUE TITLE
New mobile phome pattern for Monaco (MC) 

### ISSUE THREAD

**Issue by ildra** [googlei18n/libphonenumber#2151]
Hello!
This is filled template for metadata issue:
Country/region affected (e.g., "US"): MC
Example number(s) affected ("+1 555 555-1234"): +377 46 180820
The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +37746XXXXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):

BR! Dragan Ilic

**Comment by kkeshava** [comment]
@ildra,
Thank you for taking the time to improve libphonenumber! For your next metadata issue, we invite
you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We can't connect to +377 46 180820. Did you have a typo? 

Please share any working numbers or evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ildra** [comment]
Hello kkeshava,
No I did not have any typo. I tried to call on this number (+37746180820, from Slovenia I called 0037746180820) and connected successfully. Could You try one ore time?
Thank you.
BR! Dragan

**Comment by ildra** [comment]
Hello, 
Could you try call +377 46 18 08 20. I don't know if format  (spaces between numbers) influent on calling this number).
BR! Dragan

**Comment by kkeshava** [comment]
@ildra,

We were able to connect to +377 46 18 08 20 today not sure why it din't work yesterday, but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need
context about the prefix that makes them valid. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by ildra** [comment]
@kkeshava 
Thank you. We will try get official evidency from our customers and context about the prefix and iform you.

**Comment by ildra** [comment]
Hello @kkeshava!
Any news here? Do you need any additional information? 
BR! Dragan
PS: I also added this issue on  Issue Tracker application.

**Comment by kkeshava** [comment]
For further updates on this, please refer our Issue Tracker https://b.corp.google.com/issues/74225062

Closing this bug.
