### ISSUE TITLE
583 Operator prefix for Mauritius not supported

### ISSUE THREAD

**Issue by kaneelyster** [googlei18n/libphonenumber#2153]
*   Country: Mauritius (MU)
*   Example number(s) and/or range(s): +230 583x xxxx
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions:
*   Where or whom did you get the number(s) from: Unsure
*   Authoritative evidence (e.g. national numbering plan, operator announcement): Search for "583" on https://www.icta.mu/mobile-prefixes.html
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B23058312345&country=MU

This was reported by a user based in Mauritius. They provided a video proving successful text message reception on a 583 number. I can share this privately since it contains PII I can't share publicly without permission.

**Comment by kkeshava** [comment]
@kaneelyster,
Thanks for providing all the details we need! We've accepted this issue and will fix this in an upcoming release. For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish the new release notes there.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by kkeshava** [comment]
Fixed in release 8.9.1.
