### ISSUE TITLE
 Verify the problem——phoneUtil.parse () 

### ISSUE THREAD

**Issue by yuanyi0510** [googlei18n/libphonenumber#2155]
1. When the phoneUtil.parse () interface is called, it returns null if the arguments are "0016267807554" and "CA". Normal should return 6267807554. Hong Kong, China has the same problem
2. If the argument is "008613671241069", "GA" returns a value of 13671241069, but 13672141069 and GA do not match

**Comment by kkeshava** [comment]
@yuanyi0510,
Thanks for reporting this! This is actually addressed in our documentation:

https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-00-parsed-the-same-as-

As a result, we'll close this issue, but let us know if we may clarify the answer and update documentation.
