### ISSUE TITLE
Validation issue with 6899334064 (IN)

### ISSUE THREAD

**Issue by panand1992** [googlei18n/libphonenumber#2156]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 6899334064

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=6899334064&country=IN)

**Comment by penmetsaa** [comment]
I have created an issue in issue tracker with all the details you have provided. We will be soon disabling issue creation in GitHub. Please provide your inputs at: 
https://issuetracker.google.com/issues/74225884
