### ISSUE TITLE
Default Country code should support "ZZ"

### ISSUE THREAD

**Issue by CarloRn** [googlei18n/libphonenumber#2157]
When using "ZZ" country code (Unknown or unspecified country), the following error is returned:

defaultCountry entered: ZZ
Language entered: en
Error type: INVALID_COUNTRY_CODE. Missing or invalid default region.

I think the lib should support this standard case. 

BR,
Carlo

**Comment by penmetsaa** [comment]
Hi Carlo,

Thanks for reporting this issue.

ZZ is not intended to use as value for defaultRegion while calling parse() function.
Reason: While parsing, we need to know the country to which number belongs to.
We try to get it by checking input phone number (if CC is present)  or from defaultRegion (if number is in national formats). 

If API not able to pick the right region, we throw above error.
Note: API like getRegionCodeForNumber() return ZZ to denote that the region of the number is UNKNOWN.

This is documented at: https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L3006

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
