### ISSUE TITLE
Support for Jersey UK Numbers

### ISSUE THREAD

**Issue by michaelnlindsay** [googlei18n/libphonenumber#2158]
Valid Jersey phone numbers not matching for Great Briton eg: 01534123456

**Comment by penmetsaa** [comment]
Hi Michael,

Thank you for taking the time to improve libphonenumber!

We are already supporting 01534123456 as valid JE number even when it is dialed from GB region.  
Check results at our demo portal: https://libphonenumber.appspot.com/phonenumberparser?number=01534123456&country=GB
https://libphonenumber.appspot.com/phonenumberparser?number=01534123456&country=JE

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
