### ISSUE TITLE
Poland Based Toll Free Numbers do not pass validation

### ISSUE THREAD

**Issue by henrymgaw** [googlei18n/libphonenumber#2159]
The phone number in question is: 0-0-800-141-0203.

1.	https://tollfreeforwarding.com/ - note that when you select Poland from their country selection, all of the numbers that they show use the same number format as the number provided above.
2.	We had someone in Warsaw, Poland call the number exactly as is, and they were able to make a successful connection.

**Comment by penmetsaa** [comment]
Hi,

Thanks for reporting this issue.

I have created an issue in issue tracker with all the details you have provided. We will be soon disabling issue creation in GitHub. We will triage this at:
https://issuetracker.google.com/issues/74296959
