### ISSUE TITLE
Arabic number that starts with '103' comes up as invalid

### ISSUE THREAD

**Issue by burugular** [googlei18n/libphonenumber#2165]
Hi
 An Arabic number that starts with '103', returns FALSE when passed to 'isValidNumber(phoneNumber)'.

This is a valid phone number but is updated in the library?

number sample - '1033XXXXXX'
Code - +20
thanks 
R

**Comment by penmetsaa** [comment]
Hi,

We are already supporting numbers of format +20 1033XXXXXX. Please see our demo results at:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B20+1033123456

To check the latest behavior for yourself  (we update metadata frequently), see the[demo](http://libphonenumber.appspot.com/) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

If there is a specific range that you think we should update and don't do so in the demo highlighted above, please file a new issue with details. See our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) to determine whether something is a real issue, and the details we need to be able to fix it.
