### ISSUE TITLE
Germany mobile numbers formatted wrong

### ISSUE THREAD

**Issue by gitdjc** [googlei18n/libphonenumber#2167]
German mobile phone numbers beginning

    +49 15X Ynnn..., +4915XYnnn..., etc.

are formatted with a 4-digit prefix:

    +49 15XY nnn...

The correct format is a 3-digit prefix:

    +49 15X Ynnn...

Mobile numbers in the 16X and 17X ranges are formatted correctly.

**Comment by kkeshava** [comment]
Hi gitdjc, please follow this issue in Issue Tracker going forward as we are now closing GitHub: https://buganizer.corp.google.com/issues/74508811 Using Issue Tracker will enable to us to get back to you more efficiently as we align GitHub user issues with ones reported at Google.

**Comment by giggsey** [comment]
@kkeshava Looks like you pasted an internal link there.

**Comment by kkeshava** [comment]
Thanks for noticing it @giggsey :) I have updated it now.
