### ISSUE TITLE
provide downloadable javascript builds

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#263]
Imported from [Google Code issue #263](https://code.google.com/p/libphonenumber/issues/detail?id=263) created by [cberzan](https://code.google.com/u/113958647858831747726/) on 2013-04-18T02:40:12.000Z:

----
Please provide the JavaScript version of libphonenumber as a download. (I only see Java versions on the downloads page.)

Currently there is too much friction in building the JavaScript version by hand. See, for example, https://code.google.com/p/libphonenumber/issues/detail?id=262.

**Comment by keghani** [comment]
Duplicate of https://github.com/googlei18n/libphonenumber/issues/683
