### ISSUE TITLE
Logging: Convert string concatenation to a message template

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#30]
Imported from [Google Code issue #30](https://code.google.com/p/libphonenumber/issues/detail?id=30) created by [kushi.p](https://code.google.com/u/113040845239955531959/) on 2011-04-27T12:42:52.000Z:

----
This is just a minor nit to make logging read cleaner.

Converted a bunch of logging cases to use message templates as provided by java.util.logging.Logger.

Code review: http://codereview.appspot.com/4444071/

P.S. How do I change the `type` of issues I submit? Everything comes up under defect which is misleading.

**Comment by keghani** [comment]
Issue obsolete.
