### ISSUE TITLE
BR required carrier codes

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#327]
Imported from [Google Code issue #327](https://code.google.com/p/libphonenumber/issues/detail?id=327) created by [psalvaro](https://code.google.com/u/110487727829148498678/) on 2013-07-25T18:40:30.000Z:

----
Generated from numbering plan data from ANATEL - Agência Nacional de Telecomunicações (Brazilian National Telecommunications Agency, http://sistemas.anatel.gov.br/sapn/ downloaded Thursday, 23 May 2013, 12:30:34 BRT). Calls between fixed terminals with same-area code but located in different local areas (&quot;áreas locais&quot;) a long distance prefix (0) and a carrier code is required.

**Comment by keghani** [comment]
Patch is no longer visible, CLA wasn't signed, and contributor wasn't on GitHub so I can't reach out.
@lararennie do you remember what the issue was? Maybe we already fixed it, or should fix it ourselves.

**Comment by lararennie** [comment]
Not sure if this was carrier selection codes? or better geocoding? Or other?

**Comment by keghani** [comment]
Infeasible at this point.
