### ISSUE TITLE
New M2M number range for NL

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#332]
Imported from [Google Code issue #332](https://code.google.com/p/libphonenumber/issues/detail?id=332) created by [jmostert@xs4all.nl](https://code.google.com/u/114219724441413103911/) on 2013-08-01T08:05:30.000Z:

----
<b>What steps will reproduce the problem?</b>
1. Look up 097001234567 as an NL number.

<b>What is the expected output? What do you see instead?</b>
Expected output is that the number is considered valid, but it's not.

<b>What version of the product are you using? On what operating system?</b>
Used the public test verstion at http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html.

<b>Please provide any additional information below.</b>
Since 2013-03-01 a new number range starting with 0970 has been allocated for Machine-to-Machine (M2M) communication. Numbers in this range are 12 digits long. Details on this range are available from https://www.acm.nl/nl/download/publicatie/?id=10289 (in Dutch).

**Comment by ameenross** [comment]
This particular number range is used for mobile internet SIMs used in tablets and laptops. The numbers are typically not used for calling, although my wife has received incoming calls on hers from some subscribers (not all).

Since this range is intended and used for the consumer market, it's rather widespread. Especially Android apps (such as Kontalk) would benefit from this addition, but I'm sure there are other usecases as well.

**Comment by daniele-athome** [comment]
Hi, just to let you know that my project @kontalk uses libphonenumber for both client (Android) and server. I could implement an ad-hoc check for both client and server, but it would be really nicer if libphonenumber would support this: some tablet users came forward that they wish to use Kontalk on their tablet, linked to its own phone number (those tablets have an internal SIM linked to a M2M number).

**Comment by andyst** [comment]
If you'd like to investigate M2M support in libphonenumber, please see:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by ameenross** [comment]
> One of the reasons libphonenumber doesn't support M2M so far is because no one could explain their use to us sufficiently.

I'm sorry but this is absolutely preposterous. If the developers don't know of any usecases then they have simply failed to read the issues about M2M and their comments carefully! And to be honest, it has been awfully mute in most if not *all* of those issues. I'm sure many people are well able and willing to answer questions if there were any, but they're not even asked, or the questions are completely different between issues! The icing on the cake is that these issues have now all been closed despite a solution not being available, nor a clear "won't fix" answer, nothing!

I even created a "canonical" M2M issue here: #680 but it has barely received any attention at all. If Google was serious about evaluating M2M support, I'd at least expect crystal clear and consistent communication. The country-specific M2M issues also don't have anything to do with arguments for or against, although hinging on the general issue of M2M support.

Can we please have a fruitful discussion over at #680? I'll try to answer questions, and I'm sure others will be willing to as well.

**Comment by andyst** [comment]
We're actually working towards a solution for M2M and as a first step, we're communicating consistently.
 - We've created a FAQ and M2M is one of the first FAQ entries.
 - We're now consistent in how we respond to requests around M2M.
 - The FAQ entry explains why we don't understand the issue yet and how to engage with us.

I missed #680. Let's continue the discussion there.
