### ISSUE TITLE
Norway's 12 digits numbers are considered invalid

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#351]
Imported from [Google Code issue #351](https://code.google.com/p/libphonenumber/issues/detail?id=351) created by [hadrien.kohl](https://code.google.com/u/110153833200453121113/) on 2013-09-16T13:13:09.000Z:

----
<b>What steps will reproduce the problem?</b>
1. Try to validate the number 0047580000474825 (or 580000474825)
2. See that it's not valid.

- What is the expected output? What do you see instead?

This number is a valid number. The library reports it as an invalid one.

- What version of the product are you using? On what operating system?

Both the javascript and java versions (r603) are reporting the number as invalid. 

- Please provide any additional information below.

According to the Norwegian post and telecommunication authority, the 12 number are defined as follow:
 58\d{10}

http://www.npt.no/marked/nummerforvaltning/e.164-nummerplan/8-og-12-sifrede-nummerserier

**Comment by keghani** [comment]
We don't support M2M numbers. Also see #910.

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers
