### ISSUE TITLE
Lib does not detect telemarketer numbers in India starting with 140

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#357]
Imported from [Google Code issue #357](https://code.google.com/p/libphonenumber/issues/detail?id=357) created by [arif.amirani](https://code.google.com/u/117686618081612103631/) on 2013-10-09T15:40:33.000Z:

----
As per the wikipedia, &quot;Telemarketers have been issued 10-digit telephone numbers starting with 140 (140XXXXXXX) by the Department of Telecommunications on TRAI's request.&quot;

An example number is +91 1409 305 260 which is considered invalid.

Source: http://en.wikipedia.org/wiki/Telephone_numbers_in_India

**Comment by lararennie** [comment]
Fixed as per demo.
