### ISSUE TITLE
Invalid isPossibleNumberWithReason() output for number such as +1 510 610 552

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#358]
Imported from [Google Code issue #358](https://code.google.com/p/libphonenumber/issues/detail?id=358) created by [tCheard](https://code.google.com/u/101682313161183350945/) on 2013-10-11T02:46:18.000Z:

---

<b>What steps will reproduce the problem?</b>
1. I have done this on my own system with my own copy of libphonenumber, but I can also replicate this on the demo host at http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
1. Go to http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html
2. Enter the number '+1 510 610 552'
3. Note the output for 'Result from isPossibleNumberWithReason():' is TOO_LONG
4. Enter the number '+1 510 610 5522'
5. Note that this is a valid number

<b>What is the expected output? What do you see instead?</b>

The result of isPossibleNumberWithReason() for the number '+1 510 610 552' should be TOO_SHORT rather than TOO_LONG.

<b>What version of the product are you using? On what operating system?</b>

r620 Javascript on my local copy. r603 with the online demo

**Comment by iklyaus** [comment]
Any chance to fix it? Or may be add an option to block local numbers?

**Comment by keghani** [comment]
Fixed in 8.6.0

**Comment by keghani** [comment]
Fixed in v8.6.0.
