### ISSUE TITLE
germany mobile phone numbers not recognized

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#359]
Imported from [Google Code issue #359](https://code.google.com/p/libphonenumber/issues/detail?id=359) created by [nicolas.schwartz@blablacar.com](https://code.google.com/u/103724355045124923451/) on 2013-10-15T08:06:45.000Z:

----
<b>What steps will reproduce the problem?</b>
1. use the demo java tool to parse a Number
2. enter the phone numbers and DE as a country, submit
3. each time isValidNumber() returns false BUT those numbers are real (I was told we had the people on the phone.)

version of the demo is r603

Here are the phone numbers (I replaced the last digit with a ? for the privacy of our members)
0176341285? =&gt; O2
017670221410? =&gt; O2
0151261416? =&gt; ???
0157399893052? =&gt; ???

**Comment by padmaksha** [comment]
Fixed in release 7.3.1
