### ISSUE TITLE
Missing Header Files

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#363]
Imported from [Google Code issue #363](https://code.google.com/p/libphonenumber/issues/detail?id=363) created by [ady.romantika](https://code.google.com/u/115792598511340332469/) on 2013-10-28T19:39:03.000Z:

----
<b>What steps will reproduce the problem?</b>
========================================
1. #include &quot;phonenumbers/phonenumberutil.h&quot;
2. Add some code
3. build with -lphonenumber

<b>What is the expected output? What do you see instead?</b>
========================================
Expected: No error

These header files are missing and not in install_manifest.txt

In file included from /usr/local/include/phonenumbers/phonenumberutil.h:32:0,
                 from /home/vagrant/phonenumber/phonenumber.cc:30:
/usr/local/include/phonenumbers/base/memory/scoped_ptr.h:25:45: fatal error: phonenumbers/base/template_util.h: No such file or directory

In file included from /usr/local/include/phonenumbers/phonenumberutil.h:33:0,
                 from /home/vagrant/phonenumber/phonenumber.cc:30:
/usr/local/include/phonenumbers/base/memory/singleton.h:56:39: fatal error: phonenumbers/base/logging.h: No such file or directory

In file included from /usr/local/include/phonenumbers/phonenumberutil.h:33:0,
                 from /home/vagrant/phonenumber/phonenumber.cc:30:
/usr/local/include/phonenumbers/base/memory/singleton.h:57:46: fatal error: phonenumbers/base/thread_checker.h: No such file or directory

In file included from /usr/local/include/phonenumbers/phonenumberutil.h:33:0,
                 from /home/vagrant/phonenumber/phonenumber.cc:30:
/usr/local/include/phonenumbers/base/memory/singleton.h:91:54: fatal error: phonenumbers/base/memory/singleton_posix.h: No such file or directory

<b>What version of the product are you using? On what operating system?</b>
========================================
Repository Root: http://libphonenumber.googlecode.com/svn
Revision: 621

OS is Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64). Vagrant Virtual Machine. https://github.com/adyromantika/vagrant-libphonenumber-build

<b>Please provide any additional information below.</b>
========================================
I was able to complete building by manually copying the files from the source directory. This is just informative. Thanks.

**Comment by keghani** [comment]
Resolved in https://github.com/googlei18n/libphonenumber/pull/570
