### ISSUE TITLE
Emden (Germany) phone number +49492180185611 incorrectly reported as invalid number 

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#376]
Imported from [Google Code issue #376](https://code.google.com/p/libphonenumber/issues/detail?id=376) created by [maria.soldatow](https://code.google.com/u/100779476600666242620/) on 2013-11-12T13:13:51.000Z:

----
<b>What steps will reproduce the problem?</b>
1. Use the function isValidNumber() with the number +49492180185611.

<b>What is the expected output? What do you see instead?</b>
I expected the result from isValidNumber() - true, but isValidNumber() reports false.

<b>What version of the product are you using? On what operating system?</b>
libphonenumber version 5.8 (based on r603)
Windows 7 Enterprise.

<b>Please provide any additional information below.</b>
The phone numbers of Emden are reported as valid only if they have maximum 7 digits after the city code (4921). The same issue is for the phone numbers of Borkum (city code 4922).

**Comment by keghani** [comment]
Number now considered valid: http://libphonenumber.appspot.com/phonenumberparser?number=%2B49492180185611+&country=DE

Please re-open if I missed something.

**Comment by AbdurRehman91** [comment]
hi all.i am facing a issue as in my case my test case number is +491765770313 is being consider invalid by the library.i am using django-phoneNumber-field which is basically a wrapper around this library.i have tested other samples german phone numbers which are greater in length than this,and they are working fine.E.g +49492180185611 series.kindly suggest the possible soultion
thanks

**Comment by lararennie** [comment]
You have to work out what version the wrapper you are using is using. If the number is valid here, we can't help you: they just have to update to the latest version - file a bug against them and encourage them to do so.

**Comment by AbdurRehman91** [comment]
hi  the issue was in the version.upgrading to 8.4.0 has solved the problem
thanks
