### ISSUE TITLE
Brazilian emergency and public utilities numbers are invalid

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#377]
Imported from [Google Code issue #377](https://code.google.com/p/libphonenumber/issues/detail?id=377) created by [fabiojmendes](https://code.google.com/u/fabiojmendes@gmail.com/) on 2013-11-13T18:09:39.000Z:

---

<b>What steps will reproduce the problem?</b>
Here are the test cases:

```
@Test
public void testEmergency() throws Exception {
    PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
    //190 in brazil is equivalent to EUA's 911
    PhoneNumber phone = phoneUtil.parse(&quot;190&quot;, &quot;BR&quot;);
    assertTrue(phoneUtil.isValidNumber(phone)); //fails
}

@Test
public void testPublicServices() throws Exception {
    PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
    //Directory assistance‎
    PhoneNumber phone = phoneUtil.parse(&quot;102&quot;, &quot;BR&quot;);
    assertTrue(phoneUtil.isValidNumber(phone)); //fails
}

@Test
public void testServiceProviderNumber() throws Exception {
    PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
    //Cable TV service provider
    PhoneNumber phone = phoneUtil.parse(&quot;10621&quot;, &quot;BR&quot;);
    assertTrue(phoneUtil.isValidNumber(phone)); //fails
}
```

<b>What is the expected output? What do you see instead?</b>
A valid number

<b>What version of the product are you using? On what operating system?</b>
libphonenumber 5.8 
Java JDK 1.7_45

<b>Please provide any additional information below.</b>

Here is the document that list all the emergency and public utilities numbers:
http://www.anatel.gov.br/Portal/exibirPortalPaginaEspecial.do?codItemCanal=746&amp;codCanal=277

I think its something like 1\d{2,3} for the basic ones and 10[356]\d{1,2} for the ones with a possible extension.

I dont fell confident to contribute to the metadata just yet but I'll try. 
Nevertheless, I'll be happy to help testing and translating the document I just linked.

**Comment by keghani** [comment]
Fixed meanwhile.

**Comment by keghani** [comment]
Except 102 :)

**Comment by keghani** [comment]
We've accepted this issue and will fix it in an upcoming release.

**Comment by keghani** [comment]
Fixed meanwhile.
