### ISSUE TITLE
Make isViablePhoneNumber method public.

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#394]
Imported from [Google Code issue #394](https://code.google.com/p/libphonenumber/issues/detail?id=394) created by [martin.freij](https://code.google.com/u/110343466730383808525/) on 2013-12-10T10:03:11.000Z:

----
I find the method PhoneNumberUtil.isViablePhoneNumber() quite useful. Would it be possible to make it public?

**Comment by keghani** [comment]
isViablePhoneNumber is meant as an internal helper method and we have no plans to make it part of the public API.
