### ISSUE TITLE
Korea phonenumber hyphenation in Dialer. Formatting for Korea

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#404]
Imported from [Google Code issue #404](https://code.google.com/p/libphonenumber/issues/detail?id=404) created by [Ahrongh](https://code.google.com/u/101029771395866669465/) on 2014-01-16T10:45:21.000Z:

---

<b>What steps will reproduce the problem?</b>
1.launch Dialer
2.enter the following digits 
  0505 should be also handled as the international call dialing number

the actual result below.
050512345678

<b>What is the expected output? What do you see instead?</b>
0505-1234-5678

<b>What version of the product are you using? On what operating system?</b>
android 4.4 KitKat

<b>Please provide any additional information below.</b>

**Comment by keghani** [comment]
There's not enough information to fix this issue. Seems at last look (before moving to GitHub) we got as far as determining 0505 to be in use for "Web Email Fax numbers", which we don't support. So closing.
