### ISSUE TITLE
Invalid Blau phonenumber in germany

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#432]
Imported from [Google Code issue #432](https://code.google.com/p/libphonenumber/issues/detail?id=432) created by [schwartn](https://code.google.com/u/102669831871247632972/) on 2014-03-03T10:25:43.000Z:

---

When trying to check a valid phonenumber, isValid returns false for a real phonenumber.

The phonenumber is : 0157899388396X (last digit hidden for privacy concerns)
The network operator is &quot;Blau&quot;, it's a low-cost operator which uses the network from e-plus.

We called the phonenumber and had the person on the phone :)

Could not find any info on the phone number plan starting with 01578.
Tell me if you need anything else !

Thank's
Nicolas Schwartz

**Comment by keghani** [comment]
Fixed meanwhile, this is now valid voicemail.
