### ISSUE TITLE
FR Mobile phone in 07 incorrect

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#438]
Imported from [Google Code issue #438](https://code.google.com/p/libphonenumber/issues/detail?id=438) created by [gael.delbos](https://code.google.com/u/103109146445956196855/) on 2014-03-19T11:07:34.000Z:

----
<b>What steps will reproduce the problem?</b>
1. Parse the following number : +33731234567 (using FR region)
2. Check phone validity

<b>What is the expected output? What do you see instead?</b>
I expect true, but got false. 

What version of the product are you using?
libphonenumber 5.9 

<b>Please provide any additional information below.</b>
See issue https://code.google.com/p/libphonenumber/issues/detail?id=391 for past exchange. 
In the given answers, it was said that as no number existed for 73 and 74, the lib would not accept those number.

One of my coworkers check the ARCEP site (http://www.arcep.fr/index.php?id=interactivenumeros) for other number in 7X and found out that there were no reservation for 79. 

My question is why does the lib accept 079 numbers but not 073 and 074?

**Comment by pvardanega** [comment]
Phone numbers starting with 07 are valid but only those starting 075 to 079 are available in France. 
Gael, you mention ARCEP. On his website, it is clearly said that 075 to 079 are available : http://www.arcep.fr/?id=8146.

**Comment by bric3** [comment]
The issue has been discussed here : https://groups.google.com/forum/#!topic/libphonenumber-discuss/rjgoPh0PuCY

Let's close the issue.

**Comment by andyst** [comment]
@dlyongemallo see https://groups.google.com/forum/#!topic/libphonenumber-discuss/rjgoPh0PuCY (link from the latest comment above). I don't see a resolution in that libphonenumber-discuss thread. Has the change been rolled back?

**Comment by bric3** [comment]
My guess on these wrong number is they are misread `1`s as `7`s, could be wrongly OCRed pictures or human error. Why? Because in many examples given for these wrong number, it looked like it was for calling business such as pizzerias, which are probably using landlines not mobile.

So `+33731234567` is probably more `+33131234567`

**Comment by bric3** [comment]
@andyst Yes. It has been fixed correctly in a subsequent release last year. The [current metadata](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L7180-L7186) is **correct**.
