### ISSUE TITLE
No location for prefix 00333875

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#450]
Imported from [Google Code issue #450](https://code.google.com/p/libphonenumber/issues/detail?id=450) created by [alessandro.casella@hisolution.it](https://code.google.com/u/112157349565416887571/) on 2014-04-10T13:14:29.000Z:

---

<b>What steps will reproduce the problem?</b>
1. Send a request to analyze French phone number 003338757xxxx
2. Search for location in response
3. Notice that returned location is &quot;France&quot;

<b>What is the expected output? What do you see instead?</b>
I expected location &quot;Metz&quot; as the phone number's one.
Returned location is generic &quot;France&quot; instead.

<b>What version of the product are you using? On what operating system?</b>
Python library version 6.0.0a on Linux (Ubuntu 12.04 LTS).
The same problem using on-line web interface on http://libphonenumber.appspot.com/.

<b>Please provide any additional information below.</b>
I noticed that the prefix '3338757' is missing in python library files included in 'geodata' directory ('data4.py' file contains French prefixes but not '3338757').

**Comment by keghani** [comment]
Closing as we didn't get evidence.
We do currently have the following in https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/33.txt:

```
3338750|Metz
3338751|Maizières-lès-Metz
3338753|Amanvillers
3338755|Metz
3338756|Metz
3338758|Moyeuvre-Grande
```

It's missing 3338757 which would be required to solve this.
