### ISSUE TITLE
Getting emergency numbers for a certain country

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#496]
Imported from [Google Code issue #496](https://code.google.com/p/libphonenumber/issues/detail?id=496) created by [jokerlee77](https://code.google.com/u/113172405757816960257/) on 2014-07-29T03:56:36.000Z:

----

<b>What steps will reproduce the problem?</b>

1. I input a chinese mobile phone, 
use PhoneNumberUtil parse(&quot;008613027727257&quot;, &quot;CN&quot;);
and PhoneNumberOfflineGeocoder to getDescriptionForNumber, only get a country name China;
but i input a fixed phone number parse(&quot;00862162083211&quot;, &quot;CN&quot;);
can get the a certain city name.

2. Could i get all the emergency numbers for a certain country, now only get a emergency number pattern by PhoneMetadata?

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>
i use Mar 07, 2013: libphonenumber-5.4 in android code

<b>Please provide any additional information below.</b>

**Comment by keghani** [comment]
Closing as it was resolved at the time.
