### ISSUE TITLE
INTERNATIONAL formatting of US numbers insert hyphens; does not comply with E123

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#506]
Imported from [Google Code issue #506](https://code.google.com/p/libphonenumber/issues/detail?id=506) created by [Jaffadog](https://code.google.com/u/116668498342990580444/) on 2014-08-25T17:05:13.000Z:

---

<b>What steps will reproduce the problem?</b>

number = phoneUtil.parse(&quot;+14349513180&quot;, null);
result = phoneUtil.format(number, PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL);
log.info(result);

<b>What is the expected output? What do you see instead?</b>
expect: +1 434 951 3180
get: +1 434-951-3180

<b>What version of the product are you using? On what operating system?</b>
6.2. Windows 7 x64.

<b>Please provide any additional information below.</b>

**Comment by davidmc24** [comment]
I agree with mihaelacr, that this is a surprising gap in support for E.123.

**Comment by penmetsaa** [comment]
@davidmc24,
We have [updated the java doc](https://github.com/googlei18n/libphonenumber/commit/3db7670b42c4c03c3d69d9ed43cfe15fde978c5e) based on inputs here. Thanks!
