### ISSUE TITLE
Not all international prefix codes recognised for Gabon

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#526]
Imported from [Google Code issue #526](https://code.google.com/p/libphonenumber/issues/detail?id=526) created by [vishaldonderia](https://code.google.com/u/101308550866083348596/) on 2014-09-29T04:51:52.000Z:

---

<b>What steps will reproduce the problem?</b>
1.Sample input:1124105777019 (Gabon Number GA)
2PhoneNumber numberv = phoneUtil.parse(input, &quot;GA&quot;);
3.boolean x= Phoneutil.isvalid(number);

<b>What is the expected output? What do you see instead?</b>
x  should be true because  input is a valid Gabon number with international calling prefix.
As i see, function is returning false value.

<b>What version of the product are you using? On what operating system?</b>
using 5.9 jar file on Eclipse LUNA, MAC 10.9.3

<b>Please provide any additional information below.</b>
There are so many international prefix codes. Google it !!

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point. We need more information i.e country from where the above number is dialed. Please see our [contribution guidelines](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
