### ISSUE TITLE
missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_CH

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#528]
Imported from [Google Code issue #528](https://code.google.com/p/libphonenumber/issues/detail?id=528) created by [renuga.android](https://code.google.com/u/104343415129865960396/) on 2014-10-08T05:54:07.000Z:

----
In android, When using this code for country CH, it throws &quot;java.lang.IllegalStateException: missing metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_CH&quot;.

phoneUtil1.parse(swissNumberStr, &quot;CH&quot;);

I tried to change the country code, it returns same error.

I am using v6.3 jar.

any solution?

**Comment by dlyongemallo** [comment]
Is it only for CH, or does it happen for any other region?

**Comment by AlexanderTolstykh** [comment]
Hello @dlyongemallo, I have same issue with DE locale. It looks like firmware issue:

java.lang.IllegalStateException: missing metadata: /bom/google/i18n/phonenumbers/datA/PhoneNumberMetadataProto_DE
       at com.google.i18n.phonenumbers.PhoneNumberUtil.loadMetadataFromFile(PhoneNumberUtil.java:622)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2045)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.getCountryCodeForValidRegion(PhoneNumberUtil.java:2215)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.getCountryCodeForRegion(PhoneNumberUtil.java:2203)


Samsung SM-N910F, Android 5.0.1

**Comment by mihaelacr-google** [comment]
Are you sure you are using the jar correctly? As mentioned previously, our demo uses the jar and we do not seem to have that problem.

**Comment by AlexanderTolstykh** [comment]
Hello @mihaelacr-google,
No, I am not using jar. It is stacktrace from release apk.

**Comment by lararennie** [comment]
Is this still a problem for you?

**Comment by AlexanderTolstykh** [comment]
Just checked and it seems that this problem relates to custom firmware, because it happens only on one user's device.

**Comment by keghani** [comment]
Thanks for confirming @AlexanderTolstykh!

**Comment by keghani** [comment]
Please take a look at our new [resource loading FAQ](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#how-do-i-load-libphonenumber-resources-in-my-android-app), the fix is probably to call `PhoneNumberUtil` API outside the main thread.
