### ISSUE TITLE
Timezone information for +44 code incorrect

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#531]
Imported from [Google Code issue #531](https://code.google.com/p/libphonenumber/issues/detail?id=531) created by [callum.macgregor@3gtelecoms.net](https://code.google.com/u/107627959646787241957/) on 2014-10-13T08:12:44.000Z:

----
Run a check against any UK mobile number and the timezone will be reported as both Atlantic/Reykjavik Europe/London. The +44 area code is for UK only so this timezone is wrong, it should only be Europe/London.

**Comment by dlyongemallo** [comment]
Fixed: https://github.com/googlei18n/libphonenumber/blob/fe577878b422aca0d007b2f396eaa27123af706f/resources/timezones/map_data.txt#L1479
