### ISSUE TITLE
Carrier information for pre 2002 mobile numbers for Greece incorrect

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#532]
Imported from [Google Code issue #532](https://code.google.com/p/libphonenumber/issues/detail?id=532) created by [cal.macgregor](https://code.google.com/u/cal.macgregor/) on 2014-10-14T14:01:24.000Z:

----
Mobile numbers registered after 2002 in Greece all start with +3069. This presents an issue as some mobile numbers are still in use and begin with the old-style prefix e.g. +309. An example of this is a mobile switching station. By looking up a number from its MSC libphonenumber doesn't take into account the added 6 and presumes the number is invalid when infact it is just using an old-style prefix.

Example:

Working number: 306971000000
Non-working number: 30971000000

BOTH are potentially correct numbers.

**Comment by keghani** [comment]
We don't bring back old-style out-of-transition numbers once we've stopped support for them in the library. This is WAI.
