### ISSUE TITLE
New mobile prefixes in India

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#536]
Imported from [Google Code issue #536](https://code.google.com/p/libphonenumber/issues/detail?id=536) created by [alexandru.manea](https://code.google.com/u/117371447375378155460/) on 2014-10-15T10:05:24.000Z:

----
A few new prefixes:

Examples:
9170893150xx
9170893420xx
9170909783xx
9170910006xx
9170924076xx
9170970105xx

@@ -10563,7 +10560,8 @@
               0(?:
                 2[2-9]|
                 [3-7]\d|
-                8[0-7]
+                8[0-79]|
+                9[0-27]
               )|
               2(?:
                 0[04-9]|

**Comment by roes** [comment]
Last one added in release 7.0.2
