### ISSUE TITLE
GB SMS Services Metadata

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#547]
Imported from [Google Code issue #547](https://code.google.com/p/libphonenumber/issues/detail?id=547) created by [giggsey](https://code.google.com/u/giggsey/) on 2014-11-03T15:28:16.000Z:

----
Source: http://code.phonepayplus.org.uk/the-appropriate-use-of-number-ranges.html

Section 2.2 states:

69x/79x/89x - SES (Adult Services)
60000-68999 and 80000–88999 - Can be used for voice/sms
70x - Charity

I'm not sure of the length, but I've found an example of a charity number being 5 digits (http://www.diabetes.org.uk/Get_involved/Ways-to-donate/Text-to-Donate/Text-to-Donate-terms-conditions/).

**Comment by keghani** [comment]
These are still not in our GB short codes but we could add them now.
@giggsey this is an old issue and the doc is not showing the information anymore. Are you aware of any GB short codes that still should be in [ShortNumberMetadata.xml](https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/ShortNumberMetadata.xml) and are not?

**Comment by giggsey** [comment]
Apologies for the delay, for some reason I missed this notification.

[GB shortcode 69060 (Demo)](http://libphonenumber.appspot.com/phonenumberparser?number=69060&country=GB)

Source: http://www.short-codes.com/codes/browse/69000-69999/100_1 (You can see it on the list that it's enabled for voice)

[PhonepayPlus's Number checker](http://www.phonepayplus.org.uk/about-us/number-checker) says this is owned by 4D Interactive, and is an Adult Service. I have not tested dialing the number from a mobile or landline.

From the short-codes website, it appears that any of them could be provisioned for voice.

**Comment by keghani** [comment]
Thanks @giggsey! These 69xxx are now valid short codes.
