### ISSUE TITLE
Belgian 15 digits m2m phone numbers reported as invalid

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#550]
Imported from [Google Code issue #550](https://code.google.com/p/libphonenumber/issues/detail?id=550) created by [marketip.it](https://code.google.com/u/107889385440756714168/) on 2014-11-06T17:04:05.000Z:

----
<b>What steps will reproduce the problem?</b>

Since 09/2013 the official telecom regulation institute of Belgium (IBPT) introduced a new phone number format with 15 digits for m2m (machine-to-machine) SIM cards.
These phone numbers are reported as invalid by the library.

<b>What is the expected output? What do you see instead?</b>
Numbers like +327700010023652 should be reported as valid phone numbers.

<b>What version of the product are you using? On what operating system?</b>
version r715

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers
