### ISSUE TITLE
Valid number in Norfolk Island reported as invalid

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#561]
Imported from [Google Code issue #561](https://code.google.com/p/libphonenumber/issues/detail?id=561) created by [oleksandr.panteleimonov@booking.com](https://code.google.com/u/111300802707021166114/) on 2014-11-25T10:06:27.000Z:

----
<b>What steps will reproduce the problem?</b>
Try to validate +672350360.

<b>What is the expected output? What do you see instead?</b>
Expected: Number is valid.

<b>What version of the product are you using? On what operating system?</b>
r715

<b>Please provide any additional information below.</b>
I called to this number (it's a hotel) and talked with this person.
http://en.wikipedia.org/wiki/Telephone_numbers_in_Norfolk_Island

**Comment by roes** [comment]
Fixed in v7.0.2
