### ISSUE TITLE
Chile mobile number not accepted as valid number

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#562]
Imported from [Google Code issue #562](https://code.google.com/p/libphonenumber/issues/detail?id=562) created by [RalphLenssen](https://code.google.com/u/115514840686149311424/) on 2014-11-25T13:08:11.000Z:

----
<b>What steps will reproduce the problem?</b>
1.Use the phone number &quot;+56 8 998xxxx&quot;  which is a valid format for a chile mobile number according to http://www.wtng.info/wtng-56-cl.html
2. The phonenumber is rejected as not a valid number

<b>What is the expected output? What do you see instead?</b>
I expect it to be a valid number

<b>What version of the product are you using? On what operating system?</b>
Using version 7.0

**Comment by lweberk** [comment]
A real one would be +56 9 xxxx xxxx. I think the number above would then be +56 9 8998 xxxx. With 9 being the mobile prefix and beginning at the 8, entering the nombers body with \d{8} digits.

**Comment by keghani** [comment]
This is working now with the real number. See http://libphonenumber.appspot.com/phonenumberparser?number=%2B56+9+8998+0000&country=CL
