### ISSUE TITLE
Chile - Invalid Format for Fixed Line Area Code 2

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#565]
Imported from [Google Code issue #565](https://code.google.com/p/libphonenumber/issues/detail?id=565) created by [pablobalegno](https://code.google.com/u/pablobalegno/) on 2014-12-02T19:08:01.000Z:

----
Given this valid E.164 mobile number: +56 2 3205 XXXX (the last part was modified to preserve the identity)

Current National Format:  error (is marked as possible phone number) 
Expected National Format: 2 3205 XXXX

Version used: 7.0.2

This information is taken from the Chile bureau of communications called Subtel.
Site: http://www.subtel.gob.cl

============================================================================
Below there is a Workaround that we made in the PhoneNumberMetadata.xml to change this behavior but we are not sure that doesn't affect other formats:

We modified these line (4237 and 4318): https://code.google.com/p/libphonenumber/source/browse/trunk/resources/PhoneNumberMetadata.xml?r=715#&nbsp;4237
and changed like this:

Line: 4237 
[...]
&lt;leadingDigits&gt;2[23]&lt;/leadingDigits&gt;
[...]

Line: 4318
[...]

 [23]\d{7}|

[...]

**Comment by mdaloia** [comment]
The link to the file on `code.google.com` is not accessible anymore.

The equivalent to `github.com` is:
https://github.com/googlei18n/libphonenumber/blob/libphonenumber-7.0.2/resources/PhoneNumberMetadata.xml#L4238

**Comment by hagbard** [comment]
Thank you for the report. I have looked on the site http://www.subtel.gob.cl but cannot find where the range is specified. I am trying to confirm that all numbers under the 3\d{7} range are valid (we have a requirement to only say numbers are valid if we expect to be able to dial at least one number within each smallest block. A block of 7 digits (ie, 10 million numbers) is very large.

**Comment by hagbard** [comment]
Do you have any more information which might help me confirm what the valid blocks are under the 3\d{7} range?

**Comment by lweberk** [comment]
Ex. for fixed line area code 2: 
+56 2 xxxx xxxx. I'd be \d{8} after the regional prefix.

**Comment by keghani** [comment]
Fixed in release 7.0.8: http://github.com/googlei18n/libphonenumber/commit/ba95e6cdf156d2c1e862a061d85e111212df9aee

Confirmed at http://libphonenumber.appspot.com/
Step 1: +56 2 3205 0000
Step 2: CL
