### ISSUE TITLE
Getting null as Region Code for St Helena

### ISSUE THREAD

**Issue by kommradHomer** [googlei18n/libphonenumber#573]
PhoneNumberUtil.getRegionCodeForNumber() returning null for Region Code for "St Helena" , even if PhoneNumberOfflineGeocoder.getDescriptionForValidNumber() returns "St Helena"

Dial code is "290"

**Comment by dlyongemallo** [comment]
I assume this is using the Java library?

Are you using the real data (PhoneNumberMetadata.xml) or the test data (PhoneNumberMetadataForTesting.xml)? I was unable to reproduce with the real data, but it fails with the test data because "SH" and "TA" are not included in the test data.

**Comment by dlyongemallo** [comment]
Closing, as I can't seem to reproduce it in the latest release. If you encounter it or have more info about a repro case, please re-open.
