### ISSUE TITLE
Valid number in Luxembourg (+352) reported as invalid

### ISSUE THREAD

**Issue by LeGast00n** [googlei18n/libphonenumber#575]
Hi there,
There are several number formats in Luxembourg that are reported as invalid.

Formats can be:
+352 12 34 56
+352 12 34 56 + from 2 to 4 digits (also written as +352 1234 5678 when there are 2 digits)
+352 6?1 123 456 (mobile phones - sometimes written as +352 6?1 12 34 56)

**Comment by wittydeveloper** [comment]
Hi @dlyongemallo, when will be the next batch of fixes ?

Cheers

**Comment by dlyongemallo** [comment]
The latest metadata changes were made 3 days ago. They include the changes for Luxembourg:
https://github.com/googlei18n/libphonenumber/pull/579

**Comment by wittydeveloper** [comment]
Okay ! Thanks.

I just checked (with the patch #579) the number "671xxxxxx" and it's marked as not mobile number.
But if you read [this article](http://www.wort.lu/en/business/new-mobile-phone-operator-launches-in-luxembourg-52e13a6ee4b02ecc4ece2064), a new pattern is now available : 

> Starting with the numbers +352 671, JOIN will do away with roaming fees by simply offering fixed rates throughout Europe.

**Comment by dlyongemallo** [comment]
Are you sure? I just checked it and it is identified as mobile:
http://libphonenumber.appspot.com/phonenumberparser

**Comment by dlyongemallo** [comment]
Sorry, the link is here:
http://libphonenumber.appspot.com/

**Comment by wittydeveloper** [comment]
Hum, that's true.

I guess that it's our `libphonenumber` ruby version that have a issue.

Thanks !
