### ISSUE TITLE
Translations for Error Codes

### ISSUE THREAD

**Issue by crhallberg** [googlei18n/libphonenumber#583]
Are translations for error codes on the roadmap? I'm asking particularly about the Javascript version.

**Comment by jias0001** [comment]
Which error codes are you talking about?

**Comment by crhallberg** [comment]
Sorry for the delay, codes is not the right term, error messages is more correct. Sometimes when a number fails validation it returns a string, such as "The string supplied did not seem to be a phone number" or "The string supplied is too long to be a phone number". These seem to be hard-coded as English into the Javascript.

**Comment by jias0001** [comment]
Sorry, we have no plan to provide translations for these. If you look at the Java version, they are enums. Clients are free to choose the best way they want to phrase them in different languages, including English.
