### ISSUE TITLE
[L OS]Phonenumber formatting issue in US region on android device

### ISSUE THREAD

**Issue by SubodhCh87** [googlei18n/libphonenumber#588]
Hi Team

We have encountered with an issue on android smartphone (L OS) related to phone number formatting in the US region.

Steps for reproduction
1.Open Contacts
2.Add new contact
3.Enter number "1111111" (length is 7)

We observe that phone number is showing as "1111-111" instead of "111-1111".This issue occurs only when number starts with 1 and length is 7.Please refer the below example.
1.Input 1111111 -> displays "1111-111"
2.Input 2111111 -> displays "211-1111"

On further debugging we found that issue seems to be with i18n library.Kindly provide your feedback on the issue.

Please revert back if you have any concern.

**Comment by dlyongemallo** [comment]
It's not possible for a national significant number to begin with "1" in the US. The formatter does not handle invalid numbers, so this is working as intended.
