### ISSUE TITLE
China Guiyang (code "0851"), fixed telephone number to upgrade from 7 to 8

### ISSUE THREAD

**Issue by fengyue8029** [googlei18n/libphonenumber#591]
url : http://www.gz007.net/service/guiyangzunyianshuntel8.html

BUG example:   
source:"085182881234"    geocoder: NOTHING         fmt: 85182881234

Correct:
source:"085182881234"    geocoder: 贵州省贵阳市    fmt: 0851 8288 1234

**Comment by andyst** [comment]
Thanks for the report. The next metadata release will have this change (for 851 changing from 7 to 8 digits, and removing 852 and 853 as prefix).

**Comment by roes** [comment]
Released in v7.0.3
