### ISSUE TITLE
AsYouTypeFormatter may cause an exception in CN

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#592]
In fact, I encountered this issue on Android-L VM. But you can still reproduce it with this code:

	public static void main(String[] args) {
		String countryISO = "CN";
		PhoneNumberUtil pnu =PhoneNumberUtil.getInstance();
		AsYouTypeFormatter formatter = pnu.getAsYouTypeFormatter(countryISO);
		
		String phoneNumber = "179513801031234";
		for (int i = 0; i < phoneNumber.length(); i++) {
			System.out.println(formatter.inputDigit(phoneNumber.charAt(i)));
		}
	}
Thank you for your reply! :)

![screenshot](https://cloud.githubusercontent.com/assets/3844627/5886168/0cc73d7e-a3c8-11e4-9f9d-fcf926a5a779.png)

**Comment by dlyongemallo** [comment]
Thanks for reporting this! This will be fixed in the next release.
