### ISSUE TITLE
Add FR expanded emergency numbers

### ISSUE THREAD

**Issue by dimbleby** [googlei18n/libphonenumber#598]
The only numbers recognised as emergency numbers in France are 15, 17, 18 and 112.  But it seems that there should be a few more...

Comments in the metadata give these references:

    
    
    

... both of which agree that all of 114, 115, 116000, 119 and 196 are emergency numbers.  The first page also lists 191.

Even English Wikipedia agrees with 114 and 115.

I'm not French so not well-placed to comment on which of these sources is most right.

**Comment by dlyongemallo** [comment]
Note that the metadata file has a much more restricted definition of an "emergency" number than in casual speech, and is basically restricted to the fire-police-ambulance trio. Think of it as numbers you can call on your mobile phone without unlocking.

There's also an "expanded emergency" tag, which is for things like emergency help-lines (e.g., rescue helicopters, flood rescue).

We have probably not been entirely consistent between different countries. For example, 116000 is Europe-wide for reporting child abductions, and I think probably belongs in expanded emergency (it is so classified in the Belgium metadata currently). If it's the same number and reaches the same organisation, it should be treated the same in all countries that support it. We're aware that the data on emergency (and expanded emergency) numbers aren't exactly complete or consistent.

Feel free to send a patch. (Please see: https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject)

**Comment by dimbleby** [comment]
If I was confident that I knew what the correct behaviour was I'd gladly send a patch.  But as I say, I'm not French and can't say with certainty which of these numbers a French person would expect to be treated as an emergency number.

While I have your attention - any chance of progress on the patches that I have offered?  #570, #571 and #572.  Obviously do move conversation over to the relevant pull request if there's any discussion needed...

**Comment by dlyongemallo** [comment]
Someone's supposed to be looking into those patches. I'll ping him again to remind him.

**Comment by keghani** [comment]
We added 116000 recently.
We'll look into adding the other expanded emergency numbers soon.

**Comment by penmetsaa** [comment]
This is fixed in release 7.2.7
https://libphonenumber.appspot.com/phonenumberparser?number=114&country=FR

Note: Please check "Short Number Results" section.
