### ISSUE TITLE
libPhoneNumber-Java cannot detect the Indian toll free format of 000 800 xxx xxxx

### ISSUE THREAD

**Issue by Meghaditya** [googlei18n/libphonenumber#603]
This issue is being raised in response to the discussion with David and Shaopeng on the following thread - https://groups.google.com/forum/#!topic/libphonenumber-discuss/w8KGXQre5Rw

This issue is impacting a lot of businesses using android devices in India.

Thanks,
Meghaditya

**Comment by andyst** [comment]
Summary from the discussion:
 - there are indeed many examples of Indian toll-free numbers with prefix "000 800".
 - might be tricky to support. Need to explore whether we can do it as a metadata update.

FYI @dlyongemallo

**Comment by shuvansaha** [comment]
@ Andyst, 

Could you please share any timeline on this? or against which Android release in road map will this be tracked? Any info on this (even tentative), will definitely be helpful.

Thanks in advance,
Shuvan

**Comment by keghani** [comment]
This was fixed in July/August 2016.
