### ISSUE TITLE
Add China prefix 149

### ISSUE THREAD

**Issue by chaoaero** [googlei18n/libphonenumber#608]
Currently I am using this project to normalize domestic phone number, while I found that I cannot handle some phone numbers with prefix 149. I cannot get its carrier in English. 
2) What's more, I cannot get the carrier in Chinese for all the mobile Phone numbers in China. 
3) The location file is not up to date and need to be updated.

**Comment by chaoaero** [comment]
It's original regular expression cannot identify mobile phones with prefix 149  in China

**Comment by andyst** [comment]
@149 as prefix:
q1) What's an example number?
q2) Is the prefix / range assignment mentioned in ITU docs? If not, is there an official source for this information? A government website?

Thanks for the report!

**Comment by chaoaero** [comment]
I found that the latest link about national number of China is http://www.itu.int/oth/T020200002B/en.  It was posted on 2011-10-05.  

Since now is 2015-02-12, There are many changes on national numbers  in China.  Some telephone numbers such as 14905001234 cannot be identified by libphonenumber, while it can be identified by http://api.showji.com/locating//#HTTP  which is the de facto standard that been used by nearly all the IT companys in China. 

The data I submitted is up to date.

**Comment by andyst** [comment]
guishu.showji.com seem to have a lot of phone number metadata but we can't just copy from there in terms of licensing. Worst case we can just go with your one example (if it connects), but it'd be much better to have another source.

 - Can you point at government websites which mention the 149 prefix/range or which mention a phone number starting with 149?
 - If not a government website, is there another website (of a business / person) which lists its own 149... phone number?

**Comment by chaoaero** [comment]
I am afraid that the 149 prefix is release several months ago by China
telecom. In China there are several telecom operators. I cannot find any
authority that can offer all the phone prefix. All we can do is
statistics.You can find result in https://www.baidu.com/  or
https://www.baidu.com/ by typing a phone number.

What's more, I found that in libphonenumber project,  part of the metadata
belonging to China part is also gatthered by statistics: "

*
# Generated from:
# Fixedline mappings(10 and [2-9]*) are generated from Internal
statistical data (2011-06-01)
# Mobile mappings(13*,14*,15*,18*) are contributed by
farmer1992@gmail.com <farmer1992@gmail.com>
*

*"*

The data I offered is used by the biggest IT company such as baidu or
sogou.  This ensures that the data is up to date. Our government is
too bureaucratic,
I cannot get the latest document about that.


2015-02-12 19:32 GMT+08:00 Andy Staudacher <notifications@github.com>:

**Comment by keghani** [comment]
@chaoaero ITU updated the China data last September.
We're adding new ranges from http://www.itu.int/oth/T020200002B/en but 149 isn't there. Have you seen any other documentation or websites in the meantime using 149?

We'll update our carrier and geocoding files (for Chinese too) with the data from the ITU document - if you were concerned about any others please let us know!

**Comment by keghani** [comment]
@chaoaero This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that 149 is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

_Help us help you! Use our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)
when reporting issues._

**Comment by keghani** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
