### ISSUE TITLE
NANPA Formatting for US/CA

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#61]
Imported from [Google Code issue #61](https://code.google.com/p/libphonenumber/issues/detail?id=61) created by [cfkoch](https://code.google.com/u/108438119205599918600/) on 2011-09-26T17:44:07.000Z:

----
Phone number 416 585 8585

Expected to see : 416-585-8585
Instead seeing : (416) 585-8585

It's standard to not place the area code in parenthesis marking the area-code as &quot;optional&quot;, in all the area codes that have mandatory 10-digit dialing.  

Would it be possible to properly mark all the mandatory overlaid area-codes, so that end-users don't need to maintain their own data pulled from NANPA to achieve this behaviour?

fr_CA (Quebec Language Authority) still enforces xxx xxx-xxxx for all numbers [this is a localization issue and probably out of scope]

**Comment by keghani** [comment]
jias0001 - can we close this?

**Comment by jias0001** [comment]
Looks good to me to close.

For completion: NANP numbers are special, in that 1 can be both the country code and trunk code. According to feedbacks from many clients, lots of people in the US has no idea what "1" is, which confuses them a lot. That is why we decided not to include the 1 in the national format.
