### ISSUE TITLE
Israeli phonenumber validating wrong

### ISSUE THREAD

**Issue by omerts** [googlei18n/libphonenumber#610]
Hello,

I am trying to validate an Israeli input number, but the validation returns a wrong result:
![image](https://cloud.githubusercontent.com/assets/4996164/6168446/fe96dbdc-b2cd-11e4-8a33-21670a1f8b1f.png)

+9725287 is not a valid Israeli number.
How could this be fixed please?

Omer

**Comment by dlyongemallo** [comment]
Actually, "*5287" is a valid number. It's just that the phone number library can't distinguish between the number with and without the "*".

**Comment by omerts** [comment]
Hello,
I am sorry, but I didn't understand your answer. "5287" is not a valid phone number in Israel.

**Comment by dlyongemallo** [comment]
Sorry, github markdown ate my stars. "[star]5287" is a valid number, and the library can't distinguish this from "5287" without the "[star]".

**Comment by omerts** [comment]
Ok I understand now, thank you!
