### ISSUE TITLE
Argentina - Invalid Format for Area Codes 3487 and 3489

### ISSUE THREAD

**Issue by mdaloia** [googlei18n/libphonenumber#611]
Given this valid E.164 number: +54 3487 44 1111 (the last part was modified to preserve the identity)
**Current National Format:** 0348 744-1111
**Expected National Format:** 03487 44-1111

Given this valid E.164 number: +54 3489 48 1111 (the last part was modified to preserve the identity)
**Current National Format:** 0348 948-1111
**Expected National Format:** 03489 48-1111

**Version used:** 7.0.2

This information is taken from the Argentinian bureau of communications called CNC. You can download this Excel where are all the assigned Area Codes (column INDICATIVO) and the Block number (column BLOQUE, which in this case are 44 and 481 respectively):

http://www.cnc.gob.ar/multimedia/noticias/archivos/201411/archivo_20141118022303_914.zip
(The link was obtained from this URL: http://www.cnc.gob.ar/asignaciones-a-la-fecha_p445 (On the right side there is a link with a "Númeración Geográfica" as a label))

You can filter INDICATIVO by 3487 and 3489, and BLOQUE by 44 and 481 to see all of them.

Below there is a Workaround that we made in the PhoneNumberMetadata.xml to change this behaviour:

We modified these 2 lines (872 and 940): https://github.com/googlei18n/libphonenumber/blob/libphonenumber-7.0.2/resources/PhoneNumberMetadata.xml#L872
https://github.com/googlei18n/libphonenumber/blob/libphonenumber-7.0.2/resources/PhoneNumberMetadata.xml#L940
and changed like this:

```
[...]
          4(?:
            [1235]|
            8[14-68]
          )|
[...]
```

**Comment by dlyongemallo** [comment]
The document says that 3487 and 3489 are area codes. It also says that 3482 and 3483 are area codes. However, it also lists 348 as an area code. Is it ever possible to distinguish between the "348" area code which just happens to be followed by 2, 3, 7, or 9 and one of the "348[2379]" area codes, or does it never happen that "348" is followed by one of those digits when the area code is "348"? Can you point to the document and page where this is clarified, and also where in the specification it says 3487 and 3489 should be formatted as a block of four digits?

**Comment by mdaloia** [comment]
I have found these documents:

1) http://www.cnc.gob.ar/numeracion-geografica_p137
It's in an excerpt in Spanish. In that page there is a link on the right called "National Numbering Plan" and send you to the PDF document of the point 2.

2) http://www.cnc.gob.ar/multimedia/noticias/archivos/201409/archivo_20140902125702_7584.pdf
This is in English. Look for the section called "III NATIONAL NUMBER STRUCTURE" in the PDF page 7.

The full subscriber number is always of 10 digits.
The national visualization format used in Argentina for land lines is `(area code) EF-GHIJ` and for mobiles `(area code) 15-EF-GHIJ`.
Depending on the length of the area code the prefix (which in this case is EF) it could be CDEF, DEF o EF.

If in the first document you filter by 348 you can see that all the values at "BLOQUE" column, in this case, start with 4 and there isn't a 3484 as an "INDICATIVO", it can't exist because there is no way to distinguish between the subscribers of the following example (i.e. there can't be overlapping):

* 348 4xxxxxx
* 3484 yyyyyy

The modified section corresponds to a 3-3-4 pattern and it will be used in case that 348 isn't followed by a 2, 3, 7 or 9 (or 0; I didn't see it before but maybe it can be added to to this pattern as there isn't a 3480 area code yet). The area codes 3482, 3483, 3487 and 3489 will be matched with the 4-2-4 pattern because they start with 3.

There are other cases (totally different area codes) that I was analysing after I sent this issue. I will try to submit them in other issue.

**Comment by hagbard** [comment]
For future reference, the area codes and BLOQUE column are in:
http://www.cnc.gob.ar/asignaciones-a-la-fecha_p445

**Comment by hagbard** [comment]
Thank you for this detailed report.
I verified that 348 is only ever followed by 2, 3, 4, 7, 9 and that 4 implies the 4-2-4 pattern.
I will look to see if you patch is sufficient to fix this (formatting is complex and other patterns might need checking).

**Comment by hagbard** [comment]
Sorry, I should have said that 4 implies the 3-3-4 pattern.
