### ISSUE TITLE
Mobile type format for MD region

### ISSUE THREAD

**Issue by ruscon** [googlei18n/libphonenumber#632]
version
"giggsey/libphonenumber-for-php":"7.0.2"

http://giggsey.com/libphonenumber/?phonenumber=%2B373+68+111+111&country=MD&language=&region=MD
show (it's mobile type)
+373 681 11 111

must be formatted as: +373 68 111 111

For local (landline) phonenumber - all good
http://giggsey.com/libphonenumber/?phonenumber=%2B373%2022%20111%20111&country=MD&language=&region=MD

**Comment by Mortimer2013** [comment]
What type of format does AsYouTypeFornatter return? For example, a number "011234567" in Slovenia, PhoneNumberUtil.format(number, PhoneNumberFormat.NATIONAL) will return "(01) 123 45 67", but AsYouTypeFormatter will format it to "01 123 45 67"(without brackets).

**Comment by keghani** [comment]
Hi ruscon, can you provide us with evidence that mobile numbers in Moldova must be formatted the same as landline numbers?

The libphonenumber demo is at http://libphonenumber.appspot.com/. We don't modify the code for http://giggsey.com/libphonenumber. If you need the PHP libphonenumber updated please file a similar bug at https://github.com/giggsey/libphonenumber-for-php.

**Comment by ruscon** [comment]
Hi @keghani, you can see formats in wiki
https://en.wikipedia.org/wiki/Telephone_numbers_in_Moldova

```
0-xx-xx-xx-xx call between localities and mobile phone companies
+373-xx-xx-xx-xx call to Moldova from abroad
```

**Comment by keghani** [comment]
I can't see anything on that page that suggests that mobile numbers must be formatted as
+373 xx xxx xxx
If I understand correctly that's what you're claiming by this issue.

**Comment by ruscon** [comment]
Yep, thats the problem, any Moldavian phone number in international format, should be formated as  
"+373 xx xxx xxx" or "+373 xx xx xx xx", first two digits after the country code it is the code of mobile operator or city (landline).

**Comment by dlyongemallo** [comment]
The National Regulatory Agency for Electronic Communications and Information Technology of the Republic of Moldova appears to treat the first group as a block of 3 rather than 2:
http://en.anrceti.md/resurse_numerotare_tel_mobila

It might be that either 3 or 2 digits are acceptable, but unless there's official governmental documentation saying otherwise, there isn't a good reason to change this.

**Comment by ruscon** [comment]
ok, thx
