### ISSUE TITLE
Sierra Leone mobile phone numbers are considered invalid

### ISSUE THREAD

**Issue by guillaumev** [googlei18n/libphonenumber#635]
Hi,

Apparently, a valid mobile phone number for Sierra Leone, such as +23299500743 is considered invalid by libphonenumber, even though it is a valid mobile phone number for this country.

**Comment by dlyongemallo** [comment]
Do you have any information on the "99" prefix, such as official documentation from the government or a telecom? Thanks.

**Comment by luishernando** [comment]
Hello. Regards from Freetown.
We are making our best to have. A friend expert in IT tell us and in general,  official documentation is hard to find when it comes to telephone systems in Sierra Leone. There is a national regulator (NATCOM) but they usually don't respond. All our numbers here in UN are +232-9950****.

What can we do? 

best regards

**Comment by keghani** [comment]
Who's the carrier for +232 99 xxx xxx?

**Comment by luishernando** [comment]
Dear Keghani
This morning we received confirmation from Africell that the 099 is a NDC allocated in their network in Sierra Leone. 

Please find attached an screenshot of the email (I cover the personal data) 
Please let me know if this is enough. I see that the validation process in services as Twitter and other is not possible for those +232-99 numbers  
Best regards

Luis
![africel099sierraleone](https://cloud.githubusercontent.com/assets/187263/6572092/152e1f20-c707-11e4-9f3a-6ec1e6d36a22.PNG)

**Comment by keghani** [comment]
Great, thanks for that Luis. This is good evidence, I'll include Africell as the carrier for 099.
Expect this fixed in the next release.

Do you have contact with Africell? They may like to know that "99" is not appearing on their "choose your number" page: http://www.africell.sl/choose-your-number.php

**Comment by luishernando** [comment]
Dear Keghani 
I have the contact. I'll send it to you in a private message. 

By the way, did you see this? http://blog.hackersonlineclub.com/2015/03/how-to-bypass-two-step-verification-code.html 

Best regards

**Comment by keghani** [comment]
Hi Luis,

No need to send me. I was suggesting that if you're already corresponding with them you may like to let them know.

**Comment by luishernando** [comment]
ok

**Comment by luishernando** [comment]
Hello again
The Chief Technical Officer in Africell will update their website.
Thanks a lot

![image](https://cloud.githubusercontent.com/assets/187263/6751709/094060ec-ceff-11e4-95aa-d1b65bee176a.png)

**Comment by roes** [comment]
Released in v7.0.4

**Comment by luishernando** [comment]
hey, thanks a lot! :)
