### ISSUE TITLE
GetNationalSignificantNumber include trunk prefix

### ISSUE THREAD

**Issue by ndextraze-pbp** [googlei18n/libphonenumber#638]
According to section 7.3.2 of the e164 spec (https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-E.164-201011-I!!PDF-E&type=items) the trunk prefix should not be included in the national significant number.

In the c# version of the library, if the PhoneNumber was parsed with a trunk prefix it will be included in the response of GetNationalSignificantNumber.

The function include the leading zero if it's present in the PhoneNumber struct. It should also validate that the country allows leading zero before doing so or the parsing should be changed so that the leading zero does not set the ItalianLeadingZero in the PhoneNumber struct for those countries.

**Comment by jias0001** [comment]
The C# version of the library is not part of this project. You should report a bug in that project instead.
