### ISSUE TITLE
National formatting for Hungarian numbers excludes the trunk prefix

### ISSUE THREAD

**Issue by petert82** [googlei18n/libphonenumber#647]
When formatting a Hungarian number into `NATIONAL` format the output does not include the `06` national trunk prefix.

### Steps to reproduce
Format the number `+36 1 808 8125` using format `NATIONAL`.

Expected output would be `(06 1) 808 8125` (or `(061) 808 8125`).

Actual output is: `(1) 808 8125`.

### Tested version

v7.0.3 [here](http://libphonenumber.appspot.com/)

**Comment by mihaelacr-google** [comment]
Hey! Thanks for the report!

The NATIONAL format output shows how we expect people to write the number down (eg: on a piece of paper). If you intend to format the number for mobile dialing, please see [this](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1292) method and the comment [here](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1321) which specifically addresses formatting for Hungary.

**Comment by petert82** [comment]
Hi, thanks for the quick reply!

It looks like `formatNumberForMobileDialing` is exactly what I was looking for.

Is it documented somewhere that `NATIONAL` is the 'how you would write the number down format'? The comment [here](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L365-366) mentions an ITU-T Recommendation, but from a skim of the E123 PDF it doesn't appear to stipulate exactly _what_ constitutes a 'National' number.

I had assumed that `NATIONAL` format was going to do what `formatNumberForMobileDialing` actually does.

It also doesn't help that there seems to be quite a bit of variance in how Hungarian [numbers](https://www.unicreditbank.hu/kapcsolat/?defaultLanguage=hungarian) [are](https://www.posta.hu/ugyfelszolgalat) [written](http://www.mnvzrt.hu/felso_menu/kapcsolat)!

But anyway, thanks for pointing me in the right direction, and given that the issue described appears to be desired behaviour, I guess this can be closed. :)
