### ISSUE TITLE
UK phone numbers are prepended with "0" when requesting Original Format

### ISSUE THREAD

**Issue by phileo** [googlei18n/libphonenumber#649]
upon running the demo (http://libphonenumber.appspot.com/) with "1223332900", the original format displays:
    1223 332900

However, Issuing the following call will prepend "0" to the formatted number:
    PhoneNumberUtil.getInstance().formatInOriginalFormat("1223332900", Locale.UK.getCountry());

**Comment by jias0001** [comment]
This seems to be very unlikely, as the demo is running the latest release. Which version of the library are you using? Also note in the library, we use "GB".

**Comment by phileo** [comment]
I am using the Android version of the library (built against KitKat):
import com.google.i18n.phonenumbers

So I guess there has been many updates ever since KitKat?

**Comment by jias0001** [comment]
Yes, that was a bug before, and have been fixed a couple of years ago. We don't have much control over the Android releases though.
