### ISSUE TITLE
NumberParseException  in i18n libary for Contact with more than 7 DTMF Digits

### ISSUE THREAD

**Issue by nehaishwar** [googlei18n/libphonenumber#650]
Issue observed in: Android JB43,KK & L
Models: Issue is occurring in Google Nexus 3 & Google Nexus 5 as well.
URL: http://code.google.com/p/libphonenumber/
Version: 6.1 (r658)
License: Apache 2
Description: Google Phone Number Library.

Issue Steps:
1->Save a number with DTMF digits (for eg: +390292189312,1234567)
2->Call that contact   (Contact Name will be displayed on IncallScreen)
3->Edit the number (+390292189312,12345678)
4->Call that contact   (Contact Name will not be displayed IncallScreen)

Expected result:
At Step 4 also Contact name should be displayed on IncallScreen

Logs analysis:

Pass Case(Saved Contact dialled with Number 7 DTMF digits):
11-03 01:36:33.202 V/InCall  ( 2404): CallerInfo - getGeoDescription('+390292189312,1234567')...  
11-03 01:36:33.212 D/InCall  ( 2404): CallerInfo - returned countryIso: US  
11-03 01:36:33.212 V/InCall  ( 2404): CallerInfo - parsing '+390292189312,1234567' for countryIso 'US'...  
11-03 01:36:33.212 V/InCall  ( 2404): CallerInfo - - parsed number: Country Code: 39 National Number: 292189312 Leading Zero(s): true Extension: 1234567  
If geoDescription returns successfully as per code further contactname look up query is sent as below:
11-03 01:36:33.352 V/InCall  ( 2404): CallerInfo - - getColumnIndexForPersonId: contactRef URI = 'content://com.android.contacts/phone_lookup_with_profile/%2B390292189312?sip=false'...  

Fail Case(Saved Contact dialled with more than 7 DTMF digits):
11-03 01:37:03.822 V/InCall  ( 2404): CallerInfo - getGeoDescription('+390292189312,12345678')...  
11-03 01:37:03.832 D/InCall  ( 2404): CallerInfo - returned countryIso: US  
11-03 01:37:03.832 V/InCall  ( 2404): CallerInfo - parsing '+390292189312,12345678' for countryIso 'US'...  
11-03 01:37:03.832 W/InCall  ( 2404): CallerInfo - getGeoDescription: NumberParseException for incoming number '+390292189312,12345678'  
11-03 01:37:03.832 V/InCall  ( 2404): CallerInfo - - parsed number: Country Code: 39 National Number: 292189312 Leading Zero(s): true  
But in Fail case as GeoDescription is returning NumberParseException,further query for contact lookup is not generated.

As getGeodescription is using i18n library ,please check why this exception has been raised.

**Comment by lararennie** [comment]
How many DTMF digits do you expect to see after a phone number in the worst case? Can you describe your use-case more?

**Comment by lararennie** [comment]
Closing this as infeasible since no more information was reported on how long extensions can be. We need a limit in practice; if someone has real phone numbers that justify us increasing it from the current somewhat arbitrary limit, we would be happy to reconsider.
