### ISSUE TITLE
Non-allocated UK mobile ranges flagged as valid mobile

### ISSUE THREAD

**Issue by callummacgregor** [googlei18n/libphonenumber#651]
According to this Ofcom list: http://www.ofcom.org.uk/static/numbering/s7_code.txt the number range 44711xxx is not allocated but according to libphonenumber is valid and is a mobile. This is incorrect, but seeing as linphonenumber hasn't got an "unallocated" type, maybe it should be given a type of "unknown"? 

FYI there are probably a load more number ranges that are not allocated, this was just the first one I came across.

**Comment by jias0001** [comment]
It would be a lot of work to get it perfect, and we have decided to care a lot more about a valid number being incorrectly classified as invalid by the library than the other way round.

That being said, we welcome contributions, if you want to make the regex pattern perfect :) We don't have unallocated type. To us, unallocated is normally treated as invalid.
