### ISSUE TITLE
628 area code not supported

### ISSUE THREAD

**Issue by Silenthillnight** [googlei18n/libphonenumber#653]
In San Francisco, the 628 area code is going into service on March 21st but libphonenumber currently does not support this area code.

http://www.cpuc.ca.gov/PUC/Telco/generalInfo/Area+Codes/415+Area+Code.htm

**Comment by jias0001** [comment]
Yes, there seems to be 4 new area codes going into service this year. We
will get them added. Thanks for reminding us! :-)

http://www.nanpa.com/enas/plannedNpasNotInServiceReport.do

Shaopeng

**Comment by jias0001** [comment]
This will be fixed in the next push.

**Comment by roes** [comment]
This was released today in v7.0.4
