### ISSUE TITLE
US National Mode should no longer use parenthesis

### ISSUE THREAD

**Issue by FesterCluck** [googlei18n/libphonenumber#654]
I'm hoping the community will comment heavily on this. According to E.123, http://en.wikipedia.org/wiki/E.123#Example_formats , parentheses are used to indicate "digits that are sometimes not dialed". As all of the US is now on 10 or 11 digit dialing, should area codes in the US still have parentheses?

**Comment by lararennie** [comment]
I'll close this as it's not an issue with the library. Good question though to bring up on 
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss)?
