### ISSUE TITLE
Canada 622 area code is not supported

### ISSUE THREAD

**Issue by Silenthillnight** [googlei18n/libphonenumber#657]
I noticed that the 622 area code that went into service on March 23rd, 2015 is not supported by libphonenumber at the current time.  Will there be support for this area code in the near future?  I noticed that this number is for machine-to-machine communication but it looks like libphonenumber does support similar area codes with this kind of function (for example, the 600 area code which 622 was placed into service as a relief.)

**Comment by roes** [comment]
Hi,
Which country are you referring to?
We don't actively support M2M numbers, but you're welcome to create a pull request if you want it added, if we already have some prefixes of that type for the country.

**Comment by Silenthillnight** [comment]
the area codes 600 and 622 are from Canada.

**Comment by dlyongemallo** [comment]
Can you provide any documentation that the area code went into effect?

Wikipedia currently says 622 is reserved to relieve 600, but not has never been used:
http://en.wikipedia.org/wiki/Area_code_600

**Comment by Silenthillnight** [comment]
If you do a query on the NANPA website, it shows that the area code has gone into service on March 23rd of this year.

http://www.nanpa.com/enas/area_code_query.do
![screen shot 2015-04-07 at 11 50 51 am](https://cloud.githubusercontent.com/assets/1617734/7030858/785d845c-dd1c-11e4-9b6f-e5f9bb1fdfe0.png)

**Comment by dlyongemallo** [comment]
This should be fixed in the library now.
