### ISSUE TITLE
asyoutypeformatter_test.js cannot be run from github cleanly.

### ISSUE THREAD

**Issue by hagbard** [googlei18n/libphonenumber#658]
Running the as-you-type formatter tests is currently broken. On a clean clone of the repository you get.

     [exec] i18n/phonenumbers/asyoutypeformatter_test.js:1164: ERROR - Access to private property getExtractedNationalPrefix_ of i18n.phonenumbers.AsYouTypeFormatter not allowed here.
     [exec]   assertEquals('0', f.getExtractedNationalPrefix_());
     [exec]                     ^
     [exec] 
     [exec] i18n/phonenumbers/asyoutypeformatter_test.js:1166: ERROR - Access to private property getExtractedNationalPrefix_ of i18n.phonenumbers.AsYouTypeFormatter not allowed here.
     [exec]   assertEquals('', f.getExtractedNationalPrefix_());
     [exec]                    ^
     [exec] 
     [exec] 2 error(s), 0 warning(s), 97.6% typed
     [exec] calcdeps.py: JavaScript compilation failed.

This seems related to how the JS compiler interprets private functions.

**Comment by dlyongemallo** [comment]
@hagbard - Can this be closed?
