### ISSUE TITLE
Add support for Somaliland

### ISSUE THREAD

**Issue by asiminiceanu** [googlei18n/libphonenumber#661]
Somaliland is not supported by the library.

For more details please see the following like:
http://somalilandsun.com/index.php/economic/2888-somaliland-as-the-new-063-cell-phone-digits-take-root-telesom-and-state-justify-addition

**Comment by dlyongemallo** [comment]
There seem to be two separate issues here:
- whether or not "Somaliland" is identified by the library as a separate country than Somalia
- whether +252 63 is supported as a mobile prefix

You can use our demo (http://libphonenumber.appspot.com/) to verify that those numbers are indeed supported, and that the carrier is identified as Telesom. As for identifying Somaliland as a country, we follow the list of countries maintained by the ITU:
http://www.itu.int/oth/T0202.aspx?parent=T0202

Until the ITU lists Somaliland as a separate country, libphonenumber won't do so. The people you need to petition to make this happen are the ITU.
