### ISSUE TITLE
Area code 048 for IE to Northern Ireland, UK calls not recognized

### ISSUE THREAD

**Issue by jakumeowski** [googlei18n/libphonenumber#663]
Northern Ireland uses the UK +44 numbering plan: http://en.wikipedia.org/wiki/Telephone_numbers_in_the_Republic_of_Ireland#Calls_to_Northern_Ireland.

Calls to Northern Ireland, e.g. `'90xx xxxx'` (Belfast) can be made from Ireland by dialing either:
`'(048) 90xx xxxx'` (from within the Republic of Ireland)
`'+44 28 90xx xxxx'` (in international format)
However, the latter can be more expensive.

(Using phonenumbers, the python port of libphonenumber)

```
>>> import phonenumbers
>>> num = phonenumbers.parse('+442890000001', 'GB')
>>> phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.NATIONAL)  # Correct for calls from within the UK
u'028 9000 0001'
>>> phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.INTERNATIONAL)  # Should be '(048) 9000 0001' from IE
u'+44 28 9000 0001'
```

From a product standpoint, we may want to display numbers in the less-expensive local format. Since we can only format a number in either `NATIONAL`/`INTERNATIONAL` format, we can't distinguish calls that are dialed from IE unless we have preemptively adjusted the raw digits to something like `'+353 48 9000 0001'` or `'+44 48 9000 0001'`, neither of which are valid numbers in international format.

Perhaps `dialing_country` would be a more appropriate parameter for this situation.

**Comment by keghani** [comment]
The problem is that there are many countries with such arrangements that are not standard. For such special arrangements we don't have support in place and don't plan on including it anytime soon.
