### ISSUE TITLE
What type of format does AsYouTypeFornatter return?

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#665]
What type of format does AsYouTypeFornatter return? For example, a number "011234567" in Slovenia, PhoneNumberUtil.format(number, PhoneNumberFormat.NATIONAL) will return "(01) 123 45 67", but AsYouTypeFormatter will format it to "01 123 45 67"(without brackets).

**Comment by keghani** [comment]
AsYouTypeFornatter uses the format specified in numberFormat → format/intlFormat. Slovenia doesn't have parentheses in the AsYouTypeFornatter result because they're not in <format>, but <nationalPrefixFormattingRule> as national prefix is involved here.

    <availableFormats>
      <numberFormat nationalPrefixFormattingRule="($NP$FG)"
        pattern="(\d)(\d{3})(\d{2})(\d{2})">
        <leadingDigits>
          [12]|
          3[4-8]|
          4[24-8]|
          5[2-8]|
          7[3-8]
        </leadingDigits>
        <format>$1 $2 $3 $4</format>
      </numberFormat>

**Comment by keghani** [comment]
[Markdown got me]

I mean they're not in \<format\>, but \<nationalPrefixFormattingRule\> as national prefix is involved here.

**Comment by Mortimer2013** [comment]
Thank you for your reply. So to estimate whether a number is formatted correctly is according to PhoneNumberUtil.format not AsYouTypeFormatter?

**Comment by keghani** [comment]
Not quite.
Use AsYouTypeFormatter for formatting on the fly, as the user is typing into an input field. If the user enters parentheses they will end up in the output.
PhoneNumberUtil.format gives you only one of possibly many "correct" formats.
Validity is about the digits, not the format.
What's your use case? If I know more maybe I can help you better.

**Comment by Mortimer2013** [comment]
Actually one tester of my company reports it to me as a bug cause she thinks PhoneNumberFormat.NATIONAL format type of a country/region is unique while AsYouTypeFormatter returns different result from AsYouTypeFormatter.

**Comment by keghani** [comment]
Is AsYouTypeFormatter returning different results on the same input? Can you give examples? Steps to reproduce?

**Comment by Mortimer2013** [comment]
011234567 in Slovenia, PhoneNumberUtil.format(number, PhoneNumberFormat.NATIONAL) will return "(01) 123 45 67", but AsYouTypeFormatter will format it to "01 123 45 67". I thnik all regions that contain nationalPrefixFormattingRule may be the same

**Comment by keghani** [comment]
If I understand correctly, you have:
Input: 011234567
PhoneNumberUtil.format(number, PhoneNumberFormat.NATIONAL): (01) 123 45 67
AsYouTypeFormatter: 01 123 45 67

In this case the result of PhoneNumberUtil.format is always the same on the given input; the result of AsYouTypeFormatter is also always the same on the given input. This is working as intended. AsYouTypeFormatter will not contain parentheses since the input doesn't.

To verify, you can test the input at http://libphonenumber.appspot.com/ (region code "SI").

**Comment by Mortimer2013** [comment]
I think what makes the difference is nationalPrefixFormattingRule which only works on PhoneNumberFormat.NATIONAL type. For example, 2015555555 in US will be formatted in the same way ((201) 555-5555) in both PhoneNumberUtil.format and AsYouTypeFormatter cause there is no nationalPrefixFormattingRule in US element.

**Comment by dwbruhn** [comment]
> AsYouTypeFornatter uses the format specified in numberFormat → format/intlFormat.

@keghani Is this still accurate? I see a difference in AsYouTypeFormatter behavior among countries.

[The US AsYouTypeFormatter output adds parentheses to match the national format:](https://libphonenumber.appspot.com/phonenumberparser?number=5104261234&country=US)

Region: US
Input: 5104261234
International format: +1 510-426-1234
National format: (510) 426-1234
__AsYouTypeFormatter output: (510) 426-1234__

[But the HU AsYouTypeFormatter output does __not__ add the parens of the national format:](https://libphonenumber.appspot.com/phonenumberparser?number=12345678&country=HU)

Region: HU
Input: 12345678
International format: +36 1 234 5678
National format: (1) 234 5678
__AsYouTypeFormatter output: 1 234 5678__

Could you help me understand what behavior I'm seeing here for HU?

**Comment by keghani** [comment]
Yes, that's expected.

From `PhoneNumberMetadata.xml`:

The format that applies for that US number is:
```
        <numberFormat pattern="(\d{3})(\d{3})(\d{4})">
          <format>($1) $2-$3</format>
          <!-- A different pattern is used when formatting internationally, as the area code is no
               longer optional and should not be in brackets. -->
          <intlFormat>$1-$2-$3</intlFormat>
        </numberFormat>
```

The format that applies for that HU number is:
```
        <numberFormat pattern="(1)(\d{3})(\d{4})">
          <leadingDigits>1</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
```

Look at `<format>`; the US ones has a parenthesis, the HU one doesn't.

Since this isn't an issue with the library, could you please write any followups to the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss)? That way others on the list could benefit from the information :)
