### ISSUE TITLE
Regex file encoding

### ISSUE THREAD

**Issue by andreagrimaldi** [googlei18n/libphonenumber#668]
I was trying read the regular expression for [Panama](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_PA) but since it's a raw file I see some strange characters. I guess this is because it's a binary file. Would you please tell me which encoding is this file using? Or, where can I find the regex this file was based on?

Thanks a lot.

**Comment by giggsey** [comment]
It's a big file, but this should link you to the section: https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L17865

**Comment by andreagrimaldi** [comment]
Thanks so much!
