### ISSUE TITLE
PhoneNumberUtil.getNumberType() always returns FIXED_LINE_OR_MOBILE

### ISSUE THREAD

**Issue by rgurley** [googlei18n/libphonenumber#669]
Out of >15000 phone numbers scanned, this method returned PhoneNumberType.FIXED_LINE_OR_MOBILE all but 18 times. 13 were TOLL_FREE. 5 were UNKNOWN. Basically, this method is completely useless.

String digits = "2018675309";
PhoneNumberUtil util = PhoneNumberUtil.getInstance();
//Always returns FIXED_LINE_OR_MOBILE
util.getNumberType(util.parseAndKeepRawInput(digits, "US"));

**Comment by roes** [comment]
The library is based on number prefixes, for the US there's no distinguishing between mobile or fixed line on that level, therefore you'll get FIXED_LINE_OR_MOBILE for US numbers.
For most other countries the sets are completely separate and you'll get FIXED_LINE or MOBILE returned when appropriate.

**Comment by rgurley** [comment]
Ah, I see. That's disappointing. All my numbers are in the US. Thanks for the explanation.
