### ISSUE TITLE
Vatican City (VA) country calling code

### ISSUE THREAD

**Issue by philtay** [googlei18n/libphonenumber#671]
The Vatican City (VA) country calling code is +39 and not +379. The latter has been assigned to the Vatican City by the ITU-T, but never used in practice. Vatican City is reached only via the Italian telephone numbering plan with country code +39. In the official ITU-T recommendation E.164, you can see that +39 is listed as the currently used country code for Vatican City. +379, instead, is marked as "reserved for future use".

http://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164D-11-2011-PDF-E.pdf

**Comment by jias0001** [comment]
According to the comment in the metadata, we were under the impression that +379 actually works at the same time with +39. Now that this is not true (also according to the latest version of wikipedia), we should simply get rid of the section of the metadata for VA. It is not listed separately by ITU anyway:

http://www.itu.int/oth/T0202.aspx?parent=T0202

Assigning to hegbard, who is on duty this week.

**Comment by philtay** [comment]
Not sure if the Pope would be happy with that! ;) In my opinion you should just change the prefix: from +379 to +39. Everything else is just fine. Not having the possibility of validating a Holy See's number could be a problem (especially for those living in Italy).

P.S. In the document I linked in my previous post Vatican City is listed separately by ITU and the prefix is +39.

**Comment by jias0001** [comment]
The only concern I have about that is we have to exclude these numbers from
the Italian numbering plan, which can be quite messy as the Vatican
numbering prefix is really specific.

**Comment by philtay** [comment]
Not sure if you really have to exclude them. They are part of the Italian numbering plan, but assigned to the Holy See as they don't have their own numbering plan.
This is a link to the Vatican State website:

http://www.vaticanstate.va/content/vaticanstate/en/servizi/servizio-telefoni/attivita.html

Here you can find some other info. At least now you have something more official than Wikipedia which states that the +379 prefix is not used. :)

**Comment by jias0001** [comment]
Thanks for the link, it is very useful. Yes, we don't have to exclude it if
we mark Italy's <territory mainCountryForCode="true">.

**Comment by philtay** [comment]
I think this is the right solution.

**Comment by roes** [comment]
This is fixed in libphonenumber 7.0.8
