### ISSUE TITLE
Saint Helena, Ascension and Tristan da Cunha

### ISSUE THREAD

**Issue by philtay** [googlei18n/libphonenumber#673]
Tristan da Cunha (TA) and Ascension Island (AC) don't exist anymore as individual countries. They have been grouped under a single ISO 3166 country code: Saint Helena, Ascension and Tristan da Cunha (SH).

http://en.wikipedia.org/wiki/ISO_3166-2:SH-AC
http://www.iso.org/iso/home/standards/country_codes.htm

**Comment by jias0001** [comment]
We don't have a 'country' concept in the library, but a 'region' concept. For example, HK is part of CN, but it has its own country calling code. This is similar to the relationship between AC and SH. We can consider dropping AC and TA if one day they are dropped completely by ISO (e.g. when it is no longer a unique region), but at this moment AC and TA are exceptionally reserved by ISO at the request of the Universal Postal Union.

We will keep monitoring the situation, and update later when it is appropriate.

**Comment by philtay** [comment]
The fact they are "exceptionally reserved" doesn't mean too much. Currently there are other 11 exceptionally reserved codes and a lot of indeterminately and transitionally reserved codes. The library doesn't support nor include any of them: only TA and AC.
Even if this is a singularity (these are the only two non-officially assigned country codes you support) there could be a reason. Saint Helena, Ascension and Tristan da Cunha (SH) is the only country in the world which has two prefixes.
Despite they are a single ISO country (or region if you prefer) the prefix of "Ascension" is +247, but "Saint Helena & Tristan" share another prefix (+290). Thus, to be standard consistent, you should at least remove Tristan da Cunha. It doesn't exists anymore as an individual region and has the same prefix of "Saint Helena, Ascension and Tristan da Cunha" (i.e. the official ISO country).

P.S. Could you please also have a look at my other issue (https://github.com/googlei18n/libphonenumber/issues/671)?

Thanks

**Comment by jias0001** [comment]
Tristan da Cunha is still an individual region. We will remove it later when the region code is marked as deprecated by BCP47/CLDR, which we generally follow for region codes.
