### ISSUE TITLE
Why the phone number format pattern is different for the same country on different devices (android and iOS) using libphonenumber library?

### ISSUE THREAD

**Issue by modibhaviks** [googlei18n/libphonenumber#675]
I have used the same library for iOS and Android with same method/code for formatting phone number

For example the format of same Indian mobile number without country code for iOS is different from android SDK

Android SDK: XX XX XXXXXX
iOS SDK: XXXXX XXXXX
While formatting of US phone number using same library in iOS and Android gives similar output but for Indian mobile number the output varies.

http://stackoverflow.com/questions/29773301/why-the-phone-number-format-pattern-is-different-for-the-same-country-on-differe

**Comment by dlyongemallo** [comment]
What versions of the library are you using? It's probable that the format just changed between versions.

**Comment by dlyongemallo** [comment]
The iOS library is a port, and it's likely that it's just out of date. But without further information about the versions you're running, we can't answer this question.

The answer given on stackoverflow that "different developers made different decisions as how to format the number" is wrong, btw. The library (and its ports) should behave identically across different systems at the same version number.

**Comment by modibhaviks** [comment]
Library does not contain any information regarding version. But in header of NBAsYouTypeFormatter file mentioned "Created by ishtar on 13. 2. 25"

**Comment by dlyongemallo** [comment]
If you look at their commits, the latest one refers to "Update metadata from libphonenumber-7.0.5", so that's what they're on:
https://github.com/iziz/libPhoneNumber-iOS/commits/master

You need to file this issue against them.
