### ISSUE TITLE
Can't detect Carrier for this phone number: 011230430XX 

### ISSUE THREAD

**Issue by aminalzanki** [googlei18n/libphonenumber#676]
Hi,

I encountered a problem with this number, 011230430XX. The library just cannot detect the Carrier for this number. It supposedly return MAXIS as a Carrier. As a result, our app user can't register an account.

Phone Number: 011230430XX 
Country-ISO: MY

Please check as soon as possible. Thanks.

**Comment by hagbard** [comment]
We always try to have some official document that shows a number range belonging to a carrier before adding it. Without some kind of documentation to back up the mapping we generally won't add them. Sorry.

Do you have any document or website that shows the carrier for these numbers is MAXIS ?

We don't have a good carrier mapping for Myanmar unfortunately as this information is not easy to come by. If you have a source of carrier mappings you can share with us, that would be great.

**Comment by aminalzanki** [comment]
@hagbard this is not in Myanmar, but Malaysia (MY). They have been implemented a few years before already. You can see the link here : http://www.skmm.gov.my/Media/Announcements/01-October-2010-Notification.aspx?feed=Media-RSS-Feed

**Comment by mihaelacr-google** [comment]
Thanks for the clarification. The carriers are clearly defined here: http://www.skmm.gov.my/skmmgovmy/media/General/pdf/Mobile-Cellular-3-8_6.pdf

We should update our data soon with the carrier info.

**Comment by aminalzanki** [comment]
![screen shot 2015-05-18 at 6 40 38 pm](https://cloud.githubusercontent.com/assets/1040492/7679243/8f30db98-fd8d-11e4-9d43-8571831f1b52.png)

The phone number considered to be too long while its a valid phone number. Could please check. Thanks.

**Comment by dlyongemallo** [comment]
Do you have any evidence that +60 11140667153 is a valid number? According to the above doc, it is too long: "1400 0000 - 1449 9999 Maxis Mobile Services Sdn Bhd"

**Comment by roes** [comment]
The updated carrier mapping were released in libphonenumber 7.0.7
If you think the number length is incorrect, please file a separate bug for that, with supporting evidence.
