### ISSUE TITLE
Swedish 010 area code

### ISSUE THREAD

**Issue by sime** [googlei18n/libphonenumber#678]
Should perhaps the 010 area code be considered a service/share cost number?

http://en.wikipedia.org/wiki/Telephone_numbers_in_Sweden

**Comment by hagbard** [comment]
The WIkipedia page just says:
010	Geographically Independent Numbers / VOIP services

If we look at the official ITU document:
http://www.pts.se/upload/Ovrigt/Tele/Nummerfragor/swedish-numbering-plan-for-telephony-acc-itu-140407.pdf
it also doesn't say much.

To be considered a shared cost number all numbers in the range must be shared cost.
You can see this in the ITU document for the 077 range. There's no indication I can see that this would be the case for all 010 numbers.

If you have evidence for the claim that all 010 numbers are shared cost, please reopen this.

**Comment by sime** [comment]
Thanks for the additional information.
