### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by doublex** [googlei18n/libphonenumber#679]
````
resources/timezones/map_data.txt
Europe/Belarus -> Europe/Minsk
````

**Comment by hagbard** [comment]
Do you have any citations for this?
It looks like it makes sense (city, not country) but I'm not sure what the accepted standard is.

**Comment by doublex** [comment]
"Europe/Minsk" is part of the "IANA time zone database":
http://en.wikipedia.org/wiki/Europe/Minsk

"Europe/Belarus" is wrong.

**Comment by mihaelacr-google** [comment]
This issue will be fixed once we do our next metadata push.

Thanks for the report!
