### ISSUE TITLE
Split Javascript to separate repo and add Bower

### ISSUE THREAD

**Issue by rvanlaak** [googlei18n/libphonenumber#683]
The library is great, but the way to install it in our project could be even greater.

Please split the Javascript code to a separate repository, and add a `bower.json` file so it can be installed as a frontend library more easily.

http://bower.io/docs/creating-packages/

**Comment by hagbard** [comment]
We have no plans to do this at the moment, but you are free to create your own repository with its own packaging requirements that clones the Javascript.

**Comment by Rvanlaak** [comment]
There already is a fork: https://github.com/nathanhammond/libphonenumber

The problem with that approach is the latest commits / releases have to be merged by the maintainer manually. Fixing this at the source would be great :+1:

**Comment by ruimarinho** [comment]
@Rvanlaak you can also give [seegno/google-libphonenumber](https://github.com/seegno/google-libphonenumber) a try which supports bower. It also includes an update script which allows you to sync with this repository in case you need faster updates.

**Comment by keghani** [comment]
We still have no plans to do this.

**Comment by rvanlaak** [comment]
I can understand that splitting in different repos is a no-go. Maybe git submodules could help with this a bit?
