### ISSUE TITLE
Curaçao

### ISSUE THREAD

**Issue by SvanThuijl** [googlei18n/libphonenumber#685]
The country-code for Curaçao is not +599 but +5999.

Previously +599 what the Netherlands Antilles. The last 9 was the areacode for Curaçao. Now Curaçao is a country on it's own and the complete countrycode is +5999.

How can i solve this in my javascript implementation?

**Comment by mihaelacr-google** [comment]
+599 is the official country code. 9 is an area code that applies to the entire country. One needs to always dial +5999 for Curaçao (+599 is the official prefix for Curaçao and the Caribbean Netherlands). 

Sources:
http://www.howtocallabroad.com/curacao/
http://en.wikipedia.org/wiki/Telephone_numbers_in_Cura%C3%A7ao_and_the_Caribbean_Netherlands
http://www.countrycallingcodes.com/country.php?country=Curacao

**Comment by SvanThuijl** [comment]
I see what you mean but in reality this is old information. Previously all these areas were part of the Netherlands Antilles. Since 2010 Curaçao and Aruba are separate countries. Aruba got their own country code +297 but Curaçao kept using +599 9. In my opinion this should be seen an separate country code.

Also on the wikipedia page below +599 9 is seen as the counties calling code.
http://en.wikipedia.org/wiki/Cura%C3%A7ao

**Comment by dlyongemallo** [comment]
The library follows the convention used by the ITU. According to the current latest ITU doc, the country code is +599 and 9 is an area code that applies to the entire country:
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000F50001PDFE.pdf

If you want this changed in the library, you need to petition the ITU to change it in their documentation first.

**Comment by SvanThuijl** [comment]
I guess you guys are right. The only thing is that users don't see it this way so they wil fail to enter the area code if they see country code +599.

**Comment by rzaryan** [comment]
@SvanThuijl  What is the best way to petition the ITU to update their documentation?
