### ISSUE TITLE
Defining static variables in phonenumberutil.h causes link problems

### ISSUE THREAD

**Issue by hubbobubbo** [googlei18n/libphonenumber#686]
There are 4 static variables defined in phonenumberutil.h such as

 static const size_t kMinLengthForNsn = 2;

I am writing a C wrapper for the C++ calls and at least in this scenario this does not work.

IMHO, the definition should go in the .cc file instead to avoid LNK2005 errors. I have moved the assignment of the value to the cc file instead and that works as expected.

wdyt

**Comment by mihaelacr-google** [comment]
Just to clarify, the constants you are referring to are the following:
 ```
 // The minimum and maximum length of the national significant number.
  static const size_t kMinLengthForNsn = 2;
  // The ITU says the maximum length should be 15, but we have found longer
  // numbers in Germany.
  static const size_t kMaxLengthForNsn = 16;
  // The maximum length of the country calling code.
  static const size_t kMaxLengthCountryCode = 3;
  static const int kNanpaCountryCode = 1;
```

other static constants, such as ` static const char kCaptureUpToSecondNumberStart[];` are not a problem?

**Comment by hubbobubbo** [comment]
Exactly, the problem only occurs when you assign a value in the .h file. Pure declarations are not an issue. As long as you define the value in the cpp file, everything is ok.

**Comment by mihaelacr-google** [comment]
Hi!

Sorry for the delay. It seems to me that you are affected by the bug mentioned here: http://stackoverflow.com/questions/16404173/does-visual-studio-2010-c-fully-support-in-class-const-variables

What do you think?

**Comment by keghani** [comment]
This seems to be a setup issue, or a Visual C++ bug.

Please see the link that @mihaelacr-google referenced above.
