### ISSUE TITLE
+3373*, +3374* and +33700* not recognized as french mobile phone numbers

### ISSUE THREAD

**Issue by nail** [googlei18n/libphonenumber#688]
Hello,

This is a follow-up of #11 . According to https://github.com/googlei18n/libphonenumber/issues/11#issuecomment-65489376 french mobile phone numbers must start with 6 or 7[5-9], however 7[3-4] and 700 should also be recognized as such.

The official plan can be found here http://www.arcep.fr/index.php?id=8146&L=1 (looks like it's only available in french, sorry)

Cheers

**Comment by jias0001** [comment]
Thanks for letting us know Renaud! We will work on fixing this.

Cheers,

Shaopeng

**Comment by andyst** [comment]
This change will be in the upcoming libphonenumber 7.0.7.

**Comment by nail** [comment]
Thanks!

**Comment by andyst** [comment]
Thanks! This is in libphonenumber 7.0.7.
