### ISSUE TITLE
Handle "+" sign for Guadeloupe (GP)

### ISSUE THREAD

**Issue by mansoury** [googlei18n/libphonenumber#689]
I have an issue for number from Guadeloupe. In my app, +590 is added automatically but libphonenumber does not valid that number. I'd like to handle the "+" sign for number from Guadeloupe "GP".
For example : 
590997580 => +590997580

 How can I do that ?

Thank you

**Comment by jias0001** [comment]
I don't understand the issue here. Could you explain exactly what is the issue with libphonenumber here?

If this is not an issue with the lib, and you just want to ask questions, please use our discussion group instead:

https://groups.google.com/forum/#!forum/libphonenumber-discuss

**Comment by mansoury** [comment]
Thank you for your answer.
Ok, I'll try to be more clear.
When I submit this number "+590997580" to libphonenumber (http://libphonenumber.appspot.com), I get this result:
Result from isPossibleNumber()	false
Result from isPossibleNumberWithReason()	TOO_SHORT
This number is considered as "UNKWNOWN"

What can I do for this number to be considered as "valid" ?

**Comment by giggsey** [comment]
The country code for GP is 590. `+590590997580` is considered a valid number (So in this case, the number in the national format is `0590 99-7580`).

**Comment by jias0001** [comment]
Exactly as giggsey said :)
