### ISSUE TITLE
New mobile prefix in Barbados

### ISSUE THREAD

**Issue by silentdon** [googlei18n/libphonenumber#698]
Digicel Barbados is using the 256 prefix for mobile phone numbers. Currently, getNumberType() returns FIXED_LINE for this prefix.

Example
+124625649xx
+124625614xx

**Comment by roes** [comment]
Hi,
Do you have any supporting documents that this is used as a mobile prefix?

**Comment by silentdon** [comment]
I only have my phone bill. I anonymized it, I hope it will suffice.
![Digicel Bill](http://i.imgur.com/J23KZWQ.png)

**Comment by roes** [comment]
Thanks, this will be apart of the next metadata update

**Comment by andyst** [comment]
This change is in libphonenumber 7.0.6 which we released a few weeks ago.
