### ISSUE TITLE
Gabon phone number detection/check

### ISSUE THREAD

**Issue by asiminiceanu** [googlei18n/libphonenumber#701]
Take two Gabon phone numbers:
+241 4111111
+241 04111111

Normally the second one should be seen after parsing as +241 4111111 as the leading zero seems to have been completely removed (http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200004E0002PDFE.pdf)

**Comment by roes** [comment]
Hi,
That document seems to say that removing of the 0 has been postponed. Can you clarify what you thing is wrong?

**Comment by asiminiceanu** [comment]
Opps, I missed that line. Let me me do some more inquire and I will come back to this matter.
For the moment I will close this issue and reopen it if needed.
