### ISSUE TITLE
+7 707* is not recognised as Tele2 Kazakhstan

### ISSUE THREAD

**Issue by endeveit** [googlei18n/libphonenumber#702]
Hello.

+7 707 is a prefix of Tele2 Kazakhstan.
It's listed [here](http://en.wikipedia.org/wiki/List_of_mobile_phone_number_series_by_country) and [here](http://www.itu.int/oth/T020200006F/en) (in PDF or DOC file)

**Comment by andyst** [comment]
+7 707 is already recognized as a valid number.

Is this request / report about carrier information, i.e. adding 7707 -> Tele2 to our carrier mapping data?

If so, do you have any official documentation (government or from tele2) as evidence?
We can't blindly trust Wikipedia on this. Thanks!

**Comment by endeveit** [comment]
Oh, yes.
This is request about adding 7707 to carrier mapping data.
I found couple of news on official Tele2 website but they are in russian language.
In [first](http://uko.tele2.kz/ru/166.html) they told that they launched DEF-code "747" in addition to 707.
And in [second](http://www.almaty.tele2.kz/ru/377.html) they told that they increased numbering series in DEF-code "707".
Is this enough?

**Comment by andyst** [comment]
That will do, thanks @endeveit . We'll close this issue here once we've had a chance to incorporate the metadata change and release a new library version. Should be part of the next release.

**Comment by endeveit** [comment]
Thanks!

**Comment by andyst** [comment]
This change will be in the upcoming libphonenumber 7.0.7 (probably released later this week).

**Comment by andyst** [comment]
Thanks! This is in libphonenumber 7.0.7.
