### ISSUE TITLE
Ukrainian mobile operator have new code 73

### ISSUE THREAD

**Issue by valerii-iermolenko** [googlei18n/libphonenumber#703]
Hi,

The Ukrainian mobile operator since 5'th Nov have new code 73.

Here is wiki page with phone codes: http://en.wikipedia.org/wiki/Telephone_numbers_in_Ukraine

The reported code is:

+380 73 xxx-xx-xx  (international call to life:) Ukraine) 

Could you add this code to mobile validator at Number::Phone::StubCountry::UA module?

Here is validator which works at my side:
my $validators = {'special_rate' => '()|(900\\d{6})|()','pager' => '','personal_number' => '','voip' => '89\\d{7}','toll_free' => '800\\d{6}','mobile' => '(?:39|50|6[36-8]|73|9[1-9])\\d{7}','fixed_line' => '(?:3[1-8]|4[13-8]|5[1-7]|6[12459])\\d{7}','geographic' => '(?:3[1-8]|4[13-8]|5[1-7]|6[12459])\\d{7}'};

Best regards,
Valerii Iermolenko

**Comment by andyst** [comment]
Thanks for the report, @valerii-iermolenko .

Is there an official government or telecom provider document that you can link to as evidence?


We'll also need to cross-check the English Wikipedia article with the Ukrainian one:

http://uk.wikipedia.org/wiki/Телефонні_коди_України
Mobile:
http://uk.wikipedia.org/wiki/Коди_мобільних_операторів_України

The 73 prefix is mentioned in the article for mobile ranges.

**Comment by andyst** [comment]
In the absence of a government / telecom document as evidence (on top of Wikipedia), can you point at a (business) website which lists a 73 number so we can verify that the number connects?

**Comment by andyst** [comment]
2) Regarding the Perl port: We're not maintaining that directly here. Once we've fixed the metadata issue here, it will take the maintainer of the Perl port to update sync to the latest metadata to the issue you've reported.

http://search.cpan.org/~dcantrell/Number-Phone-3.0007/lib/Number/Phone.pm
David Cantrell <david@cantrell.org.uk>

**Comment by Fer0x** [comment]
Results of the regular NCCIR meeting dated of 6 January, 2015
http://www.nkrzi.gov.ua/index.php?r=site/index&pg=99&id=733&language=uk

**Comment by andyst** [comment]
Thanks! I've created an internal task to make the change.
We'll close the issue here once the change made it into a release.

**Comment by b4d26f6fc7fc** [comment]
I'm glad you have this and wasn't important for me but damned let Robin and all im shutting it down

**Comment by hemeri** [comment]
Hi,
Did you know when this will be on maven central ?

**Comment by roes** [comment]
This will be in libphonenumber 7.0.8, which we plan on pushing later this week.

**Comment by b4d26f6fc7fc** [comment]
Hey this is Daniels fiance and I don't know why but I'm still not sure what
to do with my life but sure you can have him cause he's going to jail for
sure and a few more

misty
