### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by mrsfixit** [googlei18n/libphonenumber#704]
Any chance of the fine people at google making a ruby port?

https://github.com/sstephenson/global_phone exists, but it appears to be unmaintained, out of date and a little buggy.

**Comment by andyst** [comment]
@jias0001 do we have a contact on https://github.com/sstephenson/global_phone/issues/34 who we could ping directly (not via github issues)? Last update was in 2013. Checking on the state of the port wouldn't be a bad thing IMO.

@mrsfixit We depend on the open source community for many ports. Each port adds significant maintenance effort. If the Ruby port by sstephenson is no longer maintained, then I'd suggest to identify some Ruby allies and fork it on github or ping sstephenson on making you a co-owner of the project.

**Comment by jias0001** [comment]
Andy,

See the original discussion here:

https://groups.google.com/forum/#!topic/libphonenumber-discuss/zRFsfss5Lq4

It has the name of the dev who did the port.

If it is no longer maintained, we can link to the second port instead, which seems to be recently updated upon a quick look:

https://github.com/daddyz/phonelib

Cheers,

Shaopeng
