### ISSUE TITLE
German mobile number(s) 491716783154 not correctly formatted

### ISSUE THREAD

**Issue by plembo-arw** [googlei18n/libphonenumber#705]
Mobile numbers issued to my colleagues at my company's Neu-Isenburg, DE, facility are all coming up with "double" country codes when displaying in INTERNATIONAL format.

So 491716783154 is being formatted by libphonenumber as:

+49 491 716783154

If the country code is stripped out of the data, it appears to format correctly:

+49 171 6783154

As it is not practical to strip country codes from our data for all users, we hope that this is a bug that can be fixed.

We are running giggsey/libphonenumber-for-php integrated into Laravel 4 (Symfony framework).

Results of Google Apps demo at https://libphonenumber.appspot.com/phonenumberparser attached.
![de-mobile-test-libphonenumber](https://cloud.githubusercontent.com/assets/6043961/7822633/ebcdc022-03c4-11e5-92e3-1e0a821770b0.png)

.

**Comment by andyst** [comment]
I don't quite understand the context (where you get those numbers that start with 49 rather than with +49 or 0049 from.

Anyway, it's true that parsing German numbers that start with 49 is difficult due to the variable length of German numbers.

I don't think we can do much here.

See the comment we have at https://github.com/googlei18n/libphonenumber/blob/ca2caff5f0f3cf9ea41ea31dbc58d7cb76b7b4c7/resources/PhoneNumberMetadata.xml#L5763

**Comment by plembo-arw** [comment]
Actually, this is very helpful. I had not noticed that comment when looking through the code.

So for my users in DE the best strategy would be to slice off the leading 49 (they actually format it as +49 xxxxxxxxxx in the incoming data). We already know that will work, but you've now confirmed it's the best way to deal with this issue.

Thanks for you quick response!

**Comment by andyst** [comment]
Actually I'd recommend +491716783154 (or +49 171 6783154) as a format exchange German phone numbers and libphonenumber handles that well too.
The problem arises when the "+" prefix is dropped. Either "+491716783154" (anywhere) or 01716783154 (on a German phone) is fine.

**Comment by plembo-arw** [comment]
Thanks andyst. I've restored the "+" to the data and can see that the libphonenumber parser is now correctly handling the string. My php app is still misbehaving, but at least that narrows the problem to the php implementation (libphonenumber-for-php) or my company's coding. Thanks again!

**Comment by giggsey** [comment]
@plembo-arw Sorry to jump in here, but feel free to open up an issue over at https://github.com/giggsey/libphonenumber-for-php, and I'll happily help.

**Comment by plembo-arw** [comment]
NP. Thanks for joining in. I just checked the string *with* the "+" restored, in the libphonenumber-for-php demo, and it parsed just fine. It looks like it's my team's code after all.

**Comment by plembo-arw** [comment]
Just a follow up. The cause of the problem was indeed in our app. It had a routine to "clean" the phone number values submitted by stripping out all but the digits independent of anything we did on the data side, which of course took any leading "+" characters with it. Everything worked just fine after I removed that routine and allowed data that included leading "+" characters to flow into libphonenumber.

**Comment by timmywil** [comment]
I think it would be more helpful to treat this as a bug. It's actually a regression. Previous versions of libphonenumber correctly removed the country code from the national number without the explicit "+". You can see what I mean when entering the valid number "491719564467" in the phoneformat.js demo, which uses libphonenumber version r680 from pre-github days. The national format is a much more useful value. My users shouldn't be forced to enter a "+" to get the expected result.

**Comment by timmywil** [comment]
The demo: http://phoneformat.com/

**Comment by dlyongemallo** [comment]
@timmywil - The problem is that both +491719564467 and +49491719564467 are valid numbers in Germany now. The number "491719564467" is ambiguous in the real world, so there's nothing we can do about it. The reason it used to work in the library is because +49491719564467 didn't use to be a valid number.

**Comment by timmywil** [comment]
Ah, fair enough. Thank you for explaining.
