### ISSUE TITLE
+68987700814 not recognized as a valid french polynesian mobile phone number 

### ISSUE THREAD

**Issue by smeet666** [googlei18n/libphonenumber#706]
It appears that +68987700814 is not recgnized as a valid French Polynesian mobile phone number, +689 being the international "country" calling code, and 87700814 a valid number for the operator VINI.

The range changed from 6 digits to 8 digits :
        - Fixed numbers are 40XXXXXX
        - Mobile numbers for the operatir VINI are 87XXXXXX
        - Mobile numbers for the operatir VODAFONE are 89XXXXXX

**Comment by dlyongemallo** [comment]
As far as I can tell, +68987700814 is recognised by our library as a valid mobile number.

![+68987700814 validation](https://cloud.githubusercontent.com/assets/9248532/8231995/a595a40c-15cc-11e5-88bf-a52943245acd.png)

**Comment by dlyongemallo** [comment]
We'll add the carrier mapping for PF in the next release.

**Comment by andyst** [comment]
Thanks! Carrier mapping is in libphonenumber 7.0.7.
