### ISSUE TITLE
False positives for German date strings

### ISSUE THREAD

**Issue by henningpeters** [googlei18n/libphonenumber#708]
I am using the phone number matcher (default to DE) to sift through a large body of German text for finding phone numbers - it works pretty good, thank you!

Unfortunately, I am getting a lot of false positives for German point-separated dates and date ranges, e.g.:

05.10.1986
03.05.1987
03.06.15
02.03.1992
05.06.2011
03.05.1984
04.07.1988
03.01.1990
03.07.90
04.06.1988

04.06.-07.06
03.07 - 17.07.15
03.06-07.06.2015
03.07 - 10.07
16.8.-1.9
04.06-07.06
08.06  - 22.06
07.08. - 25.08
05.10-09.10.2015
03.08.15-04.08.15

Not sure about validity of these numbers, but I suppose many people would classify them not as phone numbers (see http://en.wikipedia.org/wiki/Date_format_by_country)

There is already an exception for SLASH_SEPARATED_DATES in PhoneNumberMatcher.java, I think it would be a good idea to extend that at least to POINT_SEPARATED_DATES. That doesn't cover of course the date ranges.

**Comment by andyst** [comment]
Yes, that's a known issue, especially with German numbers which have a huge range of possibly valid numbers in terms of the length. Similar issues are known e.g. with Italian numbers too.

A reasonable phone number annotator in free text should check for high confidence date patterns first. Once you've ruled out that it's a not a date (e.g. applying ICU as a high precision low recall date parser), you can apply the phone number library.

**Comment by henningpeters** [comment]
Hmm, why shouldn't that be part of PhoneNumberMatcher.java which as far as I can tell is designed to be exactly such an annotator? As noted there is already an exception for slash dates:

```
private static final Pattern SLASH_SEPARATED_DATES =
      Pattern.compile("(?:(?:[0-3]?\\d/[01]?\\d)|(?:[01]?\\d/[0-3]?\\d))/(?:[12]\\d)?\\d{2}");
```

As you can see from my Wikipedia link there are dozens of countries that use a point convention for dates. Or is 05.10.1986 a more valid phone number than 05/10/1986?

**Comment by jias0001** [comment]
Indeed is 05.10.1986 a more valid phone number than 05/10/1986. We have often seen dot as a valid separator (in addition to space, dash) for phone number formatting. However, slash as a separator never gets used beyond separating area code and subscriber number, which means there should be no more than 1 slash in a phone number.

**Comment by jias0001** [comment]
Also, note there are multiple leniency levels implemented for the phone number matcher, which you can use to cut down false positives.
