### ISSUE TITLE
Bulgaria, prefix +359 999 not supported in libphonenumber. Max Telecom allocated range

### ISSUE THREAD

**Issue by bgmaxtel** [googlei18n/libphonenumber#711]
The numbering range for Max Telecom operator is not supported. 

Here is the output when trying to use the lib

http://en.wikipedia.org/wiki/Telephone_numbers_in_Bulgaria#Mobile_numbers

![screen shot 2015-06-02 at 17 51 02](https://cloud.githubusercontent.com/assets/12711046/7938804/0dc8649e-0950-11e5-97ba-40d427fb481e.png)

**Comment by andyst** [comment]
I've responded to an email that was sent to me in private. We can continue the discussion here if you prefer.

**Comment by dlyongemallo** [comment]
This will be fixed in the next release.

**Comment by andyst** [comment]
Thanks! This is in libphonenumber 7.0.7.
