### ISSUE TITLE
Missing prefix for Vodafone Uganda and Equitel Kenya

### ISSUE THREAD

**Issue by ckithika** [googlei18n/libphonenumber#712]
Uganda (+256) Vodafone - http://mynumber.vodafone.co.ug - Prefix: 0723

Kenya (+254) Equitel - http://www.businessdailyafrica.com/Corporate-News/-/539550/2486734/-/vbubydz/-/index.html - Prefix: 0763

**Comment by bmarry** [comment]
Thank you for your mail

Please see phone number parser demo
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

For the Uganda case, I entered

+256*723*123456 it returned as a valid number

or 0723123456 with country code UG also works

Result

****Parsing Result:****
{"country_code":256,"national_number":723123456,"raw_input":"0723123456","country_code_source":20,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: UG
Result from getNumberType(): MOBILE

****Formatting Results:****
E164 format: +256723123456
Original format: 0723 123456
National format: 0723 123456
International format: +256 723 123456
Out-of-country format from US: 011 256 723 123456
Out-of-country format from Switzerland: 00 256 723 123456

****AsYouTypeFormatter Results****
Char entered: 0 Output: 0
Char entered: 7 Output: 07
Char entered: 2 Output: 072
Char entered: 3 Output: 0723
Char entered: 1 Output: 0723 1
Char entered: 2 Output: 0723 12
Char entered: 3 Output: 0723 123
Char entered: 4 Output: 0723 1234
Char entered: 5 Output: 0723 12345
Char entered: 6 Output: 0723 123456

===================================

For Kenya also the demo is passing the range as valid, using the number

+254763123456

Result

****Parsing Result:****
{"country_code":254,"national_number":763123456,"raw_input":"+254763123456","country_code_source":1,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: KE
Result from getNumberType(): MOBILE

****Formatting Results:****
E164 format: +254763123456
Original format: +254 763 123456
National format: 0763 123456
International format: +254 763 123456
Out-of-country format from US: 011 254 763 123456
Out-of-country format from Switzerland: 00 254 763 123456

****AsYouTypeFormatter Results****
Char entered: + Output: +
Char entered: 2 Output: +2
Char entered: 5 Output: +25
Char entered: 4 Output: +254
Char entered: 7 Output: +254 7
Char entered: 6 Output: +254 76
Char entered: 3 Output: +254 763
Char entered: 1 Output: +254 763 1
Char entered: 2 Output: +254 763 12
Char entered: 3 Output: +254 763 123
Char entered: 4 Output: +254 763 1234
Char entered: 5 Output: +254 763 12345
Char entered: 6 Output: +254 763 123456


Thanks
Brendan




On 5 June 2015 at 09:48, Charles Kithika <notifications@github.com> wrote:

> Uganda (+256) Vodafone - http://mynumber.vodafone.co.ug - Prefix: 0723
>
> Kenya (+254) Equitel -
> http://www.businessdailyafrica.com/Corporate-News/-/539550/2486734/-/vbubydz/-/index.html
> - Prefix: 0763
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/712>.
>



-- 
Brendan Marry | Google International Product Manager EMEA |
bmarry@google.com | +41 79 763 37 13

This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it went to
the wrong person.  Thanks.
