### ISSUE TITLE
German +49 32 * not recognized

### ISSUE THREAD

**Issue by futuretap** [googlei18n/libphonenumber#713]
The German area code 032 is not recognized as a valid phone number. This area code is location independent.

see http://de.wikipedia.org/wiki/Vorwahl_032_(Deutschland) (in German)

**Comment by bmarry** [comment]
Please see the phone number parser demo. It validates area code 32 as a
valid number

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Number
32123456789 (And add the region code DE) or
032123456789 (And add the region code DE or
+4932123456789

Result

****Parsing Result:****
{"country_code":49,"national_number":32123456789,"raw_input":"32123456789","country_code_source":20,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: DE
Result from getNumberType(): FIXED_LINE

****Formatting Results:****
E164 format: +4932123456789
Original format: 32 123456789
National format: 032 123456789
International format: +49 32 123456789
Out-of-country format from US: 011 49 32 123456789
Out-of-country format from Switzerland: 00 49 32 123456789

****AsYouTypeFormatter Results****
Char entered: 3 Output: 3
Char entered: 2 Output: 32
Char entered: 1 Output: 321
Char entered: 2 Output: 3212
Char entered: 3 Output: 32123
Char entered: 4 Output: 321234
Char entered: 5 Output: 3212345
Char entered: 6 Output: 32123456
Char entered: 7 Output: 321234567
Char entered: 8 Output: 3212345678
Char entered: 9 Output: 32123456789

On 5 June 2015 at 10:46, Ortwin Gentz, FutureTap <notifications@github.com>
wrote:

> The German area code 032 is not recognized as a valid phone number. This
> area code is location independent.
>
> see http://de.wikipedia.org/wiki/Vorwahl_032_(Deutschland) (in German)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/713>.
>



-- 
Brendan Marry | Google International Product Manager EMEA |
bmarry@google.com | +41 79 763 37 13

This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it went to
the wrong person.  Thanks.

**Comment by futuretap** [comment]
Try `+49 32 3465402`. This is a valid number and is considered invalid.

**Comment by bmarry** [comment]
When I tried to dial this number it did not connect

The ITU specification is 11 digits min and max length your example has 9  (32
3465402)

Please confirm the number works and present more evidence.

Brendan

On 5 June 2015 at 12:05, Ortwin Gentz, FutureTap <notifications@github.com>
wrote:

> Try +49 32 3465402. This is a valid number and is considered invalid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/713#issuecomment-109247263>
> .
>



-- 
Brendan Marry | Google International Product Manager EMEA |
bmarry@google.com | +41 79 763 37 13

This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it went to
the wrong person.  Thanks.

**Comment by futuretap** [comment]
Brendan, I believe you're right and the number is indeed invalid.
