### ISSUE TITLE
International Prefix is missing is parsing

### ISSUE THREAD

**Issue by githubsaturn** [googlei18n/libphonenumber#714]
I was doing some unit tests and noticed that if I do:

PhoneNumber numberProto = phoneUtil.parse("001-778-222-1122", "CA");

then, phoneUtil.isValidNumber(numberProto) returns false... But it should return true... 

 if I do:

PhoneNumber numberProto = phoneUtil.parse("+1-778-222-1122", "CA");

then, phoneUtil.isValidNumber(numberProto) returns true...

The first format is a valid international format in some countries: "001-778-222-1122"

**Comment by roes** [comment]
Hi,
It shouldn't return true for the first case because for Canada, which you're using as the region to dial from, 00 is not the international dialing prefix. If you tried it for 'SE' for example, it would return true.
