### ISSUE TITLE
Lebanese mobile phone range, +961 81 XXX XXX, is wrongly detected as a "Shared Cost"

### ISSUE THREAD

**Issue by manitua** [googlei18n/libphonenumber#717]
Tested on 7.0.6

Lebanese mobile phone range, +961 81 XXX XXX, is wrongly detected as a "Shared Cost".
It states in ITU document, http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000770001PDFE.pdf from 2014-12-16, that actual range is used for shared cost numbers.

But latest document from Lebanese Ministry of Telecommunications, on 2015-04-29, http://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-OB.1076-2015-OAS-PDF-E.pdf (page 139), announces that they have introduced new range into service:

+961 81 XXX XXX is now GSM Number range

/Jasmin

**Comment by dlyongemallo** [comment]
Thanks for the report. This is being fixed internally and should be out with the next release.
