### ISSUE TITLE
US toll-free area code 844 not recognized

### ISSUE THREAD

**Issue by ellenchristine** [googlei18n/libphonenumber#719]
The following should all be valid US toll-free area codes (according to https://www.fcc.gov/guides/toll-free-numbers-and-how-they-work): 800, 888, 877, 866, 855, 844

844 is the only one failing isValidNumberForRegion(). Can you help solve this issue? We have users who are trying to sign up with that number and the service is rejecting it.

**Comment by dlyongemallo** [comment]
Can you give an example number (X out the last 4 digits for privacy) that doesn't work? As far as I can tell, 844 behaves exactly like 800.

****Parsing Result:****
country_code: 1
national_number: 8445551234
raw_input: "+18445551234"
country_code_source: 1
preferred_domestic_carrier_code: ""

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: US
Location: 
Result from getNumberType(): TOLL_FREE

**Comment by ellenchristine** [comment]
For example 1-844-692-XXXX. All of the other area codes work with this phone number.

**Comment by dlyongemallo** [comment]
AFAICT, 844 behaves exactly like 800 and has done so for a very long time. Are you running a very old version of the library? Can you give us more details about how you're calling it? When you say that "the service" is rejecting it, what service are you referring to?

You can verify this here:
libphonenumber.appspot.com

![result](https://cloud.githubusercontent.com/assets/9248532/8254107/f34d4ef6-1695-11e5-9152-2ef545fbdc82.png)

**Comment by ellenchristine** [comment]
Yes, looks like we're still on 5.9. Let me update and see if that resolves it.

**Comment by ellenchristine** [comment]
That was the issue. Thanks!

**Comment by andyst** [comment]
Seems to be working as intended then.
