### ISSUE TITLE
[cpp/RE2] USE_RE2=ON fails to switch on RE2 regexp

### ISSUE THREAD

**Issue by Brahmasmi** [googlei18n/libphonenumber#724]
**Build Environment**: gcc 4.8.1, RE2 installed from source
**Steps**:from libphonenumber/cpp
$ mkdir build
$ cd build
$ cmake -D USE_ICU_REGEXP=OFF -D USE_RE2=ON ..
$ make
**Output**: snipped successful output
...
Linking CXX executable libphonenumber_test
CMakeFiles/libphonenumber_test.dir/test/phonenumbers/regexp_adapter_test.cc.o: In function `i18n::phonenumbers::ICURegExpFactory::ICURegExpFactory()':
regexp_adapter_test.cc:(.text._ZN4i18n12phonenumbers16ICURegExpFactoryC2Ev[_ZN4i18n12phonenumbers16ICURegExpFactoryC5Ev]+0x1f): undefined reference to`vtable for i18n::phonenumbers::ICURegExpFactory'
collect2: error: ld returned 1 exit status
make[2]: **\* [libphonenumber_test] Error 1
make[1]: **\* [CMakeFiles/libphonenumber_test.dir/all] Error 2
make: **\* [all] Error 2
$
**Actual**: ICU is being switched on, RE2 is not.
**Expected**: RE2 should be switched on, not ICU.
**Fix**: In file cpp/test/phonenumbers/regexp_adapter_test.cc,
:%s/USE_RE2/I18N_PHONENUMBERS_USE_RE2
**Post-fix**: Output as Expected.

**Comment by Brahmasmi** [comment]
Ping.

This appears to be a simple fix.

**Fix**: In file cpp/test/phonenumbers/regexp_adapter_test.cc,
:%s/USE_RE2/I18N_PHONENUMBERS_USE_RE2
i.e. replace "USE_RE2" with "I18N_PHONENUMBERS_USE_RE2"

In case I am missing something here, please let me know.

**Comment by jias0001** [comment]
This looks reasonable. Could you send a patch to fix this? Please also remember to sign the CLA first if you haven't done so:

https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject

**Comment by Brahmasmi** [comment]
Hi @jias0001, would it be possible for someone on the libphonenumber team to please perform the string find and replace? I understand little about CLAs. Also, it would be considerably simpler for someone who already has everything setup.

On a related note, is it OK to use RE2 instead of ICU? I am trying to understand the trade off between the ICU and RE2 engines with respect to libphonenumber. In my very limited understanding, RE2 is the safer one, which is why I used USE_RE2=ON and this entire issue started.

**Comment by keghani** [comment]
Yes, it's OK to use RE2. They're both supported: https://github.com/googlei18n/libphonenumber/blob/master/cpp/README

I'll send a patch to fix this.

**Comment by keghani** [comment]
Oh nice feature! I said the PR fixes the issue and when I merged the PR the issue automatically close.

Note though that this is not yet released. It will be in the next GitHub tag.

**Comment by Brahmasmi** [comment]
Danke @keghani for the fix.

On a side note, would it be possible for you to share any insight/guidance regarding the tradeoff between ICU and RE2 engines with respect to libphonenumber? As mentioned earlier in the thread, in my limited understanding, RE2 seems to be the safer option.

**Comment by keghani** [comment]
I actually don't have context into ICU vs RE2 for regex matching in C++. would others be able to chime in?

**Comment by keghani** [comment]
And you're welcome :)
