### ISSUE TITLE
[cpp] GCC 4.8: Build failure

### ISSUE THREAD

**Issue by Brahmasmi** [googlei18n/libphonenumber#725]
**Build Environment**: gcc 4.8.1
**Steps**: from libphonenumber/cpp
$ mkdir build
$ cd build
$ cmake ..
$ make
**Output**:snipped successful output
...
Scanning dependencies of target phonenumber_testing
[  2%] Building CXX object CMakeFiles/phonenumber_testing.dir/src/phonenumbers/asyoutypeformatter.cc.o
In file included from libphonenumber/cpp/src/phonenumbers/asyoutypeformatter.h:39:0,
                 from libphonenumber/cpp/src/phonenumbers/asyoutypeformatter.cc:15:
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h: In constructor ‘i18n::phonenumbers::DefaultDeleter<T>::DefaultDeleter(const i18n::phonenumbers::DefaultDeleter<U>&)’:
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h:52:20: error: typedef ‘U_ptr_must_implicitly_convert_to_T_ptr’ locally defined but not used [-Werror=unused-local-typedefs]
                    U_ptr_must_implicitly_convert_to_T_ptr);
                    ^
libphonenumber/cpp/src/phonenumbers/base/basictypes.h:201:39: note: in definition of macro ‘COMPILE_ASSERT’
   typedef CompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                       ^
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h: In constructor ‘i18n::phonenumbers::scoped_ptr<T, D>::scoped_ptr(i18n::phonenumbers::scoped_ptr<U, V>)’:
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h:242:41: error: typedef ‘U_cannot_be_an_array’ locally defined but not used [-Werror=unused-local-typedefs]
     COMPILE_ASSERT(!is_array<U>::value, U_cannot_be_an_array);
                                         ^
libphonenumber/cpp/src/phonenumbers/base/basictypes.h:201:39: note: in definition of macro ‘COMPILE_ASSERT’
   typedef CompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                       ^
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h: In member function ‘i18n::phonenumbers::scoped_ptr<T, D>& i18n::phonenumbers::scoped_ptr<T, D>::operator=(i18n::phonenumbers::scoped_ptr<U, V>)’:
libphonenumber/cpp/src/phonenumbers/base/memory/scoped_ptr.h:257:41: error: typedef ‘U_cannot_be_an_array’ locally defined but not used [-Werror=unused-local-typedefs]
     COMPILE_ASSERT(!is_array<U>::value, U_cannot_be_an_array);
                                         ^
libphonenumber/cpp/src/phonenumbers/base/basictypes.h:201:39: note: in definition of macro ‘COMPILE_ASSERT’
   typedef CompileAssert<(bool(expr))> msg[bool(expr) ? 1 : -1]
                                       ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/phonenumber_testing.dir/src/phonenumbers/asyoutypeformatter.cc.o] Error 1
make[1]: *** [CMakeFiles/phonenumber_testing.dir/all] Error 2
make: *** [all] Error 2
**Workaround**: in cpp/CMakeLists.txt
:%s/add_definitions ("-Wall -Werror")/add_definitions ("-Wall -Werror -Wno-unused-local-typedefs")
**Fix**: Pending

**Comment by roubert** [comment]
While I haven't been able to reproduce this failure (I don't have any installation of GCC 4.8.1 and my GCC 4.8.4 compiles the code just fine), there is no reason for this code to be compiled at all with modern GCC as C++11 already implements static_assert which is the same as COMPILE_ASSERT.

See this proposed fix: https://github.com/googlei18n/libphonenumber/pull/742

**Comment by roes** [comment]
roubert's proposed fix is now merged. Please reopen this is you're still having problems after building with that.

**Comment by Brahmasmi** [comment]
@roubert Thank you for your time and attention. The merged patch does not fix the issue. The output is the same as in the original bug report. Please see below for details.

@roes Request that the issue be please reopened.

Based on my limited understanding of the patch, the macro switches on ```__cplusplus```. From what I could gather (https://github.com/gcc-mirror/gcc/blob/gcc-4_8_1-release/libcpp/init.c#L479-483, https://github.com/gcc-mirror/gcc/blob/gcc-4_8_4-release/libcpp/init.c#L479-483), the default value of ```__cplusplus``` is ```199711L```, unless there is a specific argument passed to ```g++``` to indicate otherwise (via ```-std=```). This behaviour seems to be consistent across gcc releases (https://github.com/gcc-mirror/gcc/blob/gcc-5_2_0-release/libcpp/init.c#L493-503), but I may be mistaken here. Crude grepping seems to suggest that we use ```-lstdc++``` and do not specify a version via ```-std=```. Could it be possible that your machine may have ```g++``` aliased to use a ```-std=c++11/c++0x```? Pardon my ignorance on the gcc compiler machinery.

As a diagnostic, I am sharing the values of ```__cplusplus``` under different arguments on the build machine. libstdc++ version is  ```libstdc++.so.6.0.21```.

Please let me know in case you need me to run any additional diagnostics to debug.

**Steps**:
```
$ echo __cplusplus > version.cpp; g++ -E version.cpp
# 1 "version.cpp"
# 1 "<command-line>"
# 1 "version.cpp"
199711L
$ echo __cplusplus > version.cpp; g++ -lstdc++ -E version.cpp
# 1 "version.cpp"
# 1 "<command-line>"
# 1 "version.cpp"
199711L
$ echo __cplusplus > version.cpp; g++ -std=c++0x -E version.cpp
# 1 "version.cpp"
# 1 "<command-line>"
# 1 "version.cpp"
201103L
$ echo __cplusplus > version.cpp; g++ -std=c++11 -E version.cpp
# 1 "version.cpp"
# 1 "<command-line>"
# 1 "version.cpp"
201103L
```
