### ISSUE TITLE
Indian mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#733]
Several 72 codes have been assigned to mobile operators in India:
7201,7202,7203,7210,7218,7220,7223,7224,7225,7226,7227,7229,7230,7231,7232,7239,7248,7249,7254,7257,7258,7260,7261,7265,7283,7284,7285,710,7266,7267,7268,7269,7270,7271,7272,7273,7274,7279,7280,7281,7282,7283,7289,7290,7291,7292,7294,7295,7296,7297,7300,7310

![docmsc code letter](https://cloud.githubusercontent.com/assets/524299/8475602/355bfb88-20b1-11e5-8334-f1e5e90ff297.png)
![docmsc code pdf i](https://cloud.githubusercontent.com/assets/524299/8475601/355ba28c-20b1-11e5-9c78-7dea91c9e7d3.png)

**Comment by keghani** [comment]
Partially resolved in release 7.0.9.
@dlyongemallo could you take a look and see what ranges are left to be done?

**Comment by keghani** [comment]
Fixed by release 7.0.11.
