### ISSUE TITLE
Morocco - missing prefix

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#736]
687 - inwi

**Comment by mihaelacr-google** [comment]
For future bug reports, please also specify what kind of number you think this range is allocated for. Is this for fixed lines or mobile lines? It makes the bug triage much faster. Thanks. 

Please also provided further documentation to support your claim. I could not find this range mentioned in any docs.

**Comment by roes** [comment]
This will be in libphonenumber 7.0.8.
