### ISSUE TITLE
Provide more help and easier build for Windows c++

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#74]
Imported from [Google Code issue #74](https://code.google.com/p/libphonenumber/issues/detail?id=74) created by [tim.jurik](https://code.google.com/u/105618026167572361730/) on 2011-11-02T14:20:56.000Z:

----
<b>What steps will reproduce the problem?</b>
1.  Try to build on any Windows OS

<b>What is the expected output? What do you see instead?</b>
A simple build process.  Right now it takes no fewer than 6 downloads and a lot of head scratching to get a build.  (I have not even been successful yet)

<b>What version of the product are you using? On what operating system?</b>
Latest revision on WIn32  C++

<b>Please provide any additional information below.</b>

I would like to be able to download one set of sources and just build the library.  Unfortunately it is quite a production to even get to that point.  The readme makes a lot of mention of linux but there is no help at all for Windows developers.

**Comment by keghani** [comment]
The readme now has a section for Windows: https://github.com/googlei18n/libphonenumber/blob/master/cpp/README

**Comment by landrix** [comment]
Sorry, the windows section is very outdated and contains invalid URLs.

**Comment by keghani** [comment]
Thanks for letting us know! We don't develop on Windows so we can't keep that up-to-date.
We're happy to accept a patch though. I closed this issue since it's from years ago and since then we did take action to fix it (it just wasn't followed up on), but that doesn't mean we're never updating the file again :)
