### ISSUE TITLE
Keep dash to separate extension

### ISSUE THREAD

**Issue by andreasgomolka** [googlei18n/libphonenumber#740]
I use libphonenumber to format phone number strings according to its country codes with this simple code snippet:
final PhoneNumberUtil util = PhoneNumberUtil.getInstance();
final PhoneNumber phoneNumber = util.parse(phoneNumberString, countryCode);
util.format(phoneNumber, PhoneNumberFormat.NATIONAL);

It works great apart from a simple issue:
I would like to keep the 'direct dial in' number separately from the main number. Either separated by a hyphen (or if thats not possible by a blank). Is that possible?

Examples:
072196385371 --> +49 721 96385371
07219638-537 --> +49 721 9638-537
07219638 537 --> +49 721 9638-537
0721-9638-537 --> +49 721 9638-537
0721 9638 537 --> +49 721 9638-537

**Comment by jias0001** [comment]
Unfortunately It is not possible as there are no clear rules we are aware of on identifying the dial-in number given a German phone number. If you know any, we would be interested in knowing.
