### ISSUE TITLE
Java demo - Status Code 500

### ISSUE THREAD

**Issue by mrhota** [googlei18n/libphonenumber#745]
My guess is something happened with the new release a couple hours ago.

**Comment by andyst** [comment]
Yes, we noticed. Some issue with maven not respecting the Java target (1.5) we have in pom.xml.
https://github.com/googlei18n/libphonenumber/blob/master/java/pom.xml#L140

We'll debug it tomorrow (it's evening here). Thanks for the heads-up.

**Comment by roes** [comment]
We've identified that the issue is caused by appcfg, which we use upload to AppEngine, building the jsp file with java 1.8, which AppEngine doesn't support.

Maven however, correctly builds Java 1.5

**Comment by roes** [comment]
It's now up and running again
