### ISSUE TITLE
New Ethiopian Prefixes coming back as invalid

### ISSUE THREAD

**Issue by jennyferpinto** [googlei18n/libphonenumber#748]
Ethiopia's telecom system has introduced some new prefixes that start with 25194* and 25192*. When looking these numbers up they come back as invalid. It doesn't look like these have been included in libphonenumber's database yet. 

Here are the results for a valid EthioMobile number that I had looked up:

Phone Number entered: +25194*******
defaultCountry entered: 
Language entered: en
Parsing Result
country_code	251
national_number	94*******
extension	
country_code_source	FROM_NUMBER_WITH_PLUS_SIGN
italian_leading_zero	false
raw_input	+25194*******
Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	false
Phone Number region	ET
Result from getNumberType()	UNKNOWN
Formatting Results
E164 format	invalid
Original format	+251 94 *** ****
National format	094 *** ****
International format	invalid
Out-of-country format from US	invalid
Out-of-country format from CH	invalid

**Comment by roes** [comment]
Hi,
Do you have supporting evidence of the numbers being valid? For example official documentation from the government, telecom authority or carrier are good. If none of them are available, news reports of the introduction of the new prefixes are also OK.

**Comment by dlyongemallo** [comment]
@jennyferpinto - Do you have the info @roes requested?

**Comment by jennyferpinto** [comment]
@dlyongemallo I am still waiting for this supporting evidence. I will be sure to update this thread once I receive it.

**Comment by guillaumev** [comment]
Hi,

I believe that the +251 94 prefixes were fixed in this issue:

https://github.com/googlei18n/libphonenumber/issues/882

However, another prefix that was added recently is +251 96. You will find below a picture of a SIM card to prove this:

![ethiopia96](https://cloud.githubusercontent.com/assets/90224/12325344/e7236862-bac9-11e5-8c90-210682303368.png)

**Comment by penmetsaa** [comment]
@jennyferpinto
Range 92 is already supported by libphonenumber library (http://libphonenumber.appspot.com/phonenumberparser?number=0921234567&country=ET). Please update to latest version of libphonenumber.
We are able to dial the numbers that found online for range 94. We will be adding this in our future releases.

@guillaumev
Thank you for taking the time to improve libphonenumber!
We will add range 966 as valid mobile prefix. We would appreciate more information on other valid digits that follow 96. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)

**Comment by Yaelle01** [comment]
@penmetsaa 
Thank you for taking care of @guillaumev 's request. I am having the same issue regarding the range 96. Would appreciate if libphonenumber could be updated. Ethio Telecom is providing this prefix, more can be found at http://www.ethiotelecom.et/?q=faq

**Comment by keghani** [comment]
@Yaelle01 
Please see @penmetsaa 's comment above on supporting the 96 range: "We would appreciate more information on other valid digits that follow 96. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)"

**Comment by penmetsaa** [comment]
@jennyferpinto 
94 prefix is now valid in release 7.2.5: 
https://libphonenumber.appspot.com/phonenumberparser?number=%2B251+94+588+9316

@guillaumev
966 prefix is now valid in release 7.2.5: 
https://libphonenumber.appspot.com/phonenumberparser?number=%2B251-966-12+00+00
