### ISSUE TITLE
German phone numbers parsed inconsistently

### ISSUE THREAD

**Issue by pigulla** [googlei18n/libphonenumber#750]
I'm trying to parse German phone numbers. One is parsed correctly, the other is not recognized. What am I doing wrong? (The last four digits of both numbers are "anonymized" for this issue.)

```
Phone Number entered:    496128966000 
defaultCountry entered:  DE
Language entered:        en

Parsing Result
country_code	      49
national_number	      496128966000
extension	 
country_code_source	  FROM_DEFAULT_COUNTRY
italian_leading_zero  false
raw_input             496128966000
```
--- 
```
Phone Number entered:    498990990000
defaultCountry entered:  DE
Language entered:        en

Parsing Result
country_code          49
national_number	      8990990000
extension	 
country_code_source   FROM_NUMBER_WITHOUT_PLUS_SIGN
italian_leading_zero  false
raw_input             498990990000000
```

**Comment by roes** [comment]
These are both valid numbers when trying in our demo http://libphonenumber.appspot.com/

You need to tell us what you think is incorrect, which one do you think is not recognised?

**Comment by pigulla** [comment]
If you look at the output generated by the first number you will notice that the `national_number` field is incorrect as it still contains Germany's country code.

In the meantime I've fixed this by always prepending `00` to the number to be parsed. So the issue probably is that the raw input does not start with `00` or `+`?

**Comment by giggsey** [comment]
Look at the E164 numbers.

Entering in `496128966000` with `DE` gives in E164: +49 4961 28966000

Entering in `00496128966000` with `DE` gives in E164: +49 6128 966000

Both of these numbers are valid, but they are two different numbers.

**Comment by roes** [comment]
Yes, if in these numbers 49 is in fact the country code, you need to prepend 00 or +. The other option is to remove the country code. The problem arises because there are valid German numbers starting with 49, and there's no way for the library to know if it's meant to be the country code or not without the 00 or +.
