### ISSUE TITLE
Some Swaziland numbers returning invalid

### ISSUE THREAD

**Issue by jacpoplar** [googlei18n/libphonenumber#753]
Some prefixes for Swaziland are considered invalid by libphonenumber, but are valid numbers.
References: https://en.wikipedia.org/wiki/Telephone_numbers_in_Swaziland
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C60001PDFE.pdf

I found the following prefixes return invalid from libphonenumber:
Prefix (City): Sample Number
2452 (Bhunya): 2452 6012
2416 (Lobamba): 2416 1049
2472 (Mahwalala): 2472 8344
2467 (Mhlambanyatsi): 2467 4177
2312 (Mhlume): 2312 0227
2442 (Ngwenya): 2442 4031
2437 (Pigg's Peak): 2437 3633
2422 (Sidwashini): 2422 0155
2382 (Simunye): 2382 1152
2482 (Siphoncosini): 2482 9459

(The sample numbers above are actual numbers I got by Googling Swaziland and the prefix)

Other prefixes that I couldn't find numbers for, but are listed in the list on Wikipedia:

2453 (Bhunya) and 2322 (Tshaneni)

Since these are second prefixes, they might not be in widespread use yet.

**Comment by keghani** [comment]
Hi,

Do you have supporting evidence of the numbers being valid? For example official documentation from the government, telecom authority or carrier are good. If none of them are available, news reports of the introduction of the new prefixes are also OK.

The ITU link does not refer to the specific area codes. We have covered the first 2 digits you specified in https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml.

The wikipedia page has been showing those area codes for years, and the references don't help. The first reference is the ITU, and the second is no longer on the web.

**Comment by jacpoplar** [comment]
The number 2416 1049 has been assigned to a property in Swaziland. The property
owner is trying to enter that number, but it is rejected. This is a valid number in that you
can call it and people will answer. All of the numbers I listed were listed as being valid
contact phone numbers. And if you have covered the numbers, why are they rejected?

On 20 Jul 2015, at 16:30, Keghani Kouzoujian <notifications@github.com> wrote:

> Hi,
> 
> Do you have supporting evidence of the numbers being valid? For example official documentation from the government, telecom authority or carrier are good. If none of them are available, news reports of the introduction of the new prefixes are also OK.
> 
> The ITU link does not refer to the specific area codes. We have covered the first 2 digits you specified in https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml.
> 
> The wikipedia page has been showing those area codes for years, and the references don't help. The first reference is the ITU, and the second is no longer on the web.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Jackie Poplar
Developer, HI:Communication

**Comment by jacpoplar** [comment]
The numbers for Bhunya are actually rejected because in the regular expression in SZ.pm, there is:
40[4-69]|67 for the digits after the initial '2'. This will reject numbers starting with '245'

**Comment by jacpoplar** [comment]
Here is the regular expression for Swaziland in the js file for the library:

2(?:2(?:0[07]|[13]7|2[57])|3(?:0[34]|[1278]3|3[23]|[46][34])|(?:40[4-69]|67)|5(?:0[5-7]|1[6-9]|[23][78]|48|5[01]))\\d{4}

Note that the 40[4-69]|67 rule validates a number that begins with '240' but not '241' , '242', etc.

**Comment by keghani** [comment]
We will update the metadata for Swaziland to support as fixed-line all 8-digit numbers starting with 22, 23, 24, and 25, taking the ITU document for evidence. This should satisfy your use case.

**Comment by jacpoplar** [comment]
Wonderful! Thank you!

On 21 Jul 2015, at 11:48, Keghani Kouzoujian <notifications@github.com> wrote:

> We will update the metadata for Swaziland to support as fixed-line all 8-digit numbers starting with 22, 23, 24, and 25, taking the ITU document for evidence. This should satisfy your use case.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Jackie Poplar
Developer, HI:Communication

**Comment by keghani** [comment]
Fixed in release 7.0.9.
