### ISSUE TITLE
Costa Rica phone number +506 20100800 returns invalid

### ISSUE THREAD

**Issue by jacpoplar** [googlei18n/libphonenumber#756]
The documentation for Costa Rica:
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000300001PDFE.pdf

On p. 7, it lists the range 20000XXX to 21999XXX as Fixed telephony services, in reserve for allocation. Apparently, they have been allocating them. The VillasSol beach resort, for example, has a phone number of 2010-0800. I just called this number and it is a working number.

Some other numbers:
2010-1111, Teatro Nacional Costa Rica
2010-6000, Radisson San Jose-Costa Rica

The regexp validating numbers starting with 2 is:
'2[24-7]\\d{6}'
in the code, so it will not validate a number starting with 20.

**Comment by bmarry** [comment]
Thank you for your email. It looks like the prefix 2010 has now been allocated, do you have any evidence that any other prefixes/ranges between 20000XXX to 21999XXX have been allocated? 

Best to change the library to validate 2010 prefix for the moment.

In addition to the links above I do not see any ITU updated documentation for example reflecting this. Do you have any other documentation that shows that this range has now been allocated? 

Thanks 
Brendan

**Comment by dlyongemallo** [comment]
This will be fixed in the next version.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
