### ISSUE TITLE
Does'nt seem to return Carrier Name for US numbers 

### ISSUE THREAD

**Issue by SiddarthaNagireddy** [googlei18n/libphonenumber#758]
Hi, 

For some reason I don't see carrier name for US phone numbers only. For all other countries it is returning the carrier name. Can anyone help me troubleshoot this issue? 

Here is an image from the demo
![capture](https://cloud.githubusercontent.com/assets/7332225/8864931/95e2674c-315c-11e5-8054-38f9d09d8491.JPG)

**Comment by dlyongemallo** [comment]
I believe this is a dup of issue #726 - it's impossible for many prefixes to infer the carrier in the US because a prefix may be served by many carriers. If you have specific evidence that 630 is served by one carrier and one carrier only, we can add that to the carrier file.

**Comment by SiddarthaNagireddy** [comment]
Its not specific to this phone number. I've tried 5 - 6 US phone numbers including mobile numbers, it does not return the carrier name for any of those. Whereas Twilio (which is built on this library) is able to retrieve the carrier name for the same phone numbers.

**Comment by SiddarthaNagireddy** [comment]
Here is another example: 
![image](https://cloud.githubusercontent.com/assets/7332225/8885878/a3f0e81a-3218-11e5-8f37-a42cb482b138.png)

**Comment by bmarry** [comment]
Hi 

The issue is these prefixes are not used by one carrier for example, on Twillio if I look up 

408 668 5451 the carrier is T-mobile USA and if I lookup
408 668 5452 the carrier is AT&T Wireless

The library does not distinguish carriers at this level and hence does not return the carrier. Only when we have a prefix that is mapped to a single carrier we will return the carrier. 

Thanks 
Brendan

**Comment by SiddarthaNagireddy** [comment]
Thanks Brendan,

Can you let me know how I can achieve that using this library? Do you have any idea on how Twilio does that? 

Thanks,
Sid

**Comment by bmarry** [comment]
Hi Sid

It is not possible to achieve this using the library as we work on prefix
matching. I do not know how Twilio does this but I would guess they have a
per number carrier mapping in the their solution and they are not using
prefix matching.

Brendan

On 27 July 2015 at 20:14, Siddartha Reddy <notifications@github.com> wrote:

> Thanks Brendan,
>
> Can you let me know how I can achieve that using this library? Do you have
> any idea on how Twilio does that?
>
> Thanks,
> Sid
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/758#issuecomment-125292828>
> .
>



-- 
Brendan Marry | Google International Product Manager EMEA |
bmarry@google.com | +41 79 763 37 13

This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else, please
erase all copies and attachments, and please let me know that it went to
the wrong person.  Thanks.

**Comment by dlyongemallo** [comment]
It seems likely that Twilio is paying to maintain a database of number-to-carrier mappings. What you want is not possible using the library, except in those instances where a prefix happens to map only to one carrier.

**Comment by SiddarthaNagireddy** [comment]
Thanks for the update.
