### ISSUE TITLE
Australian mobile numbers need updating

### ISSUE THREAD

**Issue by meowcakes** [googlei18n/libphonenumber#766]
Hello,

According to the Wikipedia page (https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#Non-geographic_numbers), the phone number range +61484XXXXXX is a valid mobile number used by Telstra, however libphonenumber reports it as an invalid number.

Thanks

**Comment by dlyongemallo** [comment]
The Wikipedia page merely says that the block has been allocated. Do you have any documents or evidence showing that it's actually in use?

**Comment by meowcakes** [comment]
I don't have any documents, nor do I know where to find any proving that the block is actually in use. However, I can use Nexmo's number insight tool to see that numbers in the block are reachable and on the Telstra network. Would a screenshot of this suffice?

**Comment by dlyongemallo** [comment]
Actually, we've found info confirming this number range. This will be fixed in the next version.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
