### ISSUE TITLE
CellC South Africa

### ISSUE THREAD

**Issue by fjmalan** [googlei18n/libphonenumber#769]
The range 2762 can be added for Cell C South Africa

![cell c numbering 062 0 to 062 4 notification-page-001](https://cloud.githubusercontent.com/assets/665965/9056102/cb0a0a50-3a90-11e5-8693-195f6986e10e.jpg)

**Comment by dlyongemallo** [comment]
The entire range appears to already be supported in our library since last year. Do you have a specific number that doesn't work?
