### ISSUE TITLE
Enter an extension in JavaScript asYouTypeFormatter

### ISSUE THREAD

**Issue by RizziCR** [googlei18n/libphonenumber#774]
Hi,

is it possible to add an extension in javascripts asYouTypeFormatter on any position?

I want to use the extension to reflect direct call numbers inside f.e. companies.

Like:
+49 221 12345 ext. 0  <--- main number
+49 221 12345 ext. 10 <-- direct call for staff member x
+49 221 12345 ext. 20 <-- direct call for staff member y

This is more a visual benefits for the caller. But very often used i think. In Germany most time the direct call part is separated by a - (minus) and has no more then 3 digits.

With the library general its possible, but the asYouTypeFormatter doesn't support to enter an extension manually at random position.

Thanks and best regards
Rizzi

**Comment by lararennie** [comment]
The as-you-type-formatter is designed for use in a dialler, where ext. like this isn't really supported. If you want to put the "-" in the as-you-type-formatter should just stop formatting for you? Anyway I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
