### ISSUE TITLE
How do I remove message prefix (the number nine at the begining of the nationalNumber)

### ISSUE THREAD

**Issue by giorgioeduardo** [googlei18n/libphonenumber#775]
How do I remove message prefix (the number nine  at  the begining of the nationalNumber)  ?
For instance:  for the number 54-9-342155208641

`Phonenumber.PhoneNumber phoneNumber = phoneUtil.parse("54-9-342155208641", "AR");`
I get the following result
phoneNumber.countryCode: 54
phoneNumber.nationalCode: 93425208641
Instead I need the following result (notice the lack of 9) 
phoneNumber.countryCode: 54
phoneNumber.nationalCode: 3425208641

**Comment by lararennie** [comment]
What do you want to remove the 9 for? Without that, we don't know it's a mobile number anymore?

**Comment by lararennie** [comment]
Also, I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further - we'd be happy to help, but it's easier on the mailing list than as a bug report :)
