### ISSUE TITLE
Sao Tome and Principe - new mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#779]
Unitel ST mobile prefixes (90) are not covered by the patterns. Example number: +239900600x

Documentation can be provided privately if required.

**Comment by roes** [comment]
Thank you for your report, we'll start work on this shortly.

**Comment by roes** [comment]
This will be part of our next release.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
