### ISSUE TITLE
Somalia - updated mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#780]
Somtel mobile prefixes need to be updated.  62, 65, 66 should be added and we can probably remove 79. I suggest making 6 pattern 9 digits long instead of 8/9: 6[1-35-9]\d{2}

252 79 xxx xxx (not in operational)
252 620 xxx xxx - 252 629 xxx xxx (this format exists from long time)
252 650 xxx xxx - 252 659 xxx xxx (migrated from 252 7 to 252 65)
252 660 xxx xxx - 252 669 xxx xxx (new range)
252 2 3xx xxx to 252 2 9xx xxx (PSTN and no change)

Documentation can be provided privately if required.

**Comment by roes** [comment]
Thank you for your report, we'll start work on this shortly, also looking further into whether 79 could be removed.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
