### ISSUE TITLE
Mauritius - new mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#782]
Cellplus Mauritius is using 580, 581 & 587 prefixes. Example number: +2305802411x

Documentation can be provided privately if required.

**Comment by roes** [comment]
Thank you for your report, we'll start work on supporting these shortly.

**Comment by roes** [comment]
The documentation provided only shows a subset of the 587 prefix being allocated, this part is already supported (587[5-7], we also support 587[18]). If you believe the rest/other parts of the prefix are also allocated, please provide additional documentation.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
