### ISSUE TITLE
India - new mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#784]
7013
7233, 7234, 7235, 7236, 7237
7240, 7241
7251, 7253, 7255, 7256

Most of them have been assigned according to http://www.dot.gov.in/sites/default/files/u10/doc00028920150605185737.pdf

There're also several new allocations: http://www.dot.gov.in/access-services/allotment-msc-codes that need updates.

**Comment by roes** [comment]
There's ongoing work on updating India mobile prefixes which will resolve most of these. However, I couldn't find mention of the 725x prefixes anywhere, could you please point me to the specific document mentioning those?

**Comment by mihaelacr-google** [comment]
Hi Alex? Can you please provide us with the evidence required for the 725x prefixes?

Thanks!

**Comment by alecx** [comment]
Sorry for the delay. 725x was allocated around May, here's the document covering 7251-7258.

http://www.dot.gov.in/sites/default/files/u10/doc00423020150515121549.pdf

**Comment by jias0001** [comment]
Thanks, we will look into this.

**Comment by keghani** [comment]
Fixed by release 7.0.11.
