### ISSUE TITLE
Nigeria - new prefix

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#786]
Etisalat Nigeria is now using +234 908. Example number: +234908174536x

**Comment by roes** [comment]
Awaiting supporting documentation.

**Comment by pblv** [comment]
I can confirm this. Please also check:
https://en.wikipedia.org/wiki/Telephone_numbers_in_Nigeria

**Comment by mihaelacr-google** [comment]
Hi!

Do you have any other source of documentation apart from Wikipedia? A government/carrier website  or a newspaper? Thanks!

**Comment by pblv** [comment]
http://www.ncc.gov.ng/index.php/index.php?option=com_content&view=article&id=113&Itemid=102

**Comment by mihaelacr-google** [comment]
This seems to be a duplicate of https://github.com/googlei18n/libphonenumber/issues/863.

**Comment by andyst** [comment]
Closing this as duplicate of
https://github.com/googlei18n/libphonenumber/issues/863
