### ISSUE TITLE
C# port link

### ISSUE THREAD

**Issue by smittysauce** [googlei18n/libphonenumber#787]
I would suggest updating the documentation at the bottom of the main page to mention C# port on Nuget vs the one you have listed now which has very little movement on Github - https://www.nuget.org/packages/libphonenumber-csharp

**Comment by hagbard** [comment]
Thanks for pointing this out. We'll look into it.

**Comment by keghani** [comment]
Thanks for the suggestion!

Seems https://github.com/aidanbebbington/libphonenumber-csharp has not little movement these days. They already have 8.6.0, and we just started updating to the next version today and haven't completed yet.

We have only linked to ports in GitHub, and I'm not sure that people would have the necessary package manager for the Nuget port, plus we don't evaluate the difference between ports in the same language. For these reasons I think another C# port shouldn't be in the README. You can though add such an analysis to the [wiki](https://github.com/googlei18n/libphonenumber/wiki) if you think it would be beneficial.
