### ISSUE TITLE
ES phone number format?

### ISSUE THREAD

**Issue by bpicolo** [googlei18n/libphonenumber#788]
It seems like the phone numbering format for national numbers for ES might be off a bit?
For reference, looks like the doc previously located at (according to resources/PhoneNumberMetadata.xml):
http://www.mityc.es/telecomunicaciones/es-ES/Servicios/Numeracion/Paginas/Plan.aspx
is now here:
http://www.minetur.gob.es/telecomunicaciones/es-ES/Servicios/Numeracion/Paginas/Plan.aspx

It looks like a number like +34800ABCDEF would be formatted 800 ABC DEF as a national number (similar for other numbers), but currently it's defined to become 800 AB CD EF:
 <numberFormat pattern="([5-9]\d{2})(\d{2})(\d{2})(\d{2})">

It's something I came across that seems a bit off... I've looked for (but haven't been able to find) justification for the current format. For what it's worth the one google phone number I've found for ES uses sets of 3:
https://www.google.es/work/apps/business/support/

Not my area of expertise, just a peculiarity I noticed. =)

**Comment by roes** [comment]
Thank you for your report. Since we currently have a lot of open issues, fixing formatting isn't as highly prioritized, but we'll look into it.

**Comment by bpicolo** [comment]
@roes Thanks! For what it's worth, I confirmed with some friends from Spain that the 9 number format is the general preference these days. : )

**Comment by penmetsaa** [comment]
@bpicolo,

This is fixed.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B34800123456
