### ISSUE TITLE
Australian mobile number range missing - +61484xxxxxx

### ISSUE THREAD

**Issue by doancaonghia** [googlei18n/libphonenumber#792]
Please add the +61484xxxxxx number range.

e.g. +61484344260 is a valid mobile number in Australia.

Thanks 
Nghĩa

**Comment by roes** [comment]
Thank you for your report, we had already been made aware of this and it will be part of the next release.

**Comment by roes** [comment]
Duplicate of https://github.com/googlei18n/libphonenumber/issues/766
