### ISSUE TITLE
+60116XXXXXXXX should be a valid MY mobile phone number

### ISSUE THREAD

**Issue by dingyonglaw** [googlei18n/libphonenumber#793]
Hello there,

+60116XXXXXXXX should be a valid MY mobile phone number, but current lib returns as invalid.

**Comment by roes** [comment]
Hi,
Do you have any official supporting evidence, for example government or carrier documentation that these numbers exist? If not, examples of businesses or websites that use numbers with this prefix?

**Comment by keghani** [comment]
@dingyonglaw Thank you for taking the time to improve libphonenumber!

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
