### ISSUE TITLE
Orange in Switzerland is now called Salt

### ISSUE THREAD

**Issue by daMupfel** [googlei18n/libphonenumber#795]
I just checked the online tool for this lib and it return orange as my provider.

Orange is now called Salt in Switzerland, they had a brand change.

http://www.telecompaper.com/news/orange-switzerland-officially-becomes-salt-on-27-april--1078719
https://www.salt.ch/en/#

Regards

**Comment by roes** [comment]
Thank you for your report.

**Comment by keghani** [comment]
Fixed in release 7.0.11.

**Comment by daMupfel** [comment]
Thanks!
