### ISSUE TITLE
+447671xxxxxx not being validated correctly

### ISSUE THREAD

**Issue by enidgjoleka** [googlei18n/libphonenumber#796]
Hello there,

It looks like the library is not validating correctly these type of numbers from GB: +447671xxxxxx.
Thank you in advanced for your time.

**Comment by giggsey** [comment]
According to the numbering list at Ofcom (http://www.ofcom.org.uk/static/numbering/#pers), 7671 is not actually allocated. It jumps from 7669 to 7677.

**Comment by enidgjoleka** [comment]
Hi,

I am really sorry but I was validating the wrong number. The correct one starts like: +447661.
I guess now the issue doesn't make any sense.

Thank you again for your time and support.
