### ISSUE TITLE
+6588XXXXXX (Singapore) is a valid mobile number now

### ISSUE THREAD

**Issue by bryannetrunner** [googlei18n/libphonenumber#797]
Currently the library only allows these as valid mobile numbers in Singapore:

65 8[1-7]XXXXXX
65 9[0-8]XXXXXX

But recently 65 88XXXXXX numbers have been added.

**Comment by roes** [comment]
Hi,
I tried this in our demo http://libphonenumber.appspot.com/ and that prefix is already supported. Please make sure you're using an up to date version.
