### ISSUE TITLE
Niger number +227 8090 XXXX is not validated

### ISSUE THREAD

**Issue by laurentS** [googlei18n/libphonenumber#800]
I recently got a sim card from Orange Niger with this number. I think the range should be +227 80 xx xx xx.
I have not found any official documentation about it online, nor from Orange, but hopefully someone here has better access to this sort of data than myself.

**Comment by roes** [comment]
Thank you for your report. If you have any evidence at all to provide us with that would speed up the process. If you want to provide us with documents privately see https://github.com/googlei18n/libphonenumber/wiki/ContributeToTheProject for details.

**Comment by keghani** [comment]
Fixed in release 7.0.11.
