### ISSUE TITLE
New Namibia phone numbers not validating

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#807]
This phone number is confirmed valid for accepting phone calls: +26463683160

Libphone says that it is a possible number but not a valid number.

The business that uses it is the Sandfontein Lodge located in Karasburg 9000, Namibia. http://www.sandfontein.com/

How can we go about ensuring that this number and others similarly formatted can be validated in libphone?

**Comment by jias0001** [comment]
Thanks for the report. We will fix it in the next release.

**Comment by keghani** [comment]
Fixed in release 7.0.11.
