### ISSUE TITLE
New Phone numbers are not giving proper results

### ISSUE THREAD

**Issue by ishanrustagi** [googlei18n/libphonenumber#808]
I am using this API:- "https://github.com/giggsey/libphonenumber-for-php", and have downloaded the whole project through composer.
So whenever the any git file is updated would i'll be notified ?
If not, how would i'll updating my API with the new number series.

**Comment by keghani** [comment]
libphonenumber-for-php is not developed or maintained by us, and I don't know the answer. Please ask at https://github.com/giggsey/libphonenumber-for-php/issues.
