### ISSUE TITLE
Fix Haiti carriers

### ISSUE THREAD

**Issue by keghani** [googlei18n/libphonenumber#809]
From @Francogo at https://github.com/googlei18n/libphonenumber/issues/746#issuecomment-123327959:

    995XXXXX, 996XXXXX, 997XXXXX, 998XXXXX and 999XXXXX are used by the carrier Access Haiti.
    980XXXXX, 981XXXXX, 982XXXXX, 983XXXXX and 985XXXXX are used by Hainet.

We already have evidence through the correspondence from the above issue.

**Comment by jias0001** [comment]
We are working on fixing this.

**Comment by keghani** [comment]
Fixed in release 7.0.11.
