### ISSUE TITLE
Missing prefix for UM (US Outlying Islands)

### ISSUE THREAD

**Issue by johnmengqin** [googlei18n/libphonenumber#810]
http://www.auslandsvorwahlen.net/en/country/268

kMapCCode2CN in NBMetadataHelper is missing object + key pair {"1", "UM"}

**Comment by jias0001** [comment]
No, we only support the region codes for countries/regions officially recognized by ITU for allocating telephone number country calling code purposes:

http://www.itu.int/oth/T0202.aspx?parent=T0202
