### ISSUE TITLE
Missing prefix for AQ and GS

### ISSUE THREAD

**Issue by johnmengqin** [googlei18n/libphonenumber#811]
kMapCCode2CN in NBMetadataHelper is missing object + key pairs  {"672", "AQ"} and {"500", "GS"}

**Comment by jias0001** [comment]
No, we only support the region codes for countries/regions officially recognized by ITU for allocating telephone number country calling code purposes:

http://www.itu.int/oth/T0202.aspx?parent=T0202

By the way, the code you mentioned doesn't officially belong to our project. It is a port maintained by other projects, and any bugs should be reported in their project instead.
