### ISSUE TITLE
Mauritania Mauritel mobile number detection

### ISSUE THREAD

**Issue by asiminiceanu** [googlei18n/libphonenumber#812]
The ITU is saying that for Mauritel mobile numbers the B part can be 0,1, 2, 3, 4, 6, 7, 8, 9.
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000870001PDFE.pdf

The same thing is said in the offical document published by them and listed as one of the references in the resources XML file:
http://are.mr/pdfs/pnn2010.pdf

I know that in the table there are no examples with 0, 1, 2, 3 and 9 but that does not mean that the numbers that have B starting with these are not valid.

Please fix the regex for Mauritel mobile numbers to support also the B part that starts with 0, 1, 2, 3 and 9.

Thanks!

**Comment by andyst** [comment]
Sounds reasonable to me.

The regexp already supports 49, but 4[123] are indeed missing.

You can check that here:
https://libphonenumber.appspot.com/
e.g. with +22249000000

**Comment by asiminiceanu** [comment]
Hi, 

I think I am using a version that did not had the support for 49 as it was fixed with this ticket:
https://github.com/googlei18n/libphonenumber/issues/529

When do you think a fix can be expected?

Thanks!

**Comment by andyst** [comment]
In the order of 2-6 weeks I suppose.

**Comment by andyst** [comment]
To be clear: I've added the task to our queue of metadata changes.

**Comment by asiminiceanu** [comment]
Thanks! 
Looking forward for the fix.

**Comment by penmetsaa** [comment]
Issue fixed by release 7.1.1
