### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [googlei18n/libphonenumber#814]
Would you like to [replace any double quotes](https://github.com/googlei18n/libphonenumber/blob/994c913514a7dbd0e52fbb3646e9abd5270a4eef/cpp/src/phonenumbers/shortnumberinfo.cc#L17 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by mihaelacr-google** [comment]
Thanks for the suggestion. The current style follows local style guidelines. We're keeping it as it is.
