### ISSUE TITLE
Indonesia 12 digit mobile phones

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#815]
Several carriers in Indonesia started using 12 digit phone numbers.

I suggest expanding the mobile pattern to 8[1-35-9]\d{7,10} and increasing possibleNumberPattern up to 12.

**Comment by mihaelacr-google** [comment]
Can you please provide us with some official documentation? Carrier docs, government docs or other official sources are OK.

**Comment by andyst** [comment]
So far you've submitted a Wikipedia URL. We need authoritative docs by carrier or government. Thanks!

**Comment by andyst** [comment]
Got it, thanks.

**Comment by padmaksha** [comment]
Fixed in release 7.1.1.
