### ISSUE TITLE
Kenya - new mobile prefixes

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#816]
79[0-2] - Safaricom
77[67] - Telekom Kenya

**Comment by mihaelacr-google** [comment]
Can you please provide us with some official documentation? Carrier docs, government docs or other official sources are OK.

**Comment by andyst** [comment]
79 (Safaricom) is already handled, will be in next release.

That part is a dupe of: https://github.com/googlei18n/libphonenumber/issues/804.

For 77[67] we need evidence, as requested by @mihaelacr-google .

**Comment by alecx** [comment]
Already sent documentation for all tickets.

**Comment by andyst** [comment]
No docs received. We received an email but it's got an empty body and no attachments.

**Comment by andyst** [comment]
Got it, thanks.

**Comment by penmetsaa** [comment]
This is fixed.
https://libphonenumber.appspot.com/phonenumberparser?number=%2B254+777+010+000
