### ISSUE TITLE
Cambodia - numbering change

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#817]
Seatel had added 1 more digit to their number range -  original 8 digits (855)18xxxxxx to 9 digits (855)18xxxxxxx

**Comment by mihaelacr-google** [comment]
Can you please provide us with some official documentation? Carrier docs, government docs or other official sources are OK.

**Comment by andyst** [comment]
Same here: The received email has your proposed pattern, but no attachment (we need authoritative evidence).

**Comment by andyst** [comment]
Got it. Thanks!

**Comment by penmetsaa** [comment]
This is fixed.
https://libphonenumber.appspot.com/phonenumberparser?number=%28855%29181234567&country=KH
