### ISSUE TITLE
Ninth digit in Brazilian numbers

### ISSUE THREAD

**Issue by michaelpaul** [googlei18n/libphonenumber#818]
In brazil mobile phone numbers are changing to have nine digits. A new digit "9" will be added to the left of the number, the new format will be like 9XXXX-XXXX.

This is a decision from ANATEL - Agência Nacional de Telecomunicações (Brazilian National Telecommunications Agency): http://www.anatel.gov.br/legislacao/resolucoes/25-2010/16-resolucao-553 

Schedule for implementation by telecommunication companies: http://www.anatel.gov.br/Portal/exibirPortalNoticias.do?acao=carregaNoticia&codigo=27064  

And here is a FAQ about it: http://www.oi.com.br/oi/sobre-a-oi/empresa/informacoes/9-digito

**Comment by luizrodrigomottin** [comment]
+1

**Comment by keghani** [comment]
This is on our roadmap and will be in the first release after October 11.

**Comment by keghani** [comment]
To be clear, the October 11th change is for area codes 31-35, 37, 38, 71, 73-75, 77 and 79.

**Comment by michaelpaul** [comment]
Ok! I will be waiting for this release, thanks @keghani.

**Comment by keghani** [comment]
Fixed in release 7.1.0.
