### ISSUE TITLE
Multiple undefined symbols 

### ISSUE THREAD

**Issue by PeterBocan** [googlei18n/libphonenumber#822]
Hello guys, I'm trying to build library on OS X Yosemite (10.10.5, Boost 1.58, ICU 55). I did run this command:
    
    cmake -DGTEST_INCLUDE_DIR:PATH=/Users/pb1/Downloads/gtest/include/ \
    -DGTEST_SOURCE_DIR:PATH=/Users/pb1/Downloads/gtest ..

Which resulted into some weird issue: It has successfully built static library for libgeocoding.a but it did fail compiling dynamic library (libgeocoding.dylib) in linking stage:
   
    Undefined symbols for architecture x86_64:
    "i18n::phonenumbers::SimpleItoa(int)", referenced from:
        i18n::phonenumbers::AreaCodeMap::Lookup(i18n::phonenumbers::PhoneNumber const&) const in area_code_map.cc.o
    "i18n::phonenumbers::SimpleItoa(long long)", referenced from:
      i18n::phonenumbers::AreaCodeMap::Lookup(i18n::phonenumbers::PhoneNumber const&) const in area_code_map.cc.o
    "i18n::phonenumbers::safe_strto64(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, long long*)", referenced from:
      i18n::phonenumbers::AreaCodeMap::Lookup(i18n::phonenumbers::PhoneNumber const&) const in area_code_map.cc.o
    "i18n::phonenumbers::PhoneNumberUtil::GetInstance()", referenced from:
      i18n::phonenumbers::AreaCodeMap::AreaCodeMap() in area_code_map.cc.o
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::Init(int const*, int, i18n::phonenumbers::CountryLanguages const* (*)(int), char const**, int, i18n::phonenumbers::PrefixDescriptions const* (*)(int)) in phonenumber_offline_geocoder.cc.o
    "i18n::phonenumbers::PhoneNumberUtil::kRegionCodeForNonGeoEntity", referenced from:
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::GetRegionDisplayName(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const*, icu_55::Locale const&) const in phonenumber_offline_geocoder.cc.o
     "i18n::phonenumbers::PhoneNumberUtil::IsValidNumber(i18n::phonenumbers::PhoneNumber const&) const", referenced from:
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::GetDescriptionForNumber(i18n::phonenumbers::PhoneNumber const&, icu_55::Locale const&) const in phonenumber_offline_geocoder.cc.o
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::GetDescriptionForNumber(i18n::phonenumbers::PhoneNumber const&, icu_55::Locale const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in phonenumber_offline_geocoder.cc.o
        "i18n::phonenumbers::PhoneNumberUtil::GetRegionCodeForNumber(i18n::phonenumbers::PhoneNumber const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const", referenced from:
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::GetCountryNameForNumber(i18n::phonenumbers::PhoneNumber const&, icu_55::Locale const&) const in phonenumber_offline_geocoder.cc.o
      i18n::phonenumbers::PhoneNumberOfflineGeocoder::GetDescriptionForValidNumber(i18n::phonenumbers::PhoneNumber const&, icu_55::Locale const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in phonenumber_offline_geocoder.cc.o
      "i18n::phonenumbers::PhoneNumberUtil::GetNationalSignificantNumber(i18n::phonenumbers::PhoneNumber const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) const", referenced from:
        i18n::phonenumbers::AreaCodeMap::Lookup(i18n::phonenumbers::PhoneNumber const&) const in area_code_map.cc.o
     ld: symbol(s) not found for architecture x86_64
     clang: error: linker command failed with exit code 1 (use -v to see invocation)
     make[2]: *** [libgeocoding.7.0.dylib] Error 1 
     make[1]: *** [CMakeFiles/geocoding-shared.dir/all] Error 2
     make: *** [all] Error 2

Any idea what I've missed?

Thanks in advance,
Peter Bocan.

**Comment by andyst** [comment]
I haven't seen this issue, but our group also usually builds it on a Linux (Ubuntu) machine.
In case you couldn't resolve the issue yet, maybe others who build it on OS X can chime in.

**Comment by SergioRAgostinho** [comment]
Bumped on the same issue having a(n almost) similar configuration.

**Comment by SergioRAgostinho** [comment]
I made a change which allowed me to compile the library but I'm not sure if this is the proper way to do things. So basically, form the error messages I had the impression the libgeocoding made references to a bunch of symbols in libphonenumber. So I decided to try this
```diff
diff --git a/cpp/CMakeLists.txt b/cpp/CMakeLists.txt
index 3539b94..9a1def9 100644
--- a/cpp/CMakeLists.txt
+++ b/cpp/CMakeLists.txt
@@ -415,7 +415,7 @@ if (${BUILD_GEOCODER} STREQUAL "ON")
   # Note that the subset of base/ on which the geocoder relies is implemented
   # on top of Boost header-only libraries (e.g. scoped_ptr.hpp).
   target_link_libraries (geocoding ${LIBRARY_DEPS})
-  target_link_libraries (geocoding-shared ${LIBRARY_DEPS})
+  target_link_libraries (geocoding-shared phonenumber-shared ${LIBRARY_DEPS})
 endif ()
 
 # Build a specific library for testing purposes.
```
and it compiled till the end. I have no idea why this hasn't failed for the static case. 

All tests are passing, even the geocoding ones. Let me know if you want me to submit a PR for this.

**Comment by johnhamelink** [comment]
I can confirm that I have this issue with El Capitan, and @SergioRAgostinho's patch also allows me to compile.

**Comment by roubert** [comment]
The root of the problem here is that the Mac linker insists on looking up symbols already when creating the shared library, instead of waiting to look them up until they are actually going to be used. This is why the target_link_libraries workaround solves the linking error, but isn't the right solution.
