### ISSUE TITLE
Missing dirent.h on Windows 

### ISSUE THREAD

**Issue by PeterBocan** [googlei18n/libphonenumber#824]
Hello guys, I want to notice you that you are using dirent.h (UNIX library) also on Windows:
[generate_geocoding_data.cc@19](https://github.com/googlei18n/libphonenumber/blob/master/tools/cpp/src/cpp-build/generate_geocoding_data.cc#L19)

This won't work. 
Sincerely, 
Peter Bocan.

**Comment by pnkjvvdy** [comment]
I also can't build libphonenumber with geocoder due to this issue. Is there any another way???

**Comment by keghani** [comment]
This seems infeasible given our bandwidth and expertise, but if you the reader have these then please
feel free to re-open this issue and take it up.

We don't actively maintain windows builds but would be able to accept a PR.
We'd also need someone else in the open-source community to test it out and help with the review. Please see the [known Windows issues](FAQ.md#what-about-windows), maybe someone else there or in the
[discussion group](https://groups.google.com/group/libphonenumber-discuss) could help.

**Comment by PeterBocan** [comment]
@keghani I may one day push PR when C++17 is stable (upcoming filesystem implementation).

**Comment by keghani** [comment]
Thanks @PeterBocan! Feel free to re-open then.
