### ISSUE TITLE
New South Carolina area code 854 not accepted

### ISSUE THREAD

**Issue by twcclegg** [googlei18n/libphonenumber#826]
https://en.wikipedia.org/wiki/Area_codes_843_and_854 phonenumbermetadata.xml does not currently allow for 854 numbers.

**Comment by keghani** [comment]
What's the region? US?

We added 854 support for US in release 7.0.11. You can try at libphonenumber.appspot.com:

Step 1: 854-212-0000
Step 2: US

**Comment by keghani** [comment]
And this is in https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/PhoneNumberMetadata.xml. Are you synced with the latest release?

**Comment by twcclegg** [comment]
Looks like I synced just before the 7.0.11 release, thanks.
