### ISSUE TITLE
Library Returning many numbers as INVALID while UI shows it as VALID

### ISSUE THREAD

**Issue by a-nil** [googlei18n/libphonenumber#832]
For NUMBER-7218616768 and REGION- IN, This Library return INVALID phone number. But actually its correct.
However, the UI view returns that it is a VALID Mobile number.

**Comment by keghani** [comment]
The UI (I assume you mean at http://libphonenumber.appspot.com) is at release 7.0.11. Please ensure you sync with the latest release.

**Comment by a-nil** [comment]
@keghani - Yes I am using the release version 7.0.11 only. and UI , I am talking about is the same one as you mentioned.

Thanks

**Comment by a-nil** [comment]
@keghani  I tried to debug the Issue. For the above mentioned phoneNumber, getNumberType() method was returning UNKNOWN as the number type, which is happening because one regex match was failing for this number.

**Comment by andyst** [comment]
https://libphonenumber.appspot.com/ reports the following results:

"""
Parsing Result
country_code	91
national_number	7218616768
extension	 
country_code_source	FROM_DEFAULT_COUNTRY
italian_leading_zero	false
raw_input	7218616768
Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	true
Result from isValidNumberForRegion()	true
Phone Number region	IN
Result from getNumberType()	MOBILE
"""

That's with libphonenumber 7.1.0.

1. Please make sure to use the latest version of the library.
2. Where do you get getNumberType() == UNKNOWN for this number? (C++, Java, JavaScript, ...?)
3. getNumberType() == UNKNOWN does not mean it's considered an invalid number. Validity is determined by isValidNumber().

**Comment by keghani** [comment]
@a-nil are you still having issues?
I'm closing this as it's not an issue with the library and we haven't heard back in a while, maybe you resolved your setup?

If you still need help after updating to the latest version please re-open this issue and reply to @andyst 's question:
Where do you get getNumberType() == UNKNOWN for this number? (C++, Java, JavaScript, ...?)
