### ISSUE TITLE
MD mobile phone number format

### ISSUE THREAD

**Issue by SergiuMir** [googlei18n/libphonenumber#838]
Hello,
PHONE_METADATA_MD should be changet at the line "mobile".
It should be:
mobile=PhoneNumberDesc(national_number_pattern='(?:562\\d|6(?:[01289]\\d{2}|1[01]\\d|21\\d|7(?:[1-6]\\d|7[0-4]))|7(?:6[07]|7[457-9]|[89]\\d)\\d)\\d{4}', possible_number_pattern='\\d{8}', example_number='62112345'),

because of MD "Orange" operator introduced new number "series": 061 and 062.
Thanks

**Comment by dlyongemallo** [comment]
Are you using a python of the phone number library? You'll have to report this there.

**Comment by SergiuMir** [comment]
Yes. I use python

On Tue, Oct 6, 2015 at 12:24 PM, David Yonge-Mallo <notifications@github.com
