### ISSUE TITLE
Add PhoneNumberUtil function overloads that take CharSequence instead of String

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#84]
Imported from [Google Code issue #84](https://code.google.com/p/libphonenumber/issues/detail?id=84) created by [cooldwind](https://code.google.com/u/107710791533787214572/) on 2011-12-21T12:46:36.000Z:

---

It would be useful that PhoneNumberUtil.parse could get raw phone number as CharSequence instead of as String.

See https://issues.apache.org/jira/browse/LUCENE-3663 for a use case.

**Comment by penmetsaa** [comment]
This is fixed as part of release 8.7.0.
PR #1847
