### ISSUE TITLE
Israeli short codes are being wrongly prefixed with *

### ISSUE THREAD

**Issue by marmor7** [googlei18n/libphonenumber#851]
Short codes (e.g. 3090) can be dialed and texted as-is in Israel.
When passed through PhoneNumberUtil.format(), formattedNumber returns as *{number} (e.g. *3090)

This causes the text/call to fail.

**Comment by keghani** [comment]
For short numbers, please use https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java instead of PhoneNumberUtil. This is working as intended.

**Comment by marmor7** [comment]
Thanks for the reply.

I'm getting in my code a phone number, and need to validate and format it. Is there a suggested method to use to decide whether I need to use PhoneNumberUtil or ShortNumberInfo for the task?
e.g. 
> if (number.length < 6) {
>         ShortNumberInfo.isValidShortNumberForRegion(...) 
> } else {
>         PhoneNumberUtil.isValidNumberForRegion(...);
> }

**Comment by keghani** [comment]
There's no one constant you can use for the regular phone number length across regions.
You can do:
```
if (shortNumberInfo.isValidShortNumber(phoneNumber)) {
  ...
} else if (phoneNumberUtil.isValidNumber(phoneNumber)) {
  ...
} else {
  ...
}
```
