### ISSUE TITLE
New slovak operator not supported

### ISSUE THREAD

**Issue by deel77** [googlei18n/libphonenumber#853]
There is new mobile operator (4ka) in Slovakia (SK) and he is using numbers in form of:
0950 xxx xxx
but they are not validated by the library

page of new operator https://www.4ka.sk (only in slovak)

**Comment by keghani** [comment]
Thanks for reporting @deel77 !

We're working on this. I have one question:

4ka is also called SWAN (according to that website), and this is the named used in the national number plan (http://www.itu.int/oth/T02020000BD/en). Is "SWAN" a well-known name locally?

**Comment by deel77** [comment]
SWAN is the company name behind mobile infrastracture, but they partnered with Slovak Post (Slovenská pošta) in order to create mobile operator and they are marketing it as "4ka".

So common people know them as "4ka" but people with technical background should know "SWAN" as well.

**Comment by keghani** [comment]
Thanks! We'll use 4ka.

**Comment by keghani** [comment]
This will be in the next release.

**Comment by keghani** [comment]
This was fixed: http://libphonenumber.appspot.com/phonenumberparser?number=0950+000+000&country=SK
