### ISSUE TITLE
how compile phonenumber.proto to phonenumber.pb.js 

### ISSUE THREAD

**Issue by dockbiz** [googlei18n/libphonenumber#855]
I found useful on this project but how command to compile *.proto to *.pb.js by using clouse lib 
Thank you

**Comment by keghani** [comment]
Hi @dockbiz,

I don't understand whether you're thanking us for the usefulness of the project or asking a question.

- If you're thanking us, you're welcome :)
- If you need help, please reopen the issue.
- If you already found an answer for your issue, no action required. It would be helpful to say this when you close the issue.

Thanks for using our library!

**Comment by dockbiz** [comment]
My project used closure library and closure compile to build bundle js package (goog.require && goog.provide ).
* for comunicate client and server ,I selected protobuf protocol module (it's exist on closure library) but none of solution for **compile *.proto to  *.pb.js by using goog.provide() - require()*** 
like
[phonenumber.proto](https://github.com/googlei18n/libphonenumber/blob/master/resources/phonenumber.proto)
to 
 [phonenumber.pb.js](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumber.pb.js)
 Your project is provide document how to compile on 
[How compile project](https://github.com/googlei18n/libphonenumber/tree/master/javascript)
But i don't want to deep on java package file and complex dependent on xml

I want to see like
`` protoc -I ./phonecall ./phonecall.proto --java_out=phonecall ``
or 
`` protoc -I ./phonecall ./phonecall.proto --go_out=plugins:grpc:phonecall``

on comnamd line like other language

I and my team really interest on protobuf concept ,May be your little advide will help my team progress for using protobuf module and your project

**Comment by keghani** [comment]
Hi @dockbiz,

I don't know the answer to your question. I'm reopening this issue so others can see it and help if they can.

**Comment by andyst** [comment]
Protobuf in JavaScript is a bit of a complicated story. protoc doesn't have a JSON or JavaScript output format.
 - But e.g. in C++ you can convert a binary protobuf byte sequence or a protobuf object to JSON. See: https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/src/google/protobuf/util/json_util.h and https://github.com/google/protobuf/blob/24fe6ba750bf8a247d41fc589460dce1bdd697a1/src/google/protobuf/util/internal/json_objectwriter.h .
 - There's also https://github.com/dcodeIO/ProtoBuf.js which is a more full blown third party solution for protobuf in JavaScript. Also recommended here: http://stackoverflow.com/questions/6912981/google-protocol-buffers-javascript

Hope this helps.

**Comment by dockbiz** [comment]
Thank you for sharing, I already write some little bit code for generate *pb.js file from *.proto file (base on goog.require).
