### ISSUE TITLE
New Brazilian Phone Numbers Not Recognized

### ISSUE THREAD

**Issue by Dynogic** [googlei18n/libphonenumber#856]
Nextel Brazil recently starting issuing phone numbers with the 99 carrier selection code. Brazilians use these selection codes to call long distance.

To test, 01511999598364 succeeds. However 09911999598364 fails, reporting that the number is invalid.

**Comment by mihaelacr-google** [comment]
Hi! Thanks for your contribution!

I looked online but could not find any official documentation that the 99 carrier section code was added. Can you point me to something? Ideally we would get a document from the carrier or government but a news article works too.

**Comment by mastavares** [comment]
Hi! I have a PDF file from the official governmental press from May 8, 2015, page 87, where 99 carrier has been authorized for Nextel Brazil, but unfortunatelly I can´t upload it in here since I have no write access. You can Google it by typing "DOU ATO No- 2.902, DE 8 DE MAIO DE 2015", it's in Portuguese, on page 87. I can also send by email if you let me know your address.

**Comment by mastavares** [comment]
Here you are the official document, I can upload images. Please let me know if it works for you.
![ato no 2 902 - de 8 de maio de 2015](https://cloud.githubusercontent.com/assets/15232098/10638882/f88959d4-77eb-11e5-9ad2-b4498b875d71.jpg)

**Comment by mihaelacr-google** [comment]
I think I found it on Google, see link [here](http://pesquisa.in.gov.br/imprensa/servlet/INPDFViewer?jornal=1&pagina=87&data=12/05/2015&captchafield=firistAccess).

Thanks for the contribution! We will include this in one of our next metadata updates.

**Comment by Dynogic** [comment]
Hi, any update?

**Comment by andyst** [comment]
It's in our task queue and should get to it in the next weeks.

**Comment by mastavares** [comment]
No update so far. Any planned date?

**Comment by padmaksha** [comment]
Hi ,
This change is under review and will go live in the next Git-Hub release 7.2.2.

**Comment by keghani** [comment]
Clarification: This wasn't included in 7.2.2, released yesterday. We're working on it but there's no planned date. Thanks for your patience.

**Comment by penmetsaa** [comment]
@Dynogic
Made necessary changes to the Library to support all the mentioned ranges(carrier selection codes).
These changes will be live in upcoming release 7.2.3.
There is no planned date yet for this release. Will update you once the release is done.

**Comment by penmetsaa** [comment]
Closing this issue. Please re-open if you reply with any questions.

**Comment by keghani** [comment]
Fixed in release 7.2.3: http://libphonenumber.appspot.com/phonenumberparser?number=09911999598364&country=BR
