### ISSUE TITLE
Deleted Austrian numbering resources

### ISSUE THREAD

**Issue by gpoul** [googlei18n/libphonenumber#857]
Several numbering resources have been put out of service during the last years. Some of them are still listed in PhoneNumberMetadata.xml.

The ones I noticed are: 711, 802, 644

The 802 and 644 date of deletion can be found at the end of https://www.rtr.at/de/tk/E129/2312_Austrian_Numbering_Plan_2011-03-30.pdf

The 711 date of deletion at https://www.rtr.at/en/tk/Abschaltungen

Would you agree to remove those? Do you want me to prepare a pull request?

**Comment by mihaelacr-google** [comment]
Hi! Thanks for you contribution. 

From the documentation you provided it seems indeed that the following ranges should be removed: 
711 (premium rate), 644 (mobile) and 802 (toll free).

Please send a pull request! Thanks!

**Comment by gpoul** [comment]
@mihaelacr-google I opened #864 with the changes that I think will be required.

**Comment by keghani** [comment]
Fixed in release 7.2.2
