### ISSUE TITLE
Costa Rica Movistar's numbers are falsely invalidated

### ISSUE THREAD

**Issue by anyanany1** [googlei18n/libphonenumber#860]
Hello,

Trying to validate numbers from Costa Rica, specifically numbers by Movistar mobile operator, always fail.
Here are some test numbers:
50663146695
50663146692
50663146691
50663146696
50663146676

**Comment by mihaelacr-google** [comment]
Hi! Thanks for your contribution!

Can you please provide us some official documentation that shows these numbers are valid? Government documents are ideal, but if you cannot find any newspapers are also accepted.

**Comment by KevinCathcart** [comment]
https://sutel.go.cr/sites/default/files/rcs-590-09_anexo_registro_de_numeracion_11_05_2015.pdf Is the offical numbering plan of Cosa Rica, as located on the site of SUTEL which is the relvant government agency.

SUTEL assigns numbers by numeric ranges, not by prefix. In any case, there are quite a few differences from their last ITU filing, with many reserved ranges in the filing now having assignments. Of particular relevance, numbers 6002000-64001999 have been assigned to  TELEFÓNICA, as in the usage category of "Mobile Telephony Services".

**Comment by padmaksha** [comment]
Thanks Kevin for providing the documentation.
We will work on the given ranges and keep you updated on the issue.

Thanks and Regards
Padmaksha

**Comment by penmetsaa** [comment]
@ KevinCathcart and anyanany1,
The library has been updated to support the mentioned ranges.
These changes will be live in next release.
In future, we will support all other ranges that are mentioned in the official document.
Will let you know once this is done.

Status: Just comment in GitHub. Not closing this issue as we need to do remaining pending updates that are mentioned in official doc.

**Comment by keghani** [comment]
Fixed in release 7.2.3: http://libphonenumber.appspot.com/phonenumberparser?number=50663146695&country=CR
