### ISSUE TITLE
7.1.0 version produce different output than earlier version.

### ISSUE THREAD

**Issue by santoshreachlocal** [googlei18n/libphonenumber#861]
private static com.google.i18n.phonenumbers.PhoneNumberUtil util = com.google.i18n.phonenumbers.PhoneNumberUtil.getInstance()
Phonenumber.PhoneNumber phoneNumber1 = util.parseAndKeepRawInput("49-2411231234 ", "DE");
Phonenumber.PhoneNumber phoneNumber2 = util.parseAndKeepRawInput("492411231234 ", "DE");
System.out.println("phoneNumber1.nationalNumber : "+phoneNumber1.nationalNumber)
System.out.println("phoneNumber2.nationalNumber : "+phoneNumber2.nationalNumber)

==========OutPUt In com.googlecode.libphonenumber:libphonenumber:5.1 =============

phoneNumber1.nationalNumber : 2411231234
phoneNumber2.nationalNumber : 2411231234

=========OutPUt In com.googlecode.libphonenumber:libphonenumber:6.0 ==============

phoneNumber1.nationalNumber : 2411231234
phoneNumber2.nationalNumber : 2411231234

=======OutPUt In com.googlecode.libphonenumber:libphonenumber:7.1.0 ===============
phoneNumber1.nationalNumber : 492411231234
phoneNumber2.nationalNumber : 492411231234

**Comment by mihaelacr-google** [comment]
Hi!

I just used our [demo](http://libphonenumber.appspot.com/) to check your example and it is working fine for me. How are you using the library? Are you getting the latest jar from Maven Central?

**Comment by santoshreachlocal** [comment]
Hi!

I used gradle for getting jar. in gradle we mention specific version number
for getting jar.
i got different output while getting *nationalNumber.*
in earlier versions(6.0 or 5.1) country code was striped but in current
version (7.1.0) country code is not striped.

Thanks,


On Thu, Oct 22, 2015 at 5:35 PM, Mihaela Rosca <notifications@github.com>
wrote:

> Hi!
>
> I just used our demo <http://libphonenumber.appspot.com/> to check your
> example and it is working fine for me. How are you using the library? Are
> you getting the latest jar from Maven Central?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/libphonenumber/issues/861#issuecomment-150201267>
> .
>



-- 

Santosh Yevle
*ReachLocal Services Pvt. Ltd.*
*mobile - +91 9224700917 | email - santosh.yevle@reachlocal.com
<santosh.yevle@reachlocal.com> | skype - santosh_yevle*
5th Floor, 'B' Wing | Express Zone Towers |  Western Express Highway |
Goregaon (E) | Mumbai – 400097 | India
[image: logo_grey-orange1] <https://www.reachlocal.com/us/en>

**Comment by santoshreachlocal** [comment]
Hi,

I go thorough demo <http://libphonenumber.appspot.com/> . it give below
output.
E164 format+49492411231234
in earlier versions(6.0 or 5.1)  output as below.
E164 format+492411231234

On Thu, Oct 22, 2015 at 5:49 PM, Santosh Yevle <santosh.yevle@reachlocal.com
> wrote:

> Hi!
>
> I used gradle for getting jar. in gradle we mention specific version
> number for getting jar.
> i got different output while getting *nationalNumber.*
> in earlier versions(6.0 or 5.1) country code was striped but in current
> version (7.1.0) country code is not striped.
>
> Thanks,
>
>
> On Thu, Oct 22, 2015 at 5:35 PM, Mihaela Rosca <notifications@github.com>
> wrote:
>
>> Hi!
>>
>> I just used our demo <http://libphonenumber.appspot.com/> to check your
>> example and it is working fine for me. How are you using the library? Are
>> you getting the latest jar from Maven Central?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/googlei18n/libphonenumber/issues/861#issuecomment-150201267>
>> .
>>
>
>
>
> --
>
> Santosh Yevle
> *ReachLocal Services Pvt. Ltd.*
> *mobile - +91 9224700917 | email - santosh.yevle@reachlocal.com
> <santosh.yevle@reachlocal.com> | skype - santosh_yevle*
> 5th Floor, 'B' Wing | Express Zone Towers |  Western Express Highway |
> Goregaon (E) | Mumbai – 400097 | India
> [image: logo_grey-orange1] <https://www.reachlocal.com/us/en>
>
>


-- 

Santosh Yevle
*ReachLocal Services Pvt. Ltd.*
*mobile - +91 9224700917 | email - santosh.yevle@reachlocal.com
<santosh.yevle@reachlocal.com> | skype - santosh_yevle*
5th Floor, 'B' Wing | Express Zone Towers |  Western Express Highway |
Goregaon (E) | Mumbai – 400097 | India
[image: logo_grey-orange1] <https://www.reachlocal.com/us/en>

**Comment by mihaelacr-google** [comment]
Yep, just saw that (I tried a different number first to see if the entire country had an issue and it worked fine).

What happens here is that 49 can actually be the start of a number in Germany. 492411231234 can be a phone number that people use to dial inside Germany. As you can see in the Demo, the the 4924 code corresponds to 'Moormerland-Oldersum'. This is why the library does not treat '49' as the country calling code.  You can see the prefix mapping in the [geocoding file](https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/de/49.txt#L2502) for Germany.

If you want to ensure that 49 gets treated as a country code you just have to add + to the phone number. 

Result from the demo for  +492411231234
```
Phone Number entered: +492411231234
defaultCountry entered: DE
Language entered: en
Parsing Result
country_code	49
national_number	2411231234
extension	 
country_code_source	FROM_NUMBER_WITH_PLUS_SIGN
italian_leading_zero	false
raw_input	+492411231234
```
