### ISSUE TITLE
How to convert proto buf to JSON/Object?

### ISSUE THREAD

**Issue by niftylettuce** [googlei18n/libphonenumber#866]
e.g. - how do I convert this to a JSON object with fields/values?
```js
{ values_: [Object],
        fields_: [Object],
        lazyDeserializer_: {},
        deserializedFields_: [Object] }
```

**Comment by andyst** [comment]
What's the broader context?

I guess this answers your questions regarding protobuf and JavaScript:
https://github.com/googlei18n/libphonenumber/issues/855
