### ISSUE TITLE
Which standard for defaultRegion string parameter?

### ISSUE THREAD

**Issue by A21z** [googlei18n/libphonenumber#878]
Parsing a phone number requires a region code string.

`public PhoneNumber parse(String numberToParse, String defaultRegion)`

The documentation does not specify what standard is used for this region code.
[RegionCode.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/test/com/google/i18n/phonenumbers/RegionCode.java) have correct contants that could be useful but this is a test class not exposed in the library. Why not expose it? Or is there an external standard I can use to make sure the input is correct?

Thanks

**Comment by andyst** [comment]
Agreed, the Javadoc / API docs should specify the identifier system used for regions. That's a bug.

To answer the question:
We use ISO 3166-1 alpha-2 country codes plus UN M.49 (3 digit) codes for higher level containers such as 001 for the world. The same system (combination of ISO and UN M.49) is used by Unicode / CLDR.
http://www.unicode.org/cldr/charts/latest/supplemental/territory_containment_un_m_49.html


Lots of functions that use a regionCode string that need better Javadoc:

PhoneNumberUtil.java :
public Set<String> getSupportedRegions() 
private boolean isValidRegionCode(String regionCode)
public String formatNumberForMobileDialing(PhoneNumber number, String regionCallingFrom,
                                             boolean withFormatting)
...
public PhoneNumber getExampleNumber(String regionCode)
public boolean isValidNumberForRegion(PhoneNumber number, String regionCode)
...
public String getRegionCodeForCountryCode(int countryCallingCode)
...
public AsYouTypeFormatter getAsYouTypeFormatter(String regionCode)
...
public PhoneNumber parse(String numberToParse, String defaultRegion)

**Comment by A21z** [comment]
Thanks for the clarification!

**Comment by lararennie** [comment]
For posterity: this is documented at the top of all our libraries, e.g. here:
https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L47
