### ISSUE TITLE
Missed data in geocoding/data/it

### ISSUE THREAD

**Issue by michelep** [googlei18n/libphonenumber#879]
Missed prefix:

'390577' => 'Siena'
'390575' => 'Arezzo'
'390574' => 'Prato'
'390583' => 'Lucca'

**Comment by roes** [comment]
Hi,
Could you please clarify what you mean? I find all these prefixes in the resource files.
https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/it/39.txt#L142

**Comment by dlyongemallo** [comment]
http://libphonenumber.appspot.com shows that numbers with these prefixes all geocode properly.

@michelep - You must be using an old version of libphonenumber. Please sync to the latest version and try again, and re-open if you are still encountering a problem. Thanks.
