### ISSUE TITLE
There is an issue with isNANPACountry.

### ISSUE THREAD

**Issue by ryanle-gamo** [googlei18n/libphonenumber#881]
I entered US number +1 3472251240. It meant that country code is +1 and phone number is 3472251240. but when I display it, country code is  +1347 and phone number is 2251240. This is first time I use it, so I don't know where the bug comes. The following is my code:

NBPhoneNumberUtil *phoneUtil = [[NBPhoneNumberUtil alloc] init];
    NSString *nationalNumber = nil;
    NSNumber *extractCountryCode = [phoneUtil extractCountryCode:customer.phone nationalNumber:&nationalNumber];
    NSString *regionCode = [phoneUtil getRegionCodeForCountryCode:extractCountryCode];
    if ([phoneUtil isNANPACountry:regionCode])
    {
        regionCode = [customer.phone substringToIndex:5];
    }
    else
    {
        NSDictionary *codes = [NSDictionary dictionaryWithPhoneCountryCodes];
        regionCode = [codes objectForKey:regionCode];
    }
    NSString *phoneNumber = [customer.phone substringFromIndex:regionCode.length];
    [self setCountryCode:regionCode];
    [self setText:phoneNumber];

This is urgent at my situation. If anyone has any ideas, please give to me.
Thanks you!

**Comment by keghani** [comment]
Which library are you using? We don't have iOS in this repository.

Note that you get your requested behavior at our demo: http://libphonenumber.appspot.com/

**Comment by ryanle-gamo** [comment]
@keghani 
I am using objective-c repo. Here you are: https://github.com/iziz/libPhoneNumber-iOS
I also checked with demo website above. It is correct. So I guess I am wrong in using. I don't which repo you are using, but can you describe how to detect this issue at your side (I mean your code)?

**Comment by keghani** [comment]
@ryanle-gamo 

The issue is not in this repository's code. I would recommend filing it against https://github.com/iziz/libPhoneNumber-iOS which is maintained by developers outside our project.

**Comment by ryanle-gamo** [comment]
@keghani 

I am sorry for wrong place. I will copy and paste this issue at iOS repo. 

Thanks you for your support anyway.

**Comment by dlyongemallo** [comment]
@ryanle-gamo - Maybe I don't understand what you're trying to do, but it seems that the region code is set to "+1347" because you've explicitly done the following:

regionCode = [customer.phone substringToIndex:5];

(In any case, you should file this against libPhoneNumber-iOS as @keghani suggests.)

**Comment by ryanle-gamo** [comment]
@dlyongemallo 
It is potential solution and I should investigate straigh forward. But I am posting in wrong place and it is causing some confusions for reader. I already moved this issue to iOS repo: https://github.com/iziz/libPhoneNumber-iOS

Thanks anyway.
