### ISSUE TITLE
Ethiopia (+251) has mobile phone numbers that start with 94

### ISSUE THREAD

**Issue by lincolnq** [googlei18n/libphonenumber#882]
I bought a SIM card recently that was not recognized by libphonenumbers. Its national number starts with 94. Photo of the SIM card attached.

![ethiotel](https://cloud.githubusercontent.com/assets/41908/10940280/90bf000c-8316-11e5-872e-986f7b57eb4d.jpg)

**Comment by roes** [comment]
Hi,
Without information from the carrier or another official source, we're likely going to add prefix 944 instead. Please let us know if you have a strong reason to believe the prefix 94 is supported as a whole.

**Comment by lincolnq** [comment]
This seems fine. I have encountered three 944 numbers but no other 94x
numbers.

**Comment by penmetsaa** [comment]
@lincolnq ,
Thanks for your input.
The library has been updated to support the mentioned 944 range.
This change will be live in next release.
Closing this issue. Please re-open if you reply with any questions.

**Comment by keghani** [comment]
Fixed in release 7.2.3: http://libphonenumber.appspot.com/phonenumberparser?number=0944102228&country=ET
