### ISSUE TITLE
Turkmenistan (993)  61 and 69 area code not supported

### ISSUE THREAD

**Issue by ahmetkarakaya** [googlei18n/libphonenumber#890]
Hello,
Although following area code range 62-68 are supported,  none of the area codes 61 and 69 is supported at current version.
Could you please add the 61 and 69 area codes in to new version?

+993-62-XXXXXX - +993-68-XXXXXX   ====> MSISDN VALID

+993-61-XXXXXX  ===>MSISDN INVALID
+993-69-XXXXXX  ===>MSISDN INVALID

Besides,

How can I add new aread code into source code manually?

Thanks.

**Comment by hagbard** [comment]
Please provide some evidence that these new number ranges should be supported. Do you have documents from an official source?

**Comment by ahmetkarakaya** [comment]
I am going to provide a related document, but first of all I would like to know how can I decode PhoneNumberMetadataProto_TM  binary file using phonemetadata.proto? If I decode it I probably change the teh reqular expression by my self then use custom API? Thanks.

**Comment by ahmetkarakaya** [comment]
Hi,
I have uploaded a document having all operators and correponsing country code-area code pairs. You can overview all other operators besides Turkmenistan
[prefiks_13112015.xlsx](https://github.com/googlei18n/libphonenumber/files/41333/prefiks_13112015.xlsx)

Thanks & Regards.

**Comment by keghani** [comment]
Thanks for the document @ahmetkarakaya 

Can you share the source? If it was found online we need the URL.

As a client of the library you shouldn't care about the format used to store the metadata - we can change this at any time without notice, as it's not part of the API.

**Please provide us with the required evidence so we can support these numbers for everyone.**
In the meantime if you need a quick fix you can update your own copy of https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml then regenerate the metadata like so:

```
$ cd java
$ ant build-phone-metadata
```

I want to stress that this process is not part of our API and we can't provide support if you write a program that assumes it will never change. That's just the way we handle things (internally) right now, and it comes with no guarantees.

**Comment by ahmetkarakaya** [comment]
Hi Keghani

this document is  IR-20 documents used at Türkcell Technology internally where I am working as an Engineer . I cannot provide a online link bu how can I provide an evidence except providing an online link?

**Comment by keghani** [comment]
Hi @ahmetkarakaya 

Can you define IR-20?

Where did you get it from? If Türkcell Technology is not the author we need to verify that it's possible to use in our library under the terms of our license: https://github.com/googlei18n/libphonenumber/blob/master/LICENSE

Alternatively, it would be sufficient if you have a document or summary authored by Türkcell Technology stating that you provide service to these specific area codes. In this case please sign the document as well as our CLA at https://cla.developers.google.com/about/google-individual

**Comment by spleenjack** [comment]
There is an example number with +993 61 prefix on this help page of TMCELL carrier: http://www.tmcell.tm/en-US/how-to-call

**Comment by keghani** [comment]
Thanks @spleenjack !

@ahmetkarakaya 
Please upgrade to the latest release, +993 69 is already supported. To check the latest behavior for yourself, see the demo (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

We found evidence for +993 61. We will fix this in an upcoming release.


_Help us help you! Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) when reporting issues._

**Comment by penmetsaa** [comment]
@ahmetkarakaya and @spleenjack 

Fixed in release 7.2.4: https://libphonenumber.appspot.com/phonenumberparser?number=61010000&country=TM
