### ISSUE TITLE
Do you take into account national formatting?

### ISSUE THREAD

**Issue by skfd** [googlei18n/libphonenumber#901]
Iphone formats Ukrainian number as: `+380 (66) 123 45 67`. Looks fine.

But `libphonenumber` formats it as `+380 66 369 5172`. That looks weird.

Is there a way to force national formatting flavour?

**Comment by hagbard** [comment]
See: https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L369

  public enum PhoneNumberFormat {
    E164,
    INTERNATIONAL,
    NATIONAL,
    RFC3966
  }
