### ISSUE TITLE
Incorrect a type of phone number 

### ISSUE THREAD

**Issue by booknara** [googlei18n/libphonenumber#902]
Phone number : +52 442 444 4686

I tested the above phone number in https://libphonenumber.appspot.com/phonenumberparser.
(I assume that the test web page uses the latest libphonenumber library)

The result webpage said that the type of phone number is FIXED_LINE.

Validation                                                   Results
Result from isPossibleNumber()	           true
Result from isValidNumber()	                   true
Result from isValidNumberForRegion()	   true
Phone Number region	                           MX
Result from getNumberType()	                   FIXED_LINE

However, it's not a landline number but a mobile phone number (Carrier : Nextel) in Mexico.

Please check it out and fix the bug.

**Comment by hagbard** [comment]
Do you have any documents as to whether everything in this range is mobile only, or can these numbers be a mix of fixed line or mobile numbers?

**Comment by booknara** [comment]
Sorry, I got this feedback from my one customer and therefore, I don't have any document to give you some phone range information.

But I'm gonna ask the customer that his phone can be a mix of fixed line or mobile numbers and update the issue. Thanks,

**Comment by andrewnicols** [comment]
Looking at the documentation from the ITU (https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200008A0002PDFE.pdf page 2), when dialling a cell phone in Mexico from abroad, the phone number must be prefixed with a 1:

```
• International calls: operators of international ports have to adapt their networks with a view to enabling calls originating abroad and having as their destination users in the local mobile service in Mexico using the “national calling party pays” mode to be made by dialling the following sequence:
+ 52 + 1 + national number
```

Using https://libphonenumber.appspot.com/ with the phone number yields the following results:

Supplied number: +52 442 444 4686 => FIXED_LINE
Using the 1 prefix: +51 1 442 444 4686 => MOBILE

**Comment by penmetsaa** [comment]
@booknara
We aren't classifying beyond mobile token(prefix 1 before the number) absence/presence at the moment. But we'll take it on as a feature request. As there is already a open issue(<a href="https://github.com/googlei18n/libphonenumber/issues/273">#273</a>) for same context, merging this issue into <a href="https://github.com/googlei18n/libphonenumber/issues/273">#273</a> issue.
