### ISSUE TITLE
Kenya (+254) numbers starting with 0790, 0791, 0792

### ISSUE THREAD

**Issue by moshthepitt** [googlei18n/libphonenumber#903]
Please see: https://twitter.com/safaricomltd/status/633134928536932352 for these,

**Comment by penmetsaa** [comment]
Hi,

Thanks for reporting this issue.

The API already supports the mentioned ranges.

You can verify this at libphonenumber.appspot.com

Closing this issue. Please re-open if you reply with any questions.

Thanks & Regards,
Aravind
