### ISSUE TITLE
Indonesia Call Center / Toll Free numbers

### ISSUE THREAD

**Issue by benskelton** [googlei18n/libphonenumber#904]
Hi, a few additional formats needed for Indonesia.  All tests done with v7.21:

1. Call center 5 digit numbers 140XX where X=0..9
Managed by Telkom http://www.infomedia.co.id/media/detail/id/58 (2nd paragraph, 2nd line)

Working Examples: 
McDonald's 14045 http://www.mcdonalds.co.id/layanan/pesan-antar
KFC 14022 http://www.kfcku.com/home-delivery-14022
Bank Mandiri 14000 http://www.bankmandiri.co.id/article/faq-24jam.aspx

Note: If called from mobile we need to dial an area code before the 5 digits. Any area code works! Example: 021 14045 or 0274 14045

Current Status in Libphonenumber:
140XX isPossibleNumber() = true isValidNumber() = false
number with an area code is reported possible and valid
Need:
to add 140XX format as a valid format for Indonesia 

2. Call Center 7 digit numbers 1500XXX where X=0..9 and its predecessor 500XXX
Managed by Infomedia Nusantara http://www.infomedia.co.id/media/detail/id/58 (2nd paragraf, last line)

Previously 6 digits (500 XXX) but the Ministry of Telecommunication changed that to add the 1 at the start in May 2014. 500XXX still can be used until 2016
http://www.postel.go.id/berita-migrasi-nomor-500xyz-menjadi-1500xyz-26-2192 (6th paragraf, 1st line)

Working Examples: 
PHD 1 500 600 https://www.phd.co.id/hotpromo.aspx
Hokben 1 500 505 http://www.hokben.co.id/special_offer/detail/large-order-delivery-hokben
Bank BCA 1 500 888 http://www.bca.co.id/

Note: For 500XXX if called from mobile we need to dial an area code before the 5 digits. Any area code works! For 1500XXX no need for an area code.

Current Status in Libphonenumber:
500XXX and 1500XXX isPossibleNumber() = true isValidNumber() = false
Need:
to add 500XXX and 1500XXX format as a valid format for Indonesia

3. 11 digit numbers (0804 XXXXXXX) 
Managed by Telkom 
Not official link https://hileudtaneuh.wordpress.com/2011/01/14/nomor-telepon-toll-free-dari-telkom/

Working Example: 
Garuda Indonesia 0804 1 807 807 https://www.garuda-indonesia.com/id/id/contact/help.page?

Current Status in Libphonenumber:
0804 XXXXXXX isPossibleNumber() = true isValidNumber() = false
Need:
to add 0804 XXXXXXX format as a valid format for Indonesia

**Comment by keghani** [comment]
This will be in the next release.

**Comment by keghani** [comment]
@penmetsaa FYI

**Comment by penmetsaa** [comment]
Hi Ben,

Thanks for reporting this issue.

LibPhoneNumber API do not support local phone numbers(The numbers without area code).

So we have taken the actions below based on your inputs and our investigation.

1.  140XX: As this code goes to the same business with any area code when dialled from mobile, we are adding it to "Short Codes". For validation of short codes you need to use the below code.

PhoneNumber phoneNumber = PhoneNumberUtil.getInstance().parse(<your_StringInput>, <your_RegionCodeObject>);
ShortNumberInfo shortNumberInfo = ShortNumberInfo.getInstance();
shortNumberInfo.isValidShortNumber(phoneNumber)

When area code is present in the input, this range is already covered as valid landline number.  

2. 500XXX and 1500XXX: When area code is present in the input, these ranges are already covered as valid landline numbers. LibPhoneNumber API do not support local phone numbers. So not making any changes regarding 500XXX range. 

Adding new range 1500XXX as valid UAN number. This range can be dialled without area code.

3. 500XXXX: When area code is present in the input, this range is already covered as valid landline number.
As LibPhoneNumber API do not support local phone numbers, not making any changes on this regards.

4. 804X XXXXXX: As per our analysis, adding this range to shared cost numbers.

Please let me know if you have any further questions. The new changes will be live in next release.

Thanks & Regards,
Aravind

**Comment by keghani** [comment]
Fixed in release 7.2.2
