### ISSUE TITLE
cannot load/parse metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_HU

### ISSUE THREAD

**Issue by adamvarhegyi** [googlei18n/libphonenumber#906]
So i was using this library since weeks, it was working fine. Until today randomly popping an error message. I just didnt changed anything that could cause this.

I got this exception when calling: 

    Phonenumber.PhoneNumber phoneNumberProto = phoneUtil.parse(phoneNumberString, null);

The phone number is a hungarian phone number like: +3670#######

And i use 7.0.2 version:

 compile 'com.googlecode.libphonenumber:libphonenumber:7.0.2' 

    11-13 13:47:39.997: E/PhoneNumberUtil(15197): cannot load/parse metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_HU
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): java.io.EOFException
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at libcore.io.Streams.readFully(Streams.java:83)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.io.DataInputStream.readFully(DataInputStream.java:99)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.io.DataInputStream.decodeUTF(DataInputStream.java:178)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.io.DataInputStream.decodeUTF(DataInputStream.java:173)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.io.DataInputStream.readUTF(DataInputStream.java:169)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.io.ObjectInputStream.readUTF(ObjectInputStream.java:2111)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.Phonemetadata$PhoneMetadata.readExternal(Phonemetadata.java:856)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.Phonemetadata$PhoneMetadataCollection.readExternal(Phonemetadata.java:956)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.loadMetadataFromFile(PhoneNumberUtil.java:601)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1945)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegionOrCallingCode(PhoneNumberUtil.java:1168)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2817)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2667)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2657)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.illion.dotodo.application.sender.activity.verification.StartVerificationActivity.onClick(StartVerificationActivity.java:83)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.view.View.performClick(View.java:5198)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.view.View$PerformClick.run(View.java:21147)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.os.Handler.handleCallback(Handler.java:739)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.os.Looper.loop(Looper.java:148)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at java.lang.reflect.Method.invoke(Native Method)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    11-13 13:47:39.997: E/PhoneNumberUtil(15197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    11-13 13:47:39.997: D/AndroidRuntime(15197): Shutting down VM
    11-13 13:47:39.998: E/AndroidRuntime(15197): FATAL EXCEPTION: main
    11-13 13:47:39.998: E/AndroidRuntime(15197): Process: com.illion.dotodo.application.sender, PID: 15197
    11-13 13:47:39.998: E/AndroidRuntime(15197): java.lang.RuntimeException: cannot load/parse metadata: /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_HU
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.loadMetadataFromFile(PhoneNumberUtil.java:618)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:1945)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegionOrCallingCode(PhoneNumberUtil.java:1168)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2817)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2667)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:2657)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.illion.dotodo.application.sender.activity.verification.StartVerificationActivity.onClick(StartVerificationActivity.java:83)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.view.View.performClick(View.java:5198)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.view.View$PerformClick.run(View.java:21147)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.os.Handler.handleCallback(Handler.java:739)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.os.Handler.dispatchMessage(Handler.java:95)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.os.Looper.loop(Looper.java:148)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.lang.reflect.Method.invoke(Native Method)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    11-13 13:47:39.998: E/AndroidRuntime(15197): Caused by: java.io.EOFException
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at libcore.io.Streams.readFully(Streams.java:83)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.io.DataInputStream.readFully(DataInputStream.java:99)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.io.DataInputStream.decodeUTF(DataInputStream.java:178)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.io.DataInputStream.decodeUTF(DataInputStream.java:173)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.io.DataInputStream.readUTF(DataInputStream.java:169)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at java.io.ObjectInputStream.readUTF(ObjectInputStream.java:2111)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.Phonemetadata$PhoneMetadata.readExternal(Phonemetadata.java:856)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.Phonemetadata$PhoneMetadataCollection.readExternal(Phonemetadata.java:956)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	at com.google.i18n.phonenumbers.PhoneNumberUtil.loadMetadataFromFile(PhoneNumberUtil.java:601)
    11-13 13:47:39.998: E/AndroidRuntime(15197): 	... 15 more

**Comment by dlyongemallo** [comment]
Do you mean version 7.2.0?

**Comment by tuo** [comment]
@adamvarhegyi ,
  you need user 7.2.1 version

**Comment by penmetsaa** [comment]
@ adamvarhegyi

Thanks for reporting this issue.

Libphonenumber version 7.2.0 is considered as bad release.

This version has been removed from maven central as well.

Please try with the new release 7.2.1 and let us know if the problem persists.

We have tried from our end, using same pattern (+3670#######). There is no issue with the 7.2.1 version.

Closing this issue. Please re-open if you reply with any questions.

Thanks & Regards,
Aravind
