### ISSUE TITLE
Usability issue with AsYouTypeFormatter for US numbers

### ISSUE THREAD

**Issue by nlwillia** [googlei18n/libphonenumber#907]
I'm using the excellent [intl-tel-input](https://github.com/Bluefieldscom/intl-tel-input) library which uses libphonenumber under the hood for formatting with very good results, but I got some challenging feedback from a usability review.

The participant was entering a US number, and they really struggled with the format.  There are two US formats configured in `PhoneNumberMetadata.xml`, one for the local 7-digit and one for the full 10-digit.  The [AsYouTypeFormatter](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) decides that the 7-digit format matches first and only switches to the 10-digit format [after the 8th digit has been typed](http://jackocnr.com/intl-tel-input.html).  This is clever if you want to support any possible national format, but it's frustrating if you intend a specific format and don't see the mask you were expecting right away.  The participant tried various ways of "fixing" the format they were seeing and did not think to just keep typing.  Knowing how the formatter works, it's easy to dismiss this as user ignorance, but it's actually fairly counter intuitive to be typing what you expect to be a 10-digit number and see it formatted as a 7-digit number (especially when the placeholder sample showed that a 10-digit number was expected).  It takes a certain amount of faith to just keep typing and hope that it will eventually work, and statistically speaking, users just don't work that way.  It would be better for us to use no mask at all, but then you give up the helpful visual feedback that an accurate placeholder/input mask can provide.

I know that US numbers aren't the only focus of this library, but for web forms in the US, the full 10-digit number is almost always required, and I wonder if that isn't a pattern that exists in other nationalities with multiple formats as well.  It would be great to have an option for the AsYouTypeFormatter that could specify that you were interested in the "full" national format of the number (acknowledging that pinning down what that means for some countries might be less clear than it is for the US).

For intl-tel-input, my workaround was to just remove the unwanted format from the data file, but since the AsYouTypeFormatter is clearly intended for creating a user experience, I think this is something that should be considered upstream.

**Comment by keghani** [comment]
Thanks for reporting this issue!

The library is not limited to web forms. The AYTF at each step has to reflect what our library would actually output if given that string of digits to format - and in this case, it's working as intended.

I would recommend a workaround as you have done.

**Comment by nlwillia** [comment]
Basically, what I'm looking for is a variant of the AYTF that excludes formats which would not produce a full E164 version of the number.  Since it's data-driven, attacking the problem from the data side is not unreasonable, but rather than having to manually edit out specific formats, would a transform that removes format variants with `<intlFormat>NA</intlFormat>` be an accurate approach?
