### ISSUE TITLE
liphonenumber installation failing.

### ISSUE THREAD

**Issue by nirrr** [googlei18n/libphonenumber#908]
hi,
im not able to install libphonenumber.

[root@localhost build]# make
[  2%] Built target generate_geocoding_data
[  7%] Built target geocoding
[ 12%] Built target geocoding-shared
[ 12%] Generating Metadata code
[ 13%] Built target generate-alt-format-metadata
[ 34%] Built target phonenumber
Linking CXX executable geocoding_test_program
libphonenumber.a(phonenumberutil.cc.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x19): undefined reference to `boost::thread_detail::enter_once_region(boost::once_flag&)'
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x2f): undefined reference to `boost::thread_detail::commit_once_region(boost::once_flag&)'
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x58): undefined reference to `boost::thread_detail::rollback_once_region(boost::once_flag&)'
collect2: error: ld returned 1 exit status
make[2]: *** [geocoding_test_program] Error 1
make[1]: *** [CMakeFiles/geocoding_test_program.dir/all] Error 2
make: *** [all] Error 2

please help...

**Comment by nirrr** [comment]
hi,
im not able to install libphonenumber.

[root@localhost build]# make
[  2%] Built target generate_geocoding_data
[  7%] Built target geocoding
[ 12%] Built target geocoding-shared
[ 12%] Generating Metadata code
[ 13%] Built target generate-alt-format-metadata
[ 34%] Built target phonenumber
Linking CXX executable geocoding_test_program
libphonenumber.a(phonenumberutil.cc.o): In function `void boost::call_once<void (*)()>(boost::once_flag&, void (*)())':
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x19): undefined reference to `boost::thread_detail::enter_once_region(boost::once_flag&)'
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x2f): undefined reference to `boost::thread_detail::commit_once_region(boost::once_flag&)'
phonenumberutil.cc:(.text._ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_[_ZN5boost9call_onceIPFvvEEEvRNS_9once_flagET_]+0x58): undefined reference to `boost::thread_detail::rollback_once_region(boost::once_flag&)'
collect2: error: ld returned 1 exit status
make[2]: *** [geocoding_test_program] Error 1
make[1]: *** [CMakeFiles/geocoding_test_program.dir/all] Error 2
make: *** [all] Error 2

**Comment by dlyongemallo** [comment]
It looks like boost isn't installed correctly.

Did you read the README and follow the instructions to install boost?

**Comment by nirrr** [comment]
hi,

im getting the same error even after re installing latest version boost_1_59_0.

i followed this steps -
./bootstrap.sh
./b2

please help..

**Comment by dlyongemallo** [comment]
Did you read the README?

**Comment by nirrr** [comment]
there is no README in the boost_1_59_0.
so i searched and run the scripts.

**Comment by nirrr** [comment]
hi,
There is no README in the boost_1_59_0.
so i searched in run scripts. what can i do?

**Comment by nirrr** [comment]
hi,
There is no README in the boost_1_59_0.
so i searched in run scripts. what can i do?

On Wed, Nov 18, 2015 at 2:28 PM, David Yonge-Mallo <notifications@github.com

**Comment by dlyongemallo** [comment]
Please read the README file:
https://github.com/googlei18n/libphonenumber/blob/master/cpp/README

Like I said, it looks like boost isn't installed correctly. Without knowing anything about your operating system and setup, and what you did to install the prerequisites for libphonenumber, we can't help you further than to point you at the README.

**Comment by nirrr** [comment]
hi,
im using centos 7.

after running this below commmand im getting output as,
 $ sudo yum install libboost-dev libboost-thread-dev libboost-system-dev

output:
[root@localhost opt]# sudo yum install libboost-dev libboost-thread-dev libboost-system-dev
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
No package libboost-dev available.
No package libboost-thread-dev available.
No package libboost-system-dev available.
Error: Nothing to do

same error in while running libphonenumber.

**Comment by dlyongemallo** [comment]
Packages on CentOS are named differently than on Debian. You'll need to, e.g., "yum install boost-devel", etc.

Closing as this is not an issue with the library.

**Comment by nirrr** [comment]
hi,

everything is installed still im gettting same error.

  Name and summary matches only, use "search all" for everything.
[root@localhost build]# yum search boost
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
==================================================================== N/S matched: boost =====================================================================
boost-atomic.i686 : Run-Time component of boost atomic library
boost-atomic.x86_64 : Run-Time component of boost atomic library
boost-chrono.i686 : Run-Time component of boost chrono library
boost-chrono.x86_64 : Run-Time component of boost chrono library
boost-context.i686 : Run-Time component of boost context switching library
boost-context.x86_64 : Run-Time component of boost context switching library
boost-date-time.i686 : Run-Time component of boost date-time library
boost-date-time.x86_64 : Run-Time component of boost date-time library
boost-devel.i686 : The Boost C++ headers and shared development libraries
boost-devel.x86_64 : The Boost C++ headers and shared development libraries
boost-doc.noarch : HTML documentation for the Boost C++ libraries
boost-examples.noarch : Source examples for the Boost C++ libraries
boost-filesystem.i686 : Run-Time component of boost filesystem library
boost-filesystem.x86_64 : Run-Time component of boost filesystem library
boost-graph.i686 : Run-Time component of boost graph library
boost-graph.x86_64 : Run-Time component of boost graph library
boost-graph-mpich.i686 : Run-Time component of parallel boost graph library
boost-graph-mpich.x86_64 : Run-Time component of parallel boost graph library
boost-graph-openmpi.i686 : Run-Time component of parallel boost graph library
boost-graph-openmpi.x86_64 : Run-Time component of parallel boost graph library
boost-iostreams.i686 : Run-Time component of boost iostreams library
boost-iostreams.x86_64 : Run-Time component of boost iostreams library
boost-locale.i686 : Run-Time component of boost locale library
boost-locale.x86_64 : Run-Time component of boost locale library
boost-math.i686 : Math functions for boost TR1 library
boost-math.x86_64 : Math functions for boost TR1 library
boost-mpich.i686 : Run-Time component of Boost.MPI library
boost-mpich.x86_64 : Run-Time component of Boost.MPI library
boost-mpich-devel.i686 : Shared library symbolic links for Boost.MPI
boost-mpich-devel.x86_64 : Shared library symbolic links for Boost.MPI
boost-mpich-python.i686 : Python run-time component of Boost.MPI library
boost-mpich-python.x86_64 : Python run-time component of Boost.MPI library
boost-openmpi.i686 : Run-Time component of Boost.MPI library
boost-openmpi.x86_64 : Run-Time component of Boost.MPI library
boost-openmpi-devel.i686 : Shared library symbolic links for Boost.MPI
boost-openmpi-devel.x86_64 : Shared library symbolic links for Boost.MPI
boost-openmpi-python.i686 : Python run-time component of Boost.MPI library
boost-openmpi-python.x86_64 : Python run-time component of Boost.MPI library
boost-program-options.i686 : Run-Time component of boost program_options library
boost-program-options.x86_64 : Run-Time component of boost program_options library
boost-python.i686 : Run-Time component of boost python library
boost-python.x86_64 : Run-Time component of boost python library
boost-random.i686 : Run-Time component of boost random library
boost-random.x86_64 : Run-Time component of boost random library
boost-regex.i686 : Run-Time component of boost regular expression library
boost-regex.x86_64 : Run-Time component of boost regular expression library
boost-serialization.i686 : Run-Time component of boost serialization library
boost-serialization.x86_64 : Run-Time component of boost serialization library
boost-signals.i686 : Run-Time component of boost signals and slots library
boost-signals.x86_64 : Run-Time component of boost signals and slots library
boost-static.i686 : The Boost C++ static development libraries
boost-static.x86_64 : The Boost C++ static development libraries
boost-system.i686 : Run-Time component of boost system support library
boost-system.x86_64 : Run-Time component of boost system support library
boost-test.i686 : Run-Time component of boost test library
boost-test.x86_64 : Run-Time component of boost test library
boost-thread.i686 : Run-Time component of boost thread library
boost-thread.x86_64 : Run-Time component of boost thread library
boost-timer.i686 : Run-Time component of boost timer library
boost-timer.x86_64 : Run-Time component of boost timer library
boost-wave.i686 : Run-Time component of boost C99/C++ pre-processing library
boost-wave.x86_64 : Run-Time component of boost C99/C++ pre-processing library
ibus-typing-booster.noarch : A typing booster engine for the IBus platform
boost.x86_64 : The free peer-reviewed portable C++ source libraries
boost-build.noarch : Cross platform build system for C++ projects
boost-jam.x86_64 : A low-level build tool

  Name and summary matches only, use "search all" for everything.
[root@localhost build]# yum install boost-thread
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
Package boost-thread-1.53.0-23.el7.x86_64 already installed and latest version
Nothing to do
[root@localhost build]# yum install boost-timer
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
Package boost-timer-1.53.0-23.el7.x86_64 already installed and latest version
Nothing to do
[root@localhost build]# yum install boost-random
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
Package boost-random-1.53.0-23.el7.x86_64 already installed and latest version
Nothing to do
[root@localhost build]#

**Comment by dlyongemallo** [comment]
Please read the following sections from the README:
"Version 1.40 or more recent is required if you need libphonenumber to be
    thread-safe. If you access libphonenumber from a single thread, you can
    avoid the Boost dependency by disabling the USE_BOOST CMake option (see
    Troubleshooting section below for information about ccmake).
[...]
Note: Boost Thread is the only library needed at link time.
[...]
Supported build parameters
--------------------------
  USE_BOOST             = ON | OFF [ON]  -- Use Boost. This is only needed in
                                            multi-threaded environments that
                                            are not Linux and Mac.
                                            Libphonenumber relies on Boost for
                                            non-POSIX (e.g. Windows)
                                            multi-threading."

Either you need boost, in which case you seem to be missing boost-thread-devel (note that you need the "-devel" packages, not just the runtime ones); or you don't need boost, in which case you should disable it. Either way, this is not an issue with the library, but with your setup. All the information you need to set up an environment for compiling the library is in the README file.

If you need help with setting up boost, I suggest you post to a boost user forum.

**Comment by nirrr** [comment]
hi,
Thank you for your suggestion.
