### ISSUE TITLE
New Icelandic (+354) mobile numbers series not supported

### ISSUE THREAD

**Issue by orvaratli** [googlei18n/libphonenumber#909]
Hello.

Thanks for you excellent library. 

I want to report update to mobile number series for Iceland (+354).
New mobile number series 78xxxxx are not supported as mobile numbers in your library. 

Also Mobile number series 760xxxx to 762xxxx need to be added as mobile numbers.

For further details see: 
http://www.pfs.is/library/Skrar/Tidnir-og-taekni/Numeramal/ISL-ENSKT%20Q_ISL_EN_1-913052015c.xlsx

Thank you very much,

Örvar

**Comment by orvaratli** [comment]
Also the 620xxxx - 628xxxx number series is also not validated as a mobile number.

**Comment by bmarry** [comment]
Hi 

Can you please provide us with supporting evidence that these ranges are in use in Iceland and or ITU documentation that these ranges have been allocated to mobile operators in Iceland

Thanks
Brendan

**Comment by orvaratli** [comment]
The document above is from the official ITU of Iceland (www.pfs.is). I put an effort into find and research this for you before posting. Please check.

**Comment by keghani** [comment]
Thanks for the link @orvaratli 

We'll support this document in an upcoming release. Can you let me know how I can get it from the English part of the website? I get to http://www.pfs.is/english/telecom-affairs/numbering/ and then?

**Comment by keghani** [comment]
Never mind, it's the same as http://www.pfs.is/library/Skrar/Tidnir-og-taekni/Numeramal/ISL-ENSKT%20Q_ISL_EN_1-913052015c.xlsx :)

**Comment by orvaratli** [comment]
Thank you very much.

**Comment by penmetsaa** [comment]
@orvaratli

Made necessary changes to the Library to support all the mentioned ranges.

These changes will be live in upcoming release 7.2.2.

Thanks & Regards,
Aravind

**Comment by orvaratli** [comment]
Thank you Aravind :)

**Comment by keghani** [comment]
Fixed in release 7.2.2
