### ISSUE TITLE
Sweden's 71[09]\d{10} phone numbers aren't recognized

### ISSUE THREAD

**Issue by mboliveira** [googlei18n/libphonenumber#910]
Hi,
I tested the mobile phone number +46719000XXXXXXX with libphonenumber library 7.2.1 and the parsing result country code was 46.

But the validation results were:
Result from isPossibleNumber()	false
Result from isPossibleNumberWithReason()	TOO_LONG

However, the above mobile phone number is really valid.

Please check it out.
Thanks.

**Comment by keghani** [comment]
Thanks for your report @mboliveira !

I already found the evidence in the document we usually consult: http://www.pts.se/upload/Ovrigt/Tele/Nummerfragor/swedish-numbering-plan-for-telephony-acc-itu-140407.pdf

We'll support this range in an upcoming release.

For future reports please provide official documentation with your initial message, so we can take action more quickly.

**Comment by mboliveira** [comment]
Thank you for your quick support.

**Comment by penmetsaa** [comment]
@mboliveira

As per Sweden official document, 710 range is used for "Mobile Broadband services" and 719 is used for "Telematic services (M2M)".

We support neither M2M(Machine to Machine) numbers nor data service numbers (Mobile Broadband services).

If you have any evidences saying that these are actual mobile numbers, please re-open the issue and provide these.

Thanks & Regards,
Aravind

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers
