### ISSUE TITLE
ParseAndKeepRawInput doesn't keep input for non-viable numbers.

### ISSUE THREAD

**Issue by cahlbin** [googlei18n/libphonenumber#914]
ParseAndKeepRawInput doesn't keep input for non-viable numbers.

E.g. in case input is only "+1", the parse helper function will return early (https://github.com/googlei18n/libphonenumber/blob/master/cpp/src/phonenumbers/phonenumberutil.cc#L1804) and thus not save the raw input (https://github.com/googlei18n/libphonenumber/blob/master/cpp/src/phonenumbers/phonenumberutil.cc#L1814).

**Comment by dlyongemallo** [comment]
When an error condition occurs, the output is not guaranteed. This is expected behaviour.
