### ISSUE TITLE
Support to Display Phone# in local language

### ISSUE THREAD

**Issue by jainnitin2411** [googlei18n/libphonenumber#915]
I am pleased to use this library for phone number formatting according to country code and its working fine. But if i change the language from English to something else like Hindi, format method will return empty string.
I tried same with i-OS library (extended library) and facing same issue. Although extended c# library working fine with other languages.

Please help to sort this issue.

**Comment by padmaksha** [comment]
Hi 

Thanks for reporting the issue 

Our libphonenumber library is non-locale specific.  We don't support formatting in anything other than ascii digits. I guess you are using a frontend in local format that uses our library.
It would be easier for us to debug the issue if you could please tell us how you are using the library, share code or screenshot reproducing the error.

Thanks and Regards
Padmaksha

**Comment by keghani** [comment]
@jainnitin2411 did you resolve the issue?

**Comment by keghani** [comment]
This doesn't seem to be an issue in our library (but in the frontend), so I'm closing it. Please re-open if you respond so we pick up on it.

Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further, perhaps other users of the library or app developers will be able to advise.
