### ISSUE TITLE
Include JavaScript in Maven Jar?

### ISSUE THREAD

**Issue by DomKM** [googlei18n/libphonenumber#916]
Would you be open to including the JavaScript source in Maven distributions? It would be quite useful for those of us using both the Java and JavaScript versions.

**Comment by padmaksha** [comment]
Hi Dom,

Thanks for coming up with this suggestion.
At this point in time we have only C++ and Java source in Maven Distributions . At this point this feature request is infeasible.

Thanks 
Padmaksha
