### ISSUE TITLE
Indonesia phone numbers are not recognized 

### ISSUE THREAD

**Issue by tranminhtan** [googlei18n/libphonenumber#918]
Hi, my friends reported that he always got `invalid phone number` message when using  +628953383255xx or +628953456259xx for validation. They're long number (14 digits) but they're valid number in ID. Seems libphonenumber does not support these numbers now.

**Comment by penmetsaa** [comment]
Hi,

Thanks for reporting this issue.

The API already supports the mentioned ranges.

You can verify this at libphonenumber.appspot.com

Please sync to the latest release.

Closing this issue. Please re-open if you reply with any questions.

Thanks & Regards,
Aravind

**Comment by tranminhtan** [comment]
@penmetsaa the latest release works fine, thank you.
