### ISSUE TITLE
Senegal number

### ISSUE THREAD

**Issue by 42buck** [googlei18n/libphonenumber#919]
Hello,

This number : 221 7820011** is a valid Senegal number has we were able to call it , but the libphonenumber returns it has an invalid phone number.
Please could you update the format for Senegal?

Thank you

**Comment by temgo** [comment]
Great one, looking forward to see this problem solved

**Comment by padmaksha** [comment]
Thanks for reporting the issue. 

When adding numbers or ranges of numbers to libphonenumber it is best it we have some supporting documentation to help us. Do you know of any website or other documentation which could help us determine which range or ranges we should add?

Anything you can do to supply evidence for the validity of the number (including screen shots or links to web pages) will be greatly appreciated.

**Comment by 42buck** [comment]
Sorry , I only found an article in french.
It explains that because of the saturation of numbers starting by 77, the Senegal Regulation Authority (ARTP) alowed the historical operator (Orange) to use numbers starting by 78.
http://www.leral.net/Des-numeros-Orange-commencant-par-78-L-Artp-donne-son-accord_a60184.html

**Comment by 42buck** [comment]
http://www.itu.int/oth/T02020000B8/en
Here the Senegal number up to date in PDF with an English version ;)

**Comment by padmaksha** [comment]
Hi,

Thanks for providing the evidence.

The API already supports the mentioned range.

You can verify this at libphonenumber.appspot.com

Closing this issue. Please re-open if you reply with any questions.

Thanks & Regards,
Padmaksha

**Comment by keghani** [comment]
To get the latest changes please upgrade to the latest version of libphonenumber.

**Comment by temgo** [comment]
Thanks, it is fantastic

**Comment by temgo** [comment]
Hello

Sorry, it appears they are still some SN numbers which are invalid in your system but in fact are valid phone numbers like 783891253

**Comment by keghani** [comment]
Thanks @temgo ! Can you file a new issue? This number is different from the original issue and not covered at http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000B80001PDFE.pdf. You can start by clicking the link at the bottom of http://libphonenumber.appspot.com/phonenumberparser?number=783891253&country=SN
