### ISSUE TITLE
Djibouti Number showing as invalid when its valid

### ISSUE THREAD

**Issue by mcocaro** [googlei18n/libphonenumber#921]
The number +253 77 080000 is a valid phone number from Evatis carrier in Djibouti and is showing up as invalid.

**Comment by padmaksha** [comment]
Hi , 

Thanks for reporting the issue. 

When adding numbers or ranges of numbers to libphonenumber it is best it we have some supporting documentation to help us. Do you know of any website or other documentation which could help us determine which range or ranges we should add?

Anything you can do to supply evidence for the validity of the number (including screen shots or links to web pages) will be greatly appreciated.

**Comment by padmaksha** [comment]
@mcocaro

We can't connect to this specific number. Did you mean to ask for +253 77 08XXXX as a range?
Please provide evidence that this range is assigned to Evatis - without documentation we can't proceed with the change.
_Help us help you! Use our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md) when reporting issues._

**Comment by penmetsaa** [comment]
@mcocaro

Fixed in release 7.2.6: https://libphonenumber.appspot.com/phonenumberparser?number=%2B253+77+080000
