### ISSUE TITLE
GB 6-digit toll free number is marked invalid

### ISSUE THREAD

**Issue by oksanaut** [googlei18n/libphonenumber#926]
Example: number 116 123 is invalid. Dialling 116 123 from your phone in UK takes you to the correct desitation. 

Prepending 0800 (toll free) validates the number, but dialling 0800 116 123 does not work.

Number example: http://www.samaritans.org/how-we-can-help-you/contact-us/calling-samaritans-roi

**Comment by keghani** [comment]
Thanks for reporting!

116123 is considered valid for the UK by [ShortNumberInfo](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java) as of 7.2.2, released yesterday.

Note that the link you shared is not for the UK :) But we added support for Ireland too.

Thanks for bringing this up. We'll link to information about short number validation at [CONTRIBUTING.md](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by keghani** [comment]
Our demo is now testing for short numbers, so you can check these easily in the future :)

See isPossibleShortNumber() at http://libphonenumber.appspot.com/phonenumberparser?number=116+123&country=GB
