### ISSUE TITLE
few Airtel mobile operator number in India is not recognised as valid mobile number

### ISSUE THREAD

**Issue by alonevision** [googlei18n/libphonenumber#931]
+917319925784 is an valid mobile number of airtel operator in india of Bihar-jharkhand circle but is is not recognising as valid mobile number

**Comment by padmaksha** [comment]
Hi, 

Thanks for reporting the issue.

When adding numbers or ranges of numbers to libphonenumber it is best  we have some supporting documentation to help us. Can you please provide some supporting documentation like government/ carrier or newspaper docs that validates the above mentioned ranges?  
We have also added contribution guidelines at [CONTRIBUTING.md](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).
You can go through the checklist there and use the template to provide us the information we need to fix this issue.

Your efforts will be greatly appreciated.

Thanks 
Padmaksha

**Comment by penmetsaa** [comment]
@alonevision 
Fixed in release 7.2.4: https://libphonenumber.appspot.com/phonenumberparser?number=+917319925784&country=IN
