### ISSUE TITLE
geocoding data file of en

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#936]
The data files in geocoder/src/com/google/i18n/phonenumbers/geocoding/data/ with suffix of 'en' include 1726_en, 1730_en, 1838_en, 1851_en, 1888_en which I do not find in the  resources/geocoding/en/1.txt file. Do those number mean area code in US?

**Comment by penmetsaa** [comment]
@Mortimer2013,

Looks like there is a bug.
Some of the binary files got obsolete.
We'll fix it in an upcoming release.

Thanks so much for reporting this issue.

Regards,
Aravind

**Comment by penmetsaa** [comment]
@Mortimer2013,
This is fixed in release 7.2.4.
