### ISSUE TITLE
Some new prefix (87 XXX ) in Ivory Coast are marked invalid

### ISSUE THREAD

**Issue by temgo** [googlei18n/libphonenumber#937]
Hello

We have noticed that some prefix from Orange Ivory Coast are marked invalid

For example, this is a valid phone number 87 10 xx xx but is marked invalid in the system

Please check this link as reference https://fr.wikipedia.org/wiki/Liste_des_indicatifs_t%C3%A9l%C3%A9phoniques_en_C%C3%B4te_d%E2%80%99Ivoire

**Comment by penmetsaa** [comment]
@temgo 
Thanks for reporting this issue.
I am able to dial the numbers of this range.
So updating libphonenumber accordingly.

We are unable to find official evidence for this new prefix. If you have any official evidence ( ITU document / Post from Government body or carrier..etc), please provide. 
We will still go ahead and make the change as we are able to dial the numbers.

We added contribution guidelines at <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md">CONTRIBUTING.md</a>.
Please ensure you go through the checklist there and use the template so we have the information we need to fix this. You can use this while reporting issues in future.


Thanks & Regards,
Aravind

**Comment by penmetsaa** [comment]
@temgo 
Fixed in release 7.2.4: https://libphonenumber.appspot.com/phonenumberparser?number=87100000&country=CI

**Comment by temgo** [comment]
Thanks so much...working perfect
