### ISSUE TITLE
Can't support  New Cambodian Provider : Seatel Cambodia

### ISSUE THREAD

**Issue by Navrattan-Yadav** [googlei18n/libphonenumber#938]
It does not support newly registered Cambodian provider named South East Asia Telecom Group Pte Ltd (SEATEL Group)  Seatel Cambodia

**Comment by dlyongemallo** [comment]
Hi,

Thanks for the report. Can you please supply the info requested in our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)?

**Comment by dlyongemallo** [comment]
Superseded by issue #1022.
