### ISSUE TITLE
Luxembourg 352 250 404 2204 reporting not valid

### ISSUE THREAD

**Issue by BalooBearUSA** [googlei18n/libphonenumber#941]
However it is... checked with other online validators and calling it works fine.

**Comment by penmetsaa** [comment]
@BalooBearUSA 

Thanks for reporting this issue.
The API already supports the mentioned range.
You can verify this at libphonenumber.appspot.com
Please upgrade to latest version(7.2.2)
Closing this issue. Please re-open if you reply with any questions.

**Comment by penmetsaa** [comment]
In future while reporting any issue, please check our <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md">contribution guidelines</a>.
