### ISSUE TITLE
Slovakia - 02 16xxx 041 16xxx

### ISSUE THREAD

**Issue by pmacko** [googlei18n/libphonenumber#945]
Hello, numbers
02 16xxx
041 16xxx
are valid, but libphonenumber return false.

Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	false
Phone Number region	SK
Result from getNumberType()	UNKNOWN
Formatting Results
E164 format	invalid
Original format	0216100
National format	0216100
International format	invalid
Out-of-country format from US	invalid
Out-of-country format from CH	invalid

**Comment by penmetsaa** [comment]
@pmacko 
Thank you for taking the time to improve libphonenumber!

The number 2 16xxx is very short. Is it short code?
What is the type of number 41 16xxx ?

We are unable to find any sample numbers or official evidences for these ranges.

We need more information to fix this. Help us help you! Use our <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md">contribution guidelines</a> when reporting issues.

**Comment by pmacko** [comment]
Hello, there are short numbers,

041 16 xxx
41 means Zilinsky kraj (as 41 433 2785 in long numbers)
16 is prefix, they means the short number
xxx is number

This numbers uses z.b. taxis.

02 16 158 - z.b. taxi in Bratislava (02 means Bratislava district)
041 16 111 - number in Zilina district (041)

**Comment by penmetsaa** [comment]
@pmacko 
We need more information to fix this. We can't connect to +4214116111 (from Switzerland 041 16 111). Please see our <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md">contribution guidelines</a> for acceptable evidence to allow us to support 041 16xxx.

**Comment by keghani** [comment]
@penmetsaa means that we tried dialling "+4214116111" from Switzerland, not "041 16 111".

**Comment by pmacko** [comment]
041 16 111 was only an example. Call to 02 16 158 was successful?

**Comment by keghani** [comment]
@pmacko 

That makes sense, I thought you gave 041 16 111 as an example of a working phone number.
I think this looks reasonable and explains the "16" service code at the official documentation: https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000BD0002PDFE.pdf

We'll update the library to support your use case. Thanks for reporting!

**Comment by penmetsaa** [comment]
@pmacko 
Fixed in release 7.2.5: https://libphonenumber.appspot.com/phonenumberparser?number=02+16+158&country=SK
