### ISSUE TITLE
prefix 173 needs to be added for CN

### ISSUE THREAD

**Issue by humanPursuit** [googlei18n/libphonenumber#947]
Hello. Forgive my poor English.
Recently, I use the repo [intl-tel-input](https://github.com/jackocnr/intl-tel-input) which alias `libphonenumber`,  and i found that phone num like this `17321044282` (start with 173) can't pass the validate, this type of number started with '173' is added by China Network Operator.
So I use the demo and judge the number, get result as follow: 
![image](https://cloud.githubusercontent.com/assets/7324767/12253890/4b21f2b4-b91e-11e5-83f1-18a457e3c6fe.png)

Thanks.

**Comment by penmetsaa** [comment]
@humanPursuit 

Thank you for taking the time to improve libphonenumber!
We are able to connect to number 17321044282.
We have found official evidence as well for this mobile range.
http://www.itu.int/oth/T020200002B/en

Please see our <a href="https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)">contribution guidelines</a> for future use.

We've accepted this issue and will fix this in an upcoming release.

**Comment by judyyanluo** [comment]
@penmetsaa seems this issue still exists in version 7.2.5
>>> pn = phonenumbers.parse('+8617301201883')
>>> phonenumbers.is_possible_number(pn)
True
>>> phonenumbers.is_valid_number(pn)
False

any idea if this will be fixed in next version? Thanks.

**Comment by padmaksha** [comment]
**@humanPursuit**

We are still working on this issue . Will keep you posted with all further updates .

**Comment by judyyanluo** [comment]
@padmaksha  thanks a lot for the reply. Please keep me updated.

**Comment by penmetsaa** [comment]
@humanPursuit and @judyyanluo 
Fixed in release 7.2.8: https://libphonenumber.appspot.com/phonenumberparser?number=17321044282&country=CN
