### ISSUE TITLE
Support for digits in localized language like Hindi

### ISSUE THREAD

**Issue by SOTG** [googlei18n/libphonenumber#954]
Is there someway to support phone number digits in local language, like Hindi or Arabic numerals?

**Comment by keghani** [comment]
@lararennie ?

**Comment by dlyongemallo** [comment]
@SOTG Can you be more specific? We do support (Eastern) Arabic numerals, e.g., http://libphonenumber.appspot.com/phonenumberparser?number=%D9%A6%D9%A5%D9%A0%D9%A5%D9%A5%D9%A5%D9%A1%D9%A2%D9%A3%D9%A4&country=US

**Comment by SOTG** [comment]
Thanks for the example. Yes, it does accept Arabic numerals as input but is outputting the formatted number in Latin numerals. Does it output in Arabic numerals?

**Comment by dlyongemallo** [comment]
Note that the library uses java.lang.Character.digit to convert the input to their integer values, so it will accept whatever that class accepts as "digits":
https://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#digit(char,%20int)

Here is where it does it:
https://github.com/googlei18n/libphonenumber/blob/fe5bfd45f58f87712545e88464fea7c147d4716d/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L710-L721

The library also follows the robustness principle: while it will accept input in different writing systems, it always produces ASCII digits as output. The user of the library may convert the output as desired.

**Comment by SOTG** [comment]
Thank you very much for clarification. I understand now how to handle this
situation now.

Hari

On Thu, Jan 21, 2016 at 2:55 AM, David Yonge-Mallo <notifications@github.com
