### ISSUE TITLE
Data numbers in Australia

### ISSUE THREAD

**Issue by beccabowen** [googlei18n/libphonenumber#955]
•	Country/region affected: AU
•	Example number affected: 0198379000
•	The phone number range(s) to which the issue applies: 0198x
•	The type of the number: Data number (fixed line)
•	The cost: Local rate
•	Supporting evidence: https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#Data_numbers_.280198.29

These numbers should be nationally formatted with a 0 on the front (NDP), as is usual in Australia, i.e. 0198x. Libphonenumber currently outputs national format without the 0 (198x), which is incorrect. The correct E.164 format is produced (+61198x). Also, the number 0198379000 is in use as the Dial-Up PoP number for iiNet, but is not recognised by libphonenumber as a valid number.

**Comment by penmetsaa** [comment]
@beccabowen
Thanks for reporting this issue.
LibPhoneNumber API presently do not support data / internet access numbers.
The phonenumber library is currently aimed at cases where numbers can be dialed to reach a human endpoint.
We have no plans to support data numbers at the moment, but might in the future.
