### ISSUE TITLE
UK local numbers treated as possible and invalidly converted to E.164

### ISSUE THREAD

**Issue by beccabowen** [googlei18n/libphonenumber#961]
Country/region affected: GB
Example number(s) affected: 1111
The phone number range(s) to which the issue applies: Numbers below 9 digits
The type of the number(s): Local/ short 
Supporting evidence: 
http://www.ofcom.org.uk/static/archive/oftel/publications/numbering/2003/num_guide.htm
http://stakeholders.ofcom.org.uk/binaries/telecoms/numbering/Numbering_Plan_July2015.pdf
http://libphonenumber.appspot.com/phonenumberparser?number=1111&country=GB

libphonenumber accepts these extremely short numbers as possible numbers, and outputs them in E.146 format as, for instance,  +441111. However, the normal UK numbering plan does not include numbers this short. There are, admittedly, nationally-dialable short codes for special services, but since some of those are 3-digit numbers (999, 111 etc.) that are not marked as 'possible' I don't think 4-digit numbers should be either.

In particular, the argument for permitting these numbers is probably that they are valid local numbers (UK local numbers go down to 4 digits in length), but in that case it is invalid to produce E.164 format by prepending +44; the area code would need to be present on the number.

**Comment by giggsey** [comment]
`isValidNumber` is returning false though, it's only `isPossibleNumber` that is returning true.

Whenever I format any numbers, I'm checking if they are valid first.

**Comment by beccabowen** [comment]
Yes, 'valid' returns false - but isPossibleNumber _shouldn't_ be returning 'true' if the base numbering plan doesn't allow the number. As I understand it, the difference between those two functions is that 'valid' will tell you if it's part of an allocated number block, and 'possible' should tell you if it could be allocated as part of the current numbering scheme. 1111 is not a possible number under the current numbering plan.

For context - I am using isPossibleNumber to decide if the numbering plan can be applied to a number, because I would like not to have to wait for an update and apply it to all systems every time a new number block starts to be assigned.

Perhaps my real question here is "why does isPossibleNumber return true, when we have a separate method isPossibleShortNumber?" I'd expect the behaviour here to be false for the former, and true for the latter.

**Comment by keghani** [comment]
To understand the behavior of functions, please refer to the documentation in the Javadoc.
See "public ValidationResult isPossibleNumberWithReason(PhoneNumber number)" in [PhoneNumberUtil.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java) for example:

```
/**
   * Check whether a phone number is a possible number. It provides a more lenient check than
   * {@link #isValidNumber} in the following sense:
   *<ol>
   * <li> It only checks the length of phone numbers. In particular, it doesn't check starting
   *      digits of the number.
   * <li> It doesn't attempt to figure out the type of the number, but uses general rules which
   *      applies to all types of phone numbers in a region. Therefore, it is much faster than
   *      isValidNumber.
   * <li> For fixed line numbers, many regions have the concept of area code, which together with
   *      subscriber number constitute the national significant number. It is sometimes okay to dial
   *      the subscriber number only when dialing in the same area. This function will return
   *      true if the subscriber-number-only version is passed in. On the other hand, because
   *      isValidNumber validates using information on both starting digits (for fixed line
   *      numbers, that would most likely be area codes) and length (obviously includes the
   *      length of area codes for fixed line numbers), it will return false for the
   *      subscriber-number-only version.
   * </ol>
   * @param number  the number that needs to be checked
   * @return  a ValidationResult object which indicates whether the number is possible
   */
```

The library is working as intended here.

**Comment by beccabowen** [comment]
Thank you for pointing me at this. I have had some trouble with the code comment, because it appeared to be false in its assertion that "It only checks the length of phone numbers" - e.g. US 1111111111 is rejected whereas 2222222222 is not. I now understand that this is because of the way these numbers are parsed.

I wonder if you could tell me whether it is actually possible to access the lengths used by isValidNumber, without doing the associated digit checking? I can't see a way to get this info out of the metadata. I will ask this question on the discussion group, instead of on this issue, if I am granted access.

**Comment by keghani** [comment]
Happy to discuss further at [libphonenumber-discuss](https://groups.google.com/forum/#!forum/libphonenumber-discuss) - leaving this here for anyone else who may have read this far.

One-off: Just look at [PhoneNumberMetadata.xml](https://raw.githubusercontent.com/googlei18n/libphonenumber/master/resources/PhoneNumberMetadata.xml).

Programatically: If you parse a [metadata file](https://github.com/googlei18n/libphonenumber/tree/master/java/libphonenumber/src/com/google/i18n/phonenumbers/data/) e.g. [PhoneNumberMetadataProto_AC](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_AC) as [phonemetadata.proto](https://github.com/googlei18n/libphonenumber/blob/master/resources/phonemetadata.proto), look at its ```general_desc.national_number_pattern``` - it will be e.g. "\d{7,10}" for GB. This isn't limited to length though, sometimes it's a more specific regex like "[1-9]\d{7}" for AM, which still is able to tell you it's 8 digits.
