### ISSUE TITLE
Please support the 5XX-NXX codes in the United States

### ISSUE THREAD

**Issue by TMcManus** [googlei18n/libphonenumber#963]
Country/region affected: US
Example number(s) affected: +15885555555
The type of the number: fixed-line, mobile
Supporting evidence: https://www.nationalnanpa.com/number_resource_info/5XX_codes.html

The +1588XXXXXXX range in the United States became available for assignment on September 9th, 2015 (https://www.nationalnanpa.com/pdf/PL_487.pdf). 

According to [the description of the 5XX-NXX range in the United States](https://www.nationalnanpa.com/number_resource_info/5XX_codes.html): 
> 5XX-NXX codes are used for applications which are non-geographic in nature, are not assigned
> to rate centers and may or may not traverse the Public Switched Telephone Network (PSTN), but
> do require an E.164 addressing scheme. The use of this NANP numbering resource is to
> communicate with both fixed and mobile devices, some of which may be unattended. This
> resource may also be used for applications enabling machines, which would include but not be
> limited to wireless devices and appliances, with the ability to share information with back-office
> control and data base systems and the people that use them. Service is limited only by terminal
> and network capabilities and restrictions imposed by the service provider.

**Comment by penmetsaa** [comment]
@TMcManus 
Thanks for providing all the details we need! 
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
@TMcManus 
Fixed in release 7.2.5: https://libphonenumber.appspot.com/phonenumberparser?number=%2B15885555555
