### ISSUE TITLE
Some valid phone numbers for Namibia does not recognized as valid

### ISSUE THREAD

**Issue by ComradeDOS** [googlei18n/libphonenumber#964]
+264 64 414500 does not recognized as valid but should be.

**Comment by penmetsaa** [comment]
@ComradeDOS 

Thank you for taking the time to improve libphonenumber!
We can add this number. But we need more information to fix this. Ex: Is it Landline / Mobile number?
Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by ComradeDOS** [comment]
According to this https://en.wikipedia.org/wiki/Telephone_numbers_in_Namibia page this should be landline.

**Comment by penmetsaa** [comment]
@ComradeDOS

We have found official evidence for this. 
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000930001PDFE.pdf
As per wiki link provided and ITU doc 6441 range belongs to landline. 
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
@ComradeDOS

Fixed in release 7.2.6: https://libphonenumber.appspot.com/phonenumberparser?number=%2B264+64+414500

**Comment by ComradeDOS** [comment]
Thx a lot!
