### ISSUE TITLE
Add javascript version to npm

### ISSUE THREAD

**Issue by janmarek** [googlei18n/libphonenumber#971]
Npm is a de facto standard way how to get javascript libraries on both node.js and frontend javascript development. It's a pity that there is no official package of this library.

**Comment by ruimarinho** [comment]
I believe this has been discussed in https://github.com/googlei18n/libphonenumber/pull/595 when I brought the issue regarding [google-libphonenumber](https://www.npmjs.com/package/google-libphonenumber).

**Comment by keghani** [comment]
Hi @janmarek,

We're not maintaining any official NPM JS package of our library, but found this from searching on npm: https://www.npmjs.com/package/libphonenumber
