### ISSUE TITLE
Currently-rejected +1 380 area code going into service 27 Feb 2016

### ISSUE THREAD

**Issue by charness** [googlei18n/libphonenumber#974]
In response to #441, libphonenumber rejects US area code 380. At the time, implementation of the area code was on indefinite hold.

The 380 area code is now set to go into service on 27 Feb 2016 as a geographic overlay of area code 614.

Country/region affected (e.g., "US"): US

Example number(s) affected ("+1 555 555-1234"): +1 380 555-1212

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +1 380 XXX-XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): fixed-line/mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence:

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B13805551212&country=US)
[NANPA planning letter](https://www.nationalnanpa.com/pdf/PL_477.pdf)
[NANPA "Planned NPAs Not Yet in Service" report](https://www.nationalnanpa.com/enas/plannedNpasNotInServiceReport.do)

**Comment by penmetsaa** [comment]
@Charness 
Thanks for providing all the details we need! 
We've accepted this issue and will fix this in an upcoming release.

**Comment by penmetsaa** [comment]
@charness

Fixed in release 7.2.6: https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+380+555-1212
