### ISSUE TITLE
M2M numbers missing for Norway

### ISSUE THREAD

**Issue by hajo1199** [googlei18n/libphonenumber#976]
The M2M ranges +4758XXXXXXXXXX and (most of) +4759XXXXXX are missing

Country/region affected (e.g., "US"): NO

Example number(s) affected ("+1 555 555-1234"): +47580009083060 

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +47 58XXXXXXXXXX
+47 59XXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile(M2M)

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Documentation: http://www.nkom.no/npt/numsys/E.164.pdf

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers
