### ISSUE TITLE
US - java lib - Landline number reported as FIXED_LINE_OR_MOBILE

### ISSUE THREAD

**Issue by 4nt01ne** [googlei18n/libphonenumber#977]
I am trying to find FIXED_LINE numbers.
I have tested several landline numbers form http://www.whitepages.com/name/Will-Smith and http://www.whitepages.com/name/Andrew-Grant but they all return a phone number type of FIXED_LINE_OR_MOBILE.
I also have tested the number +1 201 205 2075 that is known to be a landline only but it is returned as a FIXED_LINE_OR_MOBILE.
Is there something I don't understand? I thought I would receive a FIXED_LINE number type at least in the last case.

Thank you

**Comment by keghani** [comment]
Hi @4nt01ne,

Thanks for asking!

Some number _ranges_ may be assigned to both fixed-line or mobile numbers.
Naturally, individual numbers in these ranges will be either fixed-line or mobile, not both. But their type cannot be determined by their prefix, so the best our library can do is say that it's one or the other.

For this particular case, there are both fixed-line and mobile numbers in the US that start with 201.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
