### ISSUE TITLE
Validation issue with 7331127454 (IN)

### ISSUE THREAD

**Issue by nareshreddym** [googlei18n/libphonenumber#980]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): IN

Example number(s) affected ("+1 555 555-1234"): 7331127454

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.):  mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 
- We are using the library for iOS And android aswell in our projects , we are trying to validate the mobile number of a user(7331127454),but even if this 7331127454 is a valid format and valid number in India,the library is returning as it is an unknown(-1) number which is blocking us from a couple of weeks,So please we are hoping for the kind attention on the issue.would be really great if this kind of issues were solved.
Thanks :)

**Comment by kkeshava** [comment]
@nareshreddym, 

Thank you for taking the time to improve libphonenumber!
We were able to connect to +91 7331127454 but we can't find official evidence for the actual ranges that are valid. We can't support single numbers, we need context about the prefix that makes them valid.
Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Friendly ping - please clarify.

**Comment by kkeshava** [comment]
Friendly ping - please clarify.

**Comment by keghani** [comment]
We found evidence for this. We'll support it in an upcoming release.

**Comment by penmetsaa** [comment]
@nareshreddym 

Fixed in release 7.2.7: https://libphonenumber.appspot.com/phonenumberparser?number=7331127454&country=IN

**Comment by nareshreddym** [comment]
@penmetsaa  
Hello,if possible could you please provide download link for recent iOS Update / release.

**Comment by keghani** [comment]
We do not maintain any iOS ports, we don't know.
See https://github.com/googlei18n/libphonenumber/blob/master/README.md#known-ports - you might be using https://github.com/iziz/libPhoneNumber-iOS, if so please ask them.

**Comment by nareshreddym** [comment]
yeah sure & really thank you so much for the assistance.
