### ISSUE TITLE
how to identify without country code

### ISSUE THREAD

**Issue by mansukhgagal** [googlei18n/libphonenumber#981]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): +91

Example number(s) affected ("+1 555 555-1234"): +40744325853

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B40744325853&country=%2B91)

**Comment by dlyongemallo** [comment]
"+91" is not a valid region. Did you mean "IN"?

Also, did you really mean "+40744325853" (a number in Romania) or "+9140744325853" (a number in India)?

**Comment by keghani** [comment]
+40744325853 is a valid number in Romania according to our library. See demo: http://libphonenumber.appspot.com/phonenumberparser?number=%2B40744325853
In this case the region code is "RO" - +91 is not a region code but a country calling code for India, but +40744325853 is not an Indian number.
Please re-open this with clarifications if I misunderstood the issue, or consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you want to understand the library better. Thanks for using libphonenumber!
