### ISSUE TITLE
South Africa: non-geographic, machine-related numbers

### ISSUE THREAD

**Issue by euskode** [googlei18n/libphonenumber#985]
We've purchased a few ZA numbers which `libphonenumber` is unable to validate.

Here's what they look like: `+27872405086xxxxx`. 

Our provider has produced the two following resources as proof:

- [ITU](https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000C10001PDFE.pdf) (section 19, on page 22)
- [Vodacom](https://www.vodacombusiness.co.za/corporate/solutions/m2m-number-migration)

Do you guys plan on supporting these any time soon?

**Comment by padmaksha** [comment]
@euskode

The phonenumber library supports the 087 prefix (plus 7 digits) in South Africa for as a VoIP number (in line with official documentation).
The reported number (14 digits for the national number) is a machine to machine number (M2M). 
The phonenumber library is currently aimed at cases where numbers can be dialed to reach a human endpoint. We have no plans to support M2M numbers at the moment, but might in the future.
The reported number +27872405086 without the trailing xxxxx is a valid VOIP number.

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by euskode** [comment]
Thanks for the details @padmaksha and @andyst.

I had reviewed those docs originally before opening the issue and my thinking was that this wouldn't be rejected due to the fact that these numbers **are indeed human reachable** (both inbound and outbound) for SMS purposes. It is in fact for this very purpose that we have purchased the numbers.

If that is not the meaning of _But to date we only accept ranges that a human might call or send an SMS to_, is there something else I am failing to consider?

**Comment by andyst** [comment]
Thanks @euskode , my concerns are currently around whether M2M consistently are there to connect humans or if it's just a subset of M2M numbers, what that means in terms of semantics, how we can support that without adding a separate API method and whether that's a good idea. Also around how M2M metadata (valid number ranges) are maintained.

Can you please contribute to the discussion at #680 ? That thread emerged as the main discussion thread for M2M.

We'll discuss a few points team internally and resume the thread there as well.

**Comment by euskode** [comment]
Fair enough, thank you. I'll follow that issue and we'll probably just remove validation for these numbers until a proper approach has been agreed upon.
