### ISSUE TITLE
US phone number with extension parsing 

### ISSUE THREAD

**Issue by igorkos** [googlei18n/libphonenumber#988]
US numbers with # (ext.) parsing lead to NumberParseException on android platform.
Code:
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
Phonenumber.PhoneNumber phoneNumber = new Phonenumber.PhoneNumber();
 try {
        phoneUtil.parse(input, Locale.getDefault().getCountry(), phoneNumber);
      } catch (NumberParseException e) {
        System.err.println("NumberParseException was thrown: " + e.toString());
     }
Sample:
input: 4084568908# lead to NumberParseException
input: 4084568908#6 lead to correct parsing

**Comment by penmetsaa** [comment]
@igorkos 
Thanks for reporting this issue.

If input have ,x#~ characters in it, libphonenumber considers it as number having extensions.
If library do not find any digit following these characters it throws NumberFormatException same as in the case of invalid input number.

Yes the exception message can be even more specific in these cases where extension characters are involved. One more option is for you (if you choose to be more lenient than the library) to trim the hash at the end before passing in the number the the parse method.

This is working as intended.
