### ISSUE TITLE
Update isNumberGeographical to return true for geographical mobile numbers

### ISSUE THREAD

**Issue by keghani** [googlei18n/libphonenumber#990]
E.g. in Brazil and Indonesia. See #989.

**Comment by keghani** [comment]
Sent https://github.com/googlei18n/libphonenumber/pull/1055

**Comment by keghani** [comment]
Fixed in master, will be in the release.

**Comment by pappacena** [comment]
Thank you very much! :)

**Comment by keghani** [comment]
You're welcome :)
