### ISSUE TITLE
Update number types for 8[689] in VN

### ISSUE THREAD

**Issue by DayiJung** [googlei18n/libphonenumber#992]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

should be changed 
Ho Chi Minh City => VietNam 

Country/region affected (e.g., "US"): VN

Example number(s) affected ("+1 555 555-1234"): +84868995234

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +8486XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article):  announcement from mobile carrier (Viettel)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B84868995234&country=VN)

**Comment by penmetsaa** [comment]
@DayiJung,

Thanks for reporting these issues.

As per [ITU doc](http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000E40001PDFE.pdf), 86 range belongs to landline numbers in "Ho Chi Minh" City. 

Can you please provide evidences for all the 86, 88 and 89 ranges. We need the link for official evidences like announcement from mobile carrier, news article..etc

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%2B84868995234
