### ISSUE TITLE
Validation issue with +84898084530 (VN)

### ISSUE THREAD

**Issue by DayiJung** [googlei18n/libphonenumber#993]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

should be changed 
Ho Chi Minh City => VietNam 

Country/region affected (e.g., "US"): VN

Example number(s) affected ("+1 555 555-1234"): +84898084530

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +8489XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): announcement from mobile carrier(Mobifone)

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B84898084530&country=VN)

**Comment by padmaksha** [comment]
@DayiJung

This issue is similar to https://github.com/googlei18n/libphonenumber/issues/992 and will be tracked there. Hence closing the issue here.
