### ISSUE TITLE
Webhook event for `CreateEvent`

### ISSUE THREAD

**Issue by ruimarinho** [googlei18n/libphonenumber#998]
As maintainer of the https://github.com/seegno/google-libphonenumber repository, a simple npm wrapper for this library, I would like to automatically have it updated as soon as a new tag is published instead of having to manually do it myself.

GitHub supports webhooks which would allow a pre-arranged URL to receive the [CreateEvent](https://developer.github.com/v3/activity/events/types/#createevent) every time a tag is created.

Would you be open to add this webhook if I build such functionality?

**Comment by penmetsaa** [comment]
@ruimarinho

Thanks for the suggestion. This sounds like a good idea.

We are happy to go ahead and create webhook for your NPM based repository.
Need your confirmation on below details.

1. Payload URL: https://github.com/seegno/google-libphonenumber

2. Content type: application/json
Note: application/x-www-form-urlencoded is also available if you need it.

3. Secret: <We will communicate to you on ruipmarinho@gmail.com while creating webhook>
Note: Please let us know if you want to receive by other means.

4. Which events would you like to trigger this webhook?: Just the push event.

**Comment by keghani** [comment]
@ruimarinho This issue is blocked on your input. Please help us by answering the above questions, otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by keghani** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.

**Comment by ruimarinho** [comment]
@keghani @penmetsaa here is the info (almost 1y later 😅):

1. Payload URL: http://35.224.5.17/webhooks
2. Content-type: application/json
3. Secret: none while testing but we can exchange it after tests run using GPG via email?
4. Events: just the push event

Thanks!

**Comment by andyst** [comment]
@ruimarinho: Instead of using a specific IP, do you have a URL with a domain name?

I think that'd be more robust and the IP seems to correspond to a server in the Google Cloud.

**Comment by ruimarinho** [comment]
@andyst this is just for the trial run as I don't have any commercial domains available. In any case, I've created `libphonenumber.crabdance.com` using a free service that will now point to the static external IP to the VM running the docker container, but please note that I intend to move to the code to a cloud function instead of a running container in the upcoming future.

**Comment by andyst** [comment]
Let's go with the IP for now then.

I'm not familiar with Github webhooks and worried about security, reliability, etc. E.g. we'd want to avoid that we are blocked from pushing to the repository / releasing because your webhook server is down. To me it looks like push webhooks won't delay / block actual pushes to the repository (I guess the webhooks are executed after the repo has been updated).

If this is a trial run, please let us know once it's running properly.

**Comment by ruimarinho** [comment]
> To me it looks like push webhooks won't delay / block actual pushes to the repository

Absolutely not. It's not a git hook but rather a github webhook, meaning it is sent after the push is sent to the github server. It works just like a push notification. 

In terms of security, the secret token allows confirming the authenticity of the message. This prevents spamming and I'm looking to introduce as soon as the test passes.

> If this is a trial run, please let us know once it's running properly.

As soon as 8.8.10 or 8.9.0 is released, I will report back. It only reacts to tag pushes.

Thanks for your help.

**Comment by penmetsaa** [comment]
@ruimarinho,
Thats great! Thanks for all the details and doing this trial run. :)
Added a webhook to push to your server.

**Comment by penmetsaa** [comment]
We have released 8.8.10v on Jan 24, 2018 i.e after adding this webhook. So could you please check whether you are able to receive push notification for this release?
https://github.com/googlei18n/libphonenumber/releases/tag/v8.8.10

**Comment by ruimarinho** [comment]
It doesn't look like it. Can you re-submit the webhook via "Webhooks > Edit > Recent Deliveries > Redeliver"? Additionally, if you can provide me the response and request payload I would be very much  appreciated.

**Comment by ruimarinho** [comment]
@penmetsaa I've fixed a small issue with version parsing so if you are able to retry the tag push delivery with 8.8.11 that would be great.

**Comment by penmetsaa** [comment]
Hi Rui,

Looks like all the push notifications sent to your server are successfull. Response code 200 is recieved against all these push notification requests.

Just now, I have tried redelivering the main metadata push notification of release 8.8.11. I am recieving 404 error this time. Sent the payload content to the mail id configured in your GitHub account. Please let us know if this info is enough?
Note: Redelivering sends the same payload.

**Comment by ruimarinho** [comment]
@penmetsaa, thanks for all the support! I have successfully confirmed that the webhook worked - https://github.com/ruimarinho/google-libphonenumber/pull/146 has been submitted automatically.

Until the file structure or build process changes, I can finally get some rest updating the npm package :)
